### ISSUE TITLE
Allow Network Security Group (NSG) Security Rule import similar to Load Balancer Listener, Hostname, Backend Set, etc. imports

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1004]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Network Security Group rules follow a pattern similar to Load Balancer-related resources:
-  Load Balancer listeners (or hostnames or certificates or backend sets) have IDs that are unique when combined with the Load Balancer OCID.
- Network Security Group rules have an ID that is unique when combined with the NSG OCID

Therefore it seems a pattern for importing NSG rules could be based on the pattern used for Load Balancers. Specifically, where this syntax is relevant for importing a listener

```hcl
$ terraform import oci_load_balancer_listener.test_listener "loadBalancers/{loadBalancerId}/listeners/{listenerName}"
```

…this similar pattern could be used to import a security rule:

```hcl
$ terraform import oci_core_network_security_group_rule.test_rule "networkSecurityGroups/{networkSecurityGroupId}/rules/{ruleId}"
```

The rule ID required for this pattern is visible when an NSG rule set is retrieved via the ```oci_core_network_security_group_rules``` or through other API operations (e.g. OCI CLI). For example:

```
$ oci network nsg rules list --nsg-id ocid1.networksecuritygroup.oc1.iad.aaafuxqkhbynftivaiwbiwnaap3c2haaajfvauxd6tbvcfm26bsycko7e3gq
{
  "data": [
    {
      "description": "Public HTTPS requests",
      "destination": null,
      "destination-type": null,
      "direction": "INGRESS",
      "icmp-options": null,
      "id": "2812E3",
      "is-stateless": true,
      "is-valid": true,
      "protocol": "6",
      "source": "0.0.0.0/0",
      "source-type": "CIDR_BLOCK",
      "tcp-options": {
        "destination-port-range": {
          "max": 443,
          "min": 443
        },
        "source-port-range": null
      },
      "time-created": "2019-12-18T16:22:50.919000+00:00",
      "udp-options": null
    }
  ]
}
```

Thus for the above example, I should be able to import this rule with the following:

```hcl
$ terraform import oci_core_network_security_group_rule.test_rule "networkSecurityGroups/ocid1.networksecuritygroup.oc1.iad.aaafuxqkhbynftivaiwbiwnaap3c2haaajfvauxd6tbvcfm26bsycko7e3gq/rules/2812E3"
```

### New or Affected Resource(s)
oci_core_network_security_group_rule

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References
- API reference for updating rules that uses the unique rule ID
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/UpdateSecurityRuleDetails
- Load Balancer Listener import
https://www.terraform.io/docs/providers/oci/r/load_balancer_listener.html#import

**Comment by jotruon** [comment]
Hi @jeliker,
Now Terraform support the import for Security Rule:  https://www.terraform.io/docs/providers/oci/r/core_network_security_group_security_rule.html#import 
I will close the ticket then
