### ISSUE TITLE
Opt in to new SDK binary acceptance testing driver

### ISSUE THREAD

**Issue by kmoe** [terraform-providers/terraform-provider-oci#1005]
Requires #1001 

Fixes https://github.com/hashicorp/terraform-plugin-sdk/issues/153, https://github.com/hashicorp/terraform-plugin-sdk/issues/118, https://github.com/hashicorp/terraform-plugin-sdk/issues/114

Versions [1.7.0](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/CHANGELOG.md#170-february-12-2020) and later of the Terraform plugin SDK allow providers to opt in to a new driver for the acceptance tests, which runs tests using the `terraform` binary instead of a vendored copy of Terraform Core, while remaining as backwards-compatible as possible.

This test driver fixes a number of existing issues with the legacy test driver.

For more information, please see https://github.com/hashicorp/terraform-plugin-sdk/pull/262, and for an example provider migration please see https://github.com/hashicorp/terraform-provider-random/pull/99. 

This feature is released as an opt-in preview in version 1 of the SDK, and will be mandatory from version 2. We do not plan to change the API, and encourage providers to enable the binary test driver now. This can be done by adding a small `TestMain` block to the provider test as described in https://github.com/hashicorp/terraform-plugin-sdk/pull/262:

```go
func TestMain(m *testing.M) {
	acctest.UseBinaryDriver("oci", Provider)
	resource.TestMain(m)
}
```

No other changes are needed in most cases to for the new driver to be enabled during local acceptance test runs, and the SDK team is ready to assist with the one-time changes needed to TeamCity build configurations.

**Comment by parrneet** [comment]
Acknowledged and is in progress.
