### ISSUE TITLE
How to do route attachment point to the primary ip of the nic

### ISSUE THREAD

**Issue by mobilesuitzero** [terraform-providers/terraform-provider-oci#1006]
Hi,

In the example,

terraform-provider-oci/examples/networking/route_table_attachment/route_table_attachment.tf 

The nic would end up have two private ips.  (one primary/one secondary ip).  And, the route would point to the secondary ip.  Is it possible to only have one private ip (primary) and, have the route point to it?

Thanks.

**Comment by zexinwanoci** [comment]
It is not possible to do that. You must have separate private IP addresses for instance and route point.
