### ISSUE TITLE
Network-Security-Group-Rules Import Feature requetst

### ISSUE THREAD

**Issue by shravanthilingam** [terraform-providers/terraform-provider-oci#1009]
Hi Team,
I see that import is not supported for https://www.terraform.io/docs/providers/oci/r/core_network_security_group_security_rule.html , I would like to know when “Import NSG Security Rules under OCI” feature would be enabled for us.
Thanks & Regards,
Shravanthi Lingam

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by srishtipmishra** [comment]
Duplicate of #1004
