### ISSUE TITLE
waaf certificates are not loaded any more !!!

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1016]
Hello
I had this code which was working previsously :
resource "oci_waas_certificate" "waf_policy_certificate" {
  compartment_id   = var.compartment_ocid
  certificate_data = file(var.ssh_certificate_data)
  private_key_data = file(var.ssh_private_key_data)
  is_trust_verification_disabled = false
}
we have run this code internally many times for workshops on the waaf.
Now this piece of code is not running any more , nothing has changed on the certs neither on the code.
the plan WORKS FINE :
  # oci_waas_certificate.waf_policy_certificate will be created
  + resource "oci_waas_certificate" "waf_policy_certificate" {
      + certificate_data               = <<~EOT
            -----BEGIN CERTIFICATE-----
            MIIGcTCCBVmgAwIBAgISA9xYfiCs2aH5gPjwoN7mfzXuMA0GCSqGSIb3DQEBCwUA
            MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
            ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA5MTYwOTQ0NTZaFw0x
            OTEyMTUwOTQ0NTZaMCcxJTAjBgNVBAMMHCoub3JhY2xlY2xvdWRwdXJzdWl0bGFi
            cy5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCAZYeWFRj/Lc1r
            XrcXqQwbaf0DnNo+aHEqgut2cH2SpO7QqPnXUIjV09ln48rzPmSGpSzu1BPmZAk0
            bzD6yiOPde5IQQ79Gr+3ywUvS3Mv6nZCYFpFhThNKMDjLHsE0IvuwPP80AcYaKIo
            lYbqmbbKvR3MVr0xL63WuzJHTQA4JdZ1mzIjETpupWZM6XI+qt1b5rTX+sgG9gEN
            mx50V57J22ewtXDwFwg8k3XZbDI9t3hQafa01TkbwpcA58wmJBwhSnirScjkSV9F
            d0CqbBtgZ86Zgi4u8lQP7Sdi6WFxn43DaVTgwrUYbKHELqa+jd95A3aBpmucY/3k
            TnmrdCwINj85Pi1oPH9IJMciYEnQdTec7DQbuAT0bPIJMzxLfClRxSE4OnAohW/n
            5Usin2Zh3OX8eVZgThbnLd45Ika8z6MQ+lPYWpj3eaebMDRQmawXldsEJv8To7uy
            WZ1Uf42n2uUWTHUUYzk0hJLPd9I0/J0qO6y5ZDqj4s+1sw6kpWCahF0mxFO4bPG4
            s2Ic5o0BCphbZ37Nw4cxmLN6voqwzzyS/8/GFL5V2O3ymXX6LQP+TeH/Uk1zX8P+
            cs+orHfCOY3/N7SBcf30kLnnB+IQ4OoJuYk2Ksg80oz/mmLU3sHgEIyeCVe0mILx
            Qg7yHKeIa6NirIhPxVSLaXCDHDlTxwIDAQABo4ICcjCCAm4wDgYDVR0PAQH/BAQD
            AgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA
            MB0GA1UdDgQWBBTkvqQ8qUuMnZOVzo4LXofQ8FwntjAfBgNVHSMEGDAWgBSoSmpj
            BH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0
            dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0
            dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcvMCcGA1UdEQQgMB6CHCou
            b3JhY2xlY2xvdWRwdXJzdWl0bGFicy5jb20wTAYDVR0gBEUwQzAIBgZngQwBAgEw
            NwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
            cnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgDiaUuuJujpQAnohhu2
            O4PUPuf+dIj7pI8okwGd3fHb/gAAAW05rOuuAAAEAwBHMEUCIQCqlEIvAlLCciDS
            8iPhzBUfUNCi/P9jKi5IpzKxPynBEAIgICBQhpkaeT5pC977A39Klm01kMX+FwxY
            HmpNQ3fHE1cAdwApPFGWVMg5ZbqqUPxYB9S3b79Yeily3KTDDPTlRUf0eAAAAW05
            rOvNAAAEAwBIMEYCIQDAZ3/o4cyDapkNICrUNb7XMc7k7zk+vmnYMvvXgydPGQIh
            AO7cs+NNPd83f6tXMwYYxKiQ+ZXgxv57OXm4qyCmGCh/MA0GCSqGSIb3DQEBCwUA
            A4IBAQAnJ2J4LidReMlvqwiKCNQES2krwoov7dV8EMkKrDa7ar0lUzYI94xcfmJ9
            zckkFrjrnjDcDZAjFxP6eOqTouNXX4y988s/VB/S1JYcC1vo+PdlTJtvWoE3uOYr
            aPsCv+inJtYBw1m3OR6a2PH4CbtPQ9qie9hQufQsEkg6V/aLPSP+bIOxBHsRC/+H
            puq77Jg3DcZAEXEVwjB1yCWj0CgU+ppBwQl+fFWH303Q5AmiRjjV680yWfNy2jag
            la2BLXGYtL1/3/Rlg1sYf5UwCmO+BgV187Twmq2I/56MsLDyDiExCLVu+zcoFx0Z
            ZAcHa+b3s/3Wbdl1uBlyp+wVo0GP
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
            MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
            DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
            SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
            GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
            AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
            q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
            SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
            Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
            a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
            /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
            AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
            CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
            bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
            c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
            VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
            ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
            MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
            Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
            AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
            uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
            wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
            X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
            PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
            KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
            -----END CERTIFICATE-----
        EOT
      + compartment_id                 = "ocid1.compartment.oc1..aaaaaaaaec5to2hjrxvzpsybpo776hs25ybtqptkksjzxn4khlnqsvxjogpa"
      + defined_tags                   = (known after apply)
      + display_name                   = (known after apply)
      + extensions                     = (known after apply)
      + freeform_tags                  = (known after apply)
      + id                             = (known after apply)
      + is_trust_verification_disabled = false
      + issued_by                      = (known after apply)
      + issuer_name                    = (known after apply)
      + private_key_data               = (sensitive value)
      + public_key_info                = (known after apply)
      + serial_number                  = (known after apply)
      + signature_algorithm            = (known after apply)
      + state                          = (known after apply)
      + subject_name                   = (known after apply)
      + time_created                   = (known after apply)
      + time_not_valid_after           = (known after apply)
      + time_not_valid_before          = (known after apply)
      + version                        = (known after apply)
    }

The apply fails :
oci_waas_certificate.waf_policy_certificate: Creating...

Error: Service error:BadErrorResponse. . http status code: 401. Opc request id: ec876fe435dcf35ad003e293018898f4/354e88b17a8ea80418bf7f28b9aabe66/545899926ad672c532e2bda33c0bebea

  on waas_eshaproxy1.tf line 14, in resource "oci_waas_certificate" "waf_policy_certificate":
  14: resource "oci_waas_certificate" "waf_policy_certificate" {

Why i see this regression ?

**Comment by varmax2511** [comment]
Hi @eugsim1 -- thanks for reach out. The above error is coming from the backend service suggesting invalid request. 
I have couple of questions:
1. Why do we have multiple certificates in `certificate_data`?
2. Are you still able to execute the above configuration using older provider versions? If yes, can you please share the version number. Also, please share debug logs without any sensitive data: 
https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider

Please refer to :
https://www.terraform.io/docs/providers/oci/r/waas_certificate.html
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/waas/waas_full.tf#L26

**Comment by eugsim1** [comment]
Its a lets encrypt certificate so it has the whole cert chain.
We have run this with previous terraform providers but i have updated the terraform version for some other issues with other terraform scripts.
from the site https://www.sslshopper.com/certificate-decoder.html the cert is decoded as:

Certificate Information:
Common Name: *.oraclecloudpursuitlabs.com
Subject Alternative Names: *.oraclecloudpursuitlabs.com
Valid From: April 8, 2020
Valid To: July 7, 2020
Issuer: Let's Encrypt Authority X3, Let's Encrypt Write review of Let's Encrypt
Serial Number: 036197cb459f89451a3e6fec7fc3a33a5691

**Comment by eugsim1** [comment]
[debug_err.txt](https://github.com/terraform-providers/terraform-provider-oci/files/4452230/debug_err.txt)

**Comment by eugsim1** [comment]
[plan.txt](https://github.com/terraform-providers/terraform-provider-oci/files/4452243/plan.txt)

**Comment by eugsim1** [comment]
thanks for the help  ... splitting in 2 parts resolve my issue i will still check side env settings
