### ISSUE TITLE
Incompatibility between terraform versions when state is generaed:

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#1021]
When generating state using resource discovery and using the generate_state option, an incompatibility between versions is detected.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v0.12.16                                                                                                                                                     
+ provider.oci v3.68.0
```

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

A state file is generated.
### Actual Behavior
A conflict between versions currently used and supported by the state manager is detected. 

```
2020/04/09 09:39:44 [TRACE] Meta.Backend: backend  does not support operations, so wrapping it in a local backend                                                 

2020/04/09 09:39:44 [TRACE] backend/local: state manager for workspace "default" will:                                                                                  

- read initial snapshot from terraform.tfstate                                                                                                                         

- write new snapshots to terraform.tfstate                                                                                                                             

- create any backup at terraform.tfstate.backup                                                                                                                       

2020/04/09 09:39:44 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate

Error refreshing state: state snapshot was created by Terraform v0.12.16, which is newer than current v0.12.4; upgrade to Terraform v0.12.16 or greater to work with this state
```
### Steps to Reproduce

1. `terraform apply`

**Comment by alexng-canuck** [comment]
This error implies that there's an existing 0.12.16 state file when you ran resource discovery.

Make sure that you don't have any existing state files when running resource discovery. The way resource discovery works, is it imports resources into Terraform state. If you have an existing state file that was created with v0.12.16, then resource discovery will fail to import resources into existing state files (as this functionality internally relies on v0.12.4 version of Terraform).

**Comment by varmax2511** [comment]
Hi @hyder -- please let us know if the above response resolves your issue?

**Comment by varmax2511** [comment]
Closing this issue. Please reopen in case of any followup questions
