### ISSUE TITLE
BDS Cluster do not create with HA

### ISSUE THREAD

**Issue by abnercosta** [terraform-providers/terraform-provider-oci#1022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

 Terraform v0.12.21
	+ provider.oci v3.70.0
 
### Affected Resource(s)

BDS Cluster HA

### Terraform Configuration Files

```hcl
# SAMPLE
################################
# BDS - OCI BIG DATA SERVICE
################################

#Cluster BDS
resource "oci_bds_bds_instance" "bds_instance" {
    #Required
    cluster_admin_password = "REVWT1BTU1VDRVNT"
    cluster_public_key = "${var.bds_cluster_pub_key}"
    cluster_version = "CDH6"
    compartment_id =  "${var.compartment_id}"
    display_name = "${var.bds_display_name}"

    is_cloud_sql_configured = "false"
    cloud_sql_details {
        block_volume_size_in_gbs = "${var.bds_cluster_sql_gbs}"
        shape = "VM.Standard2.16"
    }
    
    is_high_availability = "true"
    is_secure = "true"

    master_node {
        #Required
        shape = "VM.Standard2.16}"
        subnet_id = "${var.bds_cluster_subnet}"
        block_volume_size_in_gbs = "${var.bds_master_block_volume}"
        number_of_nodes = "2"
    }
    util_node {
        #Required
        shape = "VM.Standard2.16"
        subnet_id = "${var.bds_cluster_subnet}"
        block_volume_size_in_gbs = "${var.bds_util_block_volume}"
        number_of_nodes = "2"
    }
    worker_node {
        #Required
        shape = "VM.Standard2.16}"
        subnet_id = "${var.bds_cluster_subnet}"
        block_volume_size_in_gbs = "${var.bds_worker_block_volume}"
        number_of_nodes = "10"
    }

    network_config {
        cidr_block = "${var.bds_vcn_cidr_block}"
        is_nat_gateway_required = "true"
    }
}

```

### Expected Behavior

BDS Cluster creation with HA

### Actual Behavior

```
Error: expected util_node.0.number_of_nodes to be in the range (1 - 1), got 2
...

Error: expected master_node.0.number_of_nodes to be in the range (1 - 1), got 2
...

```

### Steps to Reproduce

1. `terraform apply`

### Recomendation
#CHANGE THIS FUNCTION
```

	func BdsBdsInstanceResource() *schema.Resource {
	....
		#lines 105 and 141

			"number_of_nodes": {
				...
				ValidateFunc: validation.IntBetween(1, 1),
			},
	....
	}
```
TO THIS ONE:

	func BdsBdsInstanceResource() *schema.Resource {
	....
		#lines 105 and 141
			"number_of_nodes": {
				...
				ValidateFunc: ValidateFunc: validation.IntBetween(1, 2), //Or whatever other value
			},
	....
	}

```

**Comment by jotruon** [comment]
Hi @abnercosta,
Thanks for reporting this issue. 
We are working on a fix to change the validation for `number_of_nodes`

**Comment by jotruon** [comment]
Release 3.71.0 confirm to fix this issue. Closing now
