### ISSUE TITLE
Imported oci_core_subnet not recognized having non-default oci_core_route_table 

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.oci v3.70.0
+ provider.template v2.1.2

### Affected Resource(s)
oci_core_subnet

### Terraform Configuration Files
```hcl
resource "oci_core_subnet" "the_subnet" {
  #Required
  cidr_block                 = var.cidr_block
  compartment_id             = var.compartment_id
  vcn_id                     = var.vcn_id

  #Optional
  route_table_id             = null
}
```
import with following
```
terraform import oci_core_subnet.the_subnet ocid1.subnet.oc1.the.subnet.ocid
```
Note that imported Subnet is _**not**_ using default Route Table for VCN. Rather, existing Subnet is using another Route Table that already exists in VCN.

Check for changes in imported Subnet compared to current tf script.

```
terraform plan

No changes. Infrastructure is up-to-date.
```

### Expected Behavior
Since imported Subnet has non-default Route Table and TF script defines Subnet with ```route_table_id = null``` I would expect plan/apply to trigger update since ```route_table_id = null``` implies VCN default route table.

### Actual Behavior
Imported Subnet with non-default Route Table and corresponding TF script with ```route_table_id = null``` is not triggering update on plan/apply. 

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
I have not yet tested but wonder if same will occur with Subnet that has non-default ```dhcp_options_id``` and non-default ```security_list_ids```

### References
* https://www.terraform.io/docs/providers/oci/r/core_subnet.html#route_table_id
_"...If you don't provide a value, the subnet uses the VCN's default route table."_

**Comment by varmax2511** [comment]
Hi @jeliker -- thanks for reaching out. Please refer to https://www.terraform.io/docs/configuration/expressions.html . Since you specified `null`, the argument `route_table_id` is ignored as their
is no default value for it in terraform provider. If you will change it to some value other than the one specified in your state file, you will see the diff as expected. Please let us know if this resolves your issue

**Comment by jeliker** [comment]
Thank you for your comment.

Based on the documentation I quoted above there _is_ a default value for ```route_table_id``` which is the default route table ID for the VCN.  Even if that wasn't the case, why should ```route_table_id = null``` cause a state file containing ```route_table_id = ocid1.routetable.oc1.my.route.table.ocid```? Shouldn't that instead be stored in state as ```null``` instead of containing a "secret" default value?

**Comment by jeliker** [comment]
Following up on my previous comment, from the Expressions documentation you share:

> If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

Thus, if I want to "omit" the ```route_table_id``` (and, I speculate the same is true for ```dhcp_options_id``` and ```security_list_ids```) what is the correct pattern so that I assume the documented default which is the VCN ```default_route_table_id``` (and ```default_dhcp_options_id``` and ```default_security_list_ids```)?

**Comment by jeliker** [comment]
Meanwhile I've adjusted my script as follows:

```hcl
variable "vcn" {
  description = "VCN resource (not OCID)"
  type = any
}

resource "oci_core_subnet" "the_subnet" {
 . . .
  vcn_id = var.vcn.id  #was vcn_id = var.vcn_id
  route_table_id = var.route_table_id != null ? var.route_table_id : var.vcn.default_route_table_id
}
```

'Tis wordy but avoids the problem while I (hopefully) await a solution.

**Comment by varmax2511** [comment]
Hi @jeliker -- here the keyword is `default` value. The value in the state file is the default value. Once you imported the subnet, the state file was updated with default value of non-default route table. Subsequent execution with 
```
 route_table_id             = null
```
will hence result in no changes. I think the above solution that you have will serve your use case.

**Comment by varmax2511** [comment]
Hi @jeliker -- please let us know if this issue can be closed?

**Comment by jeliker** [comment]
I think I am recognizing a misunderstanding I've carried.

It seems you are saying ```null``` only causes the default value to be set when launching. I was expecting that changing to ```null``` would change an existing value from its explicit value (i.e. ```route_table_id```) back to its default value.  Is that not ever the case in Terraform and/or in the OCI provider?

**Comment by varmax2511** [comment]
Hi @jeliker -- per documentation https://www.terraform.io/docs/configuration/expressions.html, `null` only causes terraform to omit an argument. Rest is a side-effect which prompts terraform to use its default value or raise error. How terraform decides `default` value is another question. Based on use cases I have tried, it appears that once a resource has been created and has a value for an argument in the state file, using `null` causes terraform to use the value present in state file as `default`.
Please let us know if this answers your question.

**Comment by jeliker** [comment]
That is an acceptable answer. I will design around that behavior.  Thank you for the details.
