### ISSUE TITLE
Changing DBaaS VM shape to lower value requires cpu_core_count being specified

### ISSUE THREAD

**Issue by tr-patrick** [terraform-providers/terraform-provider-oci#1026]
# Terraform Version and Provider Version

- Terraform v0.12.20
- provider.oci v3.70.0
  
# Affected Resource(s)

oci_database_db_system

# Issue explanation
You are allowed to change the shape of a dbsystem to a higher/lower value. 

For example: You can change the shape from VM.Standard2.1 to VM.Standard2.2 **without** specifying the cpu_core_count. The cpu_core_count is optional and documentation says  
**This parameter is not used for virtual machine DB systems because virtual machine DB systems have a set number of cores for each shape**

Changing the shape from VM.Standard2.1 to VM.Standard2.2. No problem

Changing the shape from VM.Standard2.2 to VM.Standard2.1 gives the below error
```
Error: Service error:InvalidParameter. The maximum CPU core count for VM.Standard2.1 DB System is 1.. http status code: 400. Opc request id: ......
```

Within the state files you can see the difference of the cpu_core_count

state file VM.Standard2.1
```
...
      "module": "module.customer-prd-db2301",
      "mode": "managed",
      "type": "oci_database_db_system",
      "name": "instance",
      "provider": "provider.oci",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "availability_domain": "QTKO:EU-FRANKFURT-1-AD-2",
            "backup_network_nsg_ids": [],
            "backup_subnet_id": null,
            "cluster_name": null,
            "compartment_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "cpu_core_count": 1,              <--------------------------
...
```
state file VM.Standard2.2
```
...
      "module": "module.customer-prd-db2301",
      "mode": "managed",
      "type": "oci_database_db_system",
      "name": "instance",
      "provider": "provider.oci",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "availability_domain": "QTKO:EU-FRANKFURT-1-AD-2",
            "backup_network_nsg_ids": [],
            "backup_subnet_id": null,
            "cluster_name": null,
            "compartment_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "cpu_core_count": 2,                     <--------------------------
...            
```                  

# Expected behavior
Because it is a Virtual Machine the parameter shouldn't have any influence. You can't control it. The OCI shouldn't give an error it should just change the shape and the cpu_core_count from 2 back to 1 without me specifying it. 

# Workaround
When changing the shape back to VM.Standard2.1 you give the cpu_core_count as a variable

**Comment by afedorch** [comment]
@tr-patrick thanks for reporting it, we will work on the fix.

**Comment by afedorch** [comment]
@tr-patrick the fix will be released in the next provider release

**Comment by tr-patrick** [comment]
@afedorch 
See the new release. Will test it this weekend. Thank you for the fast changes

**Comment by afedorch** [comment]
@tr-patrick I am closing this one. Please let us know if you still see the issue, thanks!

**Comment by tr-patrick** [comment]
@afedorch
Sorry we were testing yesterday because of other work.

The problem is solved. Thank you so much for the fast fix
