### ISSUE TITLE
Provider and API docs both wrong? Default boot_volume_type is now pv not iscsi

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1028]
Both API docs and TF docs for ```oci_core_instance``` say iSCSI is default ```boot_volume_type``` and ```remote_data_volume_type``` for Oracle images. In my experience having launched many instances over the past multiple months this has changed as I consistently
see PV as the default.

Can you confirm?

### References
* https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchOptions
* https://www.terraform.io/docs/providers/oci/r/core_instance.html

**Comment by afedorch** [comment]
@jeliker we have redirected this question to the service team to confirm. Thanks!
As you mentioned TF and API docs are in sync it means that Terraform provider expects the documented behavior as well.

**Comment by afedorch** [comment]
@jeliker as per the service team, the default bootVolumeType for OCI provided system images is PV now. Both docs will be updated, thanks!

**Comment by jeliker** [comment]
Good news! Thank you!
