### ISSUE TITLE
Error when setting pv_encryption in launch_options

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.oci v3.71.0
+ provider.template v2.1.2

### Affected Resource(s)
oci_core_instance

### Terraform Configuration Files

```hcl
resource "oci_core_instance" "the_instance" {
  #Required
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_id
  shape               = var.instance_shape

  create_vnic_details {
    #Required
    subnet_id        = var.subnet_id
    assign_public_ip = var.assign_public_ip
  }
  launch_options {
    is_pv_encryption_in_transit_enabled = var.is_pv_encryption
  }
  metadata = {
    ssh_authorized_keys = var.ssh_authorized_keys
  }
  source_details {
    #Required
    source_id   = var.source_id
    source_type = var.source_type
  }
}
```

### Debug Output
```
2020-04-16T08:25:10.772-0400 [DEBUG] plugin.terraform-provider-oci_v3.71.0_x4: X-Content-Type-Options: nosniff
2020-04-16T08:25:10.772-0400 [DEBUG] plugin.terraform-provider-oci_v3.71.0_x4: 
2020-04-16T08:25:10.772-0400 [DEBUG] plugin.terraform-provider-oci_v3.71.0_x4: {
2020-04-16T08:25:10.772-0400 [DEBUG] plugin.terraform-provider-oci_v3.71.0_x4:   "code" : "InvalidParameter",
2020-04-16T08:25:10.772-0400 [DEBUG] plugin.terraform-provider-oci_v3.71.0_x4:   "message" : "Overriding PvEncryptionInTransitEnabled in LaunchOptions is not supported"
```

### Expected Behavior

Should be able to set only ```is_pv_encryption_in_transit_enabled``` in ```launch_options``` since all attributes in that block are marked "optional"
### Actual Behavior

Error when setting ```is_pv_encryption_in_transit_enabled=false``` in ```launch_options```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Have also tried setting ```is_pv_encryption_in_transit_enabled=false``` outside of ```launch_options``` with success but only if I remove the setting from ```launch_options```. If both are set I see the same error. This is unexpected more so than when setting in only ```launch_options``` because the error says

> Overriding PvEncryptionInTransitEnabled in LaunchOptions is not supported.

…and I am not "overriding" anything as I am setting the value to "false" both inside ```launch_options``` and outside.

 

### References
* https://www.terraform.io/docs/providers/oci/r/core_instance.html#launch_options
See ```launch_options``` and all attributes of ```launch_options``` are marked "optional"
* https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchOptions
See `all attributes in API ```LaunchOptions``` type are marked "optional"

**Comment by afedorch** [comment]
@jeliker thanks for reporting it!
I agree that the API description and the error message looks confusing here. The LaunchOptions is used in [LaunchInstanceDetails](https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchInstanceDetails) as `[Options for tuning compatibility and performance of VM shapes]` [here](https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchOptions) . Any attribute in `launch_options` will be treated by the service as an attempt to override the default behavior (and/or top-level attribute in your case). If the override is not supported or not allowed for the current configuration the service will return 4xx response. As I know it was mainly introduced to allow override for the `network_type` value.

To specify `is_pv_encryption_in_transit_enabled` behavior you need to use top-level attribute only for your configuration.

**Comment by jeliker** [comment]
Thank you for the details

Based on your comments would you say still this is a bug in behavior seeing that all of the "optional" parameters are apparently required as well as requiring the top-level pv_encrytion?  Otherwise, perhaps a documentation update is warranted since only through trial-and-error did I discover that even when setting pv_encryption=false (the default) do I need to not include that in launch_options as well as the top-level.

Note that I am explicitly setting it false because I'm creating the compute resource via module and passing in var.pv_encryption thus using input value as true, false, or null (and finding that set to false or null causes an error in launch_options).

**Comment by afedorch** [comment]
@jeliker In terms of `optional` parameters it depends on the service - it is possible to have `dependency` between different `optional` arguments and specify `unexpected` configuration and get 4xx response back. I am not sure that the service will be able to change public API at this point. However, to my mind the description for `launchOptions` should be added in [LaunchInstanceDetails](https://docs.cloud.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchInstanceDetails) - I will file this request for the service team.

Please confirm the behavior from the TF provider side:
- you can create `oci_core_instance` resource without setting `is_pv_encryption_in_transit_enabled` (at top-level and in `launch_options`)
- you can create `oci_core_instance` resource specifing any value for the top level `is_pv_encryption_in_transit_enabled` attribure

Thanks!

**Comment by jeliker** [comment]
I can create ```oci_core_instance``` without ```is_pv_encryption_in_transit_enabled``` top-level or with it set to ```false``` or set ```null``` all with same result. Once created I can change value to ```null``` or ```false``` or remove attribute entirely and no change is flagged on ```apply```.

Is attribute ```is_pv_encryption_in_transit_enabled``` at top-level and in ```launch_options``` entirely redundant then? That is, if I am setting it I should use top-level then, if I also have set of parameters to set in ```launch_options``` (i.e. for imported custom image that requires BIOS boot) I must also duplicate the setting there?

Also, is it appropriate to say I don't need ```launch_options``` unless I am overriding value for one of its attributes _other than_ ```is_pv_encryption_in_transit_enabled```?

**Comment by afedorch** [comment]
@jeliker that's sound correct to me - you do not need to use `launch_options` for the `is_pv_encryption_in_transit_enabled` ovverride. 
As I mentioned we expect the service team to update the documentation for the `launch_options` that will explain the current support information for the attributes. Thanks!

**Comment by jeliker** [comment]
Thank you for the detailed explanation.
