### ISSUE TITLE
Get details on single oci_core_image by image_id?

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1035]
I need to get OS details for an ```image_id```. I want to use those details to control when/if to execute certain ```remote_exec``` provisioners.  I expected to fine ```oci_core_image``` data source or option for ```image_id``` filter on ```oci_core_images``` datasource but don't find either option.

Is there a way to get details as would be returned by ```oci_core_images``` but for only a single ```image_id```? I know I can filter on ```display_name``` on ```oci_core_images``` but, as I read in best-practices for OCI provider, I should not rely heavily on ```display_name``` so prefer to locate by ```image_id``` for absolute certainty.

**Comment by rashik-bhasin** [comment]
Currently, we are not supporting `oci_core_image` data source but we'll support it in future. 
For now if you want to filter based on `image_id` you can do it on `oci_core_images` data source using `id` as `id` is the image_id. Hope this resolves your issue.

**Comment by jeliker** [comment]
What you say is a reasonable work-around. However the documentation does not list ```id``` as a valid input showing, instead, only these:

* compartment_id
* display_name
* operating_system
* operating_system_version
* shape
* state
* sort_by
* sort_order

Is the documentation in error?

**Comment by rashik-bhasin** [comment]
This is not mentioned in the documentation, I'll check why that is. 
But here is an example which is filtering `oci_core_images`  using `id` [link_to_example](https://github.com/terraform-providers/terraform-provider-oci/blob/abe93b2bc6f61d3be89360b9d7e1b3b3d54a84a3/examples/compute/image/image.tf#L103) . Then you can output the image data similar to [this](https://github.com/terraform-providers/terraform-provider-oci/blob/abe93b2bc6f61d3be89360b9d7e1b3b3d54a84a3/examples/compute/image/image.tf#L136) . 
Thanks!

**Comment by jeliker** [comment]
I see that syntax generally described here: https://www.terraform.io/docs/providers/oci/guides/filters.html

It says this applies to "...resources support filtering semantics" which you say includes ```oci_core_images```.

This is helpful. Thank you!
