### ISSUE TITLE
Imported oci_file_storage_mount_target does not retain ip_address and hostname_label

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.oci v3.71.0

### Affected Resource(s)
* oci_file_storage_mount_target

### Terraform Configuration Files
```hcl
resource "oci_file_storage_mount_target" "mount_target" {
  #Required
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_id
  subnet_id           = var.subnet_id

  #Optional
  hostname_label      = "fss-test"
  ip_address          = "172.31.2.17"
}
```

### Debug Output
After above mount target has been created (through Terraform or other means) and, ensuring resource is not already in state file (i.e. manually build resource or remove from state file before importing), ```terraform import``` and see the following:

```hcl
  # oci_file_storage_mount_target.mount_target must be replaced
-/+ resource "oci_file_storage_mount_target" "mount_target" {
        availability_domain = "OQhv:US-ASHBURN-AD-1"
        compartment_id      = "ocid1.compartment.oc1...the.ocid"
      ~ defined_tags        = {} -> (known after apply)
      ~ display_name        = "mt-6953" -> (known after apply)
      ~ export_set_id       = "ocid1.exportset.oc1.iad..the.ocid" -> (known after apply)
      ~ freeform_tags       = {} -> (known after apply)
      + hostname_label      = "fss-test" # forces replacement
      ~ id                  = "ocid1.mounttarget.oc1.iad..the.ocid" -> (known after apply)
      + ip_address          = "172.31.2.17" # forces replacement
      + lifecycle_details   = (known after apply)
      ~ nsg_ids             = [] -> (known after apply)
      ~ private_ip_ids      = [
          - "ocid1.privateip.oc1.iad..the.ocid",
        ] -> (known after apply)
      ~ state               = "ACTIVE" -> (known after apply)
        subnet_id           = "ocid1.subnet.oc1.iad.the.ocid"
      ~ time_created        = "2020-04-21 11:15:01.128 +0000 UTC" -> (known after apply)

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior
Imported ```oci_file_storage_mount_target``` should have ```ip_address``` and ```hostname_label``` as defined in resource.

### Actual Behavior
Imported ```oci_file_storage_mount_target``` is not including ```hostname_label``` and ```ip_address```

### Steps to Reproduce

1. Create resource using above HCL
2. After created, remove from state file ```terraform state rm oci_file_storage_mount_target.mount_target```. _Note can also use existing mount target created by another means instead of these steps 1, 2. If so, ensure existing mount target also has ```hostname_label``` defined so as to validate the error condition as described here._
3. Import using OCID for resource that was created ```terraform import -var-file=vars.tfvars oci_file_storage_mount_target.mount_target ocid1.mounttarget.oc1.iad.the.ocid```
4. Use ```terraform apply``` to compare imported to actual
5. Note need for "replace" because ```ip_address``` and ```hostname_label``` are detected as changes.

**Comment by varmax2511** [comment]
Hi @jeliker -- we observe that the upstream service is not returning the parameters `hostname_label` and `ip_address` as part of their GET response. We have raised the issue with them and are awaiting a resolution. 
Till then please try using the above fix and let us know if this unblocks you

**Comment by varmax2511** [comment]
Hi @jeliker -- can you please let us know if you are unblocked?

**Comment by jeliker** [comment]
Confirmed manually adding to state file allows me to move ahead. After import then edit to state file I found ```terraform plan``` detects "no changes." Also tried ```terraform refresh``` then ```terraform plan``` and still "no changes."

Thank you for this suggestion and for pursuing the matter further!

**Comment by parrneet** [comment]
Hi @jeliker - This has been fixed. Please use the [latest released provider ](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.76.0)
