### ISSUE TITLE
When launching long-running resource builds, can we launch multiple in parallel if no dependencies among them?

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1040]
If I am launching multiple DB systems that do not depend on each other, can I cause all to launch concurrently vs. waiting for the first to complete before the next begins? Otherwise resource ```oci_database_db_system``` takes typically 60 minutes (or more) each to launch one after the other.

I understand that later dependencies may need to pause to wait for DB but the DB Systems can safe fully launch all in parallel (as would be the case if launched via OCI Console).

**Comment by varmax2511** [comment]
Hi @jeliker -- this is more of a question for Terraform than terraform-provider-oci.However, terraform executes the resources in parallel as applicable based on the dependencies in your config and the resources provided by the machine terraform is running on. 
Please refer to the below document for more information:
https://www.terraform.io/docs/internals/graph.html

**Comment by varmax2511** [comment]
Closing this query. Please feel to reopen in case of followup questions
