### ISSUE TITLE
subnet referencing from scratch created virtual network and subnet

### ISSUE THREAD

**Issue by kviktorman** [terraform-providers/terraform-provider-oci#1044]
### Terraform Version and Provider Version

```
Terraform v0.12.24
+ provider.oci v3.72.0
```

### Affected Resource(s)

* resource "oci_core_virtual_network"
* resource "oci_core_subnet"
* data "oci_core_subnets"
* data "oci_core_subnet"

### Terraform Configuration Files

```hcl
// # creates new virtual network at the target space/compartment
resource "oci_core_virtual_network" "oci_test_virtual_network" {
  cidr_block     = var.network.networkCIDR
  compartment_id = var.target_deploy_compartment
  display_name   = var.network.networkDisplayName
}

// # creates new virtual network subnet at the target space/compartment
resource "oci_core_subnet" "oci_test_virtual_network_subnet" {
  for_each = { for setting in var.network.subnets : setting.subnetDisplayName => setting }

  compartment_id      = var.target_deploy_compartment
  vcn_id              = oci_core_virtual_network.oci_test_virtual_network.id
  cidr_block          = each.value.subnetCIDR
  display_name        = each.value.subnetDisplayName
  availability_domain = each.value.subnetAvailabilityZone
}

# query all subnet
data "oci_core_subnets" "subnet_list" {
  compartment_id = var.target_deploy_compartment
  vcn_id         = oci_core_virtual_network.oci_test_virtual_network.id
}

# query filtered subnet
data "oci_core_subnets" "filtered_subnet" {
  compartment_id = var.target_deploy_compartment
  vcn_id         = oci_core_virtual_network.oci_test_virtual_network.id
  display_name   = var.network.subnets[0].subnetDisplayName
}

/*# query specific subnet
data "oci_core_subnet" "test_subnet" {
  subnet_id = oci_core_subnet.oci_test_virtual_network_subnet.id
}*/

output "network" {
  value = {
    NetworkDetails  = data.oci_core_subnets.subnet_list,
    FilteredNetwork = data.oci_core_subnets.filtered_subnet
    //  Info            = data.oci_core_subnet.test_subnet
  }
}
```

### Debug Output

Output -1 
```
network = {
  "FilteredNetwork" = {
    "compartment_id" = "ocid1...."
    "display_name" = "test-network-subnet-1"
    "id" = "2020-04-28 09:37:32.831779452 +0000 UTC"
    "subnets" = []
    "vcn_id" = "ocid1...."
  }
  "NetworkDetails" = {
    "compartment_id" = "ocid1...."
    "id" = "2020-04-28 09:37:32.749622268 +0000 UTC"
    "subnets" = []
    "vcn_id" = "ocid1...."
  }
}
```

Output -2
By adding the specific subnet query ("test_subnet") to the output I got the following error:
```
Error: Missing resource instance key

  on main.tf line 52, in data "oci_core_subnet" "test_subnet":
  52:   subnet_id = oci_core_subnet.oci_test_virtual_network_subnet.id

Because oci_core_subnet.oci_test_virtual_network_subnet has "for_each" set,
its attributes must be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    oci_core_subnet.oci_test_virtual_network_subnet[each.key]

```
### Expected Behavior

Some way receiving the subnet id details, so they can be referenced by other resources.
i.e: "oci_containerengine_node_pool"

### Actual Behavior

As you create your environment from scratch one of the first steps is to create the virtual cloud network (vcn) and its subnets. In case you want to create a Kubernetes environment the node pool resource requires the node_config_details to be set (availability domain, subnet).

Using an automated referencing of the network subnets seems to be not possible due a bug or a missing feature. See more details in the Factoids section and I have referenced use case as well in the References section. 

Thanks for your help with my issue.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It seems when the vcn id becomes available it will return an empty subnet list, because the subnets are not yet created. (See output -1 "NetworkDetails")

In case you explicitly reference the virtual subnet display name (optional attribute) the list will be also empty. This is because the virtual network is created, but the subnets are not yet created. (See output -1 "FilteredNetwork")

Querying directly the subnet seems to be not possible, because the subnets are created via a loop, which means that the id's are handled as a list. (See output -2 error message)

### References

You can find more information regards to the subnet referencing use case in the [24557 issue](https://github.com/hashicorp/terraform/issues/24557) tracked in the core Terraform repository.

**Comment by jotruon** [comment]
Hi @kviktorman,

Thanks for reporting this issue.
At the time resource `oci_core_subnets` is created, the datasource for `subnets` is empty (Basically this is a List API call parallel at the time subnets are created so service will return empty List as expected)

A workaround is that you need to set depends_on for the datasource:
```
data "oci_core_subnets" "subnet_list" {
  depends_on = ["oci_core_subnet.oci_test_virtual_network_subnet"]
  ....
}

data "oci_core_subnets" "filtered_subnet" {
  depends_on = ["oci_core_subnet.oci_test_virtual_network_subnet"]
  ...
}
```
so that it will wait for subnets are created successfully to start the datasource.

Hope this can help you

**Comment by kviktorman** [comment]
Hi @jotruon ,
following your workaround advice I have managed to retrieve the subnets.

I'm glad that you were able to answer, you made my day !!! 
I have tried couple of ways to make it work, but I did not think about putting there the depends_on.

Thanks a lot,
Viktor
