### ISSUE TITLE
IDCS oci_identity_identity_provider_groups data source has null for all display-names

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1048]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.oci v3.72.0

### Affected Resource(s)

* oci_identity_identity_provider_groups

### Terraform Configuration Files

```hcl
data "oci_identity_identity_provider_groups" "idcs_groups" {
  identity_provider_id = var.idcs_provider_id
}

output "provider_groups" {
  value = data.oci_identity_identity_provider_groups.idcs_groups
}
```

### Debug Output
```
provider_groups = {
  "id" = "2020-04-29 21:41:52.203869 +0000 UTC"
  "identity_provider_groups" = [
    {
      "display_name" = ""
      "external_identifier" = "DEADBEEFBADF00D"
      "id" = "ocid1.idpgroup.oc1..idcs.group.ocid.here"
      "identity_provider_id" = "ocid1.saml2idp.oc1..idcs.group.ocid.here"
      "time_created" = "2020-03-31 14:36:57.426 +0000 UTC"
      "time_modified" = "2020-04-27 21:07:56.263 +0000 UTC"
    },
    {
      "display_name" = ""
      "external_identifier" = "86753099035768"
      "id" = "ocid1.idpgroup.oc1..idcs.group.ocid.here"
      "identity_provider_id" = "ocid1.saml2idp.oc1..idcs.ocid.here"
      "time_created" = "2019-11-09 02:10:12.786 +0000 UTC"
      "time_modified" = "2020-04-28 15:49:10.337 +0000 UTC"
    }
  ]
  "identity_provider_id" = "ocid1.saml2idp.oc1..idcs.ocid.here"
}
```

### Expected Behavior
Results for ```oci_identity_identity_provider_groups``` should have display-names as shown in IDCS identity console or as shown in OCI Console > IDCS Provider > Group Mappings page

### Actual Behavior
Results for ```oci_identity_identity_provider_groups``` does not include ```display-name``` values.

### Steps to Reproduce

1. `terraform refresh`

### Important Factoids
I am wanting to script the group mappings by building template of resulting names and identity provider IDs. I expected to find display names so that I could render as follows:

```
idcs_groups = {
  "OCI_Administrators" = "ocid1.idpgroup.oc1..idcs.group.ocid.here",
  "OCI_ReadOnly" = ""ocid1.idpgroup.oc1..another.idcs.group.ocid.here"
}
```

I don't understand why ```display-name``` would be blank in all cases as currently occurs.

**Comment by jotruon** [comment]
Hi @jeliker,
Thanks for reporting this issue.
Yes the service return incorrect model for "display_name" (it return "name" instead) so it shows blank in this case.

I transferred this issue to service team.

**Comment by jotruon** [comment]
Hi @jeliker ,
For update, service team is working on the fix and provide new API.

**Comment by heena2507** [comment]
> Hi @jeliker ,
> For update, service team is working on the fix and provide new API.

,,l.mlmllml

**Comment by heena2507** [comment]
> Hi @jeliker,
> Thanks for reporting this issue.
> Yes the service return incorrect model for "display_name" (it return "name" instead) so it shows blank in this case.
> 
> I transferred this issue to service team.



> > Hi @jeliker ,
> > For update, service team is working on the fix and provide new API.
> 
> ,,l.mlmllml



> Hi @jeliker,
> Thanks for reporting this issue.
> Yes the service return incorrect model for "display_name" (it return "name" instead) so it shows blank in this case.
> 
> I transferred this issue to service team.

**Comment by jotruon** [comment]
confirm the fix has been deployed. Closing ticket now
