### ISSUE TITLE
Cannot add a compute instance as a backend to a load balancer backend set

### ISSUE THREAD

**Issue by ShetuRaj** [terraform-providers/terraform-provider-oci#1052]
### Terraform Version
0.12.23
### OCI Provider Version
3.51.0
### Problem
I am trying to create a complete load balancer system which has a **compute instance** as a backend but the problem here is that in the `oci_load_balancer_backend` resource there is no attribute using which I can do so. Only **ip address** can be used as a backend as shown in the resource block below which I don't want to use. How can I make a compute instance as a backend instead of an ip address?

### Resource Block
```
resource "oci_load_balancer_backend" "test_backend" {
    #Required
    backendset_name = "${oci_load_balancer_backend_set.test_backend_set.name}"
    ip_address = "${var.backend_ip_address}"
    load_balancer_id = "${oci_load_balancer_load_balancer.test_load_balancer.id}"
    port = "${var.backend_port}"

    #Optional
    backup = "${var.backend_backup}"
    drain = "${var.backend_drain}"
    offline = "${var.backend_offline}"
    weight = "${var.backend_weight}"
} 

```

**Comment by zexinwanoci** [comment]
Hello Shetu, you can refer to our example in the lb_full: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/load_balancer/lb_full/lb_full.tf
To create a compute instance as a separate resource and use that ip address in the backend resource.
