### ISSUE TITLE
Resource oci_identity_compartment is not destroyed on `terraform destroy`

### ISSUE THREAD

**Issue by tmpg** [terraform-providers/terraform-provider-oci#1056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.24
provider.oci v3.73.0
### Affected Resource(s)
resource "oci_identity_compartment" 
### Terraform Configuration Files

```hcl
resource "oci_identity_compartment" "CreateCompartment" {
  compartment_id = var.tenancy_ocid
  description    = var.compartment_description
  name           = var.compartment_name
}
```

### Expected Behavior

When `terraform apply` creates a compartment, `terraform destroy` should destroy that compartment

### Actual Behavior

`terraform destroy` **does not** destroy the compartment

### Steps to Reproduce

1. Create a `.tf` which creates a compartment
2. `terraform apply`
3. `terraform destroy`
4. Check if compartment still exists

**Comment by abhilash-av** [comment]
Hi @tmpg,

In order to destroy the compartment, please add the argument **enable_delete** to the resource schema as in document: https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/identity_compartment.html.markdown#argument-reference
Closing this issue, let us know if you have any other questions.

Thanks
