### ISSUE TITLE
How do we keep the connection intact post a PS Script in main.tf that requires a reboot

### ISSUE THREAD

**Issue by anil-shenoy-in** [terraform-providers/terraform-provider-oci#1058]
i have put in place the PS script in main.tf using user_data as follows.

metadata = {
        user_data = "${base64encode(file("C:/temp/JoinDomRenComp.ps1"))}"
    }

The main terraform instance creates an instance and i'm using a powershell script to Join the Server to the domain and rename the computer. All of this in one script.

Once we use Add-Computer cmdlet, our system will require a restart.

Now, i need the terraform script to stay intact and execute the next cmdlet
Rename-Computer

Can anyone please suggest, if this is possible in terraform and with OCI ?

**Comment by rashik-bhasin** [comment]
Hi,
Thank you for asking the question.
Can you share the terraform config and provider version you are trying to run.

Thanks!

**Comment by rashik-bhasin** [comment]
Closing this issue as no response.
Feel free to open this if you have any follow up questions.
Thanks!
