### ISSUE TITLE
Update documentation example for oci_core_ipsec_connection_tunnel_management to include ike_version

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1059]
See this page in documentation:

* https://www.terraform.io/docs/providers/oci/r/core_ipsec_connection_tunnel_management.html

Inconsistent with other examples, the example code here does not include optional parameter

```ike_version```

Please consider adding to the example code.

Note that ```ike_version``` is currently noted in the Attribute Reference on the bottom of the page.

**Comment by rashik-bhasin** [comment]
Hi,
Thanks for asking the question. We will be updating the document in future. But for now if you need to use ike_version, you can simply add the ike_version in your configuration and the values can be "V1" or "V2". 
Hope this resolves the issue if you are stuck anywhere.
