### ISSUE TITLE
OCI container engine with default K8s service CIDR references incorrectly kube-dns service

### ISSUE THREAD

**Issue by kviktorman** [terraform-providers/terraform-provider-oci#1060]
### Terraform Version and Provider Version

```
Terraform v0.12.24
+ provider.oci v3.74.0
```

### Affected Resource(s)

* oci_containerengine_cluster
* oci_containerengine_node_pool (indirectly)

### Terraform Configuration Files

```hcl

# cluster with default service CIDR
resource "oci_containerengine_cluster" "test_cluster" {
  compartment_id     = var.target_deploy_compartment
  kubernetes_version = var.cluster.kubernetesVersion
  name               = var.cluster.kubernetesClusterName
  vcn_id             = oci_core_virtual_network.oci_test_virtual_network.id
}


# cluster with custom service CIDR
resource "oci_containerengine_cluster" "test_cluster" {
  compartment_id     = var.target_deploy_compartment
  kubernetes_version = var.cluster.kubernetesVersion
  name               = var.cluster.kubernetesClusterName
  vcn_id             = oci_core_virtual_network.oci_test_virtual_network.id

  # optional settings 
  options {
    kubernetes_network_config {
      # in case of default this value is 10.96.0.0/16
      services_cidr = "10.125.0.0/16"
    }
  }
}

```

### Debug Output

```hcl
# Example 1
# Correct kube-dns referencing
# Oracle cloud web interface created K8s cluster (with default settings)

$ kubectl get services -A
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  51m
kube-system   kube-dns     ClusterIP   10.96.5.5    <none>        53/UDP,53/TCP,9153/TCP   49m

$ kubectl get pods
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
default       apache-deployment-857d559965-752vp     1/1     Running   0          22m

$ kubectl exec -it apache-deployment-857d559965-752vp -n default  -- /bin/bash
[root@apache-deployment-857d559965-752vp /]# cat /etc/resolv.conf 
nameserver 10.96.5.5

# Example 2
# Incorrect kube-dns referencing
# Terraform created K8s cluster (with default settings)

$ kubectl get services -A
NAMESPACE     NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP                  16m
kube-system   kube-dns     ClusterIP   10.96.108.66   <none>        53/UDP,53/TCP,9153/TCP   14m

$ kubectl get pods
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
default       apache-deployment-857d559965-d7m4c     1/1     Running   0          22m

$ kubectl exec -it apache-deployment-857d559965-d7m4c -n default  -- /bin/bash
[root@apache-deployment-857d559965-d7m4c /]# cat /etc/resolv.conf 
nameserver 10.96.5.5

# Example 3
# Correct kube-dns referencing
# Terraform "oci_containerengine_cluster" with custom services CIDR (services_cidr = "10.125.0.0/16")

$ kubectl get services -A
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.125.0.1   <none>        443/TCP                  36m
kube-system   kube-dns     ClusterIP   10.125.5.5   <none>        53/UDP,53/TCP,9153/TCP   34m

$ kubectl get pods
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
default       apache-deployment-779dd79f6d-2f7mq     1/1     Running   0          22m

$ kubectl exec -it apache-deployment-779dd79f6d-2f7mq -n default  -- /bin/bash
[root@apache-deployment-779dd79f6d-2f7mq /]# cat /etc/resolv.conf 
nameserver 10.125.5.5
```

### Expected Behavior

When cluster is created via Terraform with default "oci_containerengine_cluster" settings it should create a cluster configured very similarly as a cluster created using the Orcale cloud web interface. This means, that the created cluster should reference the kube-dns service's IP correctly.

### Actual Behavior

When creating the Kubernetes cluster with the default service CIDR (10.96.0.0/16) the kube-dns service will take a random cluster IP and the dns is expected to be resolved from a fix IP. (See in Example 2. The 10.96.108.66 is the random IP which is allocated for the dns service and the 10.96.5.5 is the IP which is referenced where it should listen ) 

The issue impacts the domain name resolving for the POD within the Kubernetes cluster. Using ping with IP will work, but pinging a domain name won't. Means that the PODs (and the applications running on them) aren't able to communicate with servers outside of the cluster referenced via domain name. 

### Steps to Reproduce

1. Create a Kubernetes cluster via Terraform with default Kubernetes service CIDR settings.
2. Connect to the K8s cluster and check the IP of the running kube-dns service 
3. Deploy a POD of any kind, which you can use for debugging and check the /etc/resolv.conf 
(It should reference the kube-dns service IP!) 
4. Login to the POD and ping an external domain name  

### Important Factoids

It seems that on the Kubernetes clusters created with default settings through the Oracle cloud web interface the `kube-dns` service will always listen on the port 10.96.5.5 and not on a random port. (See in Example 1)

By configuring a custom CIDR for the Kubernetes internal services it is noticeable, that for the `kube-dns` the x.x.5.5 IP should be reserved, where x.x. is the fix part of the IP (See in Example 3)

The back-end workflow for creating a Kubernetes cluster via Terraform and via the Oracle cloud web interface seems to differ. It might be, because the various interfaces are using different API calls or the API is the same, but the execution plan differs.

The issue is independent from the selected Kubernetes version and happens only with clusters using default Kubernetes CIDR service settings.

**Comment by shyamradhakrishnan** [comment]
We have reproduced the issue and will be working on a fix in the next few days

**Comment by kviktorman** [comment]
Hi @shyamradhakrishnan, 
thanks for the confirmation!

If you manage to find the root cause and its not a Terraform bug, can you please link it somehow to here?
It might be helpful in the future if somebody runs into a similar issue.

Thanks a lot!
Viktor

**Comment by shyamradhakrishnan** [comment]
The bug is in OKE server, we have created a bug in OKE bug system, unfortunately, that is not a public facing bug system.

**Comment by shyamradhakrishnan** [comment]
@kviktorman This bug has been fixed, please check and update the bug as appropriate

**Comment by kviktorman** [comment]
Hi @shyamradhakrishnan, 
sorry for the late reply. 

I have checked, it works.
Thanks a lot for the fix and with the linking to the SR.

Viktor
