### ISSUE TITLE
Changing from VM.Standard2.x to VM.Standard.E3.Flex should trigger rebuild

### ISSUE THREAD

**Issue by twmcelroy** [terraform-providers/terraform-provider-oci#1063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
$ terraform -v
Terraform v0.12.20
+ provider.null v2.1.2
+ provider.oci v3.74.0

### Affected Resource(s)
oci_core_instance

### Terraform Configuration Files
Terraform will perform the following actions:

  module.instance1.oci_core_instance.this will be updated in-place
  ~ resource "oci_core_instance" "this" {
        availability_domain                 = "AD"
        boot_volume_id                      = "ocid1.bootvolume.oc1.abc"
        compartment_id                      = "ocid1.compartment.oc1..abc"
        defined_tags                        = {}
        display_name                        = "instance1"
        extended_metadata                   = {}
        fault_domain                        = "FAULT-DOMAIN-1"
        freeform_tags                       = {}
        hostname_label                      = "instance1"
        id                                  = "ocid1.instance.oc1.abc"
        image                               = "ocid1.image.oc1.phx.abc"
        is_pv_encryption_in_transit_enabled = false
        launch_mode                         = "NATIVE"
        metadata                            = {
            "ssh_authorized_keys" = <<~EOT
                ssh-rsa abc     EOT
            "user_data"           = "IA=="
        }
        preserve_boot_volume                = false
        private_ip                          = "10.0.1.10"
        public_ip                           = "129.146.xxx.xxx"
        region                              = "phx"
      ~ shape                               = "VM.Standard2.4" -> "VM.Standard.E3.Flex"
        state                               = "RUNNING"
        subnet_id                           = "ocid1.subnet.oc1.phx.abc"
        system_tags                         = {}
        time_created                        = "2020-04-15 21:11:07.949 +0000 UTC"

        agent_config {
            is_management_disabled = false
            is_monitoring_disabled = false
        }

        create_vnic_details {
            assign_public_ip       = "true"
            defined_tags           = {}
            display_name           = "instance1"
            freeform_tags          = {}
            hostname_label         = "instance1"
            nsg_ids                = []
            private_ip             = "10.0.1.10"
            skip_source_dest_check = false
            subnet_id              = "ocid1.subnet.oc1.phx.abc"
        }

        launch_options {
            boot_volume_type                    = "PARAVIRTUALIZED"
            firmware                            = "UEFI_64"
            is_consistent_volume_naming_enabled = true
            is_pv_encryption_in_transit_enabled = false
            network_type                        = "PARAVIRTUALIZED"
            remote_data_volume_type             = "PARAVIRTUALIZED"
        }

      ~ shape_config {
            gpus                          = 0
            local_disks                   = 0
            local_disks_total_size_in_gbs = 0
            max_vnic_attachments          = 4
            memory_in_gbs                 = 60
            networking_bandwidth_in_gbps  = 4.099999904632568
          ~ ocpus                         = 4 -> 6
            processor_description         = "2.0 GHz Intel® Xeon® Platinum 8167M (Skylake)"
        }

        source_details {
            boot_volume_size_in_gbs = "47"
            source_id               = "ocid1.image.oc1.phx.abc"
            source_type             = "image"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Debug Output

module.instance1.oci_core_instance.this: Modifying... [id=ocid1.instance.oc1.phx.abc]

Error: Service error:LimitExceeded. The number of VNICs on the current instance exceeds the maximum number of VNICs supported by shape VM.Standard.E3.Flex. Detach VNICs before changing shape.. http status code: 400. 

### Expected Behavior
Terraform would mark the instance for destruction and creation.

### Actual Behavior
Terraform tried to change the shape to Flex which would change the processor

### Steps to Reproduce
Have an existing instance on VM.Standard2.x and try to change to VM.Standard.E3.Flex
Terraform apply

**Comment by abhilash-av** [comment]
@twmcelroy 

Starting from Provider version 3.56.0 as mentioned in https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md#3560-december-18-2019(Support VM Instance resizing with reboot in oci_core_instance resource) shape is Updatable as far as the new shape is within the scope mentioned in https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md#notes-1  In all other cases Users will need to explicitly destroy and create the instance.
Closing this issue for now, let us know if you have any other questions.

 Thanks.
