### ISSUE TITLE
regional wallet download.

### ISSUE THREAD

**Issue by AmanDhaka1986** [terraform-providers/terraform-provider-oci#1064]
how could i download a regional wallet via terraform for an Autonomous database ?
only oci_database_autonomous_database_regional_wallet_management i can see not the oci_database_autonomous_database_regional_wallet ?

Thanks,
Aman

**Comment by rashik-bhasin** [comment]
Hi,
Thanks for asking the question. 
In terraform there is no oci_database_autonomous_database_regional_wallet, we refer to it as oci_database_autonomous_database_regional_wallet_management. It is the same thing. For getting the regional wallet data, you can use a this example: [example_link](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/wallets_management/regional/autonomous_database_regional_wallet_management.tf) .
Hope this helps.

**Comment by AmanDhaka1986** [comment]
Thanks Mate,
But my understanding is its just the wallet rotation not the wallet download option ?Please clarify.
Thanks,
Aman

**Comment by AmanDhaka1986** [comment]
tried this it just updated the wallet on GUI did not downloaded it, looking for a expample where i can download a regional wallet on my local system.
Thanks,
Aman

**Comment by AmanDhaka1986** [comment]
tried 

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}

provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}

resource "oci_database_autonomous_database_regional_wallet_management" "test_autonomous_database_regional_wallet_management" {
  should_rotate = false
}

data "oci_database_autonomous_database_regional_wallet_management" "test_autonomous_database_regional_wallet_management" {}

resource "local_file" "autonomous_database_wallet_file" {
  content_base64 = "${data.oci_database_autonomous_database_regional_wallet_management.test_autonomous_database_regional_wallet_management.content}"
  filename       = "${path.module}/autonomous_database_wallet.zip"
}


but did not worked, **



Error: Unsupported attribute

  on wallet.tf line 22, in resource "local_file" "autonomous_database_wallet_file":
  22:   content_base64 = "${data.oci_database_autonomous_database_regional_wallet_management.test_autonomous_database_regional_wallet_management.content}"

This object has no argument, nested block, or exported attribute named
"content".

**Comment by rashik-bhasin** [comment]
Hi, 
Thanks for the response. 
Firstly there is no resource with name "local_file" supported in the terraform provider. You can only specify the names that are supported by the terraform provider.  You can find them here: for database data sources [here](https://www.terraform.io/docs/providers/oci/d/database_autonomous_container_database.html) and database resources [here](https://www.terraform.io/docs/providers/oci/r/database_autonomous_container_database.html). 

Also how terraform works is that when you run this [example](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/wallets_management/regional/autonomous_database_regional_wallet_management.tf) , there will be a terraform.tfstate file created in the same directory as the example. It will have all the data present in it that is being sent in the response sent by the service team. 
You can check what response is sent by the service teams [here](https://docs.cloud.oracle.com/en-us/iaas/api/#/en/database/20160918/AutonomousDatabaseWallet/GetAutonomousDatabaseRegionalWallet)
Hope this clears your doubt. 

Closing this issue for now, let us know if you have any other questions.
Thanks

**Comment by AmanDhaka1986** [comment]
i tried to modify the code given here , local file is used 
terraform-provider-oci/examples/database/adb/autonomous_database_wallet.tf

with this above code wallet is being downloaded very nicely but only instance wallet not the regional wallet, that's why raised bug here as i do not see any provision to download a regional wallet ,

the link provided by you earlier is just managing the regional wallet it is not generating the file and download it for us, like instance wallet is being downloaded provided the link by me above.

I assume the issue and bug is still open to look by someone in community , we should not close the ticket.
