### ISSUE TITLE
oci_core_default_route_table missing from provider docs

### ISSUE THREAD

**Issue by twirrim** [terraform-providers/terraform-provider-oci#1066]
Under https://www.terraform.io/docs/providers/oci
You'll find no reference to oci_core_default_route_table as used here:

https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/vcn_default/vcn.tf#L33

This presented an interesting stumbling block to getting NAT routing working as desired, until I found the above example.

**Comment by alexng-canuck** [comment]
Does this help? https://www.terraform.io/docs/providers/oci/guides/managing_default_resources.html

**Comment by rashik-bhasin** [comment]
Closing this issue. Feel free to reach out to us.
Thanks!

**Comment by et304383** [comment]
Anyone coming from Google the docs for this appear to now be located at:

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-vcndefaults.htm
