### ISSUE TITLE
Download Regional wallet for Autonomous databases.

### ISSUE THREAD

**Issue by AmanDhaka1986** [terraform-providers/terraform-provider-oci#1067]
creating the bug again as 1064 has been closed, there is scope of getting the new code or improvement as one functionality is not yet available.
Regional wallet download option is not there via terraform yet.
Thanks,
Aman

**Comment by AmanDhaka1986** [comment]
https://github.com/terraform-providers/terraform-provider-oci/issues/1064#issue-617392954

**Comment by rashik-bhasin** [comment]
Hi,
Thanks for the response. 
I get your point now. Currently it's not supported by the service team, raised the issue with them. Once they implement it, we'll support that as well.
Thanks.

**Comment by rashik-bhasin** [comment]
Hi,
Thanks for reporting this issue. 
The content type is not supported for the regional wallet by the service team at the moment. 
I have transferred this to the service team.

**Comment by rashik-bhasin** [comment]
Hi,
Using this example here: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/adb/autonomous_data_warehouse_wallet.tf#L9 and also setting generate_type = "ALL"  will download the regional wallet. It is  mentioned here as well: https://www.terraform.io/docs/providers/oci/d/database_autonomous_database_wallet.html. 
Can you try this out and confirm if you are able to download the regional wallet.
Thanks.

**Comment by rashik-bhasin** [comment]
Closing this ticket. Feel free to reach out to us.
