### ISSUE TITLE
How to detect drift in rules assigned to an NSG?

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1068]
I've encountered issues recently with Network Security rules that were manually added and therefore not recognized as changes via ```terraform plan```. I am looking for advice (hopefully not "don't let people use the OCI Console") on techniques to detect drift among the rules.

While a Subnet Security List exposes drift because the rules are managed as a "set" I don't yet see any means for similar detection among NSG rules.  I appreciate that they are independent "resources" to be tracked and managed but still hoping for a way to reliably "compare" or otherwise recognize whether the rules defined in my collection of ```oci_core_network_security_group_security_rule``` resources match or vary from the collection of all rules associated with an NSG.

Even knowing a variance exists is useful whether or not I can easily correct the variance via script or manual effort.

Thank you for your kind input.

**Comment by rashik-bhasin** [comment]
Hi,
Can you share the terraform config that you are trying to run?
Thanks!

**Comment by jeliker** [comment]
Consider this

```hcl
resource "oci_core_network_security_group" "nsg1" {
  compartment_id = var.compartment_id
  vcn_id         = var.vcn_id

  display_name   = "NSG1"
}

resource "oci_core_network_security_group_security_rule" "rule1" {
  network_security_group_id = oci_core_network_security_group.nsg1.id
  direction                 = "INGRESS"
  description               = "Secure HTTP"
  protocol                  = 6 #TCP

  source                    = "0.0.0.0/0"
  source_type               = "CIDR_BLOCK"
  stateless                 = false
  tcp_options {
    destination_port_range {
      max = 443
      min = 443
    }
  }
}
```

Assume that is deployed via `terraform apply`. Now, if one from the OCI management team adds a new rule—lets say they add **ingress from 0.0.0.0/0 to tcp/80**—from Terraform we have no direct knowledge of that change.  If we delete all rules in the above script (the one rule I show), `terraform refresh` and such will suggest there are no rules remaining.

This is unlike behavior of the Security List which considers the entire set of rules to be "right" or "wrong."

Where this is most concerning is when there are many, many rules (not my simple example). If a "rogue" rule is added among the collection of valid rules it's not easy to locate or even notice.

**Comment by kostasns** [comment]
After reading this I've went and tried it in our setup and can confirm this. Adding a rule to NSG does not trigger terraform to remove it.

**Comment by parrneet** [comment]
Hi @jeliker - Reason for terraform not complaining about the new rule is because network security group security rules are separate resources and in this case this new rule is simple a resource that you have in console but is not managed by terraform.

To put this in another scenario, this is like having a core instance only in console in addition to the infrastructure managed by terraform. Terraform won't complain about any such additional resource you have in console.

This works for security lists because rules are part of the security list resource and a plan after adding rules from another surface will result and config and state mismatch for the resource.

NSG Security Rule are by design like this due to the API limitations.

**Comment by jeliker** [comment]
Thank you for the explanation. I'm glad to see your words match my understanding and variation from handling of Security Lists and related rules.

I was hoping to understand a technique to process by which one could reliably monitor for drift among the NSG ruleset.  In the absence of best-practice for such management, perhaps I'll explore some trickery related to `data.oci_core_network_security_group_security_rules` to formulate an audit script.

Thank you for your comments.
