### ISSUE TITLE
Replacing oci_load_balancer_backend_set does not trigger replacement of assigned oci_load_balancer_backend resources

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.oci v3.76.0

### Affected Resource(s)

* oci_load_balancer_backend_set
* oci_load_balancer_backend

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_backend_set" "bes1" {
  health_checker {
    protocol = "TCP"
  }
  load_balancer_id = var.lb_id
  name             = "BES1"
  policy           = "ROUND_ROBIN"
}

resource "oci_load_balancer_backend" "be1" {
  backendset_name  = oci_load_balancer_backend_set.bes1.name
  ip_address       = var.ip_address
  load_balancer_id = oci_load_balancer_backend_set.bes1.load_balancer_id
  port             = var.port
}
```

### Expected Behavior

Replacing `oci_load_balancer_backend_set` should cause all assigned `oci_load_balancer_backend` to be replaced

### Actual Behavior

Replacing `oci_load_balancer_backend_set` via `terraform taint` or `terraform destroy` leaves assigned `oci_load_balancer_backend` behind. Subsequent `terraform refresh` or `terraform apply` delays while trying to refresh the missing resources.

### Steps to Reproduce

1. `terraform apply`
 Plan: 2 to add, 0 to change, 0 to destroy.
 Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
2. `terraform taint oci_load_balancer_backend_set.bes1`
 Resource instance oci_load_balancer_backend_set.bes1 has been marked as tainted.
3. `terraform apply`
 oci_load_balancer_backend_set.bes1 is tainted, so must be replaced
 Plan: 1 to add, 0 to change, 1 to destroy.
 Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
4. `terraform state list`
 oci_load_balancer_backend.be1
 oci_load_balancer_backend_set.bes1 _(thinks the backend still exists but it does not)_
5. `terraform state refresh` _(followed by long delay while it tries to refresh oci_load_balancer_backend.be1)_
6. `terraform state list`
 oci_load_balancer_backend_set.bes1

Following I can use apply to recreate the backend that was removed.

**Comment by varmax2511** [comment]
Hi @jeliker  -- thanks for reaching out. I find that issuing destroy for `oci_load_balancer_backend_set` using `terraform destroy -target oci_load_balancer_backend_set.bes1` triggers destroy for both `oci_load_balancer_backend_set` and `oci_load_balancer_backend`

 ```
  # oci_load_balancer_backend.be1 will be destroyed
2020/05/26 17:36:40 [DEBUG] command: asking for input: "Do you really want to destroy all resources?"
  - resource "oci_load_balancer_backend" "be1" {
      - backendset_name  = "BES1" -> null
      - backup           = false -> null
      - drain            = false -> null
      - id               = "xxxxxxx" -> null
      - ip_address       = "xxxxxx" -> null
      - load_balancer_id = "xxxxxx" -> null
      - name             = "xxxxx" -> null
      - offline          = false -> null
      - port             = xx -> null
      - state            = "SUCCEEDED" -> null
      - weight           = 1 -> null
    }

  # oci_load_balancer_backend_set.bes1 will be destroyed
  - resource "oci_load_balancer_backend_set" "bes1" {
      - backend          = [
          - {
              - backup     = false
              - drain      = false
              - ip_address = "xxxx"
              - name       = "xxxxxx"
              - offline    = false
              - port       = xxx
              - weight     = 1
            },
        ] -> null
      - id               = "xxxxx" -> null
      - load_balancer_id = "xxxxxx" -> null
      - name             = "BES1" -> null
      - policy           = "ROUND_ROBIN" -> null
      - state            = "SUCCEEDED" -> null

      - health_checker {
          - interval_ms         = xxx -> null
          - port                = 0 -> null
          - protocol            = "TCP" -> null
          - response_body_regex = ".*" -> null
          - retries             = xx -> null
          - return_code         = xxxx -> null
          - timeout_in_millis   = xxxx -> null
        }
    }

Plan: 0 to add, 0 to change, 2 to destroy.
 ```

 I am able to reproduce the scenario you mentioned above in case of `taint` for `oci_load_balancer_backend_set`, where tainting the resource doesn't ask for recreating the `oci_load_balancer_backend`. This can be attributed to the fact that `taint` is different than `destroy` per https://www.terraform.io/docs/commands/taint.html
 ```
 Note that tainting a resource for recreation may affect resources that depend on the newly tainted resource. For example, a DNS resource that uses the IP address of a server may need to be modified to reflect the potentially new IP address of a tainted server. 
 ```
Once a terraform plan or refresh is done, only then is effect visible. 
This behavior is related to terraform core and not terraform oci provider. Please let us know if this resolves the issue.

**Comment by varmax2511** [comment]
Hi @jeliker -- did the above comment resolve your issue?

**Comment by varmax2511** [comment]
Closing the issue, please feel free to reopen if further questions
