### ISSUE TITLE
 data "oci_containerengine_work_request_log_entries" returns emply lists

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1072]
Hi the  call :
data "oci_containerengine_work_request_log_entries" "test_work_request_log_entries" {
    #Required
    compartment_id =xxx
    work_request_id = xxxx
}

from https://www.terraform.io/docs/providers/oci/d/containerengine_work_request_log_entries.html
is supposed to return the the logs of a work request.

Actually this call returns an empty list

in my code :
output "work_request_log" {
value = data.oci_containerengine_work_request_log_entries.test_work_request_log_entries.work_request_log_entries
}

 terraform -v
Terraform v0.12.25
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.oci v3.75.0
+ provider.template v2.1.2

work_request_log = []

i m internal you can ping me and i will give you the details of the tf cluster , work request id to reproduce
thanks
eugene

**Comment by rashik-bhasin** [comment]
Hi,
I tried on one of our examples and i am able to get the logs.  This is the example i ran: 
`variable "tenancy_ocid" {}

variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  region           = "${var.region}"
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

variable "compartment_id" { default = "ocid1.compartment.oc1.. Insert your compartment id here" }

resource "oci_containerengine_cluster" "test_cluster" {
  compartment_id = "${var.compartment_id}"
  kubernetes_version = "${data.oci_containerengine_cluster_option.test_cluster_option.kubernetes_versions[length(data.oci_containerengine_cluster_option.test_cluster_option.kubernetes_versions)-1]}"
  name = "name"
  vcn_id = "${oci_core_vcn.test_vcn.id}"
}

resource "oci_core_subnet" "clusterSubnet_1" {
  availability_domain = "${lower("${data.oci_identity_availability_domains.test_availability_domains.availability_domains.0.name}")}"
  cidr_block = "10.0.20.0/24"
  compartment_id = "${var.compartment_id}"
  dns_label = "cluster1"
  vcn_id = "${oci_core_vcn.test_vcn.id}"
}

resource "oci_core_subnet" "clusterSubnet_2" {
  availability_domain = "${lower("${data.oci_identity_availability_domains.test_availability_domains.availability_domains.0.name}")}"
  cidr_block = "10.0.21.0/24"
  compartment_id = "${var.compartment_id}"
  dns_label = "cluster2"
  vcn_id = "${oci_core_vcn.test_vcn.id}"
}

data "oci_identity_availability_domains" "test_availability_domains" {
  compartment_id = "${var.tenancy_ocid}"
}

data "oci_containerengine_cluster_option" "test_cluster_option" {
  cluster_option_id = "all"
}

resource "oci_core_vcn" "test_vcn" {
  cidr_block = "10.0.0.0/16"
  compartment_id = "${var.compartment_id}"
  dns_label = "dnslabel"
}

data "oci_containerengine_work_requests" "test_work_requests" {
  cluster_id = "${oci_containerengine_cluster.test_cluster.id}"
  compartment_id = "${var.compartment_id}"
  resource_id = "${oci_containerengine_cluster.test_cluster.id}"
  resource_type = "CLUSTER"
  status = []
}

data "oci_containerengine_work_request_log_entries" "test_work_request_log_entries" {
  compartment_id = "${var.compartment_id}"
  work_request_id = "${lookup(data.oci_containerengine_work_requests.test_work_requests.work_requests[0], "id")}"
}

output "work_request_log" {
  value = ["${data.oci_containerengine_work_request_log_entries.test_work_request_log_entries.work_request_log_entries}"]
}
`
Can you check if you are missing something on in the terraform config?

**Comment by eugsim1** [comment]
thanks for the reply i have to review my code to check why the list is empy
your implementation gives back all the details :)
