### ISSUE TITLE
How can I use terraform regular expressions to get latest OCI image

### ISSUE THREAD

**Issue by psaddi** [terraform-providers/terraform-provider-oci#1078]
My goal is to always get the latest OCI Image for say Oracle Linux 7.8. OCI provide 2 images in the list shown below. However I would like to use a regex so the Gen2-GPU image is filtered out. Could you please suggest me the best way to do this?

- Oracle-Linux-7.8-2020.04.17-0
- Oracle-Linux-7.8-Gen2-GPU-2020.04.17-0

Here's a simple snippet of code :

variable "os_version" {
  default = "7.8"
}
variable "os_name" {
  default = "Oracle Linux"
}

data "oci_core_images" "os_images" {
    #Required
    compartment_id = "${var.compartment_ocid}"

    operating_system = "${var.os_name}"
    operating_system_version = "${var.os_version}"
    state = "AVAILABLE"
    sort_by = "TIMECREATED"
    sort_order = "DESC"

    filter {
        name = "display_name"
        regex = true
        **values = ["(?:Gen2-GPU)??"]**
    }
}

output "image_list" {
  value = data.oci_core_images.os_images.images
}

The above always lists both the 7.8 images, while I only want the non Gen2 image only.

My regex is based on what terraform provides here : https://www.terraform.io/docs/configuration/functions/regex.html

**Comment by psaddi** [comment]
Using values = ["^([a-zA-z]+)-([a-zA-z]+)-([\\.0-9]+)-([\\.0-9-]+)$"], seems to solve it but is pretty dirty and verbose and too dependent on the structure. I would like to be able to use a negation pattern instead

**Comment by varmax2511** [comment]
Hi @psaddi -- thanks for reaching out. Please try to use the below pattern to filter Gen2-GPU image
```
data "oci_core_images" "os_images" {
  #Required
  compartment_id = "${var.compartment_ocid}"

  operating_system = "${var.os_name}"
  operating_system_version = "${var.os_version}"
  state = "AVAILABLE"
  sort_by = "TIMECREATED"
  sort_order = "DESC"

  filter {
    name = "display_name"
    regex = true
    values = [".*Gen2-GPU.*"]
  }

}
```
Please let us know if this resolves your issue

**Comment by psaddi** [comment]
Thank you for your response. Actually I don't want the Gen2-GPU image, so I would like to use a negation pattern. Is there a way to add a regex which can give me all images who don't have 'Gen2-GPU'

**Comment by mulpk** [comment]
investigating the possible options here. I will get back on this shortly

**Comment by mulpk** [comment]
```^((?!Gen2-GPU).)*$``` regex is what you are looking for but it doesn't work with the filter as Golang regex library doesn't support negative lookahead.  

I see ```["^([a-zA-z]+)-([a-zA-z]+)-([\\.0-9]+)-([\\.0-9-]+)$"]``` is the best option for getting non Gen2-GPU images

tested the regex with Oracle Linux 7x and 6x images and it works fine. 
https://docs.cloud.oracle.com/en-us/iaas/images/oraclelinux-7x/
https://docs.cloud.oracle.com/en-us/iaas/images/oraclelinux-6x/

**Comment by psaddi** [comment]
Thank you. I will use that work around. Appreciate you guys looking at it
