### ISSUE TITLE
Return the secret for a customer secret key created using oci_identity_customer_secret_key resource

### ISSUE THREAD

**Issue by jsmcnair** [terraform-providers/terraform-provider-oci#1085]
I'm using the OCI terraform provider to provision resources on behalf of customers. One aspect of this is that they use Object storage via the S3 compatibility layer. To do this I will have to provision a customer secret key on their behalf.

I have used the `oci_identity_customer_secret_key` resource successfully but I can't see how to retrieve the secret. The key id is available via the REST endpoint, but not (as far as I can tell) the secret.

Does anyone have any prior success with this? Is it even possible?

**Comment by alexng-canuck** [comment]
Have you tried referencing the `key` attribute of the `oci_identity_customer_secret_key` resource? https://www.terraform.io/docs/providers/oci/r/identity_customer_secret_key.html#key

**Comment by alexng-canuck** [comment]
@jsmcnair , does the above reference answer your question?

Let us know if you have further questions.

**Comment by jsmcnair** [comment]
Hi @alexng-canuck. As far as I could tell this only returned the key id. We need the secret to be accessible also otherwise the key is useless.

**Comment by alexng-canuck** [comment]
@jsmcnair , I ran the following example and the `key` value I get back from the `oci_identity_customer_secret_key` resource is the key value (not an ID).

For example:
```
resource "oci_identity_customer_secret_key" "customer-secret-key1" {
  user_id      = "${oci_identity_user.user1.id}"
  display_name = "tf-example-customer-secret-key"
}

output "customer-secret-key" {
  value = "${oci_identity_customer_secret_key.customer-secret-key1.key}"
}
```

And the output value I get from the `key` attribute is a key value that looks like this, rather than an ID: `aBcdeFGHukinzR9ZXKNEcXpLU9/99abCde6FGHi2jKl=`

Have you tried this? What kind of value do you get back instead?

**Comment by alexng-canuck** [comment]
Also keep in mind that these keys are only accessible from the `oci_identity_customer_key` resource. 

If you're using a data source to get the key value, that isn't supported because the service APIs do not allow returning keys as part of queries (for security reasons).

**Comment by jsmcnair** [comment]
Thanks @alexng-canuck I was getting the ID and the key mixed up, which doesn't help. However it was also not clear to me that the ID of the key is supplied by the ID attribute. I was misled by the description which says "The OCID of the secret key". I was thinking of a normal Oracle OCID, so was expecting the retrieve the key ID via another property.

I don't know if it's just me but I'm think it might be more intuitive to update the documentation to explicitly state that the ID is not an OCID style but the actual key ID?

**Comment by alexng-canuck** [comment]
@jsmcnair 

I see your point. The documentation mentions:
```
id - The OCID of the secret key.
key - The secret key.
```

The `key` description is correct (it is the secret key that we get back from the service). The `id` description is incorrect, however, as it currently returns the access key and not an OCID.

This doc issue is also in the relevant service API documentation for this feature: https://docs.cloud.oracle.com/en-us/iaas/api/#/en/identity/20160918/CustomerSecretKey/

We will work with the relevant service team to address this in the documentation.
