### ISSUE TITLE
clone of dedicated database ATP.

### ISSUE THREAD

**Issue by AmanDhaka1986** [terraform-providers/terraform-provider-oci#1095]
Hi All,
Trying to create clone of dedicated autonomous database via terraform but failing with below error, any help plz..

Error: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. Opc request id: bb415ef662288245c9d2b8053d2b4381/034594DCD65AB3EA7215040DFDC05125/AAC446F2E69FDA942406E1B2F47F1A5D

  on main.tf line 1, in resource "oci_database_autonomous_database" "autonomous_database":
   1: resource "oci_database_autonomous_database" "autonomous_database" {

Terraform file ...

[oracle@daznadmin dedicated_exadata]$ cat main.tf
resource "oci_database_autonomous_database" "autonomous_database" {
  admin_password           = "*******"
  compartment_id           = "ocid1.compartment.oc1..a******************"
  cpu_core_count           = "8"
  data_storage_size_in_tbs = "2"
  db_name                  = "SP****"
  clone_type               = "FULL"
  display_name             = "SP*****"
  is_auto_scaling_enabled  = "false"
  is_dedicated             = "true"
  license_model            = "PAID"
  source                   = "DATABASE"
  autonomous_container_database_id = "ocid1.autonomouscontainerdatabase.oc1*******"
  source_id                = "ocid1.autonomousdatabase.oc1.uk-london-********"
}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by alexng-canuck** [comment]
Hi @AmanDhaka1986 ,

We are following up with the upstream service. The error is coming from the service and indicates a possible misconfiguration. Will keep you posted.

Thanks,
Alex

**Comment by alexng-canuck** [comment]
@AmanDhaka1986 , to help investigate, can you share details of your tenancy OCID, region, and container OCID with us via e-mail? If you can associate your e-mail address with your github profile, we can contact you outside of github.

**Comment by AmanDhaka1986** [comment]
I got the issue solved, Thanks.

**Comment by alexng-canuck** [comment]
@AmanDhaka1986 glad to see it was resolved. Just for our information, how was it resolved? Was this an issue with the configuration?
