### ISSUE TITLE
issue on data "oci_database_databases" 

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1096]
Hi team
i m running a simple call :

data "oci_database_databases" "test_databases" {
    #Required
    compartment_id= var.oci_base_general.compartment_id
}
and i m getting the following error :
Error: Service error:MissingParameter. This request is missing a required value for at least one of the following arguments: dbHomeId,systemId. http status code: 400. Opc request id: 02d6852fe1e1f54773e2d228cb8730e0/4D8ABF5DCB123DAB7FE588BF8FEF0D52/0CC2D6A82AAA6E4E20D3292495A77508

  on datasources.tf line 26, in data "oci_database_databases" "test_databases":
  26: data "oci_database_databases" "test_databases" {
but in the docs and unless i m wrong only the first parameters is mandatory
is there an issue ?

**Comment by eugsim1** [comment]
in the docs its said databases in database home ... maybe the doc is wrong  :
The following arguments are supported:

    compartment_id - (Required) The compartment OCID.
    db_home_id - (Optional) A Database Home OCID.
    db_name - (Optional) A filter to return only resources that match the entire database name given. The match is not case sensitive.
    state - (Optional) A filter to return only resources that match the given lifecycle state exactly.
    system_id - (Optional) The OCID of the Exadata DB system that you want to filter the database results by. Applies only to Exadata DB systems.

**Comment by alexng-canuck** [comment]
@eugsim1 , it looks like a docs issue.

The Database service requires one of either `db_home_id` or `system_id` to be set, in order to get your databases. 

Unfortunately, the current doc structure doesn't have a good way of saying when either one of 2 fields is required; and that's why they're both marked as `(Optional)`.

Will follow-up to see how the docs can be improved.

**Comment by eugsim1** [comment]
yes i was reading the optional and i have removed them from my code ... then reading back the doc it was somehow more clear ... no worries
