### ISSUE TITLE
description of oci_load_balancer_backend_set  is missing several fields in the example usage

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1100]
Hello
Can you please provide a detailed updated example usage of the api  : https://www.terraform.io/docs/providers/oci/r/load_balancer_backend_set.html#oci_load_balancer_backendset

Reading the example i see that there are several missing fields : backend - (Optional) (Updatable)
we cannnot guess every time what is needed if the example usage is not explicit

**Comment by srishtipmishra** [comment]
@eugsim1 - Working examples can be found here - https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/load_balancer/lb_full

Thanks for bringing these to notice. Terraform team will take this to better our documentation.

**Comment by eugsim1** [comment]
Hi 
then please update them with all flags just to be sure that we dont reinvent the wheel neither we spend time trying to guess
