### ISSUE TITLE
How to create a compute instance and assign a second private ip to the first VNIC

### ISSUE THREAD

**Issue by LorenzKeller** [terraform-providers/terraform-provider-oci#1103]
Dear,
I like to create a compute instance and assign to the primary VNIC (public ip ..., private ip 10.4.9.2) a second private ip 10.4.9.3. (not creating a secondary VNIC!).

I cannot find anything in the examples.
Any idea, how to do this is welcome!

Kind regards
Lorenz

**Comment by rramge** [comment]
Hi Lorenz,

not sure if I understand your problem correctly, but I would point you towards https://www.terraform.io/docs/providers/oci/r/core_private_ip.html

Give the ID of the primary VNIC as argument and it should work

Ralf

**Comment by parrneet** [comment]
Thank you @rramge for the response. 

Hi @LorenzKeller 
@rramge 's suggestion is the way to add secondary private IP to an existing VNIC.  

Feel free to reopen the issue, if this does not work for you.
