### ISSUE TITLE
Re: mount_target_id is null in export set

### ISSUE THREAD

**Issue by csetarun2** [terraform-providers/terraform-provider-oci#1104]
I am trying to import File system export set information to terraform state file, It got exported but in the export set parameters the mount_target_id value showing null....
[When we create mount target it will create an export set for that mount target, so it must return mount_target_id in the export set parameters. it should not be null]

In the export set API , this parameter not exist.

`
>>> es=fs.get_export_set(export_set_id="ocid1.exportset.oc1.phx.aaaaaby27vfaiggaobuhqllqojxwiotxxxxxxxxxx")
>>> print(es.data)
{
  "availability_domain": "wdWU:PHX-AD-2",
  "compartment_id": "ocid1.compartment.oc1..aaaaaaaa4fr2bnlfwxxh35mtc4rminc2bxspdgqobeerkk347xxxxxxxxxx",
  "display_name": "MountTarget-20200622-1119 - export set",
  "id": "ocid1.exportset.oc1.phx.aaaaaby27vfaiggaobuhqllqojxwiotqnb4cxxxxxxxxx",
  "lifecycle_state": "ACTIVE",
  "max_fs_stat_bytes": 9223372036854775807,
  "max_fs_stat_files": 9223372036854775807,
  "time_created": "2020-06-22T11:20:03.211000+00:00",
  "vcn_id": "ocid1.vcn.oc1.phx.amaaaaaav7zeaxyaw3skhbobzbov6cagasgno7spkgxxxxxxxxxxxxxx"
}
>>>            
`

when I execute this import command 
`terraform import oci_file_storage_export_set.singlMT-ES ocid1.exportset.oc1.phx.aaaaaby27ve7fs5kobuhqllqojxwiotqnb4c2ylefuzqaaaa`

the terraform file will generate like this 

`
terraform.tfstate
    {
      "mode": "managed",
      "type": "oci_file_storage_export_set",
      "name": "singlMT-ES",
      "provider": "provider.oci",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "availability_domain": "wdWU:PHX-AD-1",
            "compartment_id": "ocid1.compartment.oc1..aaaaaaaa4fr2bnlfwxxh35mtc4rminc2bxspdgqobeerkkxxxxxxxxxx",
            "display_name": "singlMT - export set",
            "id": "ocid1.exportset.oc1.phx.aaaaaby27ve7fs5kobuhqllqojxwiotqxxxxxxxxxxxx",
            "max_fs_stat_bytes": "9223372036854775807",
            "max_fs_stat_files": "9223372036854775807",
            **"mount_target_id": null,                                                                      ->       Its taking null value**
            "state": "ACTIVE",
            "time_created": "2020-06-26 09:44:11.055 +0000 UTC",
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "vcn_id": "ocid1.vcn.oc1.phx.amaaaaaav7zeaxyaw3skhbobzbov6cagasgno7sxxxxxxxxxxxxx"
          },
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjo5MDAwMDAwMDAwMDAsImRlbGV0ZSI6OTAwMDAwMDAwMDAwLCJ1cGRhdGUiOjkwMDAwMDAwMDAwMH0sInxxxxxxxxxxxxxxxxxxxxxx"
        }
      ]
    },

`
From where its picking value, it should not return null value

**Comment by parrneet** [comment]
Hi @csetarun2 

Thank you for reporting this.
Terraform provider does not get this field from GET API so we can't set it. We have raised this with the service to return the field in response.

Meanwhile, if this is blocking you, workaround is to set the field manually in config and state file.

**Comment by nagulako** [comment]
Hi Parrneet - The Python API shows that this data is available when retrieving the Mount Target via the Python API:

https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/file_storage/models/oci.file_storage.models.MountTarget.html#oci.file_storage.models.MountTarget

Is there a different GET API that TF is targetting?

**Comment by srishtipmishra** [comment]
Closing the ticket as per discussion with customer - resorted to not using export_set resource explicitly and modifying
oci_file_storage_export resource to use export_set_id = "${oci_file_storage_mount_target.""" + mount_target_tf_name + """.export_set_id}"
