### ISSUE TITLE
IAM dynamic group example incorrect

### ISSUE THREAD

**Issue by smithzc** [terraform-providers/terraform-provider-oci#1113]
The example code is:

 matching_rule  = "instance.compartment.id = ${data.oci_identity_compartments.compartments1.compartments.0.id}"

This doesn't actually work - it should be:

 matching_rule  = "ANY {instance.compartment.id = '${data.oci_identity_compartments.compartments1.compartments.0.id}'}"

**Comment by yifnfan** [comment]
Hi,
Thanks for the reporting. I've cut a ticket to update it in our example.

**Comment by yifnfan** [comment]
Hi smithzc,
we've updated the examples in release 3.85.0. Please check it later. Thanks for the reporting again. I will close this ticket now
