### ISSUE TITLE
Route table/gateway dependency graphs might be incorrect

### ISSUE THREAD

**Issue by michael-cico** [terraform-providers/terraform-provider-oci#1114]
I've been trying to recreate gateways in our VCNs, by adding conditionals to the gateway (SGW, IGW, NAT) resources and then conditionalizing the route-table references that use them.  The plan looks correct, but on apply I get failures because Terraform is trying to destroy the gateways before removing the route table references.  It would seem to be a problem with the dependency graph between those resources.

I also tried using the "taint" command to force re-creation of the gateways; the plan again looked correct but I'm getting CONFLICT errors when applying, in the same manner.

This is with the 3.72 provider.

**Comment by michael-cico** [comment]
The tool in the UI shapshots above is just a wrapper around Terraform and the OCI provider.  I get the same plan on the command-line.

**Comment by yifnfan** [comment]
Hi michael-cico,
Thanks for the reporting. Could you share the log of the error and the tf configuration files with us to help us determine what happens in this situation?

**Comment by michael-cico** [comment]
I'm going to try to create a minimal reproducer from an example if I can.

**Comment by jotruon** [comment]
Hi @michael-cico,
This is a service limitation, Terraform try to do the right thing with the graph and plan.
