### ISSUE TITLE
Public Key present in example

### ISSUE THREAD

**Issue by smithzc** [terraform-providers/terraform-provider-oci#1119]
Might want to sanitize this:

https://github.com/terraform-providers/terraform-provider-oci/blob/b081fddbb26a517bb647cca2c4e7ea822d58b7fe/examples/storage/fss/variables.tf#L17-L19

**Comment by zexinwanoci** [comment]
Thanks for reporting it, will fix in this week's release.

**Comment by zexinwanoci** [comment]
Fix is in the newest release, closing this ticket.
