### ISSUE TITLE
data "oci_dns_records"  should return 0 record if there arent any and not give an error in terrafrom 

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1122]
Hello
I using the datasource data "oci_dns_records"  to create a report on the dns configuration in several tenancies if there no zones in the compartement the call fails and breaks terraform in the logs i see that either the call doesnt have the Authorisation or the resource is not found
Resource not found should return 0 records and not an exception 

Error: Service error:TooManyRequests. Too Many Requests. http status code: 429. Opc request id: 72de828a0be14f388e07b20ebafef7b5/EC0DFA65DFE249F9935B5DCDE82DEDB8/9264138537E149DB858FECE46DCB55EE

in the go.sdk code this is a minor modification !

  on datasource.tf line 175, in data "oci_dns_records" "dns_records":
 175: data "oci_dns_records" "dns_records" { 

compared to oci cli the behavior is correct 

{
  "opc-total-items": "0"
}

{
  "data": [
    {
      "compartment-id": "ocid1.compartment.oc1..aaaaaaaakjdnf7ik2kejcaj73uwx6tsochnlq5olj3vebgbwcf67bjnab3ya",
      "defined-tags": {
        "Oracle-Tags": {
          "CreatedBy": "oracleidentitycloudservice/XXXXXXXXX",
          "CreatedOn": "2020-05-22T22:25:45.645Z",
          "ResourceAllocation": "Global"
        }
      },
      "freeform-tags": null,
      "id": "ocid1.dns-zone.oc1..14b0eda79dac4a97ac331dec4644486a",
      "lifecycle-state": "ACTIVE",
      "name": "oraclecloudpursuitlabs.com",
      "self-uri": "https://dns.eu-frankfurt-1.oraclecloud.com/20180115/zones/oraclecloudpursuitlabs.com",
      "serial": 112,
      "time-created": "2020-05-22T22:25:48+00:00",
      "version": "112",
      "zone-type": "PRIMARY"
    }
  ],
  "opc-total-items": "1"
}

**Comment by zexinwanoci** [comment]
Hello, we were not able to reproduce this issue since we can not create a zone withougt any dns records(it automatically create 5 for default and they can not be deleted). And we suggest you to run this following tf file in a clean folder with no other resources so we can confirm that this is an issue with terraform or go sdk. 
/*
 * Open a new folder, run this script against the Zone for which your DNS record data source is throwing an error
 * We are not repro the scenario where a Zone is having no DNS records
 */

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  region           = "${var.region}"
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

data "oci_dns_records" "rs" {
  zone_name_or_id = "oraclecloudpursuitlabs.com"
}

output "records" {
  value = "${data.oci_dns_records.rs.records}"
}

**Comment by eugsim1** [comment]
Hello the issue is when i m trying to read dns info from a compartment that hasnt any zones 
My workaround is the following :
Get all dns zones from every compartment
Pass the compartments with the dns zone to the call  see the code :
```
## get all zones from every compartment of the tenancy 
data "oci_dns_zones" "dns_zones" {
  count          = (var.report_dns_zones == true) ? "${length(local.ALL_COMPARTMENT_OCID)}" : 0
  compartment_id = local.ALL_COMPARTMENT_OCID[count.index] 
}


resource "local_file" "dns_zones" {
  count = (var.report_dns_zones == true) ? 1 : 0
  content = "[dns_zones]${join(" ", formatlist("\n%-30s %-30s %-30s %-30s %s  ",
    flatten(data.oci_dns_zones.dns_zones[*].zones[*].name),
    data.oci_identity_compartment.DNS_compartment[*].name,
    flatten(data.oci_dns_zones.dns_zones[*].zones[*].compartment_id),
    flatten(data.oci_dns_zones.dns_zones[*].zones[*].id),
    ##flatten(data.oci_dns_zones.dns_zones[*].zones[*].nameservers[*] ),
  flatten(data.oci_dns_zones.dns_zones[*].zones[*].state), ), )}"
  filename = "report_tenancy_config/dns_zones.txt"
}


/*
## this call has issues here i m getting TF errors 
data "oci_dns_records" "dns_records_terraform" {
  depends_on = [ data.oci_dns_zones.dns_zones" ]
  count          = (var.report_dns_records == true) ?  length(local.DNS_COMPARTMENT_ID) : 0
  compartment_id = local.DNS_COMPARTMENT_ID[count.index]
  zone_name_or_id = "oraclecloudpursuitlabs.com" #"${oci_dns_zone_name_or.test_zone_name_or.id}"

  ##count          = "${length(local.COMPARTMENTS_OCID)}"
  ##compartment_id = local.COMPARTMENTS_OCID[count.index] ###"ocid1.compartment.oc1..aaaaaaaakjdnf7ik2kejcaj73uwx6tsochnlq5olj3vebgbwcf67bjnab3ya"##
   #Optional
  #   domain = "${var.record_domain}"
  #   domain_contains = "${var.record_domain_contains}"
  #   rtype = "${var.record_rtype}"
  #   zone_version = "${var.record_zone_version}"
}
*/

### give the list of the zones from the previous call 
### and get all dns records 
data "oci_dns_records" "dns_records" {
  depends_on      = [data.oci_dns_zones.dns_zones]
  count           = (var.report_dns_records == true) ? length(local.ZONE_NAMES) : 0
  zone_name_or_id = local.ZONE_NAMES[count.index] ###"oraclecloudpursuitlabs.com" 
}


resource "local_file" "dns_records" {
  count = (var.report_dns_records == true) ? 1 : 0
  content = "[dns_records]${join(" ", formatlist("\n%s %s %s %s %s",
    ##flatten(data.oci_identity_compartment.DNS_compartment[*].name),
    ##local.DNS_COMPARTMENT_ID,
    flatten(data.oci_dns_records.dns_records[*].records[*].compartment_id),
    flatten(data.oci_dns_records.dns_records[*].records[*].domain),
    flatten(data.oci_dns_records.dns_records[*].records[*].rdata),
    flatten(data.oci_dns_records.dns_records[*].records[*].rtype),
  flatten(data.oci_dns_records.dns_records[*].records[*].ttl)), )}"
  filename = "report_tenancy_config/dns_records.txt"
}
```

**Comment by eugsim1** [comment]
as i go the workaround i m closing the issue
