### ISSUE TITLE
Ability to assign a public ip to an existing vnic 

### ISSUE THREAD

**Issue by shankar-bala** [terraform-providers/terraform-provider-oci#1124]
### Description

Ability to assign public ip to an existing vnic.

We have VOIP applications that use 'SIP', and it need to know its public ip at os level and so there shouldnt be any NAT'ng. 
In order to do that we take an ip reserved IP public pool and assign it to an instance as  private and public ip addresses. This is required because OCI treats as private ip address even though they are the public range.

We were able to use existing terraform resources , but there is no resources that assigns a given public ip to a private ip ocid.
"oci_core_public_ip" resource assigns dynamically a public ip to a private ip ocid.

But our use case, is to give the user ability to assign a **specific** public ip to a vnic . It would be nice to have that feature enabled so that the VOIP based services can be run on OCI infrastructure.

**Comment by abhilash-av** [comment]
@shankar-bala 
Thank you for your request.
Could you please review https://www.exitas.be/blog/assigning-reserved-public-ips-to-guests-with-oracle-cloud-and-terraform/ and let me know if this resolves your request.

Thanks

**Comment by abhilash-av** [comment]
@shankar-bala 
The suggestion provided in https://github.com/terraform-providers/terraform-provider-oci/issues/1124#issuecomment-665819307 should have helped the customer. 

Closing this issue as there is no response from the Customer. @shankar-bala please feel free to open a new issue if you need anything more.

Thanks.
