### ISSUE TITLE
the call https://www.terraform.io/docs/providers/oci/d/dns_records.html returns empy compartment_id par record

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1125]
From the specs of this API i should get the compartement_id per dns records (unless if my understanding is wrong)

The following attributes are exported:

    compartment_id - The OCID of the compartment the resource belongs to.
    domain - The fully qualified domain name where the record can be located.

all the dns records are having the compartment_id empty this blows my scrpipts the compartement_id is located one level up not per record can you please update the code :

this is a result call
dns_record_from_workshop = [
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaakjdnf7ik2kejcaj73uwx6tsochnlq5olj3vebgbwcf67bjnab3ya"
    "id" = "2020-07-28 08:47:46.280916235 +0000 UTC"
    "records" = [
      {
        "compartment_id" = ""
        "domain" = "bastion.oraclecloudpursuitlabs.com"
        "is_protected" = false
        "rdata" = "130.61.142.172"
        "record_hash" = "0522c19b576e1e36b6a95b8ee058e544"
        "rrset_version" = "2"
        "rtype" = "A"
        "ttl" = 30
        "zone_name_or_id" = ""
      },
      {
        "compartment_id" = ""
        "domain" = "dbcs0-omc4db.oraclecloudpursuitlabs.com"
        "is_protected" = false
        "rdata" = "130.61.173.207"
        "record_hash" = "6ca57777226b12d2d49dc676ef1c22e8"
        "rrset_version" = "11"
        "rtype" = "A"
        "ttl" = 3600
        "zone_name_or_id" = ""
      },
    i

**Comment by abhilash-av** [comment]
@eugsim1  Thank you for your issue.

The fix has been made to the document and is expected to be released in Provider version 3.88.0

**Comment by rashik-bhasin** [comment]
Fix released in v3.88.0.
