### ISSUE TITLE
Make instance boot_volume_size_in_gbs changes in-place rather than re-creating the entire resource

### ISSUE THREAD

**Issue by andycoates** [terraform-providers/terraform-provider-oci#1128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `oci_core_instance` resource has an option to specify the boot volume size with `boot_volume_size_in_gbs`.  Changing this after the creation triggers the entire resource re-creation.  Since it is possible to increase the boot volume size on-the-fly (e.g. via the OCI Console UI), shouldn't Terraform treat this as an on-the-fly change too?  

Additional block volumes have the ability to resize without re-creating the block volume as well.

Side note: If this feature is added, it should only allow increasing the size, as this is also a limitation by the UI and with other block volumes.

### New or Affected Resource(s)

`oci_core_instance` resource:

```
    source_details {
        #Optional
        boot_volume_size_in_gbs = "${var.instance_source_details_boot_volume_size_in_gbs}"
    }
```

**Comment by abhilash-av** [comment]
@andycoates Thank you for your request.

The enhancement was done and is available in provider version 3.94.0 which was released on 9/23.

Closing this ticket for now.
