### ISSUE TITLE
wrong results on data "oci_apigateway_gateways" "gateways" 

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1130]
The call  data "oci_apigateway_gateways" "gateways" 
data "oci_apigateway_gateways" "gateways" {
  count          = (var.report_gateways == true) ? "${length(var.tenancy_compartments_id)}" : 0
  compartment_id = "${var.tenancy_compartments_id[count.index]}"
  state = "ACTIVE"
   /*
   filter {
    name   = "state"
    values = ["ACTIVE"]
  }
with the state either "active" or with the filter map return a wrong  result set please correct
I thought that ACTIVE should return only the compartments where an API is deployed and is active ???
  :

see the results of my tenancy with the state "ACTIVE" all the compartment are returned +  the compartment where the gateways are deployed and active

 {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaausg2mylj6zdlv6lw2jrpgagszg2l5mvgojvmwtghxxzxyd5bh65a"
    "gateway_collection" = []
    "id" = "2020-07-29 18:31:13.124407616 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaa6v4ddl3ljmq2nonozrnba5yf2qqnhzvdtoyl52wwkdd5qadwj37q"
    "gateway_collection" = [
      {
        "compartment_id" = "ocid1.compartment.oc1..aaaaaaaa6v4ddl3ljmq2nonozrnba5yf2qqnhzvdtoyl52wwkdd5qadwj37q"
        "defined_tags" = {
          "Mandatory_Tag.CreateDate" = "2020-01-27T16:37:27.878Z"
          "Mandatory_Tag.CreatedBy" = "ocid1.saml2idp.oc1..aaaaaaaaofk4hczswo3eewraxwcmldcilwhrkvv6ajgn4lgk5wqfb7wafcsa/kadday.oucif@oracle.com"
        }
        "display_name" = "gw-hello"
        "endpoint_type" = "PUBLIC"
        "freeform_tags" = {
          "faas" = "kadde"
        }
        "hostname" = "l247m4k73cdidjqwxnbir4gvf4.apigateway.eu-frankfurt-1.oci.customer-oci.com"
        "id" = "ocid1.apigateway.oc1.eu-frankfurt-1.amaaaaaa4g77oeya2oznon227mrp3znx2r5z2atoncvaa4ra637rmnbktf4q"
        "lifecycle_details" = "Updated Successfully"
        "state" = "ACTIVE"
        "subnet_id" = "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaar6xkcqc37es6w44gamasxvellwaabjerr7bwa2g4ltqqfkohxu7q"
        "time_created" = "2020-01-27 16:37:28.793 +0000 UTC"
        "time_updated" = "2020-06-02 14:54:01.448 +0000 UTC"
      },
    ]
    "id" = "2020-07-29 18:31:13.167271323 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaawtrqd4rofxwnbzuvtvm4yu55b2pmfuqm66lqlmp6houxvyxdkk2q"
    "gateway_collection" = []
    "id" = "2020-07-29 18:31:13.37613897 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaaslzwfdlzkhi2rhtszdsm5a7uob2xk2ypxd6276zqxkbuyi2rhaga"
    "gateway_collection" = []
    "id" = "2020-07-29 18:31:13.329184024 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaajhav56fnrqpbx5hp6r37ehpxbbvld6tprutng7rrui4cesfhwzoq"
    "gateway_collection" = []
    "id" = "2020-07-29 18:31:13.376104976 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaa6oasrxpy337xk4ask6qlhl2ydjk3hmnqb4vwliqtalaoei7so5lq"
    "gateway_collection" = []
    "id" = "2020-07-29 18:31:13.510866185 +0000 UTC"
    "state" = "ACTIVE"
  },

**Comment by rashik-bhasin** [comment]
Answered to terraform behavior here: https://github.com/terraform-providers/terraform-provider-oci/issues/1131 .

**Comment by eugsim1** [comment]
Hello i dont agree with the explanation this is a bug :
From the docs :
state - (Optional) A filter to return only resources that match the given lifecycle state. Example: SUCCEEDED
this should be the expected behavior
so the programmer here has simply copied all the result sets to the collection and has not applied a filter to REMOVE ALL COMPARTMENTS wich they DONT HAVE THE GATEWAY IN THE ACTIVE STATE
Please correct the code its a bug


{
"compartment_id" = "ocid1.compartment.oc1..aaaaaaaausg2mylj6zdlv6lw2jrpgagszg2l5mvgojvmwtghxxzxyd5bh65a"
"gateway_collection" = []
"id" = "2020-07-29 18:31:13.124407616 +0000 UTC"
"state" = "ACTIVE"
},

**Comment by rashik-bhasin** [comment]
As discussed with @eugsim1 on call, closing the issue as this is the expected behavior.
