### ISSUE TITLE
Terraform creation of BlockChain on my tenancy fails using release 3.85

### ISSUE THREAD

**Issue by psaddi** [terraform-providers/terraform-provider-oci#1132]
- I am using  Terraform 0.12.25
- provider.oci v3.85.0
- https://www.terraform.io/docs/providers/oci/r/blockchain_blockchain_platform.html

-  Documentation says idcs_access_token - (Optional) IDCS access token .But this is a mandate. Can the documentation be fixed to convey that. Also can you publish what Scopes are needed for this token. I know we dealt with the same with Analytics Cloud, which needed the /v1/Me scope, but was never mentioned anywhere

- I am using the simple example provided in your documentation to create a founder. I am able to create a founder from OCI console, so we can confirm that our tenancy is BlockChain enabled

- Terraform plan shows no issues

- Terraform apply works for 2 minutes and then breaks. I don't see any activity on the oci console to see if it got kicked off
- Putting TF_LOG=TRACE gave me only 1 warning during plan and apply, as shown below

2020/07/30 15:18:42 [WARN] Provider "registry.terraform.io/-/oci" produced an invalid plan for oci_blockchain_blockchain_platform.test_blockchain_platform, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .replicas: attribute representing nested block must not be unknown itself; set nested attribute values to unknown instead

- This is the error I see on the screen, which doesn't give me anything 

![image](https://user-images.githubusercontent.com/89501/88909515-d8987500-d278-11ea-9442-012e3cf2df23.png)

**Comment by jotruon** [comment]
Hi @psaddi,
I check the log and the error show:
`java.security.InvalidParameterException: Platform Role Founder`

So you can fix your config for `platform_role`, the valid value is `FOUNDER` 
This case service should return 400. I forward this bug to them.

About the `idcs_access_token`, I can check with service for the docs and make the change.

Thanks

**Comment by psaddi** [comment]
Thanks jotruon, I tried that and as you said got 400 error.I wanted to make sure the same was from CLI

oci blockchain blockchain-platform create --display-name XYZ --compartment-id $TF_VAR_compartment_ocid --platform-role FOUNDER --compute-shape STANDARD --idcs-access-token $TF_VAR_tims_idcs_access_token
ServiceError:
{
    "code": "InvalidParameter",
    "message": "Invalid idcsAccessToken",
    "opc-request-id": "1BB53E37445243B7BB39F5ED2C3AFD55/4FAFBE3DC8123DB794C5B18EBBC5000F/167B3A68E18C0811715B2A2E35875A55",
    "status": 400
}

**Comment by jotruon** [comment]
The error you get from CLI is "Invalid idcsAccessToken"
This can be your token has been expired.
you can try again with new token.

Thanks

**Comment by psaddi** [comment]
That is correct. I recreated the token and it is fine now. So the only thing left is more of a documentation issue for other consumers.

- Make the idcs_access_token a mandate variable in terraform docs
- Publish the grants needed for this token to work
- platform_role - (Required) Role of platform - founder or participant .
      - can you fix terraform documentation to make them upper case

**Comment by jotruon** [comment]
sure, let me update the service ticket. 
If you don't have any other questions, I can close this issue

**Comment by psaddi** [comment]
Yes, please close it. However, how would I know when the documentation is updated though, if this bug gets closed? Thank you for your very prompt response.
