### ISSUE TITLE
No error message for oci_core_instance creation failure

### ISSUE THREAD

**Issue by zhfkt** [terraform-providers/terraform-provider-oci#1137]
Hi terraform-provider-oci team,

I was creating an oci_core_instance resource. On apply, the error message from Terraform was:

```
Error: unexpected state 'TERMINATING', wanted target 'RUNNING'. last error: %!s(<nil>)

  on modules/compute/compute.tf line 34, in resource "oci_core_instance" "oscsCompute":
  34: resource "oci_core_instance" "oscsCompute" {
```
In the debug log:
```
2020/08/05 14:15:00 [DEBUG] module.es_cluster.module.esComputeDataInstances.oci_core_instance.oscsCompute[7]: apply errored, but we're indicating that via the Error pointer rather than returning it: unexpected state 'TERMINATING', wanted target 'RUNNING'. last error: %!s(<nil>)
```

Going into the Oracle UI to test, I found more userful that "all 29 non-reserved IP addresses of 100.73.50.64/27 for ocid1.subnet.oc1.iad.aaaaaaaadaflxhvvd3scgf6knajhgg4nbpgoouz3rhhqj37suvsatm5mdlyq have already been allocated"

![image](https://user-images.githubusercontent.com/4969804/89390435-4a6d3480-d739-11ea-94bc-ef077b96667d.png)

I would like to see the detailed error message during the terraform operation instead of only "unexpected state 'TERMINATING', wanted target 'RUNNING'".

This issue is very similar with this one https://github.com/hashicorp/terraform/issues/2564 on AWS side. So we need to also show the detailed error in Oracle Cloud Service for oci_core_instance creation failure.

### Terraform Version and Provider Version

Terraform Version - 0.12.26
The issues are both observed in the oci provider v3.62.0 and v3.40.0-1

### Affected Resource(s)

oci_core_instance 

### Debug Output

[fengkzhulq16-zyjxtxoq-1413-tfdebug.log](https://github.com/terraform-providers/terraform-provider-oci/files/5027138/fengkzhulq16-zyjxtxoq-1413-tfdebug.log)

### Expected Behavior

We should show the following detailed error instead of only  "Error: unexpected state 'TERMINATING', wanted target 'RUNNING'. last error: %!s(<nil>)":

`A problem occurred while preparing the instance's VNIC. (All 29 non-reserved IP addresses of 100.73.50.64/27 for ocid1.subnet.oc1.iad.aaaaaaaadaflxhvvd3scgf6knajhgg4nbpgoouz3rhhqj37suvsatm5mdlyq have already been allocated.)
`

![image](https://user-images.githubusercontent.com/4969804/89390435-4a6d3480-d739-11ea-94bc-ef077b96667d.png)

### Actual Behavior

The output on the screen:
```

Error: unexpected state 'TERMINATING', wanted target 'RUNNING'. last error: %!s(<nil>)

  on modules/compute/compute.tf line 34, in resource "oci_core_instance" "oscsCompute":
  34: resource "oci_core_instance" "oscsCompute" {
```

In the log, it said

`2020/08/05 14:15:00 [DEBUG] module.es_cluster.module.esComputeDataInstances.oci_core_instance.oscsCompute[7]: apply errored, but we're indicating that via the Error pointer rather than returning it: unexpected state 'TERMINATING', wanted target 'RUNNING'. last error: %!s(<nil>)`

### Important Factoids

If we directly create the host on the OCI by terraform, the correct error (All 29 non-reserved IP addresses have already been allocated) will be printed on the screen. However,  we are doing a scale out in the terraform i.e. increase count in the  oci_core_instance (for example - increase 2 to 6), and this issue will happen.

```
resource "oci_core_instance" "oscsCompute" {
  count                = "${var.NumInstances}"
  ........

}
```

Pls review.

Thank you !

**Comment by rashik-bhasin** [comment]
Hi, this has been fixed in v4.4.0.
Thanks!
