### ISSUE TITLE
vsphere provider. Multiple VMs different datastores

### ISSUE THREAD

**Issue by alexandrudu** [terraform-providers/terraform-provider-oci#1140]
Hi,
Was wondering if terraform vsphere provider is capable of separating vms in specific datastores.
I know it is possible if i have individual VMs.
But what if i have count = 2 or more (to create 2 or more vms) then all those will go within the same datastore. Is there any available option for me to use count with the datastore and create a counter in the for the datastore name (i will create 2 or more datastores with a number at the end on the vcenter side).

Or would that be possible using dynamic "datastore_id" ? does something like that exist? Already using dynamic for network_interfaces and disk

**Comment by alexandrudu** [comment]
Or would that be possible using dynamic "datastore_id" ? does something like that exist? Already using dynamic for network_interfaces and disk

**Comment by varmax2511** [comment]
Hi @alexandrudu -- you have raised the question in queue for Terraform OCI provider. I believe you wish to raise this in https://github.com/hashicorp/terraform-provider-vsphere?

**Comment by alexandrudu** [comment]
true sorry bout that.
