### ISSUE TITLE
Error: Post https://iaas.ca%E2%80%94toronto-1.oraclecloud.com/20160918/vcns: dial tcp: lookup iaas.xn--catoronto-1-zg3f.oraclecloud.com on 192.168.2.1:53: no such host

### ISSUE THREAD

**Issue by omarfarooq1** [terraform-providers/terraform-provider-oci#1149]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

Before using this template, check whether your question is already answered in one of the following guides:
* [Frequently Asked Questions](https://www.terraform.io/docs/providers/oci/guides/faq.html)
* [Troubleshooting](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html)

If you have a support request related to Oracle Cloud Infrastructure services, please [contact Oracle support](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm)

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by omarfarooq1** [comment]
Any one has an idea. I am using toronto region as part of trial account

**Comment by govindrao55** [comment]
@omarfarooq1  Can you please explain what are you trying to do and what steps were taken that resulted in this error?

**Comment by omarfarooq1** [comment]
Hi Govindra, on mac I am setting up terraform towards oracle cloud and when I apply the terraform apply command on my mac, this is what I am getting. seems like it is unable to resolve this entry and hence terraform is failing.

**Comment by govindrao55** [comment]
@omarfarooq1 can you share the following details:
1) sanitized terraform config file i.e. make sure you hide security information and request specific information
2) terraform CLI version and OCI provider version used

You may also check out our [examples folder](https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples) to understand how to provision a specific resource.

**Comment by omarfarooq1** [comment]
Hi Govidrda

terraform version is  v0.12.29 OCI provider is 3.74.0 

env-vars.sh file below
export TF_VAR_tenancy_ocid=xxxx
export TF_VAR_user_ocid=xxx
export TF_VAR_fingerprint=xxxxxx
export TF_VAR_private_key_path=/Users/test/.OCI/oci_api_key.pem
# export TF_VAR_region="ca-toronto-1"
export TF_VAR_compartment_ocid=xxxxxx

main.tf 




resource "oci_core_virtual_network" "myvcn" {
  cidr_block = "10.1.0.0/16"
compartment_id = "var.compartment_ocid"
  display_name = "TFExampleVCN"
  dns_label = "tfexamplevcn"
}


resource "oci_core_subnet" "ExampleSubnet" {
 # availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[var.AD - 1],"name")}"
  cidr_block = "10.1.20.0/24"
  display_name = "TFExampleSubnet"
  dns_label = "tfexamplesubnet"
 # security_list_ids = ["${oci_core_virtual_network.ExampleVCN.default_security_list_id}"]
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${oci_core_virtual_network.myvcn.id}"
 # route_table_id = "${oci_core_route_table.ExampleRT.id}"
 # dhcp_options_id = "${oci_core_virtual_network.ExampleVCN.default_dhcp_options_id}"
}
 # */

Provider.tf 
provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "${var.region}"
  # disable_auto_retries = "true"
  version    = "=3.74.0"
}

variables.tf

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
# variable "private_key_password" {}

**Comment by omarfarooq1** [comment]
please note any thing In bold was commented out using #

**Comment by govindrao55** [comment]
Can you confirm the value being used for region variable is correct? The url `iaas.ca%E2%80%94toronto-1` in the post call looks incorrect. The region should be `ca-toronto-1`, the gibberish chars in the POST call decodes to EM_DASH (http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=342+200+224&mode=obytes) which looks very similar to hypen. 
If you have any of TF_VAR environment variable, `~/.oci/config` or `.tfvars` setting in place, please check if this region variable value is correctly set. Prefer physically typing the values instead of copy-paste to be sure.
