### ISSUE TITLE
Data source to get information on specific Load Balancer using its OCID

### ISSUE THREAD

**Issue by kostasns** [terraform-providers/terraform-provider-oci#1153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Introduce new data source to get information on specific load balancer using its id or add ability to filter by load balancer ocid.
Currently the only data source which is available is the list of lbs with filter by name

Example:
https://www.terraform.io/docs/providers/oci/d/core_vcn.html
https://www.terraform.io/docs/providers/oci/d/core_vcns.html

### New or Affected Resource(s)

Data Source: oci_load_balancer_load_balancer

### Potential Terraform Configuration

```hcl
data "oci_load_balancer_load_balancer" "test_load_balancer" {
    #Required
    load_balancer_id = "${var.load_balancer_id}"

    #Optional
    detail = "${var.load_balancer_detail}"
    state = "${var.load_balancer_state}"
}

```

**Comment by alexng-canuck** [comment]
Hi @kostasns ,

Have you considered using the `filter` attribute with the `oci_load_balancer_load_balancers` data source like this?

```
data "oci_load_balancer_load_balancers" "test_load_balancers" {
    #Required
    compartment_id = "${var.compartment_id}"

    #Optional
    detail = "${var.load_balancer_detail}"
    state = "${var.load_balancer_state}"

    # Do client-side filtering of results.
    filter {
        name = "id"
        values = ["ocid1.phx.loadbalancer.blahblahblahblah"]
    }
}
```

This leverages client-side filtering logic from the OCI provider to return a list of items that match the filter. More details about client-side filtering are here: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/filters

You can then access the specified LB info by doing this:

```
data.oci_load_balancer_load_balancers.test_load_balancers.load_balancers[0]
```

**Comment by kostasns** [comment]
Hi @alexng-canuck,
Thank you for suggestion.
We are currently using a display_name to filter out the required balancer, but client-side filtering seems to do what we want.
