### ISSUE TITLE
Limit for oci_core_network_security_group_security_rule per NSG is 500 but error after 120 rules created

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.28
+ provider.oci v3.90.0

### Affected Resource(s)
```oci_core_network_security_group_security_rule```

### Terraform Configuration Files
```hcl
resource "oci_core_network_security_group_security_rule" "the_rules" {
  count                     = 500
  network_security_group_id = var.network_security_group_id
  direction                 = "INGRESS"
  protocol                  = "1"

  destination               = "0.0.0.0/0"
  destination_type          = "CIDR_BLOCK"

  tcp_options {
    destination_port_range {
      max = 30000 + count.index
      min = 30000 + count.index
    }
  }
}
```

### Debug Output
Error: Service error:InvalidParameter. Total security rules count 121 cannot be greater than 120. http status code: 400. Opc request id: 8bd8bbe76D0943/8C32c21a543dc0f6bb6a11e6a74C9354858EB34592BADAA90065E025DF7F35C26f5/2CEDC90286AEA92

  on nsg-rules.tf line 1, in resource "oci_core_network_security_group_security_rule" "the_rules":
   1: resource "oci_core_network_security_group_security_rule" "the_rules" {

### Expected Behavior
According to docs (see link below) a total of 500 ingress and egress rules (combined) are allowed per NSG. I do not expect an error until attempting to create rule number 501

### Actual Behavior
When rule number 121 attempted to create, an error was shown and the rule creation failed

### Steps to Reproduce

1. `terraform apply`

### References
* https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/servicelimits.htm
See here where limit is 500 rules per Network Security Group

**Comment by alexng-canuck** [comment]
Hi @jeliker ,

The Terraform provider does not limit the number of rules you can create. This appears to be a service side error. We have shared your feedback with the relevant service team. 

Since errors related to service limits are generally NOT Terraform provider bugs, I would also recommend that you reach out to Oracle support for help with this issue: https://docs.cloud.oracle.com/en-us/iaas/Content/GSG/Tasks/contactingsupport.htm

**Comment by Yinliwa** [comment]
Hi @jeliker ,

You can have 500 rules by creating five NSGs in assigning them to a single vnic. It's 500 total rules and not 500 per nsg.

**Comment by alexng-canuck** [comment]
@jeliker , this appears to be a documentation issue which will be addressed by the relevant service. I will close this issue for now.
