### ISSUE TITLE
terraform -v Terraform v0.13.1 not reading -var-file="phx_l.tfvar" getting Error: Unsupported argument

### ISSUE THREAD

**Issue by tutorialbyexample** [terraform-providers/terraform-provider-oci#1161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
terraform -v
Terraform v0.13.1

### Terraform Configuration Files

variable.tf

```hcl
variable "environment" {
  description = "Environment name."
  default     = "PreProduction"
}

variable "regulatory_domain" {
  description = "Regulatory Domain."
  default     = "q"
}

```

phx_q.tfvars
```hcl
environment = "PreProduction"
regulatory_domain = "q"
```

```hcl
kumvinov-mac:tf_tee_network kumvinov$ terraform init -var-file="phx_q.tfvars" -backend-config="phx_q.tfvars" -backend-config="endpoint=https://XXXXXXXXXXXXXXXXXXage.us-phoenix-1.oraclecloud.com"
Initializing modules...
- vcn in .terraform/modules/vcn/vcn
--------------------------------
Initializing the backend...

Error: Unsupported argument

  on phx_q.tfvars line 17:
  17: environment = "PreProduction"

An argument named "environment" is not expected here.


Error: Unsupported argument

  on phx_q.tfvars line 18:
  18: regulatory_domain = "q"

An argument named "regulatory_domain" is not expected here.

```

### Expected Behavior
In terraform version 0.12.0 it is working fine.

### Actual Behavior

terraform init getting failure 

Initializing the backend...

Error: Unsupported argument

  on phx_q.tfvars line 17:
  17: environment = "PreProduction"

An argument named "environment" is not expected here.

Error: Unsupported argument

  on phx_q.tfvars line 18:
  18: regulatory_domain = "q"

An argument named "regulatory_domain" is not expected here.

### Steps to Reproduce

1. `terraform apply`
Terraform init only getting failure.

**Comment by tutorialbyexample** [comment]
We are getting this issue once we are using backend as s3.
terraform init -var-file="phx_l.tfvars" -backend-config="phx_l.tfvars" -backend-config="endpoint=https://axkXXXXXXXXXXs-phoenix-1.oraclecloud.com"

```
#State management in Object Storage
terraform {
  backend "s3" {
    bucket   = var.bucket
    key      = var.key
    region   = var.region
    endpoint = var.endpoint
    shared_credentials_file = "~/.aws/credentials"
    profile                 = var.profile

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}
```

While removing backend part working fine but we need backend:

kumvinov-mac:tf_tee_network kumvinov$ terraform init -var-file="phx_l.tfvars"
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Installing hashicorp/oci v3.90.1...
- Installed hashicorp/oci v3.90.1 (signed by HashiCorp)

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/oci: version = "~> 3.90.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by srishtipmishra** [comment]
@tutorialbyexample - Thanks for bringing this to our notice. This looks like an intentional change from terraform team for 0.13
https://github.com/hashicorp/terraform/issues/26038

As mentioned in the hashicorp ticket - backend configis invalid whenattempting to use a full configuration file as an override

Please refer to - https://www.terraform.io/docs/configuration/backend.html#partial-configuration

**Comment by tutorialbyexample** [comment]
I can confirm once we used only backend config variable in dedicated file for it and another file for -var-file as .tfvars then it's working. But not good as have so many file for same purpose, however validation needed as per above message.

FYI:

```
kumvinov-mac:tf_tee_network kumvinov$ terraform init -var-file="phx_l.tfvars" -backend-config="phx_l_bec.tfvars" -backend-config="endpoint=https://xxxxxxxx6uo.compat.objectstorage.us-phoenix-1.oraclecloud.com"
Initializing modules...
- vcn in .terraform/modules/vcn/vcn

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Installing hashicorp/oci v3.91.0...
- Installed hashicorp/oci v3.91.0 (signed by HashiCorp)

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/oci: version = "~> 3.91.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
Thanks @srishtipmishra for your quick response with details.

**Comment by srishtipmishra** [comment]
Closing this issue as resolution was confirmed by user.
