### ISSUE TITLE
Local Peering Gateway peer_id update

### ISSUE THREAD

**Issue by kviktorman** [terraform-providers/terraform-provider-oci#1164]
Hi,

I'm trying to set up two Virtual Cloud Networks (VCN) which are connected via Local Peering Gateway (LPG). The LPGs for the VNCs are created programmatically using a for loop.  

This is the workflow which I have now:
1. one module which creates a VCN (call it two times)
2. one module which loops through the LPG list and creates them on the VCNs

As a third step I wanted to add a module which establishes the linking between the two VCNs, but I got stuck.

It seems that the "oci_core_local_peering_gateway" can not be filtered by the local peering gateway id. I'm wondering how the programmatically created resource should be altered without any filtering. Can you please give me some suggestions?

My other question is that, how you make the LPG linking using the peer_id (which is the target VCN's LPG id) on both sides if the field is not marked updateable? 

On the documentation page I see the following note:
```
** IMPORTANT ** Any change to a property that does not support update will force the destruction and recreation of the resource with the new property values
```

Thanks,
Viktor

**Comment by kviktorman** [comment]
Hi,
It seems that the implementation of the linking should be in the same module and actually on the same resource definition. Otherwise terraform will create a new resource with the same name. On OCI console you will see that the status of the LPGs (which carry the same name) is connected.

I did a separate test by creating the resource first and with a second terraform run provide the id for the LPG, what I noticed is that the peer_id value setting from null to a valid id will recreate the gateway resource (it seems that it counts as an update). 

Shall I assume that LPG should not be managed via terraform?

Here is the output:

```
  # module...oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"] must be replaced
-/+ resource "oci_core_local_peering_gateway" "local_peering_gateway" {
        compartment_id               = "ocid1..."
      ~ defined_tags                 = {} -> (known after apply)
        display_name                 = "OCI-APP-network-LPG"
      ~ freeform_tags                = {} -> (known after apply)
      ~ id                           = "ocid1..." -> (known after apply)
      ~ is_cross_tenancy_peering     = false -> (known after apply)
      + peer_advertised_cidr         = (known after apply)
      ~ peer_advertised_cidr_details = [] -> (known after apply)
      + peer_id                      = "ocid1..." # forces replacement
      ~ peering_status               = "NEW" -> (known after apply)
      ~ peering_status_details       = "Not connected to a peer." -> (known after apply)
      + route_table_id               = (known after apply)
      ~ state                        = "AVAILABLE" -> (known after apply)
      ~ time_created                 = "2020-09-07 15:07:41.917 +0000 UTC" -> (known after apply)
        vcn_id                       = "ocid1..."

module....module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Destroying... [id=ocid1...]
module....module.OCI_DMZ_app_network.data.oci_core_subnets.cloud_network_data: Refreshing state...
module....module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Destruction complete after 0s
module....module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Creating...

Error: Service error:InvalidParameter. Either Local Peering Gateway with ID ocid1... does not exist or you are not authorized to access it.. http status code: 400. Opc request id: ...

```

Thanks, 
Viktor

**Comment by kviktorman** [comment]
It seems that for connecting two LPGs, you need to specify only one side the peer_id. It would be really helpful if you could include that in the documentation.

Also what I noticed is that after successful "terraform apply" the next terraform apply will force replace the LPG even if you have done state refresh ("terraform refresh") between the two applies. The second apply will go to error.

```
  # module...OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"] must be replaced
-/+ resource "oci_core_local_peering_gateway" "local_peering_gateway" {
        compartment_id               = "ocid1..."
      ~ defined_tags                 = {} -> (known after apply)
        display_name                 = "OCI-APP-network-LPG"
      ~ freeform_tags                = {} -> (known after apply)
      ~ id                           = "ocid1..." -> (known after apply)
      ~ is_cross_tenancy_peering     = false -> (known after apply)
      ~ peer_advertised_cidr         = "10.0.0.0/16" -> (known after apply)
      ~ peer_advertised_cidr_details = [
          - "10.0.0.0/16",
        ] -> (known after apply)
      ~ peer_id                      = "ocid1..." -> (known after apply) # forces replacement
      ~ peering_status               = "PEERED" -> (known after apply)
      ~ peering_status_details       = "Connected to a peer." -> (known after apply)
      + route_table_id               = (known after apply)
      ~ state                        = "AVAILABLE" -> (known after apply)
      ~ time_created                 = "2020-09-08 15:09:29.552 +0000 UTC" -> (known after apply)
        vcn_id                       = "ocid1..."
    }

module...module.OCI_DMZ_app_network.data.oci_core_subnets.cloud_network_data: Refreshing state...
module...module.OCI_database_network.data.oci_core_subnets.cloud_network_data: Refreshing state...
module...module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Destroying... [id=ocid1...]
module...module.OCI_DMZ_app_network_LPG.data.oci_core_local_peering_gateways.local_gateways: Refreshing state...
module...module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Destruction complete after 1s
module...module.OCI_DB_network_LPG.oci_core_local_peering_gateway.local_peering_gateway["OCI-APP-network-LPG"]: Creating...

Error: Service error:InvalidParameter. The Local Peering Gateway with ID ocid1... has already been connected.. http status code: 400. Opc request id: ...

```

**Comment by parrneet** [comment]
Hi @kviktorman - Referring to this [example ](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/local_vcn_peering/local_vcn_peering.tf#L40) 
Your understanding is correct, When peering a vcn (vcn1) to another vcn (vcn2), each vcn needs a peering gateway and `peer_id` is specified in only one of the peering gateways. 
After `terraform apply`, the one with `peer_id` in config will have peer id in state and the other peering gateway will have `null` in state.
Specifying the `peer_id` after creation of LPG will cause the resource to be deleted and created again. 

If you are still facing issues, Please provide the steps and simplified TF config to reproduce the issue.

**Comment by kviktorman** [comment]
Hi @parrneet,

I was preparing you the use case, but the issue seems to be gone. Maybe there was a fix somewhere which solved it. 
Will reopen the ticket if needed.

Thanks for the link, for the confirmation and for updating the docs, 
Viktor
