### ISSUE TITLE
Are Gov regions supported or not?

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1168]
I see in the OCI documentation on this page that US Government regions are not supported:

  https://docs.cloud.oracle.com/en-us/iaas/Content/General/Concepts/govfedramp.htm

Can you confirm what this means as I found (through informal exploration) that the Terraform provide did indeed work in some capacity.  What I'm looking for is a more complete answer such as whether this is related to technical limitations or incomplete certification. I ask because the nature of the constraint (certification vs. technical) may suggest how soon we might reasonably see Terraform support formally included for the Government regions.

**Comment by parrneet** [comment]
A version of the provider with FIPS support is on the roadmap. There is no published schedule.
