### ISSUE TITLE
faling to build .trf for OCI existingcompartment 

### ISSUE THREAD

**Issue by akshays244** [terraform-providers/terraform-provider-oci#1169]
When i try to utilize the module i see below error .i am running over windows 10 CMD with OCI CLI configured 

.\terraform-provider-oci_v3.91.0_x4.exe -command=export -compartment_name=compartment_test -output_path=/.C:\Users\test\.oci\aktest
-------------------------------------------------------------------
INFO 2020/09/11 00:02:04.156479 [INFO] discovering resources with data source 'oci_waas_waas_policies'
INFO 2020/09/11 00:02:04.495019 [32m=== COMPLETED ===[0m
INFO 2020/09/11 00:02:04.496011 open /\analytics.tf.tmp: The specified path is invalid.
open /\analytics.tf.tmp: The specified path is invalid.

---------------------------------------------------

![OCIerr](https://user-images.githubusercontent.com/26789972/92782449-99eef200-f3c2-11ea-8174-b8e39ffaa713.JPG)

**Comment by parrneet** [comment]
Hi @akshays244 - Looks like an issue with the output path `-output_path=/.C:\Users\test.oci\aktest`, Can you try without the preceding `/.`

**Comment by akshays244** [comment]
@parrneet  Thank you very much , It worked perfectly

**Comment by akshays244** [comment]
Closing as the command syntax which was causing trouble in saving *.tf file, got resolved as @parrneet suggested .
