### ISSUE TITLE
Using Bash constructs in HCL code

### ISSUE THREAD

**Issue by torstenboe** [terraform-providers/terraform-provider-oci#1170]
On some examples, like: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/identity/tenancy.tf

The example code is using bash constructs together with an old notation for variables, even though the functionality is covered in HCL. As a result outputs are in plain text rather than JSON and terraform throws an error because the varaible is not given in raw text.

Current example:

output "tenancy" {
  value = <<EOF
name            = ${data.oci_identity_tenancy.tenancy.name}
description     = ${data.oci_identity_tenancy.tenancy.description}
tenancy_id      = ${data.oci_identity_tenancy.tenancy.tenancy_id}
home_region_key = ${data.oci_identity_tenancy.tenancy.home_region_key}
EOF
}

Valid HCL2 code

output "tenancy" {
  value = data.oci_identity_tenancy.tenancy
}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by jotruon** [comment]
Thanks @torstenboe for the suggestion. We will convert these configs to HCL2

**Comment by jotruon** [comment]
@torstenboe, this is not a blocking issue and user can chose which type of output value and bash construct is a valid one.
Closing this ticket.
