### ISSUE TITLE
local peering gateway (lpg) forced resource recreation when using a loop

### ISSUE THREAD

**Issue by kviktorman** [terraform-providers/terraform-provider-oci#1179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```bash
$ terraform -v
Terraform v0.12.29
+ provider.oci v3.93.0
```

### Affected Resource(s)

```
* oci_core_local_peering_gateway
```

### Terraform Configuration Files

For simplicity reasons I crated a repository instead pasting the code here, you can find it on the following [link](https://github.com/kviktorman/terraform-provider-oci-lpg-issue).

### Debug Output

```
  # module.gatewayArrayOnB.oci_core_local_peering_gateway.local_peering_gateway_array["gatewayToA2"] must be replaced
  -/+ resource "oci_core_local_peering_gateway" "local_peering_gateway_array" {
        compartment_id               = "ocid1.compartment..."
      ~ defined_tags                 = {} -> (known after apply)
        display_name                 = "gatewayToA2"
      ~ freeform_tags                = {} -> (known after apply)
      ~ id                           = "ocid1.localpeeringgateway..." -> (known after apply)
      ~ is_cross_tenancy_peering     = false -> (known after apply)
      ~ peer_advertised_cidr         = "10.0.0.0/16" -> (known after apply)
      ~ peer_advertised_cidr_details = [
          - "10.0.0.0/16",
        ] -> (known after apply)
      ~ peer_id                      = "ocid1.localpeeringgateway..." -> (known after apply) # forces replacement
      ~ peering_status               = "PEERED" -> (known after apply)
      ~ peering_status_details       = "Connected to a peer." -> (known after apply)
      + route_table_id               = (known after apply)
      ~ state                        = "AVAILABLE" -> (known after apply)
      ~ time_created                 = "2020-09-21 09:42:05.524 +0000 UTC" -> (known after apply)
        vcn_id                       = "ocid1.vcn..."
    }

  Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior

I think terraform `plan` and `apply` should act similarly when local peering gateway resources are created and linked  using a static way (write all the connection down one by one) or dynamically way (using a for loop).

### Actual Behavior

When the resource connection is written down in a static way, means defining the resource connection manually for each of them one by one, the next terraform `plan` and `apply` will say everything is cool.

When the connection is done dynamically, means the connection is defined using a for loop, terraform will create successful the connection, but the next terraform `plan` and `apply` will trigger resource recreation. I tried to to do a refresh between the two runs, but terraform still wants to recreate the connection. The second `apply` with the force recreation will completely break the peered Local Peering Gateways.

### Steps to Reproduce

1. `terraform apply`
2. `terraform refresh` (This is optional doesn't make any difference)
3. `terraform plan` OR `terraform apply`

### Important Factoids

The strange thing is that after the first `terraform apply` on the web console everything seems to be Ok, the VCNs are peered successfully. If you let the second terraform apply go then it will break the peered connection.

**Comment by kviktorman** [comment]
I started to redesign our code so we can progress while we wait for the answer. I noticed something, which might be related. 
I removed the loop, hardcoded the "display_name", but kept the peer_id as a lookup and seeing exactly the same behavior.
Did also a reverse test, hardcoded the peer_id, put back the loop and force recreation is gone. 

It seems that the peer_id setting differs when the value is hard coded or when it comes as a result of an array search...

```
# forcing the recreation with next terraform plan or apply
resource "oci_core_local_peering_gateway" "local_peering_gateway_array" {
    compartment_id = var.target_compartment
    vcn_id = var.target_network.networkOCID
    display_name = "gatewayToA2"
    peer_id = var.available_lpg_list["gatewayToB2"].gatewayId
}

# no recreation is forced with next terraform plan or apply
resource "oci_core_local_peering_gateway" "local_peering_gateway_array" {
    for_each = { for setting in var.gateway_info : setting.gatewayName => setting } 

    compartment_id = var.target_compartment
    vcn_id = var.target_network.networkOCID
    display_name = each.value.gatewayName
    
    peer_id = "hardcoded id here"
}
```

**Comment by zexinwanoci** [comment]
Can you also include the config for variable "available_lpg_list"? Thank you

**Comment by kviktorman** [comment]
Hi @zexinwanoci ,
thanks for having a look. The `gatewayArrayOnA` module is constructing that data, it's printed out as well as an output after the first apply.

```
module.gatewayArrayOnA.vcn_local_peering_gateways
```

I made a small test converting the LPG OCID to a string, after that the force recreation seems not to happen. 

This is what I have now:

```
resource "oci_core_local_peering_gateway" "local_peering_gateway_array" {
    for_each = { for setting in var.gateway_info : setting.gatewayName => setting } 

    compartment_id = var.target_compartment
    vcn_id = var.target_network.networkOCID
    display_name = each.value.gatewayName
    
    peer_id = tostring(var.available_lpg_list[each.value.targetGatewayName].gatewayId)
}
```

I'm wondering if using an array search like this might returning just the memory reference where the result will be available instead the actual value and by using the `tostring` we force it to evaluate before the comparison happens. What do you think?

Cheers

**Comment by zexinwanoci** [comment]
I think you are exactly right, if the field is not using the actual value but a reference then terraform compare may not be able to identify that. I'm glad now you have it work out. Is there anything else we can help you?

**Comment by kviktorman** [comment]
I guess we should live with it. Thanks for the confirmation.
