### ISSUE TITLE
cipher-suite is getting recreated always.

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#1180]
Hi,
We are trying to import the state of the objects in OCI to tf state file using python code but we find that the objects get recreated once the import is complete: Please see below scenario -
We observed that the cipher suites of LBR gets recreated every time. Procedure followed manually as a part of understanding the behavior:
1. Created Cipher Suites via terraform(terraform apply)
2. Deleted the state of the newly created cipher from tfstate file.
3. Imported the state of the same cipher - using terraform import command.
4. Ran Terraform plan
Ideally it should say no changes to be made and that the state is in synch, but i got the following:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
  # oci_load_balancer_ssl_cipher_suite.test3 must be replaced
-/+ resource "oci_load_balancer_ssl_cipher_suite" "test3" {
      + ciphers          = [
          + "AES256-SHA",
          + "AES256-SHA256",
          + "AES256-GCM-SHA384",
          + "AES128-SHA256",
        ] # forces replacement
      ~ id               = "loadBalancers/ocid1.loadbalancer.oc1.phx.aaaaaaaahnb2nwkj2i4xwwvzds4p5tti6hfamb3rffkpmo6sgaqsue4kvy6q/sslCipherSuites/test3" -> (known after apply)
        load_balancer_id = "ocid1.loadbalancer.oc1.phx.aaaaaaaahnb2nwkj2i4xwwvzds4p5tti6hfamb3rffkpmo6sgaqsue4kvy6q"
        name             = "test3"
      + state            = (known after apply)
      - timeouts {}
    }
Plan: 1 to add, 0 to change, 1 to destroy.
------------------------------------------------------------------------
Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Would like to know why does it re-create the cipher suite? Is there anything that i am missing here?

**Comment by zexinwanoci** [comment]
Hello, cipher is a `Required` and `ForceNew` filed.

**Comment by shruthi2703** [comment]
Okay. That explains. Thank you. Are SSL Certificates too force new ? We find similar behavior with Certificates as well.

**Comment by zexinwanoci** [comment]
Yes, that as well.

**Comment by shruthi2703** [comment]
thank you. Okay.
