### ISSUE TITLE
Rule sets get recreated on tf apply when their state is imported.

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#1181]
Hi,

We are trying to import the state of the objects in OCI to tf state file using python code but we find that the objects get recreated once the import is complete: Please see below scenario -

Exported data from OCI - Rule Sets (reponse of Python API as shown below)
Note the exported data for action - CONTROL_ACCESS_USING_HTTP_METHODS

{
  "items": [
    {
      "action": "REMOVE_HTTP_RESPONSE_HEADER",
      "header": "ruleset-new"
    },
    {
      "action": "ADD_HTTP_REQUEST_HEADER",
      "header": "ruleset-test",
      "value": "ruletest-value"
    },
    {
      "action": "CONTROL_ACCESS_USING_HTTP_METHODS",
      "allowed_methods": [
        "ACL",
        "GET",
        "LABEL"
      ],
      "status_code": 405
    }
  ],
  "name": "RS1"
}
Created Terraform files and imported the state of Rule Set to tfstate file
On terraform Plan, it shows the following: (Please note that CONTROL_ACCESS_USING_HTTP_METHODS gets removed, So does the other rules below. They get re-created)

  # oci_load_balancer_rule_set.c28268b4a-b6a7-4026-8923-e272421b371b-RS1 will be updated in-place
  ~ resource "oci_load_balancer_rule_set" "c28268b4a-b6a7-4026-8923-e272421b371b-RS1" {
        id               = "loadBalancers/ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q/ruleSets/RS1"
        load_balancer_id = "ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q"
        name             = "RS1"

      - items {
          - action                         = "ADD_HTTP_REQUEST_HEADER" -> null
          - allowed_methods                = [] -> null
          - are_invalid_characters_allowed = false -> null
          - header                         = "ruleset-test" -> null
          - http_large_header_size_in_kb   = 0 -> null
          - response_code                  = 0 -> null
          - status_code                    = 0 -> null
          - value                          = "ruletest-value" -> null
        }
      + items {
          + action                         = "ADD_HTTP_REQUEST_HEADER"
          + allowed_methods                = []
          + are_invalid_characters_allowed = false
          + header                         = "ruleset-test"
          + http_large_header_size_in_kb   = 0
          + prefix                         = (known after apply)
          + response_code                  = 0
          + status_code                    = 0
          + suffix                         = (known after apply)
          + value                          = "ruletest-value"
        }
      - items {
          - action                         = "CONTROL_ACCESS_USING_HTTP_METHODS" -> null
          - allowed_methods                = [
              - "ACL",
              - "GET",
              - "LABEL",
            ] -> null
          - are_invalid_characters_allowed = false -> null
          - http_large_header_size_in_kb   = 0 -> null
          - response_code                  = 0 -> null
          - status_code                    = 405 -> null
        }
      + items {
          + action                         = "CONTROL_ACCESS_USING_HTTP_METHODS"
          + allowed_methods                = [
              + "LABEL",
              + "GET",
              + "ACL",
            ]
          + are_invalid_characters_allowed = (known after apply)
          + description                    = (known after apply)
          + header                         = (known after apply)
          + http_large_header_size_in_kb   = (known after apply)
          + prefix                         = (known after apply)
          + response_code                  = (known after apply)
          + status_code                    = 405
          + suffix                         = (known after apply)
          + value                          = (known after apply)

          + conditions {
              + attribute_name  = (known after apply)
              + attribute_value = (known after apply)
              + operator        = (known after apply)
            }

          + redirect_uri {
              + host     = (known after apply)
              + path     = (known after apply)
              + port     = (known after apply)
              + protocol = (known after apply)
              + query    = (known after apply)
            }
        }
      - items {
          - action                         = "REMOVE_HTTP_RESPONSE_HEADER" -> null
          - allowed_methods                = [] -> null
          - are_invalid_characters_allowed = false -> null
          - header                         = "ruleset-new" -> null
          - http_large_header_size_in_kb   = 0 -> null
          - response_code                  = 0 -> null
          - status_code                    = 0 -> null
        }
      + items {
          + action                         = "REMOVE_HTTP_RESPONSE_HEADER"
          + allowed_methods                = []
          + are_invalid_characters_allowed = false
          + header                         = "ruleset-new"
          + http_large_header_size_in_kb   = 0
          + prefix                         = (known after apply)
          + response_code                  = 0
          + status_code                    = 0
          + suffix                         = (known after apply)
        }

        timeouts {}
    }

I do not find most of these options on console as well. Could you please let us know why is it re-creating these rules?
CONTROL_ACCESS_USING_HTTP_METHODS --> does not have any option to enter called - are_invalid_characters_allowed in OCI console.

**Comment by zexinwanoci** [comment]
Can you paste both your tf.state file and the .tf config file that cause the force create? Thank you.

**Comment by shruthi2703** [comment]
i do not have the same ruleset; i have the rules separated but then also i have same issue so pasting them here: 

Rule Set for CONTROL_ACCESS_USING_HTTP_METHODS alone:

```
resource "oci_load_balancer_rule_set" "c28268b4a-b6a7-4026-8923-e272421b371b-TEST" {
    #Required

    items {
        #Required
        action = "CONTROL_ACCESS_USING_HTTP_METHODS"

        #Optional
        allowed_methods = ["LABEL","GET","ACL"]
        
        status_code = 405
        
    }
    ## Add_rules_here ##

    load_balancer_id = oci_load_balancer_load_balancer.c28268b4a-b6a7-4026-8923-e272421b371b.id
    name = "TEST"
}
```


Its state file contents:

```
    {
      "mode": "managed",
      "type": "oci_load_balancer_rule_set",
      "name": "c28268b4a-b6a7-4026-8923-e272421b371b-TEST",
      "provider": "provider[\"registry.terraform.io/hashicorp/oci\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "loadBalancers/ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q/ruleSets/TEST",
            "items": [
              {
                "action": "CONTROL_ACCESS_USING_HTTP_METHODS",
                "allowed_methods": [
                  "ACL",
                  "GET",
                  "LABEL"
                ],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 405,
                "suffix": "",
                "value": ""
              }
            ],
            "load_balancer_id": "ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q",
            "name": "TEST",
            "state": null,
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            }
          },
          "private": "eyJlMmJmxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
      ]
    },
```

Rule set for the Headers:

```
resource "oci_load_balancer_rule_set" "c28268b4a-b6a7-4026-8923-e272421b371b-RS1" {
    #Required

    items  {
        #Required
        action = "REDIRECT"

        conditions {
            #Required
            attribute_name = "PATH"
            attribute_value = "/home_next"

            #Optional
            operator = "SUFFIX_MATCH"
        }
        redirect_uri {

            #Optional
            host = "{host}"
            path = "/home"
            
            port = "80"
            
            
            protocol = "http"
            
        }
        response_code = "302"
    }
    items  {
        #Required
        action = "EXTEND_HTTP_REQUEST_HEADER_VALUE"
        header = "rulleset"
        
        prefix = "test"
        
        
        suffix = "pass"
        
        
    }
    items  {
        #Required
        action = "REDIRECT"

        conditions {
            #Required
            attribute_name = "PATH"
            attribute_value = "/home"

            #Optional
            operator = "EXACT_MATCH"
        }
        redirect_uri {

            #Optional
            host = "{host}"
            path = "/world"
            
            port = "80"
            
            
            protocol = "http"
            
        }
        response_code = "302"
    }
    items {
        #Required
        action = "HTTP_HEADER"
        are_invalid_characters_allowed = true
        
        http_large_header_size_in_kb = 16
        
     }
     items  {
        #Required
        action = "REMOVE_HTTP_RESPONSE_HEADER"
        header = "ruleset-new"
        
        prefix = ""
        
        
        suffix = ""
        
        
    }
    items  {
        #Required
        action = "ADD_HTTP_REQUEST_HEADER"
        header = "ruleset-test"
        
        prefix = ""
        
        
        suffix = ""
        
        
        value = "ruletest-value"
        
    }
    items  {
        #Required
        action = "EXTEND_HTTP_RESPONSE_HEADER_VALUE"
        header = "ruleset-new2"
        
        prefix = "world"
        
        
        suffix = "peace"
        
        
    }
    ## Add_rules_here ##







    load_balancer_id = oci_load_balancer_load_balancer.c28268b4a-b6a7-4026-8923-e272421b371b.id
    name = "RS1"
}

```

tfstate file contents for the above:

```
    {
      "mode": "managed",
      "type": "oci_load_balancer_rule_set",
      "name": "c28268b4a-b6a7-4026-8923-e272421b371b-RS1",
      "provider": "provider[\"registry.terraform.io/hashicorp/oci\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "loadBalancers/ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q/ruleSets/RS1",
            "items": [
              {
                "action": "ADD_HTTP_REQUEST_HEADER",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "ruleset-test",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 0,
                "suffix": "",
                "value": "ruletest-value"
              },
              {
                "action": "CONTROL_ACCESS_USING_HTTP_METHODS",
                "allowed_methods": [
                  "ACL",
                  "GET",
                  "LABEL"
                ],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 405,
                "suffix": "",
                "value": ""
              },
              {
                "action": "EXTEND_HTTP_REQUEST_HEADER_VALUE",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "rulleset",
                "http_large_header_size_in_kb": 0,
                "prefix": "test",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 0,
                "suffix": "pass",
                "value": ""
              },
              {
                "action": "EXTEND_HTTP_RESPONSE_HEADER_VALUE",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "ruleset-new2",
                "http_large_header_size_in_kb": 0,
                "prefix": "world",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 0,
                "suffix": "peace",
                "value": ""
              },
              {
                "action": "HTTP_HEADER",
                "allowed_methods": [],
                "are_invalid_characters_allowed": true,
                "conditions": [],
                "description": "",
                "header": "",
                "http_large_header_size_in_kb": 16,
                "prefix": "",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 0,
                "suffix": "",
                "value": ""
              },
              {
                "action": "REDIRECT",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [
                  {
                    "attribute_name": "PATH",
                    "attribute_value": "/home",
                    "operator": "EXACT_MATCH"
                  }
                ],
                "description": "",
                "header": "",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [
                  {
                    "host": "{host}",
                    "path": "/world",
                    "port": 80,
                    "protocol": "http",
                    "query": ""
                  }
                ],
                "response_code": 302,
                "status_code": 0,
                "suffix": "",
                "value": ""
              },
              {
                "action": "REDIRECT",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [
                  {
                    "attribute_name": "PATH",
                    "attribute_value": "/home_next",
                    "operator": "SUFFIX_MATCH"
                  }
                ],
                "description": "",
                "header": "",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [
                  {
                    "host": "{host}",
                    "path": "/home",
                    "port": 80,
                    "protocol": "http",
                    "query": ""
                  }
                ],
                "response_code": 302,
                "status_code": 0,
                "suffix": "",
                "value": ""
              },
              {
                "action": "REMOVE_HTTP_RESPONSE_HEADER",
                "allowed_methods": [],
                "are_invalid_characters_allowed": false,
                "conditions": [],
                "description": "",
                "header": "ruleset-new",
                "http_large_header_size_in_kb": 0,
                "prefix": "",
                "redirect_uri": [],
                "response_code": 0,
                "status_code": 0,
                "suffix": "",
                "value": ""
              }
            ],
            "load_balancer_id": "ocid1.loadbalancer.oc1.phx.aaaaaaaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6q",
            "name": "RS1",
            "state": null,
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            }
          },
          "private": "eyJlMmJmYjcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
      ]
    },
```
Below are the parameters that i used in tf files; we use these templates to generate the tf configuration files:

For CONTROL_ACCESS_USING_HTTP_METHODS -

items {
        #Required
        action = "{{ action }}"

        #Optional
        allowed_methods = {{ method_list }}
        status_code = {{ status_code }}
    }
-----------------------------------------------------
For ADD_HTTP_REQUEST_HEADER -

items  {
        #Required
        action = "{{ action }}"
        header = "{{ header }}"
        prefix = "{{ prefix }}"
        suffix = "{{ suffix }}"
        value = "{{ value }}"
    }


Could you please let me know if there is anything wrong?

**Comment by zexinwanoci** [comment]
The only two fields may cause recreate are
"load_balancer_id" and "name"

Which from your config, load_balancer_id are changed, which is causing the recreate,

**Comment by shruthi2703** [comment]
But it does not say that it is going to replace my load balancer, then  how can it change? I am sorry, i am a bit confused here.

**Comment by zexinwanoci** [comment]
Yes, What I mean is for the resource "oci_load_balancer_rule_set", it has a filed called "load_balancer_id", which is a forced new field. Although the "items" field remain unchanged, but since "load_balancer_id" is different from your config and your state file, the entire resource will recreate due to the forcenew.

**Comment by shruthi2703** [comment]
no, there are situations where if we do not give query parameter for REDIRECT URI, it does not take the default instead it says it will recreate my resource...why does that happen?? 

this error disappears when i add query = "?{query}" isnt that an optional parameter and a default value?

Example:

  # oci_load_balancer_rule_set.lb will be updated in-place
  ~ resource "oci_load_balancer_rule_set" "lb" {
        id               = "loadBalancers/ocid1.loadbalancer.xxxxxxxxxxxxxxxxaq/ruleSets/lb"
        load_balancer_id = "ocid1.loadbalancer.xxxxxxxxxxxxxxxaq"
        name             = "lb"

      + items {
          + action                         = "REDIRECT"
          + allowed_methods                = (known after apply)
          + are_invalid_characters_allowed = (known after apply)
          + description                    = (known after apply)
          + header                         = (known after apply)
          + http_large_header_size_in_kb   = (known after apply)
          + prefix                         = (known after apply)
          + response_code                  = 302
          + status_code                    = (known after apply)
          + suffix                         = (known after apply)
          + value                          = (known after apply)

          + conditions {
              + attribute_name  = "PATH"
              + attribute_value = "/*"
              + operator        = "PREFIX_MATCH"
            }

          + redirect_uri {
              + host     = "{host}"
              + path     = "/{path}"
              + port     = 443
              + protocol = "https"
              + query    = (known after apply)
            }
        }
      - items {
          - action                         = "REDIRECT" -> null
          - allowed_methods                = [] -> null
          - are_invalid_characters_allowed = false -> null
          - http_large_header_size_in_kb   = 0 -> null
          - response_code                  = 302 -> null
          - status_code                    = 0 -> null

          - conditions {
              - attribute_name  = "PATH" -> null
              - attribute_value = "/*" -> null
              - operator        = "PREFIX_MATCH" -> null
            }

          - redirect_uri {
              - host     = "{host}" -> null
              - path     = "/{path}" -> null
              - port     = 443 -> null
              - protocol = "https" -> null
              - query    = "?{query}" -> null
            }
        }

        timeouts {}
    }

**Comment by zexinwanoci** [comment]
Ok, this looks like an issue on terraform end, we will investigate why it happens and work on a fix. Thank you for reporting.

**Comment by zexinwanoci** [comment]
Hello Shruthi2703, can you try to make     
items {
        #Required
        action = "CONTROL_ACCESS_USING_HTTP_METHODS"

        #Optional
        allowed_methods = ["LABEL","GET","ACL"]
...
}

into 

items {
        #Required
        action = "CONTROL_ACCESS_USING_HTTP_METHODS"

        #Optional
        allowed_methods = ["ACL",","GET", "LABEL"]
...
}
? It seems like this type is currently stored as a list on terraform but as a set in the server. We will make the fix released next week. If this can be a temporary work around it will be good.

**Comment by shruthi2703** [comment]
okay thank you...
