### ISSUE TITLE
When I create a node pool (oci_containerengine_node_pool), Terraform doesn't wait for compute to be fully created

### ISSUE THREAD

**Issue by gibsster** [terraform-providers/terraform-provider-oci#1184]
I wrote a couple of TF modules to create OKE Clusters and node pools.
I need to output the worker nodes IPs to attach them to an LBaaS once the OKE and node pool are fully deployed. For this I'm using Terragrunt.
When I run this resource **oci_containerengine_node_pool**, Terraform does not wait until the compute is created in the node pool and therefore, the output in the first run looks like this 
`worker_node_ips = []`

If I run the terraform file a minute later then I get the expected result.
`worker_node_ips = [
  "100.100.183.144",
  "100.100.183.146",
  "100.100.183.145",
]`

Is there a way to implement a wait for that resource to finish once the compute has been created?
or do you happen to know if there is a workaround for this?
As I mentioned, I'm using Terragrunt to build everything in one shot `terragrunt apply-all` but it's failing when creating the backend sets because there are no IPs in the Terraform state file.

Thank you so much,
Carlos

**Comment by zexinwanoci** [comment]
I was not able to find the "worker_node_ips" in the "oci_containerengine_node_pool". Can you share the config to create this resource so we can try to reproduce it? Thank you.

**Comment by gibsster** [comment]
worker_node_ips is the name I put in my outputs file which is basically outputting the private ip of each node in the nodepool `oci_containerengine_node_pool.nodepools`

The problem is that TF doesn't populate my output called `worker_node_ips` to the terraform state file in the first execution because terraform does not wait for the nodes to be created but only for the node pool which is created in like one or two seconds.
If I  run the module again then the values are populated to the state file.

Below I'm putting the module I wrote

```
resource "oci_containerengine_node_pool" "nodepools" {
  for_each       = var.node_pools.node_pools
  cluster_id     = oci_containerengine_cluster.k8s_cluster.id
  compartment_id = var.compartment_id
  depends_on     = [oci_containerengine_cluster.k8s_cluster]

  kubernetes_version = var.oke_cluster.cluster_kubernetes_version
  name               = var.label_prefix == "none" ? each.key : "${var.label_prefix}-${each.key}"

  node_config_details {
    dynamic "placement_configs" {
      iterator = ad_iterator
      for_each = data.oci_identity_availability_domains.ad_list.availability_domains
      content {
        availability_domain = ad_iterator.value.name
        subnet_id           = var.oke_cluster.cluster_subnets["workers"]
      }
    }
    # set quantity to a minimum of 1 to allow small clusters.
    size = max(1, lookup(each.value,"node_pool_size",1))
  }

  dynamic "node_shape_config" {
    for_each = length(regexall("Flex", lookup(each.value, "shape", "VM.Standard.E3.Flex"))) > 0 ? [1] : []
    content {
      ocpus = max(1, lookup(each.value, "ocpus", 1))
    }
  }

  node_source_details {
    boot_volume_size_in_gbs = lookup(each.value,"boot_volume_size",50)
    image_id    = var.node_pools.node_pool_image_id == null ? data.oci_core_images.latest_images[each.key].images[0].id : var.node_pools.node_pool_image_id
    source_type = "IMAGE"
  }

  node_shape = lookup(each.value,"shape","VM.Standard.E3.Flex")

  ssh_public_key = file(var.oke_ssh_keys.ssh_public_key_path)

  lifecycle {
      ignore_changes = [kubernetes_version]
  }
```

Variable File
```
variable "compartment_id" {}

variable "label_prefix" {}


variable "oke_ssh_keys" {
  type = object({
    ssh_private_key_path = string
    ssh_public_key_path  = string
  })
}

variable "node_pools" {
  type = object({
    node_pools            = map(any)
    node_pool_name_prefix = string
    node_pool_image_id    = string
    node_pool_os          = string
    node_pool_os_version  = string
  })
}

```

Data sources:

```
data "oci_core_images" "latest_images" {
  for_each                 = var.node_pools.node_pools
  compartment_id           = var.compartment_id
  operating_system         = var.node_pools.node_pool_os
  operating_system_version = var.node_pools.node_pool_os_version
  shape                    = lookup(each.value,"shape","VM.Standard.E3.Flex")
  sort_by                  = "TIMECREATED"
}

data "oci_identity_availability_domains" "ad_list" {
  compartment_id = var.compartment_id
}
```


This is the output 

```
output "worked_node_ips" {
  value = flatten([
    for node in oci_containerengine_node_pool.nodepools:
        node.nodes.*.private_ip
  ])
}
```

**Comment by zexinwanoci** [comment]
Hello, since nodes are computed filed, and they are not part of the creation step for the nodepools resource, it is up to the service to decide if they want to wait for it to be fully provisioned before returning "available" state to us.
However, one of the workaround you can try is to create a null resource that depends on the resource "oci_containerengine_node_pool" "nodepools" and make it sleep.
For example you can try

resource "null_resource" "remote-exec" {
  depends_on = [oci_containerengine_node_pool.nodepools]

  provisioner "local-exec" {
    command = "sleep 60" 
  }
}


and

output "worked_node_ips" {
depends_on = [null_resource.remote-exec]
  value = flatten([
    for node in oci_containerengine_node_pool.nodepools:
        node.nodes.*.private_ip
  ])
}

**Comment by gibsster** [comment]
Thanks for your help, That works for me.
