### ISSUE TITLE
Multiple databases creation on a DB System : "The existing Db System with ID <OCID> has a conflicting state of UPDATING"

### ISSUE THREAD

**Issue by twandja** [terraform-providers/terraform-provider-oci#1185]
Hi,

I am trying to create 30 databases (oci_database_database resource) under 5 existing db_homes. All of these resources are under a single DB System :

When applying my code, a first database is successfully created then when terraform attempts to create the second one I get the following error message : "Error: Service error:IncorrectState. The existing Db System with ID <OCID> has a conflicting state of UPDATING", which causes the execution to stop.

If I re-apply my code, the second database is created then I get the same previous error when terraform attempts to create the third one.

I am assuming I get this message because terraform starts creating the following database as soon as the first one is created, but the DB System status is not up to date yet (still 'UPDATING' instead of 'AVAILABLE').

A good way for the OCI provider to avoid this issue would be to consider a database creation as completed when the creation is indeed completed AND the associated db home and db system's status are back to 'AVAILABLE'.

Any suggestion on how to adress the issue I am encountering ?

Thank you.
Thierry

**Comment by zexinwanoci** [comment]
Can you add
-parallelism=n
into your terraform apply operation?

**Comment by twandja** [comment]
Hi @zexinwanoci ,

Adding -parallelism=n into my terraform apply operation won't fix the issue because the next database creation will still start as soon as the "creation complete" message from the first database creation will be returned.

The problems comes from the fact that the "creation complete" message is returned while the associated db_home and or db system's status is still 'UPDATING' during a few seconds (~5s) after the database is created which causes the "IncorrectState" error message.

**Comment by zexinwanoci** [comment]
I have tried to reproduce it and seems like it works for me. Did you change the retry logic or something? Can you also provide your provider and terraform version and your config? Thank you

2020-10-01T23:19:25.283-0700 [DEBUG] plugin.terraform-provider-oci_v3.92.0_x4:   "code" : "IncorrectState",
2020-10-01T23:19:25.283-0700 [DEBUG] plugin.terraform-provider-oci_v3.92.0_x4:   "message" : "The existing Db System with ID ocid1.dbsystem.oc1.phx.abyhqljr25r4uu6heb4qecdtzyea665f7ljcl3tvlgxyf2eidb3h536fuhqq has a conflicting state of UPDATING."
2020-10-01T23:19:25.283-0700 [DEBUG] plugin.terraform-provider-oci_v3.92.0_x4: }
2020-10-01T23:19:25.283-0700 [DEBUG] plugin.terraform-provider-oci_v3.92.0_x4: DEBUG 2020/10/01 23:19:25.283085 asm_amd64.s:1337: waiting 1m0.047382172s before retrying operation

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

**Comment by twandja** [comment]
Hi @zexinwanoci ,

I indeed set the retry_duration_seconds parameter within my provider : 

`provider "oci" {
  version          = ">= 3.0.0"
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
  retry_duration_seconds = "36000"
}`

Here is my local module definition in ./modules/database/main.tf : 

`resource "oci_database_database" "database" {
    database {
        admin_password = var.admin_password
        db_name        = var.db_name
        character_set  = var.character_set
        db_workload    = var.db_workload
        ncharacter_set = var.ncharacter_set
        pdb_name       = var.pdb_name
        db_backup_config {
            auto_backup_enabled = var.auto_backup_enabled
        }
    }
    db_home_id = var.db_home_id
    source     = var.db_source
    db_version = var.db_version

    timeouts {
        create = "24h"
    }
}`

And here is a snippet of the databases.tf files which creates the 30 databases (I voluntarily faked out the db_home_id values) : 

`module "DB1" {
    source              = "./modules/database"
    admin_password      = "azerty123"
    db_name             = "DB1"
    character_set       = "AL32UTF8"
    ncharacter_set      = "AL16UTF16"
    db_home_id          = "ocid1.dbhome.xxxxxxxxxxxxxx"
    db_version          = "11.2.0.4"
    auto_backup_enabled = "false"
}

module "DB2" {
    source              = "./modules/database"
    admin_password      = "azerty123"
    db_name             = "DB2"
    character_set       = "WE8ISO8859P15"
    ncharacter_set      = "UTF8"
    db_home_id          = "ocid1.dbhome.xxxxxxxxxxxxxx"
    db_version          = "11.2.0.4"
    auto_backup_enabled = "false"
}`

Should I remove the retry_duration_seconds setting from my provider ?

**Comment by twandja** [comment]
I removed the retry_duration_seconds setting from provider.tf and retried the databases creation. The first database was created succesfully then I had the same error again : 

```
module.FHOMOGEN.oci_database_database.database: Creation complete after 20m1s [id=ocid1.database.oc1.eu-frankfurt-1.abtheljreh7e6uqrsutqo6tqsjy43xurzwg23hvbl2lrvoetxle6ie4ahh5q]
Error: Service error:IncorrectState. The existing Db System with ID ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljrswo7a3ajbcgpz2zv2l2n254zv6x34l2b47i4f2dcducliv246kzq has a conflicting state of UPDATING.. http status code: 409. Opc request id: 445563fcbdf3608b1f383c9a83eb87af/2FFC89EBDA9821CAA6A10EA166B90615/60D10FF12D05ECF94CD5689F2E4E2B7A

  on .terraform/modules/FBE1FORM/main.tf line 1, in resource "oci_database_database" "database":
   1: resource "oci_database_database" "database" {
```

Followed by this error message : 

```
Error: Service error:TooManyRequests. Too many requests for the tenant. http status code: 429. Opc request id: fcaff46bec06b1e65842956c848735b0/35DEFEEEC953BC478ED68D8AB66F9E60/6A80E81208AE52269BCB1FBAFC45C411

  on .terraform/modules/dbhome_T11G/main.tf line 2, in resource "oci_database_db_home" "db_home":
   2: resource "oci_database_db_home" "db_home" {
```

**Comment by zexinwanoci** [comment]
Hello Twandja, so this error message is expected, since db_system will be updated everytime when there is a new database created within it. However it should not break terraform apply and terraform should retry it. Can you share the terraform version and terraform provider version?

**Comment by twandja** [comment]
Hi,

The terraform version is **0.12.24**.

The terraform provider version is 3.95.0 : 

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "oci" (hashicorp/oci) 3.95.0...

Terraform has been successfully initialized!
```

**Comment by zexinwanoci** [comment]
Hum, This should not happened, can you enable the debug log and post the error message around the message "message" : "The existing Db System with ID ocid1.dbsystem.oc1.phx.abyhqljr25r4uu6heb4qecdtzyea665f7ljcl3tvlgxyf2eidb3h536fuhqq has a conflicting state of UPDATING." ?

This error message is expected but terraform should retry it until timeout, which should be around 10min.

**Comment by twandja** [comment]
Test

**Comment by twandja** [comment]
Hi,

Sorry for the delay in my reply. Here are the terraform apply logs around the error obtained :

```
module.DBTEST02.oci_database_database.database: Still creating... [21m0s elapsed]
2020/10/13 11:18:45 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.DBTEST02.oci_database_database.database"
2020/10/13 11:18:47 [TRACE] dag/walk: vertex "provider.oci (close)" is waiting for "module.DBTEST02.oci_database_database.database"
2020/10/13 11:18:48 [TRACE] dag/walk: vertex "root" is waiting for "provider.oci (close)"
2020-10-13T11:18:49.411Z [DEBUG] plugin.terraform-provider-oci_v3.96.0_x4: 2020/10/13 11:18:49 [DEBUG] BaseCrud.setState: state: "AVAILABLE"
2020/10/13 11:18:49 [WARN] Provider "registry.terraform.io/-/oci" produced an unexpected new value for module.DBTEST02.oci_database_database.database, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .database[0].backup_id: was null, but now cty.StringVal("")
      - .database[0].backup_tde_password: inconsistent values for sensitive attribute
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalMaybeTainted
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalWriteState
2020/10/13 11:18:49 [TRACE] EvalWriteState: recording 0 dependencies for module.DBTEST02.oci_database_database.database
2020/10/13 11:18:49 [TRACE] EvalWriteState: writing current state object for module.DBTEST02.oci_database_database.database
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalApplyProvisioners
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalMaybeTainted
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalWriteState
2020/10/13 11:18:49 [TRACE] EvalWriteState: recording 0 dependencies for module.DBTEST02.oci_database_database.database
2020/10/13 11:18:49 [TRACE] EvalWriteState: writing current state object for module.DBTEST02.oci_database_database.database
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalIf
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalIf
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalWriteDiff
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalApplyPost
2020/10/13 11:18:49 [TRACE] module.DBTEST02: eval: *terraform.EvalUpdateStateHook
2020/10/13 11:18:49 [TRACE] [walkApply] Exiting eval tree: module.DBTEST02.oci_database_database.database
2020/10/13 11:18:49 [TRACE] vertex "module.DBTEST02.oci_database_database.database": visit complete
2020/10/13 11:18:49 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/10/13 11:18:49 [TRACE] dag/walk: upstream of "provider.oci (close)" errored, so skipping
2020/10/13 11:18:49 [TRACE] dag/walk: upstream of "root" errored, so skipping
module.DBTEST02.oci_database_database.database: Creation complete after 21m5s [id=ocid1.database.oc1.eu-frankfurt-1.abtheljrfawberlbeicbohtmvlasbgco6khlzyjuh5dkc6r2uedvpr6agnna]

Error: Service error:IncorrectState. The existing Db System with ID ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljrswo7a3ajbcgpz2zv2l2n254zv6x34l2b47i4f2dcducliv246kzq has a conflicting state of UPDATING.. http status code: 409. Opc request id: c39ff1072f444adb09302abc781e6476/1D3DE592FAA7C0873BA22B8BFCAA3E20/CD970D7B253879E3057187A7FE1C3034

  on .terraform/modules/DBTEST01/main.tf line 1, in resource "oci_database_database" "database":
   1: resource "oci_database_database" "database" {



Error: Service error:IncorrectState. The existing Db System with ID ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljrswo7a3ajbcgpz2zv2l2n254zv6x34l2b47i4f2dcducliv246kzq has a conflicting state of UPDATING.. http status code: 409. Opc request id: 396703e56831fbd256480a734c42a27f/2F043FDE24D16544CF16A734F1014C8A/BDD0C4D3ECE47E94523F1408EE13A445

  on .terraform/modules/DBTEST03/main.tf line 1, in resource "oci_database_database" "database":
   1: resource "oci_database_database" "database" {


2020-10-13T11:18:49.481Z [DEBUG] plugin: plugin process exited: path=/home/jenkins/agent/workspace/groupe-erp/90408/deploy_databases/recette/.terraform/plugins/linux_amd64/terraform-provider-oci_v3.96.0_x4 pid=329
2020-10-13T11:18:49.481Z [DEBUG] plugin: plugin exited
```

**Comment by twandja** [comment]
Hi @zexinwanoci ,

Could you please get back to me regarding the issue ?

Thank you.

**Comment by srikanthpandarangi** [comment]
Can someone please provide a solution for this issue.  I am trying to create multiple DB's in DB home.  After creation of 1 DB i am getting below error.

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/oci v4.22.0

first DB ["db_instance1"]: Creation complete after 22m2s.

Error: 409-IncorrectState 
Provider version: 4.22.0, released on 2021-04-14. This provider is 1 updates behind to current. 
Service: Database 
Error Message: The operation cannot be performed because the Db System with ID ocid1.cloudvmcluster.oc1.iad.abuwcljtqopg7wagdf5hx462mpnerawesq6so7duucuxytyowmxt3vmxd3uq is in the UPDATING state. 
OPC request ID: fac82fa80e84fd4702e2861133c5e9fd/640BBBE7E1BFD60071FFF38442A889DC/BDA43114CA453AFB0830946316257FCA 
Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Database
