### ISSUE TITLE
ID of backup policy - data source is getting modified, but why?

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#1186]
![image](https://user-images.githubusercontent.com/35778318/94309080-22f65380-ff95-11ea-81e6-f76a3b66b6e7.png)

Hi ,

I am unable to understand what is the id that it is trying to modify here? Data source should not come like this right?
Could you please explain? It seems to be some time of creation? but why is it changing?

**Comment by zexinwanoci** [comment]
What is your terraform CLI version? It looks like a bug that is introduced in the tf 13.

**Comment by shruthi2703** [comment]
yes i am using v0.13 of terraform

**Comment by zexinwanoci** [comment]
Hi Shruthi2703, this is a known issue for v0.13 version of terraform, we have submitted the issue to Hashicorp and it will be fix in 0.14. In the main time can you try to use v0.12 and see if it goes away? Thank you.

**Comment by shruthi2703** [comment]
okay thank you.
