### ISSUE TITLE
Documentation regarding instance scaling is out-of-date; no longer required to preserve Boot Volume and term/launch

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1190]
Documentation refers to process for preserving Boot Volume in support of instance scaling. That is no longer required and may be misleading to those new to OCI Terraform.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References
* https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/boot_volume_troubleshooting_reuse

**Comment by govindrao55** [comment]
Hi @jeliker , Thanks for pointing this out. I've updated the documentation to clarify when the preserve boot volume is still needed.
