### ISSUE TITLE
Provide cloudinit capability to oci_database_db_system

### ISSUE THREAD

**Issue by psaddi** [terraform-providers/terraform-provider-oci#1192]
### Description

Hi There,

We would like to be able to use cloud-init for the DB vms provisioned using oci_database_db_system. Just like how add cloud-init for computes would it be possible to do the same for VM based databases. This will greatly simplify the DB connectivity issues for us especially when we create DBS in private subnets and can't access it directly using ip addresses and would instead need to depend on a bastion.

Please do let me know if you need any further information

**Comment by rashik-bhasin** [comment]
We have raised this issue with service to add support for cloud-init.
Thanks!

**Comment by s2solbach** [comment]
Unfortunately would cloud-init run before the full DBCS instance is deployed. This could create multiple issues, as it is very hard to guarantee that the DBCS instance would create successfull. Additionally DBCS instances don't run within the customer tenancy...

Both things are solvable, but definitely not with cloud init.

As an agent is running on DBCS instances (e.g. for adding ssh keys) the solution could be that we allow passing a script to the agent. This again is however could pose a security issue by simply allowing it.

What customization exactly are you looking for? Maybe there is another way to solve this or enhance the agent explicitly for this as other customers might need same functionality.

**Comment by psaddi** [comment]
Hi Sebastian,

Thank you for looking at it. I work on a product which allows Sales people to easily customize on OCI resources and show case some demos. What we do is provide docker images with runnable terraform entry points which would create the OCI resources and then they could add their own customizations to resources that we create for them.

There could be sometimes different customizations each team needs and rather than forcing them connect to the resources separately, I was hoping if we provided cloud-init support to the owner of the resource, would make it easy for them.

The workaround is definitely there which is to connect to the db after provisioning and performing whatever they want, through a script, which could very well be a perfect option for cloud-init.

If it is not doable ( effort wise/ security constraints), then I can live with my existing option, but just wanted to see if you guys wanted to make things simpler , if it were not a concern

**Comment by parrneet** [comment]
We are closing this ticket as it is not a Terraform issue and we connected you to the Database team to find a workaround.
