### ISSUE TITLE
What version oci provider can work with "is_data_guard_enabled" for ADB?

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#1193]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

Before using this template, check whether your question is already answered in one of the following guides:
* [Frequently Asked Questions](https://www.terraform.io/docs/providers/oci/guides/faq.html)
* [Troubleshooting](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html)

If you have a support request related to Oracle Cloud Infrastructure services, please [contact Oracle support](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm)

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Hi Team,

I have tried to enable autonomous dataguard for ADB but it is errorred out like below.

Error: module.autonomous-database.oci_database_autonomous_database.ATPCTEST1: : invalid or unknown key: is_data_guard_enabled
Error: module.autonomous-database.oci_database_autonomous_database.ATPCTEST1: : invalid or unknown key: switchover_to

We have OCI provider version.

Terraform v0.11.13
--
14:19:40 |   |   | + provider.external v1.2.0
14:19:40 |   |   | + provider.local v1.4.0
14:19:40 |   |   | + provider.null v2.1.2
14:19:40 |   |   | + provider.oci v3.74.0
14:19:40 |   |   | + provider.random v2.2.1
14:19:40 |   |   | + provider.template v2.1.2
14:19:40 |   |   | + provider.tls v2.1.1

Can you let me know which version should we go for?

Cheers

**Comment by rashik-bhasin** [comment]
Hi,
`is_data_guard_enabled` for ADB was released in v3.85.0: https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.85.0 . 
Thanks!

**Comment by rashik-bhasin** [comment]
Closing this issue. 
Let us know if you have any more questions.

Thanks!
