### ISSUE TITLE
When selecting E3.Flex as node shape for container engine node pool, allow memory to be specified

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#1197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

When creating an instance and the E3.Flex shape is used, we can specify both the number of OCPUs and memory e.g.

```
    shape_config {

        #Optional
        memory_in_gbs = "${var.instance_shape_config_memory_in_gbs}"
        ocpus = "${var.instance_shape_config_ocpus}"
    }
```

However, we can specify only the number of ocpus when creating node pools in container engine:

```
node_shape_config {
        #Optional
        ocpus = var.node_pool_node_shape_config_ocpus
    }
```

Can we please also have the ability to specify the desired amount of memory for worker nodes in node pools just as we can for normal instances?

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by rashik-bhasin** [comment]
We have raised the issue with service team to add support for this field.
Thanks!
