### ISSUE TITLE
Duplicate Period on different day being detected on backup policy definition

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [terraform-providers/terraform-provider-oci#1199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.29
+ provider.oci v3.96.0
+ provider.template v2.2.0

### Affected Resource(s)

 "oci_core_volume_backup_policy"

### Terraform Configuration Files

```hcl
resource "oci_core_volume_backup_policy" "mt_std_backup_policy" {
  #Required
  compartment_id = var.compartment_id

  #Optional
  destination_region = var.paired_regional_unit
  display_name       = "Mitratech Standard Geo-Redundant Daily"

  schedules {
    #Required
    backup_type       = "FULL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "SATURDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "SUNDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "MONDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "TUESDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "WEDNESDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "THURSDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }
  
  schedules {
    #Required
    backup_type       = "INCREMENTAL"
    period            = "ONE_WEEK"
    retention_seconds = 1209600

    #Optional
    day_of_week = "FRIDAY"
    hour_of_day = 0
    time_zone   = "REGIONAL_DATA_CENTER_TIME"
  }

  ## Defined Tag Info ##
  ## Add comma seperated tags in addition to the Environment tag, which is required.
  defined_tags = var.environment_tag == null ? null : merge(var.environment_tag)

  freeform_tags = {
    # Terraform Tags
    "terraform_managed" = "true"

  }
}

output "id" {
  value = oci_core_volume_backup_policy.mt_std_backup_policy.id
}

```

### Debug Output
https://gist.github.com/AndreasFrangopoulos/1d1b87eab0ff58715925c465377f056e

### Expected Behavior
A single policy with one Full backup day at midnight and incrementals for the rest of the week. One a day

### Actual Behavior
 Error: Service error:InvalidParameter. You can only create one schedule with the same time period per day within the same backup policy.. http status code: 400.

### Steps to Reproduce

1. `terraform apply`

**Comment by AndreasFrangopoulos** [comment]
Hi @rashik-bhasin , I've updated the gist with more of the previous output. Hopefully that has what you need in it. Prior to this, as far as I can tell, is just Terraform working internally and then certificate exchanges with the API
https://gist.github.com/AndreasFrangopoulos/1d1b87eab0ff58715925c465377f056e

**Comment by rashik-bhasin** [comment]
Hi @AndreasFrangopoulos, this looks like a service issue or something that service needs to clarify if there is an issue with the details filled to create the resource, so i have created a ticket with them. 
Thanks!

**Comment by parrneet** [comment]
Hi @AndreasFrangopoulos 

According to service, This is by design. Please set a daily incremental policy and add a weekly full backup policy on Saturday?

Feel free to reopen the issue if this does not resolve the problem.
