### ISSUE TITLE
container repo pull fails with  "repo1.maven.org: Name or service not known"

### ISSUE THREAD

**Issue by bieksaz** [terraform-providers/terraform-provider-oci#1201]
### Affected Resource(s)

container DNS resolution (as it looks)

### Expected Behavior

should resolve DNS addresses

### Actual Behavior

can not resolve any DNS address. Was working in past without issues

### Steps to Reproduce

regular deployment of container services

### Important Factoids

seems IP's can be reached, so it is not a connectivity issue, only domain names cannot be resolved. 

example:
[root@qh-mw-XXXXX /]# ping repo1.maven.org
ping: repo1.maven.org: Name or service not known
[root@qh-mw-XXXXX  /]# ping 199.232.192.209
PING 199.232.192.209 (199.232.192.209) 56(84) bytes of data.
64 bytes from 199.232.192.209: icmp_seq=1 ttl=55 time=2.78 ms
64 bytes from 199.232.192.209: icmp_seq=2 ttl=55 time=1.36 ms

**Comment by rashik-bhasin** [comment]
Can you please share the terraform configuration, provider version Go version that you are using?
From the details you have shared it doesn't look like a terraform issue to me.
Thanks!

**Comment by bieksaz** [comment]
it truly shouldn't be terraform issue, this same configuration was still working fine around a month ago when I last tried and it also deploys without failures now.  This is more like something general with oci. Basically the issue happens already after container deployment once application starts and tries to download required libraries. This is why I registered in oci section, if it is a wrong place for such ticket, could you point me where should I register it

**Comment by bieksaz** [comment]
well, nothing is working, so its not a question, but an issue, please take actions or either direct to a proper channel where such issue should be analyzed.  After all, we need to pay for service which is non operational.

**Comment by rashik-bhasin** [comment]
I looks like a java issue to me seeing that you are using maven, so you can create an issue on oci-java-sdk for this: https://github.com/oracle/oci-java-sdk/issues . 
Closing this issue as it's not a terraform provider issue. Feel free to create an issue of you face any issues.
Thanks!

**Comment by bieksaz** [comment]
> I looks like a java issue to me seeing that you are using maven, so you can create an issue on oci-java-sdk for this: https://github.com/oracle/oci-java-sdk/issues .
> Closing this issue as it's not a terraform provider issue. Feel free to create an issue of you face any issues.
> Thanks!

looks like an issue of an cloud instance network interface rashik. But yes, it is easier to close ticket than think about it. I guess I will need to open SR in oracle support if this is not the place where they care about oci problems

**Comment by alexng-canuck** [comment]
Hi @bieksaz 
This forum is mainly for issues related to Terraform OCI provider and is monitored mainly by Terraform provider developers.  

We are limited in our ability to troubleshoot general OCI issues. If you are having general issues with OCI, the recommended support path is through Oracle support.
