### ISSUE TITLE
dns-label length isn't checked at the plan stage

### ISSUE THREAD

**Issue by rml1997** [terraform-providers/terraform-provider-oci#1204]
If a dns-label with a length over 15 is submitted, it is only picked up during the API call (when the apply is confirmed).

It should be picked up at the plan stage

**Comment by varmax2511** [comment]
Hi @rml1997 -- please specify the terraform provider resource you are encountering the issue with. Terraform provider as a client doesn't validate the input for the backend service. `Plan` phase is to validate the terraform configuration for syntax and semantics. 
https://www.terraform.io/docs/commands/plan.html

Validating the input length and its correctness is validated by `apply` when the actual call is made to the backend.
