### ISSUE TITLE
Add memory_in_gbs to oci_core_instance_configuration shape_config

### ISSUE THREAD

**Issue by ngucandy** [terraform-providers/terraform-provider-oci#1214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, oci_core_instance_configuration does not support memory_in_gbs under shape_config as supported by oci_core_instance shape_config.  Without this option, memory is fixed to 16GB / OCPU for flex shapes.  Can this option be added to oci_core_instance_configuration?

### New or Affected Resource(s)

oci_core_instance_configuration

### Potential Terraform Configuration

```hcl
resource oci_core_instance_configuration test_instance_config {
  ...
  instance_details {
  ...
    launch_details {
    ...
      shape = "VM.Standard.E3.Flex"
      shape_config {
        ocpus = 16
        memory_in_gbs = 512
      }
    }
  }
}
```

**Comment by govindrao55** [comment]
Hi @ngucandy , Thanks for reaching out. To expose this functionality in terraform, the service needs to support it in the instance configuration creation flow. I've internally raised a ticket with the service team to request this change.

**Comment by ngucandy** [comment]
Hi @govindrao55.  Thanks for looking at this.  I'm not sure what you mean by the service needs to support it in the instance creation flow.  The support for supplying memory_in_gbs is already in the OCI Go SDK that's vendored: https://github.com/terraform-providers/terraform-provider-oci/blob/e84e172a903d9778bc0fe8ab72a667ded96d1171/vendor/github.com/oracle/oci-go-sdk/v27/core/instance_configuration_launch_instance_shape_config_details.go#L29.  It looks like the schema for CoreInstanceConfigurationResource is missing an option under shape_config for memory_in_gbs.

**Comment by varmax2511** [comment]
Hi @ngucandy -- with Terraform provider version  4.2.0, support for `memory_in_gbs` is now available in `oci_core_instance_configuration` shape_config

https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v4.2.0

Please let us know if this resolves the issue.
