### ISSUE TITLE
Issue with Terraform Plan execution

### ISSUE THREAD

**Issue by bsmahara** [terraform-providers/terraform-provider-oci#1217]
Hi All ,
I am trying to run terraform to verify before applying and get the below error .
Please advise on how can i avoid this error . I checked the variables multiple time but didn't find the exact issue .
Steps are as below : 

1. terraform -version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/oci v4.0.0
2. source env-vars ( runs fine)
3. terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/oci v4.0.0

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/oci: version = "~> 4.0.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
4. terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

**data.oci_identity_availability_domain.ad: Refreshing state...

**Error: did not find a proper configuration for private key

  on datasources.tf line 4, in data "oci_identity_availability_domain" "ad":
   4: data "oci_identity_availability_domain" "ad" {****

I have verified the below : 

a. have public and private keys in PEM format as OCI accepts them 
b. All other variables with OCI ID's etc have been defined properly in "env-vars" .
c. datasources.tf has the below format : 

// Copyright (c) 2017, 2020, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0

data "oci_identity_availability_domain" "ad" {
  compartment_id = var.compartment_ocid
  ad_number = 1
}

# Get DB node list
data "oci_database_db_nodes" "db_nodes" {
  compartment_id = var.compartment_ocid
  db_system_id   = oci_database_db_system.test_db_system.id
}

# Get DB node details
data "oci_database_db_node" "db_node_details" {
  db_node_id = data.oci_database_db_nodes.db_nodes.db_nodes[0]["id"]
}

# Gets the OCID of the first (default) vNIC
#data "oci_core_vnic" "db_node_vnic" {
#    vnic_id = data.oci_database_db_node.db_node_details.vnic_id
#}

data "oci_database_db_homes" "db_homes" {
  compartment_id = var.compartment_ocid
  db_system_id   = oci_database_db_system.test_db_system.id
}

data "oci_database_databases" "databases" {
  compartment_id = var.compartment_ocid
  db_home_id     = data.oci_database_db_homes.db_homes.db_homes[0].db_home_id
}

data "oci_database_backups" "test_backups" {
  database_id = data.oci_database_databases.databases.databases[0].id

  filter {
    name   = "id"
    values = [oci_database_backup.test_backup.id]
  }

  filter {
    name   = "state"
    values = ["AVAILABLE"]
  }
}

data "oci_database_db_system_patches" "patches" {
  db_system_id = oci_database_db_system.test_db_system.id
}

data "oci_database_db_system_patch_history_entries" "patches_history" {
  db_system_id = oci_database_db_system.test_db_system.id
}

data "oci_database_db_home_patches" "patches" {
  db_home_id = data.oci_database_db_homes.db_homes.db_homes[0].db_home_id
}

data "oci_database_db_home_patch_history_entries" "patches_history" {
  db_home_id = data.oci_database_db_homes.db_homes.db_homes[0].db_home_id
}

data "oci_database_db_systems" "db_systems" {
  compartment_id = var.compartment_ocid
  backup_id      = oci_database_backup.test_backup.id
}

data "oci_database_db_versions" "test_db_versions_by_db_system_id" {
  compartment_id = var.compartment_ocid
  db_system_id   = oci_database_db_system.test_db_system.id
}

data "oci_database_db_system_shapes" "test_db_system_shapes" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  compartment_id      = var.compartment_ocid

  filter {
    name   = "shape"
    values = [var.db_system_shape]
  }
}

data "oci_database_db_node_console_connections" "test_db_node_console_connections" {
  db_node_id = data.oci_database_db_nodes.db_nodes.db_nodes[0]["id"]
}

data "oci_database_db_node_console_connection" "test_db_node_console_connection" {
  db_node_id = data.oci_database_db_nodes.db_nodes.db_nodes[0]["id"]
  id         = oci_database_db_node_console_connection.test_db_node_console_connection.id
}

Please help resolve this issue .

Thanks,
Bhabani

**Comment by govindrao55** [comment]
Hi @bsmahara , There can be multiple reasons for this like:
- Not specifying either a `private_key` or `private_key_path` in the config
- Specifying a `private_key_path` that's not a valid path to a private key file
- Not specifying a `private_key_password` for a private key that's encrypted
- Specifying an incorrect `private_key_password` for an encrypted private key

Can you please check values are set correctly in environment using TF_VAR_{variable_name} ?

**Comment by govindrao55** [comment]
Hi @bsmahara , please re-open if you need to. Closing for now.
