### ISSUE TITLE
ExaCS: cannot create db_home after migrating to resource model

### ISSUE THREAD

**Issue by lucianf** [terraform-providers/terraform-provider-oci#1218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/oci v4.0.0

### Affected Resource(s)

`oci_database_db_home`

### Terraform Configuration Files

```hcl
resource "oci_database_cloud_exadata_infrastructure" "x01" {
  compartment_id      = oci_identity_compartment.db.id
  availability_domain = local.ad_list.AD1

  display_name = "x01"
  shape        = "Exadata.Quarter3.100"
}

resource "oci_database_cloud_vm_cluster" "xclu01" {
  compartment_id                  = oci_identity_compartment.db.id
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.x01.id

  display_name = "xclu01"
  cluster_name = "xclu01"

  cpu_core_count              = 16
  data_storage_percentage     = 80
  is_local_backup_enabled     = false
  is_sparse_diskgroup_enabled = true
  time_zone                   = "UTC"
  gi_version                  = "19.0.0.0" //19.8.0.0.0
  license_model               = "LICENSE_INCLUDED"

  hostname         = "x01-xxxxx"
  subnet_id        = oci_core_subnet.db1.id
  backup_subnet_id = oci_core_subnet.db2.id

  ssh_public_keys = [chomp(file(local.ssh_key_list.x01))]

  lifecycle {
    ignore_changes = [
      gi_version
    ]
  }
}

resource oci_database_db_home x01_dbhome5 {
  depends_on    = [oci_database_db_home.x01_dbhome4]
  vm_cluster_id = oci_database_cloud_vm_cluster.xclu01.id

  display_name = "ora19dbhome5"
  db_version   = "19.0.0.0"

  database {
    pdb_name = "pdb"
    db_name  = "cdb"

    db_workload    = "OLTP"
    character_set  = "WE8ISO8859P1"
    ncharacter_set = "AL16UTF16"

    admin_password = local.admin_passwords_list.x01.dbhome5

    db_backup_config {
      auto_backup_enabled = "false"
    }
  }

  timeouts {
    create = "2h"
    delete = "2h"
  }
}

```

### Expected Behavior

Creating a new db_home with a new database should work as expected.

### Actual Behavior

Terraform fails after exactly 2 minutes with the following error:

```
oci_database_db_home.x01_dbhome5: Creating...
oci_database_db_home.x01_dbhome5: Still creating... [10s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [20s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [30s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [40s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [50s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m0s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m10s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m20s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m30s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m40s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [1m50s elapsed]
oci_database_db_home.x01_dbhome5: Still creating... [2m0s elapsed]

Error: Service error:InternalError. Internal error occurred. http status code: 500. Opc request id: 594a751bfdf40fea86f5cbd720ecf629/5A63D7CEE843AD0B3E61ECEBCE5676EC/2E867A255772D4E593D010D34773B6ED, The service for this resource encountered an error. Please contact support for help with that service

  on exadata.tf line 189, in resource "oci_database_db_home" "x01_dbhome5":
 189: resource oci_database_db_home x01_dbhome5 {

```

### Important Factoids

- The Exadata environment was created through Terraform as a DB System with 2 db homes containing 1 database each
- This was subsequently migrated to the new infrastructure resource model.  The Terraform `oci_database_db_system` was then replaced with a pair of `oci_database_cloud_exadata_infrastructure` and `oci_database_cloud_vm_cluster`, as shared above (the VM cluster pointing to the old dbsystem OCID).
- Adding new db homes (e.g. dbhome5 above) fails with the above error.

However, I managed to manually add 2 more db homes (dbhome3 and dbhome4) just fine using the OCI console and OCI CLI respectively, therefore the problem seems to only be with the Terraform OCI provider.

**Comment by govindrao55** [comment]
Hi @lucianf , for the `oci_database_db_home` resource, the default value of [`source`](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_db_home#source)=`NONE` is being sent to the service which is incorrect for your use case. The `source` can either be `VM_CLUSTER_BACKUP` or `VM_CLUSTER_NEW` when [`vm_cluster_id`](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_db_home#vm_cluster_id) is set. 

Can you correct the value for `source` argument in `oci_database_db_home` resource and try again? Let me know if that works. The error message is not very indicative sorry about that, I've raised a ticket internally with service team to improve the error message.

**Comment by lucianf** [comment]
Thanks @govindrao55 unfortunately that doesn't seem to work, I'm getting a different error after I added `source="VM_CLUSTER_NEW"`:

```
Error: Service error:InvalidParameter. Operation failed, use the CloudVmCluster APIs for resource ocid1.dbsystem.oc1.xx-xxx-1.xxxoq4a.. http status code: 400. Opc request id: 60f846c2711d4cbf704b3f3fa16aafc1/772F3902976804D330669FC95C3A6114/3BEB54CBCE1C6BC5EEB87F199BB8D72A
```

**Comment by govindrao55** [comment]
Hi @lucianf , I see `xx-xxx-1` in the OCID `ocid1.dbsystem.oc1.xx-xxx-1.xxxoq4a..`, which looks incorrect. Can you confirm if the value of the region variable is set correctly? it will be better if you write the value for region variable instead from copy-paste to avoid introducing invalid characters. Check [this](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence) to understand how variables can be defined and their precedence. Let me know if the value for region variable is as expected.

**Comment by lucianf** [comment]
That's not the problem - I just edited the OCID for privacy.

**Comment by govindrao55** [comment]
@lucianf , I've created a ticket with the service team, will add the new error on the ticket and let you know once I've any update from service team.

**Comment by lucianf** [comment]
Thank you @govindrao55.  Are you sure this issue lies with the service team?

As mentioned above I'm able to create new databases & dbhomes within this VM cluster just fine using the OCI console & OCI CLI, which I presume both use the same underlying APIs as the Terraform OCI provider (namely `CreateDbHome` and `CreateDbHomeWithVmClusterIdDetails` for the dbhome, and `CreateDatabase`, `CreateNewDatabaseDetails`, and `CreateDatabaseDetails` for the database).

If the former work fine but the latter throws an error could it not be because of incorrect/incomplete parameters to the database OCI APIs?

**Comment by lucianf** [comment]
@govindrao55 I suspect you're calling the wrong APIs.

Back without defining the source attribute (i.e. `source=NONE`) running `terraform apply` under DEBUG I noticed:

```
2020-10-27T22:37:32.611Z [DEBUG] plugin.terraform-provider-oci_v4.0.0_x4: DEBUG 2020/10/27 22:37:32.611555 http.go:617: Marshaling to Request: CreateDbHomeRequest
2020-10-27T22:37:32.611Z [DEBUG] plugin.terraform-provider-oci_v4.0.0_x4: DEBUG 2020/10/27 22:37:32.611587 http.go:555: Marshaling to body from field:CreateDbHomeWithDbSystemIdDetails
```

But the correct subtype of `CreateDbHomeBase` for creating a DB Home for **Exadata Cloud Service (ExaCS)** is actually `CreateDbHomeWithVmClusterIdDetails`.

As for when running `terraform apply` with `source=VM_CLUSTER_NEW` I noticed:

```
2020-10-27T22:32:37.603Z [DEBUG] plugin.terraform-provider-oci_v4.0.0_x4: DEBUG 2020/10/27 22:32:37.603361 http.go:617: Marshaling to Request: GetVmClusterRequest
2020-10-27T22:32:37.603Z [DEBUG] plugin.terraform-provider-oci_v4.0.0_x4: DEBUG 2020/10/27 22:32:37.603395 http.go:551: Marshaling to path from field: VmClusterId in template: /vmClusters/{vmClusterId}
```

But then `GetVmClusterRequest` is an API for **Exadata Cloud@Customer** only (ExaCC, not ExaCS) hence the error.

Hope this helps.

**Comment by alexng-canuck** [comment]
@lucianf , I presume the `GetVmClusterRequest` is coming from inside a `oci_database_db_system` resource? Can you share the details about that resource?

**Comment by alexng-canuck** [comment]
@lucianf , I think you may be on to something.

The `oci_database_db_home` resource has some polling logic that relies on `GetVmCluster` API to wait for a vm cluster to finish updating before creating the db_home (to avoid errors that could happen if trying to create a Db home while cluster is being updated).

That polling logic seems to have missed taking into account that the `vm_cluster_id` could be sourced from a Exacc vmcluster (and hence it is only calling `GetVmCluster` instead of also considering `GetCloudVmCluster`)

**Comment by alexng-canuck** [comment]
We're taking a look to see if the polling logic can be updated to call either of the 2 APIs depending on the format of the `vm_cluster_id` OCID.

**Comment by lucianf** [comment]
Thanks @alexng-canuck.  Not sure you can use the `vm_cluster_id` OCID format reliably, or at least you have to look for edge cases - in my case it's actually a DB System OCID, since the resource has been converted from the old model (a cloud VM cluster OCID was not assigned during the resource migration).  I'm not familiar with ExaCC but it might be using similar OCIDs.

Do you not have access to the underlying resource type of the `vm_cluster_id` if declared as such in the code (rather than as a literal OCID)?  I'd assume my case of `vm_cluster_id = oci_database_cloud_vm_cluster.xclu01.id` would be a pretty standard approach, and from there you could infer that `xclu01` is an ExaCS cloud VM cluster rather than an ExaCC one (or a DB System, if you were to judge by the OCID).

**Comment by lucianf** [comment]
In that case using `cloud_vm_cluster_id` for ExaCS might be a reliable KISS workaround.  Even the code would be more consistent, after all this is exactly where the distinction is between the ExaCS and ExaCC OCI APIs - with/without the `cloud`.

(I thought this was what the `source` attribute was for, I'm still confused with the differences between `NONE` and `VM_CLUSTER_NEW` - perhaps a new flag there would be another option).

**Comment by alexng-canuck** [comment]
The differences between `source` attributes are outlined here: https://docs.cloud.oracle.com/en-us/iaas/api/#/en/database/20160918/datatypes/CreateDbHomeBase

Whether you use NONE or VM_CLUSTER_NEW depends on whether you're passing in a db_system_id or a vm_cluster_id for creation.

**Comment by alexng-canuck** [comment]
@lucianf , another thing that is worth trying as workaround. You mentioned that the ExaCS vm cluster OCID is still a db_system OCID from a converted db system.

I suspect the DB Home creation from the service still treats converted db systems the same as before.

Can you try creating db home with following settings (`source` = `NONE`, use `db_system_id` instead of `vm_cluster_id`)?
```
resource oci_database_db_home x01_dbhome5 {
  depends_on    = [oci_database_db_home.x01_dbhome4]

  # Use db_system_id instead of vm_cluster_id
  db_system_id = oci_database_cloud_vm_cluster.xclu01.id 

  # This is optional, as default will be "NONE" even if no source is specified.
  source = "NONE"
 ......
}
```

**Comment by lucianf** [comment]
Thank you @alexng-canuck, that worked!
Happy to close this ticket from my side, unless you want to keep it open to monitor implementing another process, or simply for documenting this workaround in the provider.

**Comment by alexng-canuck** [comment]
@lucianf , there is a limitation to this workaround because as you've noticed, the service happily accepts `db_system_id` during create but it will then realize that it's actually a vm cluster and return the value back via the `vm_cluster_id` in any Get/List requests.

If creating the db_home through Terraform, this is not an issue as Terraform stores both attributes in state and is able to detect no diffs. 

But if doing import of an existing db home, this will lead to the issues you described. As the provider doesn't get a value from the service for `db_system_id` to match your configs. So the workaround for this, is to then update your configs to be consistent.

The current experience is not good for ExaCS, and you are correct that the ideal case is to use `vm_cluster_id` with `source=NONE`. We are investigating a better fix for this.

**Comment by alexng-canuck** [comment]
The way we are addressing this is to remove any polling logic that results in `GetVmCluster`/`GetCloudVmCluster`/`GetDbSystem` calls in the `oci_database_db_home` resource, because the client has no reliable way of knowing the underlying type of the source OCID (particularly in the case of imports).

You should be able to specify the ExaCS cluster using the `vm_cluster_id` and `source=VM_CLUSTER_NEW`. The fix is expected to go out this week in v4.3.0.

**Comment by alexng-canuck** [comment]
@lucianf , the fix for this should be part of v4.3.0, which was released today.

Can you see if this addresses the issue?

**Comment by alexng-canuck** [comment]
Here's the commit if you're interested: https://github.com/terraform-providers/terraform-provider-oci/commit/d0a9a8100f07da8e00f2263abce8dc6b4180f1ad

**Comment by lucianf** [comment]
Thanks, I was now able to provision dbhomes with `vm_cluster_id` and `source=VM_CLUSTER_NEW`.  Note however there's still a small inconsistency - any ExaCS dbhomes created outside the new process are still reported by the OCI API with `source=NONE`, hence if they are to be imported into Terraform their `source` must also be set to `NONE` (or left unset).
