### ISSUE TITLE
Can custom endpoints be set?

### ISSUE THREAD

**Issue by DonaghM1982** [terraform-providers/terraform-provider-oci#1224]
In the SDK and CLI we have the ability to overwrite the the endpoint

Python SDK: id_client = IdentityClient(config, service_endpoint=custom_endpoint) 

or in the cli we can do it in the command

CLI: oci iam user list --c $tenant --endpoint $custom_endpoint 

Can the endpoint be customised when executing via the terraform-provider-oci config?

**Comment by parrneet** [comment]
Hi @DonaghM1982 - We'd like to understand your use case for custom endpoints.

**Comment by DonaghM1982** [comment]
Just something I am playing around with as an Oracle employee. I got around the is issue by setting the domain_name_override env in my env.vars file. Thanks for getting back to me.
