### ISSUE TITLE
Can I retrieve encrypted value from Vault/KMS then decrypt (vs. providing encrypted value statically)?

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1226]
I would like to retrieve encrypted values and decrypt to use as inputs. For example, with OCI CLI I can do this…

```
oci secrets secret-bundle get --secret-id "OCID_SOMETHING"
```
…which returns ```data.secret-bundle-content.content``` that is base64-encoded decrypted value.

The closest I find with Terraform provider is this…

```hcl
data "oci_kms_decrypted_data" "the_data" {
  ciphertext      = var.ciphertext
  crypto_endpoint = var.crypto_endpoint
  key_id          = var.key.id
}

output "decrypted" {
  value = oci_kms_decrypted_data.the_data.plaintext
}
```

However, this requires I supply ```var.ciphertext``` as static value rather than the method I show above with OCI CLI whereby I retrieve the cipher text from a Secrets bundle.

Can this be done where I can retrieve ciphertext from a resource?

**Comment by parrneet** [comment]
Hi @jeliker 
[kma_encrypted_data resource](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/kms_encrypted_data) will return encrypted data in `ciphertext` field.

Feel free to reopen if this does not answer your question.

**Comment by jeliker** [comment]
Thank you for the information but I'm looking for how to decrypt not from plaintext that I supply but from a stored Secrets entry. Seems the oci_kms_encrypted_data resource takes only plaintext as input.

Maybe the simper question is: how can I retrieve the encrypted content of a stored Secret?

**Comment by wei-tehama-io** [comment]
I am looking for the same thing.  Is there a solution for it?
