### ISSUE TITLE
OKE cluster creation failure - Nodes get stuck with software installation

### ISSUE THREAD

**Issue by SriniThanneeru** [terraform-providers/terraform-provider-oci#1231]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by SriniThanneeru** [comment]
I see that on worker nodes, following timeout issue, ports are white listed on public subnet. Both OKE cluster subnet and worker node subnets are public

/usr/bin/systemctl status proxymux-certs -l
● proxymux-certs.service - Proxymux Certs Preparation
   Loaded: loaded (/etc/systemd/system/proxymux-certs.service; enabled; vendor preset: disabled)
   Active: activating (start) since Wed 2020-11-11 19:42:00 UTC; 2h 6min ago
 Main PID: 6248 (proxymux-client)
    Tasks: 11
   Memory: 11.8M
   CGroup: /system.slice/proxymux-certs.service
           └─6248 /usr/local/bin/proxymux-client certs --config=/etc/proxymux/config.yaml

Nov 11 21:26:10 oke-cztgntdhezd-n2gkn3egu4d-soqknfgnbaq-0 proxymux-client[6248]: time="2020-11-11T21:26:10Z" level=error msg="fail to request tls certs" TLSCertRequest="{}" error="Get https://147.154.119.137:12250/tkw/tlscerts: dial tcp 147.154.119.137:12250: connect: connection timed out

**Comment by srishtipmishra** [comment]
Thanks for reporting this issue. 
1. Can you confirm the oci provider version (command - **terraform init**) and Terraform version(command - **terraform version**) that you're using?
2. Can you share the terraform config you're using? 
3. If the failure is reproducible can you run Terraform apply with TF_LOG=DEBUG set?

**Comment by SriniThanneeru** [comment]
terraform version
Terraform v0.12.12
+ provider.local v2.0.0
+ provider.oci v4.2.0

**Comment by srishtipmishra** [comment]
As per Container Engine best practices - this is an expected behavior
We need to use either Natgateway or service gateway not internet gateway for oracle production tenancies.

Closing this ticket. Please reopen if needed.
