### ISSUE TITLE
Hello can someone have a look at this issue with teh waaf calls  and fix it ASAP as its a security threat

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1245]
Hello
i m getting theses errors from the waaf provider , please correct them asap as it exposes PUBLIC URL thought tf exception code.
And if this is not coming from the terraform provider then check the code of the waaf asap
you can ping me i m internal !
and BTW the tf calls are not scaling if i create 1 -> 5 waaf i dont see this issue when the tf tries to create more then tf crashes
 
```
Error: work request did not succeed, workId: ocid1.waasworkrequest.oc1..aaaaaaaagwol2asrfdf2y7oeby4hzt3zb663qtjdfwiu35jxc5qqmxm5utga, entity: waas, action: CREATED. Message: retrying operation due to error. (got a blocking error. stop here and retry: create Webapp failed: Post https://dojo.zenedge.com/api/v3/partner/companies_api/2d39d60f-575c-44fe-a3ef-32ddc1d3c9f5/webapps: net/http: request canceled (Client.Timeout exceeded while awaiting headers))
retrying operation due to error. (got a blocking error. stop here and retry: create Webapp failed: Post https://dojo.zenedge.com/api/v3/partner/companies_api/2d39d60f-575c-44fe-a3ef-32ddc1d3c9f5/webapps: net/http: request canceled (Client.Timeout exceeded while awaiting headers))
retrying operation due to error. (got a blocking error. stop here and retry: create Webapp failed: Post https://dojo.zenedge.com/api/v3/partner/companies_api/2d39d60f-575c-44fe-a3ef-32ddc1d3c9f5/webapps: net/http: request canceled (Client.Timeout exceeded while awaiting headers))

  on modules/waf/waf.tf line 32, in resource "oci_waas_waas_policy" "waf_policy":
  32: resource "oci_waas_waas_policy" "waf_policy" {

```

**Comment by varmax2511** [comment]
Hi @eugsim1 -- thanks for reaching out to us. The above error is returned by the upstream service when it was unable to complete the request. Terraform provider as a client is simply displaying the error message returned by the upstream service. The same is true for the scale from 1 --> 5, terraform provider as a client is making the request and expects the service to return a response. 
I can reach out to the upstream service and raise your concerns.

**Comment by varmax2511** [comment]
Hi @eugsim1 --  The service is working on addressing the error message and timeout issues. I have sent the internal ticket detail to you.

**Comment by varmax2511** [comment]
Hi @eugsim1 -- service team has pushed a fix regarding error message. Please let us know if this addresses your issue.
