### ISSUE TITLE
Invalid index

### ISSUE THREAD

**Issue by pguerin3** [terraform-providers/terraform-provider-oci#1248]
What is a valid input if I can't use ap-sydney-1?

```
Error: Invalid index

  on main.tf line 59, in data "oci_identity_availability_domain" "ad":
  59:   ad_number      = var.ad_region_mapping[var.region]
    |----------------
    | var.ad_region_mapping is map of string with 3 elements
    | var.region is "ap-sydney-1"

The given key does not identify an element in this collection value.
```

**Comment by varmax2511** [comment]
Hi @pguerin3 -- thanks for reaching out. It seems that in your config, the variable map `ad_region_mapping` doesn't have the key `ap-sydney-1`. An example of such a map with region as keys is https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/instance/instance.tf#L64

Please let us know if this helps.

**Comment by pguerin3** [comment]
So the key ```ap-sydney-1``` is going to map to what?

**Comment by RahulMetangale** [comment]
HI @pguerin3 Assuming you have variable defined as follows:
```
variable "ad_region_mapping" {
  default = {
   "ap-sydney-1"   = {
            "ad_number": 1,
            "compartment_id": "",
            "id": ""
          }
  }
}

```
and var.region is set to "ap-sydney-1" then you can set ad_number as follows
    ad_number  = var.ad_region_mapping[var.region].ad_number

Hope this helps.

Thanks,
Rahul

**Comment by varmax2511** [comment]
thanks @RahulMetangale . @pguerin3 does the above comment resolve your issue?

**Comment by varmax2511** [comment]
Closing issue, feel free to reopen if any help is required.

**Comment by pguerin3** [comment]
Actually the issue was that I need to use a value of SYD in the field, instead of AP-SYDNEY-1.
