### ISSUE TITLE
Docs list the load balancer shape 10Mbps-micro and it should be 10Mbps-Micro

### ISSUE THREAD

**Issue by Mmm-Biscuits** [terraform-providers/terraform-provider-oci#1252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.4.0

Your version of Terraform is out of date! The latest version
is 0.14.2. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

oci_load_balancer_load_balancer

### Terraform Configuration Files

resource "oci_load_balancer_load_balancer" "vanity_load_balancer" {

    compartment_id = oci_identity_compartment.tf-compartment.id
    display_name = "LB1"
    **shape = "10Mbps-Micro"**
    subnet_ids = [oci_core_subnet.vcn-public-subnet.id]
}

### Debug Output

Error: Service error:InvalidParameter. Invalid load balancer shape: 10Mbps-micro. http status code: 400. Opc request id: 6b0e16ef6ca106df1a883ea1837774a7/CBD2FA530F0F1271E4B56551D9261F02/CD3B44A156F1430FD76FCCEDFE8804D4

### Panic Output

none

### Expected Behavior

Load Balancer would create

### Actual Behavior

above error

### Steps to Reproduce

Create a Load Balancer with the shape 10Mbps-Micro and 10Mbps-micro. It will error on the 10Mbps-micro

### Important Factoids

This is just to change the reference on the doc page at

https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/load_balancer_load_balancer

to reflect 10Mbps-Micro and not 10Mbps-micro

### References

https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/load_balancer_load_balancer

**Comment by govindrao55** [comment]
Hi @Mmm-Biscuits - Thanks for pointing this out. I've fixed the load balancer docs and they will be updated in the next release.

**Comment by Mmm-Biscuits** [comment]
Thanks! Happy to help.
