### ISSUE TITLE
Error: "filter" contains an invalid JSON: invalid character 'v' looking for beginning of value

### ISSUE THREAD

**Issue by pguerin3** [terraform-providers/terraform-provider-oci#1261]
I'm running the terraform-provider-oci\examples\metering_computation script.
I get the error:
```
Error: "filter" contains an invalid JSON: invalid character 'v' looking for beginning of value
```
My version of Terraform is:
```
>terraform -v
Terraform v0.12.29
+ provider.oci v4.7.0
```
The output log is here:
[output.txt](https://github.com/terraform-providers/terraform-provider-oci/files/5753631/output.txt)

**Comment by varmax2511** [comment]
Hi @pguerin3 -- thanks for reporting this issue. Till the time we fix the example, please replace the value here https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/metering_computation/main.tf#L61 with 

```
"value": "${var.dimensions_value}"
```
to resolve the above error.

**Comment by pguerin3** [comment]
Ok - the fix has got me farther, but I still get an error.
The last few lines of the output is as follows:

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

oci_metering_computation_usage.test_usage: Creating...
oci_metering_computation_usage.test_usage: Still creating... [10s elapsed]

Error: Post https://usageapi.ap-sydney-1.oci.oraclecloud.com/20200107/usage: net/http: TLS handshake timeout

  on main.tf line 40, in resource "oci_metering_computation_usage" "test_usage":
  40: resource "oci_metering_computation_usage" "test_usage" {
```

**Comment by varmax2511** [comment]
This appears a configuration or proxy issue. Please refer to https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/troubleshooting#common-issues

**Comment by pguerin3** [comment]
Could of been a network issue.
The latest error is this:
```
Error: Service error:InvalidParameter. Passed date does not have the right precision. http status code: 400.
```
Which documentation tells me the valid date formats?

**Comment by varmax2511** [comment]
This should be the format for dates. 

```
"2021-01-01T00:00:00Z"
```
All documentation for this resource is under https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/metering_computation_usage. We can ask the upstream service to add the format details in the documentation.

**Comment by pguerin3** [comment]
OK - I got it to work with these dates:
time_usage_ended   = "2020-12-30T00:00:00Z"
time_usage_started = "2020-12-29T00:00:00Z"

So I got a successful execution as below:
```
oci_metering_computation_usage.test_usage: Creating...
oci_metering_computation_usage.test_usage: Still creating... [10s elapsed]
oci_metering_computation_usage.test_usage: Creation complete after 16s [id=2021-01-02-105749-101267300]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Where is the metering computation usage report?

**Comment by varmax2511** [comment]
please refer to https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/metering_computation_usage#attributes-reference

**Comment by varmax2511** [comment]
Examples are fixed now
