### ISSUE TITLE
attribute "idcs_access_token" marked as OPTIONAL in "oci_analytics_analytics_instance" documentation

### ISSUE THREAD

**Issue by absalonr1** [terraform-providers/terraform-provider-oci#1264]
"idcs_access_token" marked as OPTIONAL in "oci_analytics_analytics_instance" docs but required by provider

terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.7.0

Error log:

Error: Service error:InvalidParameter. OAC-DAL-001034: idcsAccessToken is a required parameter, but was not specified. http status code: 400. Opc request id: b322e5deac1d2e890723c8f39fc72d94/F4C4358FAB9577D9002FE12F94456C22/A797F4C929B77FA150018213A544561A

terraform resource

resource "oci_analytics_analytics_instance" "rdg_analytics_instance" {
    #Required
     capacity {
        capacity_type  = "OLPU_COUNT"
        capacity_value = 1
    }
    compartment_id = var.compartment_ocid
    feature_set = "ENTERPRISE_ANALYTICS"
    license_type = "LICENSE_INCLUDED"
    name = "test-rdg"

    #Optional
    defined_tags = {
        "tag"="value"
    }

    description = "test-rdg"
    email_notification = "a@test.com"
    #idcs_access_token = "var.idcs_access_token"
    network_endpoint_details {
        #Required
        network_endpoint_type = "PRIVATE"

        #Optional
        subnet_id = var.private_subnet_id
        vcn_id = var.vcn_id
    }
}

**Comment by srishtipmishra** [comment]
Hi @absalonr1 - This is a service requirement as the error mentions. Terraform provider has it as optional attribute to avoid Plan errors from customer usability point of view. Also, we do not check the validity of idcs token (only service does).

**Comment by srishtipmishra** [comment]
We're looking to better the user experience by adding this fields as a Required attribute too.

**Comment by absalonr1** [comment]
Thanks srishtipmishra. This attribute is not required when you create OAC instance in OC Console. it will be removed in the future?

**Comment by srishtipmishra** [comment]
@absalonr1 - The service team is better suited to answer this question. We have fixed this issue in our latest release - https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md

Closing this issue.

**Comment by kk-hiraskar** [comment]
> Thanks srishtipmishra. This attribute is not required when you create OAC instance in OC Console. it will be removed in the future?

can somebody answer this question?  
while creating OAC in OCI console, access token is not asked.  
and also please guide, how to generate this token from terraform.  

For REST calls, we can generate in one call, and use it in next,  
**but how for terraform?**
