### ISSUE TITLE
How to retrieve the encrypted contents of a stored secret?

### ISSUE THREAD

**Issue by oehrlis** [terraform-providers/terraform-provider-oci#1266]
Hi

How to retrieve the encrypted contents of a stored secret? This question has been discussed in #1226 but I do not think that the question is answered. In particular not for secrets values.

Using oci-cli it is possible to retrieve the value of a secret using

````
oci secrets secret-bundle get --secret-id <OCID> --stage CURRENT
````

The OCI terraform provider includes the data source _oci_vault_secret_. But this data source just provide generic information on the secret an not the content itself.

Is there a way to get the value of the secret and / or use it for other terraform resources e.g. where a resource requires a password, private key etc.

Regards
Stefan

**Comment by zexinwanoci** [comment]
Hello oehrlis, thank you for reporting. We are investigating this issue, we will let you know once we have an answer. Thank you.

**Comment by zexinwanoci** [comment]
Hello, for the secret content, do you mean the content value from 

  "data": {
    "metadata": null,
    "secret-bundle-content": {
      "content": "dGVzdA==",
      "content-type": "BASE64"
    }
?
If so we do not support this action from terraform end as content is not an exposed filed.

**Comment by oehrlis** [comment]
Hi

Yes the content value which I planned to use it in additional resource.

Regards
Stefan

**Comment by zexinwanoci** [comment]
Hi Stefan, I have check our code and currently we only support secretcontent as an input for create and update, and do not support get request for this field. So it is impossible to retrieve it from terraform right now. If you would like us to support it you can create a new ticket for requesting of this operation. I will close this ticket for now.
