### ISSUE TITLE
Sparse diskgroup option is not supported with DB system shape VM.Standard2.1 error in the API

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1272]
Hello
I m getting this exception over and over 

Error: Service error:InvalidParameter. LaunchDbSystem Sparse diskgroup option is not supported with DB system shape VM.Standard2.1. http status code: 400. Opc request id: e497b2f907c8c896e2587ef83735e847/ED1C35E799B92A1DB78AAF05B2E4D0EB/0FB21B1473D5C63392961FFF057AE6BC

  on modules/db_systems/main.tf line 18, in resource "oci_database_db_system" "dbcs_system":
  18: resource "oci_database_db_system" "dbcs_system" {

BUT in the terraform i have put explicit flag to false the API doenst care about this flag , when i remove the line the tf script works this is a bug the doc describes (Optional) If true, Sparse Diskgroup is configured for Exadata dbsystem. If False, Sparse diskgroup is not configured, with false terraform blows out:

 ```
   database_source                           = "NONE" # (Optional) The source of the database: Use NONE for creating a new database. Use DB_BACKUP for creating a new database by restoring from a backup. Use DATABASE for creating a new database from an existing database, including archive redo log data. The default is NONE.
    database_source_db_system_id              = ""     # (Required when source=DB_SYSTEM) The OCID of the DB system.
    database_sparse_diskgroup                 = "false"    # (Optional) If true, Sparse Diskgroup is configured for Exadata dbsystem. If False, Sparse diskgroup is not configured.
    database_time_zone                        = "Europe/Helsinki"     # (Optional) The time zone to use for the DB system. For details, see DB System Time Zones.
  }
```

**Comment by zexinwanoci** [comment]
Hello, eugsim1, sorry for bad documentation that sparse_diskgroup does not apply to the type of VM.Standard2.1.

**Comment by zexinwanoci** [comment]
Updated the document and now we noted that Sparse diskgroup option is only for exadata type.
