### ISSUE TITLE
Support attach and detach of IPv6 on oci_core_instance

### ISSUE THREAD

**Issue by fcecagno** [terraform-providers/terraform-provider-oci#1278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At this moment the provider doesn't allow creation and deletion of IPv6 on instances - it's possible to assign an IPv6 block on `oci_core_subnet`, but it's not possible to assign an IP from that block to the instance (as the user can perform on the web console).
In order to overcome this limitation we use the `local-exec` provisioner along with `oci-cli`. On creation, we do:

```
VNIC_ID=$(oci compute instance list-vnics --instance-id $INSTANCE_ID | jq -j '.data[0].id')
oci network ipv6 create --vnic-id $VNIC_ID --is-internet-access-allowed true | jq -j '.data."public-ip-address"'
```

On deletion, we do:
```
VNIC_ID=$(oci compute instance list-vnics --instance-id $INSTANCE_ID | jq -j '.data[0].id')
IPV6_ID=$(oci network ipv6 list --vnic-id $VNIC_ID | jq -j '.data[0].id')
oci network ipv6 delete --force --ipv6-id $IPV6_ID
```

As `oci_core_vcn` supports `is_ipv6enabled`, I'd suggest to add properties to `create_vnic_details` on `oci_core_instance` in order to configure:
1. if the instance will have an IPv6 assigned
2. if the IPv6 is going to be publicly accessible
3. the IPv6 itself, if the user wants to manually assign an IPv6 from the VCN block.

Additionally, it would be important to be able to get the IPv6 from the resource.

### New or Affected Resource(s)

oci_core_instance

**Comment by varmax2511** [comment]
Thanks for reporting this enhancement. We will look into adding this feature.

**Comment by varmax2511** [comment]
Hi @fcecagno -- with provider version 4.22.0 we have introduced a new resource for launching IPV6 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_ipv6_resource.go

https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v4.22.0
Can you please check and let us know if this issue can be closed?

**Comment by fcecagno** [comment]
Awesome! I'll test it shortly.
I couldn't find any parameter on `oci_core_ipv6` for the paramenter `--is-internet-access-allowed` used on `oci-cli`. Is it `true` by default?

**Comment by varmax2511** [comment]
@fcecagno -- I don't see this parameter in OCI CLI as well https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.23.0/oci_cli_docs/cmdref/network/ipv6/create.html#optional-parameters

**Comment by fcecagno** [comment]
I confirm it's working as expected, thanks.
