### ISSUE TITLE
Error: Service error:Conflict. instance ocid1.instance.oc1....oly4gq is currently being modified, try again later. http status code: 409.

### ISSUE THREAD

**Issue by chandrashekhar-linux** [terraform-providers/terraform-provider-oci#1282]
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.11.0

2021-01-28T19:36:26.403+0530 [DEBUG] plugin.terraform-provider-oci_v4.11.0_x4: DEBUG 2021/01/28 19:36:26.402876 http.go:916: Unmarshaling from header to field: OpcRequestId
data.oci_core_vnic.sbc_vnic_wancom1[1]: Read complete after 0s [id=ocid1.vnic.oc1.phx.abyhqljsnc3ppikhocdhckfuhnabsldjkxksixj4jt5kxv4go24ok44opu3a]

Error: Service error:Conflict. instance ocid1.instance.oc1.phx.anyhqljsq5fbg5acveq7ipi72h3dv6ahmrkzhncbzpq5w3qer5dimaoly4gq is currently being modified, try again later. http status code: 409. Opc request id: c7e43f2b77b78b30452bd966ffd73f40/E810503B34F263977D6D9E8791BC80A3/1EBAA23F72DEF17E030EB9D7C1488E8F

  on instance.tf line 186, in resource "oci_core_vnic_attachment" "sbc_wancom2":
 186: resource "oci_core_vnic_attachment" "sbc_wancom2" {

2021-01-28T19:36:26.607+0530 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-28T19:36:26.610+0530 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-28T19:36:26.613+0530 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64/terraform-provider-null_v3.0.0_x5 pid=4780
2021-01-28T19:36:26.613+0530 [DEBUG] plugin: plugin exited

[apply.log](https://github.com/terraform-providers/terraform-provider-oci/files/5887889/apply.log)

**Comment by chandrashekhar-linux** [comment]
Hi @varmax2511 thanks for reply, I haven't disabled the retries (by default it is enabled I guess)
but the above url suggests that, retry_duration_seconds is meant for HTTP errors 429 and 500 and not for 409
Not sure if this solves my problem.

`Note that the retry_duration_seconds field only affects retry duration in response to HTTP 429 and 500 errors; as these errors are more likely to result in success after a long retry duration. Other HTTP errors (such as 400, 401, 403, 404, and 409) are unlikely to succeed on retry. The retry_duration_seconds field does not affect the retry behavior for such errors.`

**Comment by varmax2511** [comment]
Hi @chandrashekhar-linux -- thanks for confirming. Terraform provider retries for 2 minutes for 409 errors. Now this looks more of a dependency issue. 
Per the apply log the instance is in state ATTACHING and simultaneously a VNIC attachment call is being made. I see that you are trying to attach multiple vnics to the same instance. All these calls seem to be happening simultaneously when they should be sequential. One call succeeded causing the instance to move to Attaching state and other failed due to conflict. 

You need to define a dependency between the two vnic attachment resources so they don't execute in parallel. Please refer to https://learn.hashicorp.com/tutorials/terraform/dependencies


Below is a sample config, I used to repro your issue and then fix (fix is commented). If the issue still persists, please share a small sample config to repro the issue.
```
variable "tenancy_ocid" {
}

variable "user_ocid" {
}

variable "fingerprint" {
}

variable "private_key_path" {
}

variable "compartment_ocid" {
}

variable "region" {
}

provider "oci" {
  region           = var.region
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
}

variable "instance_image_ocid" {
  type = map(string)

  default = {
    us-phoenix-1   = "ocid1.image.oc1.phx.aaaaaaaaoqj42sokaoh42l76wsyhn3k2beuntrh5maj3gmgmzeyr55zzrwwa"
    us-ashburn-1   = "ocid1.image.oc1.iad.aaaaaaaageeenzyuxgia726xur4ztaoxbxyjlxogdhreu3ngfj2gji3bayda"
    eu-frankfurt-1 = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaaitzn6tdyjer7jl34h2ujz74jwy5nkbukbh55ekp6oyzwrtfa4zma"
    uk-london-1    = "ocid1.image.oc1.uk-london-1.aaaaaaaa32voyikkkzfxyo4xbdmadc2dmvorfxxgdhpnk6dw64fa3l4jh7wa"
  }
}

resource "oci_core_instance" "test_instance" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  compartment_id      = var.compartment_ocid
  display_name        = "TestInstance"
  shape               = "VM.Standard2.8"

  create_vnic_details {
    subnet_id        = oci_core_subnet.test_subnet.id
    display_name     = "Primaryvnic"
    assign_public_ip = true
    hostname_label   = "tfexampleinstance"
  }

  source_details {
    source_type = "image"
    source_id   = var.instance_image_ocid[var.region]
    # Apply this to set the size of the boot volume that's created for this instance.
    # Otherwise, the default boot volume size of the image is used.
    # This should only be specified when source_type is set to "image".
    #boot_volume_size_in_gbs = "60"
  }

  # Apply the following flag only if you wish to preserve the attached boot volume upon destroying this instance
  # Setting this and destroying the instance will result in a boot volume that should be managed outside of this config.
  # When changing this value, make sure to run 'terraform apply' so that it takes effect before the resource is destroyed.
  #preserve_boot_volume = true

  timeouts {
    create = "60m"
  }
}

resource "oci_core_vnic_attachment" "secondary_vnic_attachment" {
  instance_id  = oci_core_instance.test_instance.id
  display_name = "secondaryVnicAttachment"

  create_vnic_details {
    assign_public_ip       = false
    display_name           = "TFSecondaryVnic"
    skip_source_dest_check = true
    subnet_id              = oci_core_subnet.test_subnet.id
  }
}

resource "oci_core_vnic_attachment" "secondary_vnic_attachment2" {
  # fix is to create dependency between the two vnic attachments
  #depends_on = [oci_core_vnic_attachment.secondary_vnic_attachment]
  instance_id  = oci_core_instance.test_instance.id
  display_name = "secondaryVnicAttachment2"

  create_vnic_details {
    assign_public_ip       = false
    display_name           = "TFSecondaryVnic2"
    skip_source_dest_check = true
    subnet_id              = oci_core_subnet.test_subnet.id
  }
}



resource "oci_core_vcn" "test_vcn" {
  cidr_block     = "10.1.0.0/16"
  compartment_id = var.compartment_ocid
  display_name   = "TestVcn"
  dns_label      = "testvcn"
}

resource "oci_core_internet_gateway" "test_internet_gateway" {
  compartment_id = var.compartment_ocid
  display_name   = "TestInternetGateway"
  vcn_id         = oci_core_vcn.test_vcn.id
}

resource "oci_core_default_route_table" "default_route_table" {
  manage_default_resource_id = oci_core_vcn.test_vcn.default_route_table_id
  display_name               = "DefaultRouteTable"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.test_internet_gateway.id
  }
}

resource "oci_core_subnet" "test_subnet" {
  availability_domain = data.oci_identity_availability_domain.ad.name
  cidr_block          = "10.1.20.0/24"
  display_name        = "TestSubnet"
  dns_label           = "testsubnet"
  security_list_ids   = [oci_core_vcn.test_vcn.default_security_list_id]
  compartment_id      = var.compartment_ocid
  vcn_id              = oci_core_vcn.test_vcn.id
  route_table_id      = oci_core_vcn.test_vcn.default_route_table_id
  dhcp_options_id     = oci_core_vcn.test_vcn.default_dhcp_options_id
}

data "oci_identity_availability_domain" "ad" {
compartment_id = var.tenancy_ocid
ad_number      = 1
}
```

**Comment by varmax2511** [comment]
Hi @chandrashekhar-linux -- please let us know if the issue still persists?

**Comment by chandrashekhar-linux** [comment]
Thank you @varmax2511, I learn that Terraform provider retries for 2 minutes for 409 errors, which is not mentioned any where.
After adding dependencies to vnic attachments, I haven't seen the issue. 

Closing the defect.
