### ISSUE TITLE
ExaCS: cannot create db_home using the Terraform for exadata cloud infrastructure.

### ISSUE THREAD

**Issue by srikanthpandarangi** [terraform-providers/terraform-provider-oci#1284]
I am trying to create Exadata cloud Infrastructure Instance, Exadata VM clusters and Database Home using the Below Terraform code. 

**"Exadata cloud Infrastructure Instance" and "Exadata VM clusters"  created successfully using Terraform resource, but  the "Database Home" creation is failing.**

Provider:    registry.terraform.io/providers/hashicorp/oci/4.9.0
Terraform v0.12.28

**Affected Resource(s)**
oci_database_db_home

**Terraform Configuration Files**

     resource "oci_database_cloud_exadata_infrastructure" "exadata-x8m" {

     compartment_id      = data.oci_identity_compartments.compartment.compartments[0].id
     display_name        =   "test-x8m"
     shape               =  "Exadata.X8M"

      compute_count =  "2"
      maintenance_window {
      #Required
       preference = "NO_PREFERENCE"
         }
      storage_count = "3"
      }

      resource "oci_database_cloud_vm_cluster" "exadata-x8m-vm" {
         compartment_id                  = data.oci_identity_compartments.compartment.compartments[0].id
         cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.exadata-x8m.id

         display_name = "exavm1"
         cluster_name = "exavmclu"

          cpu_core_count              =  "4"
          data_storage_percentage     =  "80"
          is_local_backup_enabled     =  "false"
          is_sparse_diskgroup_enabled = "false"
          time_zone                   = "America/New_York"
          gi_version                  = "19.0.0.0"
          license_model               = "BRING_YOUR_OWN_LICENSE"

          hostname         = "exa-vm-clus"
          subnet_id        = data.oci_core_subnets.subnet.subnets[0].id
          backup_subnet_id = data.oci_core_subnets.backup_subnet.subnets[0].id
          ssh_public_keys  = var.ssh_public_keys
     }
     
     resource "oci_database_db_home" "x8m-rac-db" {
     #Required
     database {
     #Required
     admin_password = chomp(file(var. admin_pass["password_file"]))

      #Optional
      db_backup_config {

      #Optional
      auto_backup_enabled = "false"
       }
       db_name     = "exa-testdb"
       db_workload = "OLTP"
      }

      display_name  =  "oradbhome1"
      source        =  "NONE"
      vm_cluster_id = "oci_database_cloud_vm_cluster.exadata-x8m-vm.id"

      timeouts {
       create = "24h"
      }
      }

**Expected Behavior**
Creating a new db_home with a new database should work as expected.

**Actual Behavior**
Terraform fails after exactly 2 minutes with the following error:

    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Creating...
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [10s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [20s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [30s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [40s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [50s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m0s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m10s elapsed] 
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m20s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m30s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m40s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m50s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [2m0s elapsed]

    Error: Service error:InternalError. Internal error occurred. http status code: 500. Opc request id: dbb132db1dcc716ea4771b5f0a88bb57/1F02CD7E69567993A0A2223BDAB36F5E/B4138A0F7417A6F3D6DCEF29AF78F02A, 
    The service for this resource encountered an error. Please contact support for help with that service

 
    tried updating the source to "VM_CLUSTER_NEW",  terraform failed again with the following error:

    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Creating...
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [10s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [20s elapsed]. 
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [30s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [40s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [50s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m0s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m10s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m20s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m30s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m40s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [1m50s elapsed]
    module.exa-x8m-01.oci_database_db_home.x8m-rac-db: Still creating... [2m0s elapsed]

     Error: Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 
    404. Opc request id: 332e832a9ac5a3e8ff76972e874204a4/0B3CA5FA3C57B0A7374FAFB1F9EB754D/04C5960CC5723D9B1DAC73F32351CCCF

 **DB Home creation is working fine from OCI console with the same user.**

**Comment by srikanthpandarangi** [comment]
Can someone please check this issue?

**Comment by srishtipmishra** [comment]
Work being tracked in database service queue. Closing this ticket.
