### ISSUE TITLE
 terraform-provider-oci/examples/load_balancer/lb_full/lb_full.tf certificate is expired

### ISSUE THREAD

**Issue by mgueury** [terraform-providers/terraform-provider-oci#1287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Last version

### Affected Resource(s)

oci_load_balancer

### Terraform Configuration Files

Just run the sample terraform-provider-oci/examples/load_balancer/lb_full/lb_full.tf
It will fails because the certificate that are hardcoded are expired.

Error: Service error:InvalidParameter. Invalid SSL configuration:
Expired CA Certificate
certificate expired on 20210116225805GMT+00:00. http status code: 400. Opc request id: daaaa94f7c714f49d2a2388aa9f18bb4/C61EE69AD9C82E096B0A3CBE96AAFD48/9E9BAAD7BB32B5543D693E7DB96FE303

**Comment by govindrao55** [comment]
Hi @mgueury , thanks for pointing this out, the example will be fixed in the next release.

**Comment by srishtipmishra** [comment]
The fix is release in provider 4.13. Closing.
