### ISSUE TITLE
In the example LOAD_BALANCER/lb_full.tf. There are 2 LB called lb1.

### ISSUE THREAD

**Issue by mgueury** [terraform-providers/terraform-provider-oci#1288]
LB2 display name is called LB1

resource "oci_load_balancer" "lb2" {
  shape          = "100Mbps"
  compartment_id = var.compartment_ocid

  subnet_ids = [
    oci_core_subnet.subnet1.id,
    oci_core_subnet.subnet2.id,
  ]

  display_name = "lb1"
}

**Comment by govindrao55** [comment]
Hi @mgueury , thanks for pointing this out, example will be fixed in the next release.

**Comment by srishtipmishra** [comment]
The fix is release in provider v4.13.
