### ISSUE TITLE
Some resources do not show up in the documentation

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#1292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

oci_core_default_*

These do not appear in the provider documentation. However, they appear in the examples. 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by govindrao55** [comment]
Hi @hyder , you can find the documentation for `oci_core_default_*` resources [here](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/managing_default_resources). Thanks.

**Comment by hyder** [comment]
Thanks @govindrao55. It's a bit odd not to find them with the other resources.
