### ISSUE TITLE
would be possible to porvide NONE values for configuration where the API is not targeted for ( db, autonomous ...etc etc)

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1293]
Hello terraform team 

I m trying to write a generic module for db utilisation BUT in my terraform code i hitting this issue :
 
```
Error: Service error:InvalidParameter. Configure access control for Autonomous Database is not supported.. http status code: 400. Opc request id: a4f0d415b54caddf6237f424eae70f67/56DC2E8422C3F061561572118725B36C/C81B111C32414A76072284A8C2EE5873

  on modules/autonomous/main.tf line 3, in resource "oci_database_autonomous_database" "autonomous_data_warehouse":
   3: resource "oci_database_autonomous_database" "autonomous_data_warehouse" {


[oracle@localhost datasafe-all-in-one]$ ./4-terraform-apply.sh

Error: Incorrect attribute value type

  on modules/autonomous/main.tf line 22, in resource "oci_database_autonomous_database" "autonomous_data_warehouse":
  22:   is_access_control_enabled                      = var.autonomous.autonomous_database_is_access_control_enabled
    |----------------
    | var.autonomous.autonomous_database_is_access_control_enabled is ""

```
So far i have to comment the code in the module but it would be more flexible in case of a multi targeted API to provide a "NONE" value so we can avoid these errors :
```
Error: Service error:InvalidParameter. Configure access control for Autonomous Database is not supported.. http status code: 400. Opc request id: a4f0d415b54caddf6237f424eae70f67/56DC2E8422C3F061561572118725B36C/C81B111C32414A76072284A8C2EE5873

  on modules/autonomous/main.tf line 3, in resource "oci_database_autonomous_database" "autonomous_data_warehouse":
   3: resource "oci_database_autonomous_database" "autonomous_data_warehouse" {


[oracle@localhost datasafe-all-in-one]$ ./4-terraform-apply.sh
```

 
Error: Incorrect attribute value type

  on modules/autonomous/main.tf line 22, in resource "oci_database_autonomous_database" "autonomous_data_warehouse":
  22:   is_access_control_enabled                      = var.autonomous.autonomous_database_is_access_control_enabled
    |----------------
    | var.autonomous.autonomous_database_is_access_control_enabled is ""

**Comment by eugsim1** [comment]
Hello 
as a "dirty workarounfd " i m setting these variables to null it works  i dont know if this is an acceptable solution ?

**Comment by govindrao55** [comment]
Hi @eugsim1 , As per `is_access_control_enabled` [documentation](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/database_autonomous_database#is_access_control_enabled): `This property is applicable only to Autonomous Databases on the Exadata Cloud@Customer platform.`.  Type `null` signifies omission (check: [this](https://www.terraform.io/docs/language/expressions/types.html#null)). Hence, It is correct / acceptable solution.

**Comment by eugsim1** [comment]
ok
