### ISSUE TITLE
Error: Resource reached unexpected lifecycle state DETACHING during creation, whereas expected lifecycle state is ATTACHED.

### ISSUE THREAD

**Issue by chandrashekhar-linux** [terraform-providers/terraform-provider-oci#1295]
I am trying to add a vnic to a new OCI instance and randomly getting this error.  I am using following terraform and oci provider versions

$ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.12.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

oci_core_vnic_attachment.sbc_s0p0[0]: Still creating... [20s elapsed]

**Error: Resource reached unexpected lifecycle state DETACHING during creation, whereas expected lifecycle state is ATTACHED.
 Affected resource OCID: ocid1.vnicattachment.oc1.phx.anyhqljsq5fbg5acxz223hvjwuihgwvxuwlo4ggnagbqv2ls473qccl6iovq**

  on sbc.tf line 219, in resource "oci_core_vnic_attachment" "sbc_s0p0":
 219: resource "oci_core_vnic_attachment" "sbc_s0p0" {

**Comment by srishtipmishra** [comment]
Thanks for reporting this. Can you share your config file with entries redacted? We'll try to reproduce this on our side too.

**Comment by srishtipmishra** [comment]
I tried creating an instance with vnic attachment using tf 14.5 and successfully provsioned. This might be a edge scenario. Can you share the error logs here? Please redact info.

**Comment by srishtipmishra** [comment]
@chandrashekhar-linux - Any luck getting logs? Thanks.

**Comment by srishtipmishra** [comment]
@chandrashekhar-linux - Can you confirm if you're still blocked? Thanks.

**Comment by srishtipmishra** [comment]
Closing this as no response from the customer. Please reopen if needed. Thanks!

**Comment by chandrashekhar-linux** [comment]
@srishtipmishra , sorry for late reply, I wasn't able to reproduce this recent times, as soon as I reproduce it will share you all the details.  This is happening especially when we try to add multiple vNICs to a VM, say 5 or more. 
Thanks,
