### ISSUE TITLE
oci resource discovery is not listing boot-volume resources

### ISSUE THREAD

**Issue by narentnj** [terraform-providers/terraform-provider-oci#1301]
As per https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/resource_discovery#supported-resources

oci_core_boot_volume is discoverable in "terraform-provider-oci -command=export"

![image](https://user-images.githubusercontent.com/15064078/108308571-f823ca80-71d5-11eb-992d-3140776110ae.png)

But it is not getting discovered. Even the support resources listing command "terraform-provider-oci -command=list_export_resources" not lists the oci_core_boot_volume

**Comment by jotruon** [comment]
Hi @narentnj, 
Can you share the full debug log from the discovery command?

**Comment by narentnj** [comment]
> Hi @narentnj,
> Can you share the full debug log from the discovery command?

command: `terraform-provider-oci -command=export  -services=core,availability_domain -compartment_id=ocid1.compartment.oc1..aaaaaaaaydx2orubbxzsvwu7bicktmir5g6tr7i4vv2iahvxc7mtzdxpa2fa -generate_state -output_path=.`

log: [tf.log](https://github.com/terraform-providers/terraform-provider-oci/files/6019722/tf.log)

**Comment by zexinwanoci** [comment]
Hello @narentnj ,can you check if it is in availability_domain.tf?
