### ISSUE TITLE
Destroy for oci_identity_compartment runs asynchronously to "work request"

### ISSUE THREAD

**Issue by ITD27M01** [terraform-providers/terraform-provider-oci#1305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/oci v4.13.0
```
### Affected Resource(s)

oci_identity_compartment
### Terraform Configuration Files

```hcl
resource "oci_identity_compartment" "compartment" {
  compartment_id = var.parent_compartment_id
  name           = var.compartment_name
  description    = local.compartment_description

  freeform_tags = merge(local.default_tags, var.tags)
}
```

### Debug Output

```
oci_identity_compartment.compartment: Destroying... [id=ocid1.compartment.oc1..aaaaaaaa5y3v2tkqbdwngxyscx7bgnkudbnrt5rqqmcwyjxyorqgctxojiaa]
oci_identity_compartment.compartment: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.
```
### Expected Behavior

As described in the [doc](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/workrequestoverview.htm) oci provider should wait for the success of the work request and fail otherwise.
### Actual Behavior

Currently the state of the infrastructure doesn't correspond to the state of the terraform. It is because terraform reports about compartment deletion, but actually compartment is present in the tenancy. 

For some reason the work request can be failed, so there should be an active loop to check the actual work request for compartment deletion.
### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. See that compartment is present on cloud.oracle.com

**Comment by jotruon** [comment]
Hi @ITD27M01, 
Please follow this docs and use `enable_delete` explicitly to destroy a compartment:
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment

**Comment by ITD27M01** [comment]
Hi @jotruon This is it, thank you!

I'll try not to think about why it's here.
