### ISSUE TITLE
Archival log is enabled by default while creating oci_logging_log resource through terraform where as in UI we have the option to choose

### ISSUE THREAD

**Issue by karthicgit** [terraform-providers/terraform-provider-oci#1306]
### Affected Resource(s)

oci_logging_log

### Expected Behavior

Attribute to enable or disable archival of log

### Actual Behavior

There is no option and archival is enabled by default

In OCI Console you will see
Legacy Archival Logs: Enabled

**Comment by srishtipmishra** [comment]
Hi @karthicgit - This field is deprecated as per our spec and service team expects Terraform or any other surface to not expose this. As per my understand console should allow user to control it either. I am unable to see it in my tenancy. Can you share -
1.  A screenshot of your console? 
2. Region that this log resource belongs to?
Thanks

**Comment by karthicgit** [comment]
Closing  this as the issue is with the console and whitelisted tenancies.
