### ISSUE TITLE
oci_mysql_mysql_db_system.configuration_id documented as optional, but cannot be left empty

### ISSUE THREAD

**Issue by mthmulders** [terraform-providers/terraform-provider-oci#1310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
terraform -version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/oci v3.97.0
```

### Affected Resource(s)

"oci_mysql_mysql_db_system"

### Terraform Configuration Files

```hcl
resource "oci_mysql_mysql_db_system" "my-database" {
  admin_password           = "just-4n-3x4mple"
  admin_username           = "admin"
  compartment_id           = var.compartment_ocid
  shape_name               = "MySQL.VM.Standard.E3.1.8GB"
  subnet_id                = oci_core_subnet.my-subnet.id
  data_storage_size_in_gb  = "50"
  display_name             = "My Database"
  availability_domain      = "MoMM:EU-FRANKFURT-1-AD-1"
}
```

### Expected Behavior

According to [the documentation](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/mysql_mysql_db_system), `configuration_id` is an optional parameter. When I configure a MySQL database manually through the Oracle Cloud web interface, it is not required to pass one indeed.

### Actual Behavior

```
Error: Missing required argument

  on database.tf line 6, in resource "oci_mysql_mysql_db_system" "my-database":
   6: resource "oci_mysql_mysql_db_system" "my-database" {

The argument "configuration_id" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by zexinwanoci** [comment]
Hello, the provider you used is 3.97.0, which by the time the filed was still required. Can you used the latest provider, which will have the update logic? Thank you.

**Comment by mthmulders** [comment]
Can confirm that it works according to the documentation with provider 4.14. Thanks for pointing that out!
