### ISSUE TITLE
Instance Pool with dynamic load_balancers block is recreated on every terraform apply

### ISSUE THREAD

**Issue by kostasns** [terraform-providers/terraform-provider-oci#1311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/cloudflare/cloudflare v2.14.0
+ provider registry.terraform.io/hashicorp/oci v4.14.0
```

### Affected Resource(s)

oci_core_instance_pool

### Terraform Configuration Files

```hcl
resource "oci_core_instance_pool" "docker_instance_pool" {
  display_name              = var.name
  compartment_id            = data.oci_core_vcn.vcn.compartment_id
  instance_configuration_id = oci_core_instance_configuration.instance_configuration.id
  freeform_tags             = var.freeform_tags
  defined_tags              = var.defined_tags
  size                      = 1
  placement_configurations {
    availability_domain = "qzwq:EU-FRANKFURT-1-AD-1"
    primary_subnet_id   = module.subnet.id
    fault_domains       = var.fault_domains
  }

  # https://www.terraform.io/docs/language/expressions/dynamic-blocks.html
  dynamic "load_balancers" {
    for_each = toset(["set-1","set-2","set-3"])
    content {
      backend_set_name = load_balancers.value
      load_balancer_id = var.load_balancer_id
      port             = 443
      vnic_selection   = "PrimaryVnic"
    }
  }
}
```

### Expected Behavior

On multiple runs the Instance Pool should not change as long as there are no changes.

### Actual Behavior

On the first run Instance Pool is created and 3 LB Attachements are created successfully.
without making any changes to the TF code I run `terraform apply` again and get random replacement

```
~ load_balancers {
          ~ backend_set_name = "set-1" -> "set-2" # forces replacement
```

or 

```
~ load_balancers {
          ~ backend_set_name = "set-2" -> "set-3" # forces replacement
```

I haven't noticed any patterns in which set is changed to which and why.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by zexinwanoci** [comment]
https://www.terraform.io/docs/language/functions/toset.html


Set collections are unordered and cannot contain duplicate values, so the ordering of the argument elements is lost and any duplicate values are coalesced:

I think this is why

**Comment by kostasns** [comment]
Yes, somehow slipped my mind sets are unordered. Let me try with map.
