### ISSUE TITLE
getPrimaryVnic shouldn't retry GetVnic call on 404

### ISSUE THREAD

**Issue by garthy** [terraform-providers/terraform-provider-oci#1314]
Due to a change in ho retries were performed from 3.91.0 to 3.94.0 an instance with multiple vnics attached that are not accessible to the caller due to security causes the provider to retry. 

https://github.com/terraform-providers/terraform-provider-oci/commit/e2471b719a20154408c03029e9d5ea4a119c34cf

This can cause reading an instance resource multiple vnics attached that are not accessible to the caller  to take a very long time  and in the worst case time out. 

The GetVnic call should probably never be retried mirroring the code comment below that ignores errors on GetVnic calls for the same reason.

**Comment by srishtipmishra** [comment]
The fix for this went out in 4.18 - To resolve this we have temporarily set disableNotFoundRetries to true for GetVnic requests. So, not found secondary Vnics will not add delays. Closing this issue. @garthy - please reopen if you need any further support.
