### ISSUE TITLE
Update `Question.md` issue template links

### ISSUE THREAD

**Issue by kral2** [terraform-providers/terraform-provider-oci#1320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Questions.md issue template](https://github.com/terraform-providers/terraform-provider-oci/blob/master/.github/ISSUE_TEMPLATE/Question.md) have obsolete links

`Frequently Asked Questions` and `Troubleshooting` are linked to the Hashicorp documentation under the Guides section.

The Guides section for OCI Terraform provider has moved to [OCI Documentation site](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraform.htm).

`Frequently Asked Questions` should use this link: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraform.htm
`Troubleshooting` should use this link: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformtroubleshooting.htm

**Comment by varmax2511** [comment]
hi @kral2 -- thanks for suggesting this change.

**Comment by govindrao55** [comment]
Hi @kral2 , the links are fixed now and released as a part of provider version v4.18.0. Thanks.
