### ISSUE TITLE
display_name does not work for Data Source: oci_core_service_gateways

### ISSUE THREAD

**Issue by vickyvikas7988** [terraform-providers/terraform-provider-oci#1328]
Hi team, 

I am trying to get local peering gateway id for single resource by using display_name = "lpg-corpdev2-hub" when I am trying it . It throws below error.

Data Source: oci_core_service_gateways

I am not able to use display_name in Data Source: oci_core_service_gateways. 

Error: Unsupported argument   
   
  on data.tf line 23, in data "oci_core_local_peering_gateways" "corp_lpg_name":   
  23:   display_name = "lpg-corpdev2-hub"   
   
An argument named "display_name" is not expected here.  

Is this expected?

**Comment by koenigdavidmj** [comment]
That is correct. You cannot search for an LPG (or a service gateway) by display name. The only supported parameters are compartment ID (required), VCN, and state (both optional).

You *can* use a filter to narrow down the results you get. See [here](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformconfig.htm#data_sources) for details.
