### ISSUE TITLE
oci_core_public_ip detects change defined_tags on every apply

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#1334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.18.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* oci_core_public_ip

### Terraform Configuration Files
Below works as expected applying the compartment default tags.
```hcl
resource "oci_core_public_ip" "the_ip" {
  #Required
  compartment_id = var.compartment_id
  lifetime       = "RESERVED"

  #Optional
  defined_tags   = null
}
```

```hcl
terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

However, if I change as noted with Load Balancer reserved IP addresses to this pattern I am prompted to change on every apply.

```hcl
resource "oci_core_public_ip" "the_ip" {
  #Required
  compartment_id = var.compartment_id
  lifetime       = "RESERVED"

  #Optional
  defined_tags   = null

  lifecycle {
    ignore_changes = [
      private_ip_id
    ]
  }
}
```

```hcl
terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # oci_core_public_ip.the_ip will be updated in-place
  ~ resource "oci_core_public_ip" "the_ip" {
      ~ defined_tags         = {
          - "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/superadmin@example.com" -> null
          - "Oracle-Tags.CreatedOn" = "2021-03-24T20:07:19.414Z" -> null
        }
        id                   = "ocid1.publicip.oc1.phx.amaaaagluw6fiicvcdhsuncdewap67aadaxktxglqqaqruhkd5krvjhipmnq"
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior
I expect `oci_core_public_ip` to not detect change in `defined_tags` when I set attribute null consistently whether or not I've set `private_ip_ip` to be ignored via lifecycle.

### Actual Behavior
If `private_ip_id` is set to be ignored via `lifecycle` block on the resource, `oci_core_public_ip` will detect attribute `defined_tags` is changed even when attribute value is set to null for the resource (letting `defined_tags` be governed entirely by Compartment default tags).

### Steps to Reproduce

1. Create script for `oci_core_public_ip` setting `defined_tags = null`
2. `terraform apply`
3. `terraform plan` again immediately and note no changes detected
4. Add `lifecycle` block to `ignore_changes` for `private_ip_id`
5. `terraform plan` and note that `defined_tags` are detected as changes

### Important Factoids
* The `oci_core_public_ip` resource is associated with a public Load Balancer using `reserved_ips`

**Comment by jotruon** [comment]
Hi @jeliker,
This issue is duplicate with https://github.com/terraform-providers/terraform-provider-oci/issues/1283, please follow the workaround step in the issue.
We are working on the fix soon.
