### ISSUE TITLE
Inconsistent Routetable IDs: Unable to snap routetable back to what is declared in terraform code

### ISSUE THREAD

**Issue by ryanpodonnell1** [terraform-providers/terraform-provider-oci#1337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform 0.14.2
OCI Provider v4.16.0

### Affected Resource(s)

oci_core_route_table_attachment

### Terraform Configuration Files

```terraform
resource "oci_core_route_table" "sdwan_route_table" {
  display_name   = var.sdwan_route_table.name
  vcn_id         = var.vcn_id
  compartment_id = var.COMPARTMENT_OCID

  dynamic "route_rules" {
    iterator = rule
    for_each = [for r in var.sdwan_route_table.rules : {
      dst : r.destination
      dst_type : r.destination_type
      network_entity_id : r.network_entity_id
    }]
    content {
      destination       = rule.value.dst
      destination_type  = rule.value.dst_type
      network_entity_id = rule.value.network_entity_id
    }
  }
}

resource "oci_core_route_table_attachment" "sdwan_route_table_attachment" {
  subnet_id      = var.sdwan_route_table.subnet_id
  route_table_id = oci_core_route_table.sdwan_route_table.id
}
```

var file
```terraform
sdwan_route_table = { name : "eng-sdwan-subnet-route-table",
  subnet_id : "<subnet_ocid>",
  rules : [{ destination : "10.0.0.0/22", destination_type : "CIDR_BLOCK", network_entity_id : "<PRIVATE_IP_OCD" }]
}
```

### Debug Output

[GIST](https://gist.github.com/ryanpodonnell1/7aa0346a8da830b3a222431ae25ab484)

### Expected Behavior

Terraform identifies there is the wrong routetable attached to the subnet and attempts to snap it back to whats in code

### Actual Behavior

Terraform exits with an error stating inconsistent routetable IDs

https://github.com/terraform-providers/terraform-provider-oci/blob/21be5538b8f3202191bb3f19e4755d4d6cb7165c/oci/core_route_table_attachment_resource.go#L132

### Steps to Reproduce

1. Create subnet
2. Using the following code create a routetable and attach to previously created subnet

vars-file:
```terraform
sdwan_route_table = { name : "test",
  subnet_id : "<SUBNET_OCID>",
  rules : []
}
COMPARTMENT_OCID = "<COMPARTMENT_OCID"

vcn_id = "<VCN_OCID>"
```

```terraform
resource "oci_core_route_table" "sdwan_route_table" {
  display_name   = var.sdwan_route_table.name
  vcn_id         = var.vcn_id
  compartment_id = var.COMPARTMENT_OCID

  dynamic "route_rules" {
    iterator = rule
    for_each = [for r in var.sdwan_route_table.rules : {
      dst : r.destination
      dst_type : r.destination_type
      network_entity_id : r.network_entity_id
    }]
    content {
      destination       = rule.value.dst
      destination_type  = rule.value.dst_type
      network_entity_id = rule.value.network_entity_id
    }
  }
}

resource "oci_core_route_table_attachment" "sdwan_route_table_attachment" {
  subnet_id      = var.sdwan_route_table.subnet_id
  route_table_id = oci_core_route_table.sdwan_route_table.id
}


variable "sdwan_route_table" {

}

variable "COMPARTMENT_OCID" {}
variable "vcn_id" {

}
```

3. Terraform Apply
4. In OCI Console, change route table to default VCN routetable
5. Run Terraform apply
6. Error:
```
Error: inconsistent route table id received: ocid1.routetable.oc1.iad.aaaaaaaa7bkjlf3jwkud7wotrqnlbztt2lgzc2afb4oqkh3zroxacvtahqkq expected: ocid1.routetable.oc1.iad.aaaaaaaaalspmojrlowslrv5dlpl5t64uor7gxyn2eqbh5mjnc65jer732ua
```

**Comment by varmax2511** [comment]
Hi @ryanpodonnell1 -- thanks for reporting this. I am able to reproduce the issue. From terraform perspective we expect that if the oci_core_route_table_attachment value has changed then it should attempt recreating the resource of `oci_core_route_table_attachment` as all its parameters are not updatable. 
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_route_table_attachment

We will investigate the behavior more and update. In the meantime, a workaround would be to manually recreate the resource when hit this error.

**Comment by varmax2511** [comment]
Hi @ryanpodonnell1 -- we have released a change allowing terraform provider to recreate the resource if the route_table_id is changed. 
https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v4.22.0
Please let us know if the issue can be closed now.

**Comment by ryanpodonnell1** [comment]
@varmax2511 thanks, I'll see if I can test this today or tomorrow
