### ISSUE TITLE
The provider provider.oci does not support resource type "oci_data_safe_on_prem_connectors_configuration".

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1344]
Initializing provider plugins...
- Finding hashicorp/oci versions matching "4.21.0"...
- Finding latest version of hashicorp/template...
- Installing hashicorp/oci v4.21.0...
- Installed hashicorp/oci v4.21.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

```
### normal oci settings mono region
###
terraform {
  required_providers {
    oci = {
      source = "hashicorp/oci"
      version = "4.21.0"
    }
  }
}

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
  ## compartement_ocid = var.compartement_ocid
}
```

```
### this works ###
resource "oci_data_safe_on_prem_connector" "on_prem_connector" {
  compartment_id = var.oci_provider.compartment_ocid
  description    = var.on_prem_connector.description
  display_name   = var.on_prem_connector.display_name
  freeform_tags  = var.on_prem_connector.freeform_tags
}

## this is unknown to the provider whats is wrong ???? ###
resource "oci_data_safe_on_prem_connectors_configuration" "on_prem_connectors_configuration" {
  on_prem_connector_id = oci_data_safe_on_prem_connector.on_prem_connector.id
  password             = var.on_prem_connector.password
}

```
[```
oracle@localhost DataSafe_connector]$ terraform -v
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/oci v4.21.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```


```
  on modules/datasafe-connector/main.tf line 9, in resource "oci_data_safe_on_prem_connectors_configuration" "on_prem_connectors_configuration":
   9: resource "oci_data_safe_on_prem_connectors_configuration" "on_prem_connectors_configuration" {

The provider provider.oci does not support resource type
"oci_data_safe_on_prem_connectors_configuration".
```


what is the issue ( typo ?? wrong code ?)

**Comment by varmax2511** [comment]
Hi @eugsim1 -- thanks for reaching out and flagging this issue. This is a documentation bug on our end and I see we don't support a resource for `oci_data_safe_on_prem_connectors_configuration`. We will remove the document in upcoming release.

**Comment by varmax2511** [comment]
Hi @eugsim1  -- we have removed the document `oci_data_safe_on_prem_connectors_configuration`. Thanks for raising this issue.
