### ISSUE TITLE
oci_core_tunnel object missing in the code

### ISSUE THREAD

**Issue by Nefelim4ag** [terraform-providers/terraform-provider-oci#1370]
oci_core_tunnel - has reference in documentation, but has no definition in docs or in code itself
https://github.com/terraform-providers/terraform-provider-oci/search?q=oci_core_tunnel

**Comment by srishtipmishra** [comment]
This was fixed in provider version 4.29 - https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_ipsec_connection_tunnel_management
