### ISSUE TITLE
depends_on not deterministic with script that creates compartment and uses that the compartment

### ISSUE THREAD

**Issue by sgaetjen** [terraform-providers/terraform-provider-oci#1371]
When creating a oci_logging_log resource in a compartment (oci_identity_compartment) resource that is created in the same script we found that we would still receive a “NotAuthorizedOrNotFound” . Putting a sleep  in the script seemed to resolve the issue. Wanted to see if there is a way to enhance the "depends_on" for our provider to ensure that a compartment is truly ready to be used

**Comment by varmax2511** [comment]
Closing this ticket as a duplicate of https://github.com/terraform-providers/terraform-provider-oci/issues/1380
