### ISSUE TITLE
Authorization failed or requested resource not found.

### ISSUE THREAD

**Issue by RupakRath** [terraform-providers/terraform-provider-oci#1373]
**Plan: 1 to add**, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

oci_core_instance.test_instance[0]: Creating...
╷
│ **Error: 404-NotAuthorizedOrNotFound**
│ Provider version: 4.23.0, released on 2021-04-21. This provider is 3 updates behind to current.
│ Service: Core Instance
│ Error Message: **Authorization failed or requested resource not found.**
│ OPC request ID: 9549b0d184c61c0f8e0771053a304af1/3F65C15D7D3D582706BEC8C3B604DF43/57F499FA8361C79A4E604DA6A62C408D
│ Suggestion: Either the resource has been deleted or service Core Instance need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm..

**Comment by varmax2511** [comment]
Hi @RupakRath  -- Per the error please check if you have required access to provision the instance. https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
