### ISSUE TITLE
Creating oci_containerengine_node_pool in terraform

### ISSUE THREAD

**Issue by edvinas31** [terraform-providers/terraform-provider-oci#1375]
Hi all, I have faced the issue when creating oci_containerengine_node_pool resource using terraform. Using oci console resource is created properly specifying same node_shape and oci image, which are "VM.Standart.E3.Flex" and "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra"

```
resource "oci_containerengine_node_pool" "test_node_pool" {
  #Required
  cluster_id          = oci_containerengine_cluster.oke-cluster.id
  compartment_id      = var.compartment_id
  kubernetes_version  = var.cluster_version
  name                = var.name
  subnet_ids          = [oci_core_subnet.workernodes.id]
  node_shape = "VM.Standart.E3.Flex"
  node_shape_config {
    #Optional
    memory_in_gbs = "8"
    ocpus = "1"
  }
  node_source_details {
      #Required
      image_id = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra"
      source_type = "image"
      #Optional
      #boot_volume_size_in_gbs = "50"
  }
}
```

Error I get says the following:

```
module.kubernetes.oci_containerengine_node_pool.test_node_pool: Creating...

Error: 400-InvalidParameter
Provider version: 4.25.0, released on 2021-05-05. This provider is 2 updates behind to current.
Service: Containerengine Node Pool
Error Message: Invalid nodeShape: Node shape and image are not compatible.
OPC request ID: d2697e2086a3c71025c4d1450b940539/4E3B0477164ABD0BE2539A0D89F1E947/952504A4F2ADB99F084C4A4CBEC1C8FB
Suggestion: Please update the parameter(s) in the Terraform config as per error message Invalid nodeShape: Node shape and image are not compatible.


  on ../../../../modules/oci/services/kubernetes/cluster.tf line 15, in resource "oci_containerengine_node_pool" "test_node_pool":
  15: resource "oci_containerengine_node_pool" "test_node_pool" {
```

I am using oci provider version 4.0 and terraform 0.14.10

**Comment by hyder** [comment]
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/oke/nodepools.tf

**Comment by edvinas31** [comment]
Thank you @hyder for answer, but where is a problem with my code? I do not want to use dynamic block at this point point of time. I tried to modify it a little bit and get a bit different error code.

```
resource "oci_containerengine_node_pool" "test_node_pool" {
  #Required
  cluster_id          = oci_containerengine_cluster.oke-cluster.id
  compartment_id      = var.compartment_id
  kubernetes_version  = var.cluster_version
  name                = var.name
	node_shape = "VM.Standart.E3.Flex"
  node_config_details {
    placement_configs {
      availability_domain = "qzwq:EU-FRANKFURT-1-AD-1"
      subnet_id = oci_core_subnet.workernodes.id
    }
    size = 3
  }
  node_shape_config {
    #Optional
    memory_in_gbs = "16"
    ocpus = "1"
  }
  node_source_details {
      #Required
      image_id  = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra"
      source_type = "image"
      #Optional
      boot_volume_size_in_gbs = "50"
  }
}
```

```
module.kubernetes.oci_containerengine_node_pool.test_node_pool: Creating...

Error: 400-InvalidParameter
Provider version: 4.25.0, released on 2021-05-05. This provider is 2 updates behind to current.
Service: Containerengine Node Pool
Error Message: the image ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra may not exist or you are not authorized to access it, or nodeShape VM.Standart.E3.Flex is not compatible with image ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra
OPC request ID: 268677c7d868f131666879ddbeee0176/C01E9FF21999876C771D4365DF8C2DD1/5916AC26E72F4D69A5E86E422B6B50D8
Suggestion: Please update the parameter(s) in the Terraform config as per error message the image ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra may not exist or you are not authorized to access it, or nodeShape VM.Standart.E3.Flex is not compatible with image ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra


  on ../../../../modules/oci/services/kubernetes/cluster.tf line 15, in resource "oci_containerengine_node_pool" "test_node_pool":
  15: resource "oci_containerengine_node_pool" "test_node_pool" {
```

**Comment by edvinas31** [comment]
I can verify that this setup works with "VM.Standart2.1" image shape:

```
resource "oci_containerengine_node_pool" "test_node_pool" {
  #Required
  cluster_id          = oci_containerengine_cluster.oke-cluster.id
  compartment_id      = var.compartment_id
  kubernetes_version  = var.cluster_version
  name                = var.name
  node_shape          = "VM.Standard2.1"
  node_config_details {
    placement_configs {
      availability_domain = "qzwq:EU-FRANKFURT-1-AD-1"
      subnet_id = oci_core_subnet.workernodes.id
    }
    size = 3
  }
  # node_shape_config {
  #   #Optional
  #   memory_in_gbs = "16"
  #   ocpus = "1"
  # }
  node_source_details {
      #Required
      image_id = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra"
      #image_id  = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaazfzlw2infpo3svzjgrcl237xsbod4l5yuzfpqdqmmawia2womz5q"
      source_type = "image"
  }
}

```

If I change shape to "VM.Standart.E3.Flex" terraform starts to throw errors about not supported image shape and image itself. Tried this with no success:

```
resource "oci_containerengine_node_pool" "test_node_pool" {
  #Required
  cluster_id          = oci_containerengine_cluster.oke-cluster.id
  compartment_id      = var.compartment_id
  kubernetes_version  = var.cluster_version
  name                = var.name
  #node_shape          = "VM.Standard2.1"
  node_shape          = "VM.Standart.E3.Flex"
  node_config_details {
    placement_configs {
      availability_domain = "qzwq:EU-FRANKFURT-1-AD-1"
      subnet_id = oci_core_subnet.workernodes.id
    }
    size = 3
  }
  node_shape_config {
    #Optional
    memory_in_gbs = "16"
    ocpus = "1"
  }
  node_source_details {
      #Required
      #image_id = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra"
      image_id  = "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaazfzlw2infpo3svzjgrcl237xsbod4l5yuzfpqdqmmawia2womz5q"
      source_type = "image"
  }
}
```

**Comment by hyder** [comment]
I think the problem could be with your image.

**Comment by edvinas31** [comment]
What image do you use? I am using this one: https://docs.oracle.com/en-us/iaas/images/image/8274a097-bc2b-46c7-ada3-dd138048c072/

**Comment by hyder** [comment]
You're assuming the same image will be immediately available by the OKE api. That's not correct. See: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/263

**Comment by hyder** [comment]
this is how we determine the image to use: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/oke/locals.tf#L20

**Comment by edvinas31** [comment]
If assuming the same image will be immediately availably by the OKE api is incorrect then why the same image "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra" works with VM.Standart2.1 shape. Why terraform works differently than in oci console. What I mean is after my k8s cluster is created I can easily create node pool using oci console specifying "VM.Standart.E3.Flex" shape and "Oracle-Linux-7.9-2021.04.09-0" image ("ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra") I expect same would work in terraform.

Also, by looking at your example I see that you are getting all the images information from https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/containerengine_cluster_option data source. It is fine, but looking at what images can be used for k8s node pool with command `"oci ce node-pool-options get --node-pool-option-id all"` I see that it is the same output as from datasource you are using. The ocid of "Oracle-Linux-7.9-2021.04.09-0" is the same. Why cannot I just hard code ocid of image I want (although I know it is not a best practice)?

**Comment by edvinas31** [comment]
Okay, so at last I have managed to create node pool with "VM.Standart.E3.Flex" image. I do not know what influenced that behaviour, but modified code looks like this:

```
resource "oci_containerengine_node_pool" "test_node_pool" {
  #Required
  cluster_id          = oci_containerengine_cluster.oke-cluster.id
  compartment_id      = var.compartment_id
  kubernetes_version  = var.cluster_version
  name                = var.name
  node_shape          = var.node_pool_node_shape
  node_config_details {
    dynamic "placement_configs" {
      iterator = ad_iterator
      for_each = var.availability_domains
      content {
        availability_domain = ad_iterator.value
        subnet_id           = oci_core_subnet.workernodes.id
      }
    }
    # set quantity to a minimum of 1 to allow small clusters. 
    size = var.k8s_nodes_number
  }
  node_shape_config {
     #Optional
     memory_in_gbs = "8"
     ocpus = "1"
  }
  node_source_details {
      #Required
    image_id    = var.image_id
    source_type = data.oci_containerengine_node_pool_option.node_pool_options.sources[0].source_type
  }
}
```

Image_id is "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa4pnql6wprjir2xhf2is2r7u2g7e4s3lufxxjp6hzm3tyepannwra" and shape is "VM.Standart.E3.Flex"

**Comment by hyder** [comment]
You can force the worker nodes to use a particular image id but you need to provide it yourself instead of looking it up. You also need to ensure 1) the value is correct 2) that image is available.

In the above project. we cater for this as well in case some teams prefer to use their own images.: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/variables.tf#L401 

If this value is "none", then we look up an image id using the data source. Otherwise, we use that value itself:

https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/main/modules/oke/nodepools.tf#L35

We are about to add an enhancement to this to cater for GPU shapes but we'll also submit an enhancement request for this feature as we think this data source is too coarse.
