### ISSUE TITLE
Documentation bug on Heatwave provider reference

### ISSUE THREAD

**Issue by dralquinta** [terraform-providers/terraform-provider-oci#1384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.15.4
on darwin_amd64

### Affected Resource(s)

Documentation bug under https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/mysql_heat_wave_cluster.html.markdown

### Expected Behavior

Resource reference should contain example, however it's missing from documentation. I see that referenced components are listed, but example is missing. 

Plugin export command should help in bringing the correct sample output. Other option is example under: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/mysql/heat_wave_cluster/main.tf 

### Actual Behavior

See link: https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/mysql_heat_wave_cluster.html.markdown

Reference example is completely empty

```shell
resource "oci_mysql_heat_wave_cluster" "test_heat_wave_cluster" {
}
```

**Comment by varmax2511** [comment]
Hi @dralquinta -- docs have been updated.
