### ISSUE TITLE
Terrform not applying the changes even the plan shows the resource will be added

### ISSUE THREAD

**Issue by krasappan** [terraform-providers/terraform-provider-oci#1415]
### Terraform Version and Provider Version

Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.35.0

### Affected Resource(s)

oci_datacatalog_data_asset

### Terraform Configuration Files

```hcl

module/data_catalog/asset_adw/asset_adw_variables.tf
variable "adw_asset_display_name" {}
variable "datacatalog_ocid" {}
variable "adw_db_name" {}

module/data_catalog/asset_adw/asset_adw.tf
resource "oci_datacatalog_data_asset" "dataAsset_adw" {
    display_name   = var.adw_asset_display_name
    type_key       = "38320846-a7c3-465f-b88d-4fb1a0ee8389" 
    catalog_id     = var.datacatalog_ocid
    
properties = {
            "default.database" : var.adw_db_name
        }
}

main.tf: 

module "asset_adw" {
  datacatalog_ocid         = module.catalog.datacatalog_ocid
  source                   = "../modules/data_catalog/asset_adw"
  adw_asset_display_name   = "SDS-${var.env_type}-${var.env_region}-ASSET-ADW"
  adw_db_name              = module.adw.adw_dbname
}

```

### Debug Output

Plan: 
```hcl
# module.asset_adw.oci_datacatalog_data_asset.dataAsset_adw will be created
  + resource "oci_datacatalog_data_asset" "dataAsset_adw" {
      + catalog_id    = "ocid1.datacatalog.oc1.xxxxxxxx"
      + created_by_id = (known after apply)
      + description   = (known after apply)
      + display_name  = "SDS-STAGE-IAD-ASSET-ADW"
      + external_key  = (known after apply)
      + id            = (known after apply)
      + key           = (known after apply)
      + properties    = {
          + "default.database" = "SDSSTAGEDB"
        }
      + state         = (known after apply)
      + time_created  = (known after apply)
      + time_updated  = (known after apply)
      + type_key      = "38320846-a7c3-465f-b88d-4fb1a0ee8389"
      + updated_by_id = (known after apply)
      + uri           = (known after apply)
    }
```
Terraform state output - doesnt show the above module. 

### Expected Behavior

Resources which are displayed during terraform plan should have been created during terraform apply.. It does  not throw any error related do the resource during the apply. 

### Actual Behavior

Terraform apply did not create the resource

### Steps to Reproduce

1) Terraform plan - Display the resources to be added
2) Terraform apply - No error / warning / completion related to above resource
3) Terraform state list -  Does not list the rsources
4) Open terraform state file in text editor - Shows the resources exists in the file as below:
```hcl
{
      "module": "module.asset_adw",
      "mode": "managed",
      "type": "oci_datacatalog_data_asset",
      "name": "dataAsset_adw",
      "provider": "provider[\"registry.terraform.io/hashicorp/oci\"]",
      "instances": []
    }
```

**Comment by varmax2511** [comment]
Hi @krasappan -- this is not an issue with terraform-oci-provider or the resource `oci_datacatalog_data_asset` in question. For a working example using this resource, please refer to https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/datacatalog
I would suggest you to please check your terraform configuration.

**Comment by krasappan** [comment]
@varmax2511 - data asset works for object storage and the oracle analytics cloud.. configuration looks fine; I was wondering how come TF plan shows the resource to be added but the apply doesn't show anything related to the resource. If TF did  not apply then how the resource is added to tf state file; if the resource exists in td state file then why it is not listed when I use terraform list state
