### ISSUE TITLE
Bug with oci_ocvp_sddc 

### ISSUE THREAD

**Issue by lionelcave-ora** [terraform-providers/terraform-provider-oci#1418]
I am am member of the Oracle Cloud Engineering VMware Solution Team. I am using oci_ocvp_sddc to deploy a SDDC with vSphere 7.2. The SDDC deploys fine, however post deployment when logging into NSX-T manager to add a new network segment or a new NSX-T Edge, those changes will not propagate to vSphere as the trust between them appears to be broken. The only way the trust can be reinstated is to include the nsx admin user into the Lockdown mode exclusion list of disable lockdown mode. Adding the NSX user into Lockdown exclusion list is a newer improvement and may be not included into TF OCVP create sddc module. This is a critical bug.

**Comment by varmax2511** [comment]
Hi @lionelcave-ora -- as discussed internally. This is not a terraform oci provider issue but a request from the OCVP service. Please follow up with the service.
https://www.oracle.com/assets/support-process-guide-cloud-4428288.pdf
