### ISSUE TITLE
Compartments dont get deleted

### ISSUE THREAD

**Issue by dirien** [terraform-providers/terraform-provider-oci#1437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```bash
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/oci v4.40.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```
### Affected Resource(s)

`oci_identity_compartment`

### Terraform Configuration Files

```hcl
resource "oci_identity_compartment" "inlets-exit-node" {
  description = "OCI compartment for the inlets exit node"
  name = "inlets-exit-node"
}
```

### Debug Output

```bash
oci_identity_compartment.inlets-exit-node: Destroying... [id=ocid1.compartment.oc1..aaaaaaaak7a73gwhgfbykswjoiygxa3fa5jvsm5oi3bfejamlhjkuizn2jya]
random_integer.dns: Destruction complete after 0s
oci_identity_compartment.inlets-exit-node: Destruction complete after 0s

```

### Expected Behavior

oci_identity_compartment should be deleted. In the UI its green. Needed to delete by hand. But the logs say deleted.

### Actual Behavior

oci_identity_compartment is not deleted

### Steps to Reproduce

1. `terraform apply`

**Comment by scross01** [comment]
See https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment#enable_delete

> Important: Unless enable_delete is explicitly set to true:
>    Terraform will not delete compartments on destroy, and

**Comment by varmax2511** [comment]
@dirien -- To delete compartments, `enable_delete` flag has to be set.
```
Important: Unless enable_delete is explicitly set to true:

    Terraform will not delete compartments on destroy, and
    For backwards compatibility, an existing compartment (not including root compartment) with the same name will be automatically imported into the state. Properties of the existing compartment will be updated to what is defined in the new configuration. This can cause a problem if multiple Terraform configurations are using the same compartment, but, for example, specify a different compartment description.
```

please refer to https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment

**Comment by dirien** [comment]
hi @scross01 and @varmax2511,

thanks for the feedback. This flag must be complet slipped through my radar!
