### ISSUE TITLE
Add support for darwin_arm64 platform

### ISSUE THREAD

**Issue by SamuelBagattin** [terraform-providers/terraform-provider-oci#1512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, the official OCI provider is not built for MacOS with Apple Silicon SOCs (darwin_arm64)
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/42091952/149130477-7a52f913-3338-4a3d-b3b1-d7ca74a2cf45.png">
Hence, everyone running this platform cannot build infrastructure with Terraform on OCI, using the official provider.
The only workaround for me has been to fork this repo and build [my own provider](https://registry.terraform.io/providers/SamuelBagattin/oci/) using the latest version of golang.<br>
Would it be possible to build and publish [the official OCI provider](https://registry.terraform.io/providers/hashicorp/oci/latest) for darwin_arm64 to the terraform registry ?

### New or Affected Resource(s)
- None

### Potential Terraform Configuration
- None

### References
- None

**Comment by rafee** [comment]
#1322 already discusses this. However, if Oracle is using this one for tracking requirements, let's put our votes here.

**Comment by rafee** [comment]
#1322 already discusses this

**Comment by SamuelBagattin** [comment]
> #1322 already discusses this. I propose this to be closed.
👍
