### ISSUE TITLE
Individual resource data sources needed

### ISSUE THREAD

**Issue by tomzepf-oracle** [terraform-providers/terraform-provider-oci#256]
### Terraform Version
v0.10.5

### OCI Provider Version
v2.0.0

### Description:
In addition to filter functionality #182, single instance data sources are also needed.

In addition to support for lists of resources like:
```
data "oci_identity_groups" "all" {
  compartment_id = "${var.compartment_ocid}"
}
```
there should be something for individual resources like:
```
data "oci_identity_group" "mygroup" {
  compartment_id = "${var.compartment_ocid}"
  group_id  = "ocid1.group.oc1..."
}
```

There appears to be very limited (no?) support for data sources returning anything but lists of items, and terraform is really horrible at dealing with lists of maps.

**Comment by briangustafson** [comment]
This is a good suggestion. Is there a particular scenario or data source where this would be particularly useful to you? If so, then that would help us prioritize.

**Comment by tjfontaine** [comment]
Actually, for configuring environments in existing resources, I think I would do the reverse order for priority

**Comment by codycushing** [comment]
We have added support for this in our code generator, expect to see singular data sources accompany any new resource. Creating them for existing resources would likely happen with any new feature addition to said resource, but if there are special requests we can attend to them, let us know.

**Comment by tomzepf-oracle** [comment]
I got stuck badly again yesterday with the FSS resources. If the only data source you have returns a list of resources (mount target), that resource has a list of attributes (private IPs), and those need to be further dereferenced (actual IP address), it is very difficult to make work. Eventually you get wrapped around limitations in Terraform where you cannot deal well with count/splat for computed resource counts. Which makes it very easy to write TF that will create resources, but then the destroys will fail.

Adding another +1 for this feature, at least for the FSS/Private IP resources.

**Comment by kilokahn** [comment]
@tomzepf-oracle @tjfontaine we are in the process of pushing out "singular" datasources for `subnet` and `volume`. More will follow in the coming weeks.

cc: @alexng-canuck

**Comment by varmax2511** [comment]
Singular datasources are now available for most Terraform resources including compartment, subnet, vcn, user and group. To learn more, check the `Data Sources` section on https://www.terraform.io/docs/providers/oci/index.html
