### ISSUE TITLE
Impossible to create a route rule pointing to private IP in the same subnet 

### ISSUE THREAD

**Issue by MarcinZablocki** [terraform-providers/terraform-provider-oci#270]
Due to the dependency problem, it's currently not possible to point private IP as a route target within the routing_table rule. I suggest creating a separate resource of route_rule that can be attached to the existing route_table.

**Comment by briangustafson** [comment]
Thanks for bringing this up and for the suggestion - we'll look into it.

**Comment by rcohenma** [comment]
See the response to Github issue #578

https://github.com/oracle/terraform-provider-oci/issues/578

**Comment by afedorch** [comment]
`oci_core_route_table_attachment` resource was introduced in v3.10.0 release to resolve this dependency cycle problem. 
the documentation for the resource: https://www.terraform.io/docs/providers/oci/r/core_route_table_attachment.html
the example to try: https://github.com/terraform-providers/terraform-provider-oci/blob/master/docs/examples/networking/route_table/attachment/route_table_attachment.tf
