### ISSUE TITLE
Support automatic update of OCI terraform plugin

### ISSUE THREAD

**Issue by sanketdjain** [terraform-providers/terraform-provider-oci#436]
### Terraform Version

Terraform v0.11.1

    provider.null v1.0.0
    provider.oci v2.0.5
    provider.template v1.0.0

### OCI Provider Version

    oci_v2.0.5 
    2018/01/05 09:35:28 [INFO] terraform-provider-oci 2.0.5

### Description:
The OCI Terraform plugin is not officially registered in Hashicorp registry. So terraform get -update command does not update the plugin automatically.

As a result, one has to download the latest plugin from the GitHub releases at the below link
https://github.com/oracle/terraform-provider-oci/releases

If you notice, the URL for each release is different. This makes it difficult to automatically download the latest plugin or update the plugin, without any manual intervention.

A proposed solution would be to create a single URL which always points to the LATEST version of the plugin.

    Release URL:
        https://github.com/oracle/terraform-provider-oci/releases/download/v2.0.6/linux.tar.gz

    Additional URL:
        https://github.com/oracle/terraform-provider-oci/releases/download/LATEST/linux.tar.gz

**Comment by hyder** [comment]
+1

**Comment by alexng-canuck** [comment]
Hi @hyder and @sanketdjain,

Just wanted to let you know that Terraform now supports automatically downloading the OCI provider using a `terraform init` command; starting with Terraform provider v3.0.0.

For more details on how to automatically upgrade to the new provider, refer to this guide: https://www.terraform.io/docs/providers/oci/guides/version-3-upgrade.html
