### ISSUE TITLE
Support most_recent when fetching images

### ISSUE THREAD

**Issue by jhorwit2** [terraform-providers/terraform-provider-oci#437]
https://www.terraform.io/docs/providers/aws/d/ami.html

It'd be useful to be able to retrieve only the latest image with a given name.

**Comment by rcohenma** [comment]
We have a task in our backlog to add an order_by and a sort_order for list operations and you'll be able to sort by time created.
This should be enough to address your case, right?

**Comment by jhorwit2** [comment]
@rcohenma yup!

**Comment by torstenboe** [comment]
Any news on that? Just ran into the same issue?

**Comment by varmax2511** [comment]
Capability to use `sort_by` and `sort_order` is now available in `images` datasource as part of commit `6d57acd037bf796faafc9241bf36858e4cec32fa`. Please refer [image example](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/image/datasources.tf)
