### ISSUE TITLE
Difficult to pass variable length and type of security rules in the security module.

### ISSUE THREAD

**Issue by neerkuma** [terraform-providers/terraform-provider-oci#449]
### Terraform Version

Terraform v0.10.8

### OCI Provider Version

 terraform-provider-oci v2.0.0

### Description:
Include a description with repro steps, expected result and actual result

We are working a series of Terraform modules in OCI,and came across an issue that we think would require a enhancement to the provider.  One of our modules for security list creation, seems to be proving difficult for variable number of security rules.  We've done some testing using the null_resource provider along with a file call to stand up a common set of security rules to any give tenancy; however, we have noticed that once ingesting these rules from a file, terraform has no way of tracking updates properly.

our use case is to create a module that will allow us to specify the various subnets associated to a new customer tenancy, and configure the standard set of common secrules that apply to all new tenancies. We would then need the ability to add/remove any rules in subsequent Terraform runs.  It appears that Amazon may have solved this by breaking out security groups and security group rules into separate resources.  Do you happen to know if anyone else has run into this issue in the past, and what has been done to solve it?  Also, is this something you could see as an enhancement to the provider?

We can think of two possible scenrio to address this, please feel free if this can be address in any other way. 

Scenrio 1 : Pass the security rules as template file 

resource "oci_core_security_list" "security_list1" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${lookup(data.oci_core_virtual_networks.VCN.virtual_networks[0],"id")}"
  display_name = "security_list1"
  egress_security_rules  = ["${file("egress_rules.json")}"]
  ingress_security_rules = ["${file("ingress_rules.json")}"]
}

ingress_rules.json
{
  "ingressSecurityRules" : [{
    "protocol" : "6",
    "source" : "10.0.1.0/24",
    "tcpOptions" : {
      "destinationPortRange" : {
        "min" : "1521",
        "max" : "1521"
      }
    }
  },{
    "protocol" : "6",
    "source" : "10.0.2.0/24",
    "tcpOptions" : {
      "destinationPortRange" : {
        "min" : "1521",
        "max" : "1521"
      }
    }
  }]

egress_rules.json

  "egressSecurityRules" : [{
    "protocol" : "6",
    "destination" : "10.0.2.0/24",
    "tcpOptions" : {
      "destinationPortRange" : {
        "min" : "1521",
        "max" : "1521"
      }
    }
  }]
}

Scenrio 2 :  add additional resource for the security rule that can be apply to the security list something like aws
resource "oci_core_security_list" "security_list1" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id = "${lookup(data.oci_core_virtual_networks.VCN.virtual_networks[0],"id")}"
  display_name = "security_list1"
  egress_security_rules  = []
  ingress_security_rules = []
}

resource "oci_core_security_rule "secrule" {
  seclist = oci_core_security_list.security_list1.id
    type = ingress
    source = "0.0.0.0/0"
    protocol = "6"
    tcp_options {
      "min" = 80
      "max" = 80

}

**Comment by olkoko** [comment]
Seconded adding standalone definition for "security rules" (separate from "security lists") to be able to define variable number of security rules based on the requirements.
It would be also great to have option to specify port list instead of port range, something like this:

```
resource "oci_core_security_rule "rule1" {
  seclist = oci_core_security_list.security_list1.id
  type = ingress
  source = "0.0.0.0/0"
  protocol = "6"
  tcp_options {
    ports = [8001, 8011]
  }
}
```

**Comment by svilmune** [comment]
Above would be good addition if security rules could be passed as standalone. Right now making a dynamic module with different number of security rules for security list is not so clear how to do it. 

Is there any best practice how to do it at the moment?

**Comment by matmacfarlane** [comment]
+1 for a separate resource for security list rules for the sake of manageability

**Comment by hyder** [comment]
+1 for both separating rules and allowing discrete ports

**Comment by varmax2511** [comment]
With Terraform v12 `dynamic` blocks https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks,  we can now dynamically pass `egress_security_rules` and `ingress_security_rules`. For example:
```
resource "oci_core_security_list" "example_security_list" {
  for_each        = "${var.security_rules_params}"
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_vcn.example_vcn.id}"
  display_name   = "exampleSecurityList"

  dynamic "egress_security_rules" {
    iterator = egress_security_rules
    for_each = each.value.egress_security_rules != null ? each.value.egress_security_rules : []

    content {
      protocol =  egress_security_rules.value.protocol
      destination = egress_security_rules.value.destination
      description = egress_security_rules.value.description
      stateless = egress_security_rules.value.stateless

      dynamic "tcp_options" {
        iterator = tcp_options
        for_each = lookup(egress_security_rules.value, "tcp_options", null) != null ? egress_security_rules.value.tcp_options : []
        content{
          dynamic "source_port_range" {
            iterator = source_port_range
            for_each = lookup(tcp_options.value, "source_port_range", null) != null ? tcp_options.value.source_port_range : []
            content {
              min = source_port_range.value.min
              max = source_port_range.value.max
            }
          }
          min = tcp_options.value.min
          max = tcp_options.value.max
        }
      }

      dynamic "udp_options" {
        iterator = udp_options
        for_each = lookup(egress_security_rules.value, "udp_options", null) != null ? egress_security_rules.value.udp_options : []

        content {
          dynamic "source_port_range" {
            iterator = source_ports
            for_each = lookup(udp_options.value, "source_port_range", null) != null ? udp_options.value.source_port_range : []
            content {
              min = source_ports.value.min
              max = source_ports.value.max
            }
          }

          min = udp_options.value.min
          max = udp_options.value.max
        }
      }

      dynamic "icmp_options" {
        iterator = icmp_options
        for_each = lookup(egress_security_rules.value, "icmp_options", null) != null ? egress_security_rules.value.icmp_options : []
        content {
          type = icmp_options.value.type
          code = icmp_options.value.code
        }
      }
    }
  }

  dynamic "ingress_security_rules" {
    iterator = ingress_security_rules
    for_each = each.value.ingress_security_rules != null ? each.value.ingress_security_rules : []

    content {
      protocol =  ingress_security_rules.value.protocol
      source = ingress_security_rules.value.source
      description = ingress_security_rules.value.description
      stateless = ingress_security_rules.value.stateless

      dynamic "tcp_options" {
        iterator = tcp_options
        for_each = lookup(ingress_security_rules.value, "tcp_options", null) != null ? ingress_security_rules.value.tcp_options : []
        content{
          dynamic "source_port_range" {
          iterator = source_port_range
          for_each = lookup(tcp_options.value, "source_port_range", null) != null ? tcp_options.value.source_port_range : []
          content {
            min = source_port_range.value.min
            max = source_port_range.value.max
          }
        }
        min = tcp_options.value.min
        max = tcp_options.value.max
      }
    }

    dynamic "udp_options" {
      iterator = udp_options
      for_each = lookup(ingress_security_rules.value, "udp_options", null) != null ? ingress_security_rules.value.udp_options : []

      content {
        dynamic "source_port_range" {
          iterator = source_ports
          for_each = lookup(udp_options.value, "source_port_range", null) != null ? udp_options.value.source_port_range : []
          content {
            min = source_ports.value.min
            max = source_ports.value.max
          }
        }

        min = udp_options.value.min
        max = udp_options.value.max
      }
    }

    dynamic "icmp_options" {
      iterator = icmp_options
      for_each = lookup(ingress_security_rules.value, "icmp_options", null) != null ? ingress_security_rules.value.icmp_options : []
      content {
        type = icmp_options.value.type
        code = icmp_options.value.code
      }
    }
    }
  }
}
```
