### ISSUE TITLE
Question: Another way to get information - ability to index output of volume datasource

### ISSUE THREAD

**Issue by rrcastro** [terraform-providers/terraform-provider-oci#479]
### Terraform Version

<details>
Terraform v0.10.8
</details>

### OCI Provider Version

<details>
2018/03/15 16:33:46 [INFO] terraform-provider-oci 2.1.1
</details>

### Description:

I am building an orchestration, where I use datasource repetition through "count".

Note through the output that I can get the same data through two options ( Option1 and Option2 ):

<p><strong>outputs.tf</strong></p>
<pre><code>output "Option1"  {
 value = "${data.oci_core_volumes.clone_volumes.2.volumes}"
}
output "Option2"  {
 value = "${data.oci_core_volumes.clone_volumes.*.volumes[2]}"
}
output "Option1_Lookup_AD"  {
 value = "${lookup(data.oci_core_volumes.clone_volumes.2.volumes[0],"availability_domain")}"
}
</code></pre>

I can extract information "availability_domain" with lookup by Option1. 

Is there any way to extract the same information with the Option2 ?

Attached:

<a href="https://github.com/oracle/terraform-provider-oci/files/1816334/datasources.tf.txt">datasources.tf.txt</a>

### Terraform Apply

<details>

Attached:

<a href="https://github.com/oracle/terraform-provider-oci/files/1816342/terraform_apply_output.log">terraform_apply_output.log</a>

</details>

**Comment by rrcastro** [comment]
### Investigation:

In both options (Option1 and Option2), it is returned as a list with only one element.

Normally, we can return an element from the list by index: LIST[IDX].

But, if we use this strategy for Option2, we get error in "terraform apply".

<p><strong>outputs.tf</strong></p>
<pre><code>...
output "Option2_Lookup_AD"  {
 value = "${lookup(data.oci_core_volumes.clone_volumes.*.volumes[2][0],"availability_domain")}"
}</code></pre>

<p><strong>terraform apply</strong></p>
<pre><code>Error: Failed to load root config module: Error loading /home/ocs/scripts/terraform/issue3/outputs.tf: Error reading config for output Option2_Lookup_AD: parse error at 1:58: expected ")" but found "["</code></pre>

**Comment by alexng-canuck** [comment]
Hello @rrcastro ,

Option2_LookupAD is not valid Terraform syntax. Can you tell us what you are trying to accomplish with Option 2, that you can't accomplish with Option 1?

Maybe we can come up with a better solution for you.

Thanks,
Alex

**Comment by rrcastro** [comment]
Hello @alexng-canuck , 

I am performing the following orchestration:

1 - Identify all the disks that are attached in an instance, with a volume display_name pattern ( 01_source_data_querys.tf );
Briefly, see: oci_core_instances => oci_core_volume_attachments => oci_core_volumes
2 - Perform a clone of these volumes ( 03_source_clone_volumes.tf );

[CloneVolumes.zip](https://github.com/oracle/terraform-provider-oci/files/1827221/CloneVolumes.zip)

**Comment by alexng-canuck** [comment]
Hello @rrcastro,
Unfortunately, this looks like a limitation of Terraform's syntax. In your example, you have a list of oci_core_volumes data sources and each data source has its own list of volumes; and you want to access a specific volume within this list of lists.

Ideally, you could do it by indexing twice like this:
```
data.oci_core_volumes.myvolumes.*.volumes[count.index][0]
``` 
But this isn't valid Terraform syntax. 

The other approach would have been to use the `element` interpolation syntax like this:
```
element(data.oci_core_volumes.myvolumes.*.volumes[count.index], 0)
```

But the `element` syntax can only be used on flat lists and the first argument above is actually a list of maps. So this also won't work.

I will share this feedback with my team and we can investigate how to handle this scenario. Perhaps the `oci_core_volumes` datasource could be improved to allow multiple IDs in the filter; so that you only need to create one `oci_core_volumes` datasource that returns all the volumes.

**Comment by kilokahn** [comment]
@rrcastro we are in the process of pushing out a "singular" datasource for volume that will help in side-stepping the terraform interpolation syntax

cc: @alexng-canuck

**Comment by alexng-canuck** [comment]
Hi @rrcastro ,

The latest version of the Terraform provider (v3.4.0) has support for singular data source for volumes that should help with your scenario.

So in your 01_source_data_query.tf file, you can now replace the `oci_core_volumes` datasource with a singular datasource like this instead:

```
data "oci_core_volume" "source_volume" {
  count = "${length(data.oci_core_volume_attachments.source_volume_attachments.volume_attachments)}"
  volume_id = "${data.oci_core_volume_attachments.source_volume_attachments.volume_attachments.*.volume_id[count.index]}"
}
```

And when you need to reference this data source for values to use in your cloned volumes, just do this:

```
${data.oci_core_volume.source_volume.*.id[count.index]}
${data.oci_core_volume.source_volume.*.size_in_gbs[count.index]}
${data.oci_core_volume.source_volume.*.availability_domain[count.index]}
etc...
```


For information on upgrading to latest version of the provider, please refer to this guide:
https://www.terraform.io/docs/providers/oci/guides/version-3-upgrade.html

Hope this helps.

**Comment by alexng-canuck** [comment]
@rrcastro I'll close this issue now that we have a workaround. Let us know if you still have any questions.
