### ISSUE TITLE
Unable to import oci_load_balancer_path_route_set resource

### ISSUE THREAD

**Issue by sanketdjain** [terraform-providers/terraform-provider-oci#529]
### Terraform Version

Terraform v0.11.1

    provider.local v1.1.0
    provider.null v1.0.0
    provider.oci v2.1.6
    provider.template v1.0.0

### OCI Provider Version

    oci v2.1.6

### Description:
Recently, as part of Issue #429 , the import of load balancer resource was implemented in the OCI plugin. 
Also, as part of Issue #434 the ability to create path route set was implemented in the OCI plugin.

Interestingly, the path route set does not get imported when importing the load balancer. There is no OCID for the path route. I tried to import it using the name, as well the parent load balancer OCID. But it does not work.

If we cannot import path route set, the fix for Issue #434  does not really help, because we want to first import the existing path route sets before making more changes. We do not want to delete any existing path route sets in the load balancers.

### Terraform Plan

$ terraform import  oci_load_balancer_path_route_set.rt  rt-0                                                                        
oci_load_balancer_path_route_set.rt: Importing from ID "rt-0"...
oci_load_balancer_path_route_set.rt: Import complete!
  Imported oci_load_balancer_path_route_set (ID: rt-0)
oci_load_balancer_path_route_set.rt: Refreshing state... (ID: rt-0)
Error importing: 1 error(s) occurred:

* oci_load_balancer_path_route_set.rt (import id: rt-0): 1 error(s) occurred:

* import oci_load_balancer_path_route_set.rt result: rt-0: oci_load_balancer_path_route_set.rt: can not marshal to path in request for field LoadBalancerId. Due to can not marshal a nil pointer

$ terraform import oci_load_balancer_path_route_set.rt  <ocid>
oci_load_balancer_path_route_set.rt: Importing from ID "ocid1.loadbalancer.oc1.phx.aaaaaaaea"...
oci_load_balancer_path_route_set.rt: Import complete!
  Imported oci_load_balancer_path_route_set (ID: ocid1.loadbalancer.oc1.phx.aaaaaaaea)
oci_load_balancer_path_route_set.rt: Refreshing state... (ID: ocid1.loadbalancer.oc1.phx.aaaaaaaea)
Error importing: 1 error(s) occurred:

* oci_load_balancer_path_route_set.rt (import id: ocid1.loadbalancer.oc1.phx.aaaaaaaea): 1 error(s) occurred:

* import oci_load_balancer_path_route_set.rt result: ocid1.loadbalancer.oc1.phx.aaaaaaaea: oci_load_balancer_path_route_set.rt: can not marshal to path in request for field LoadBalancerId. Due to can not marshal a nil pointer

**Comment by kohashim** [comment]
Thank you for the report.  Currently OCI Terraform provider doesn't support importing any resources that have no OCIDs.

**Comment by sanketdjain** [comment]
Hi Koji

Is it possible to manually update the terraform state to detect the path route set ? If you guys can put a wiki page to use as workaround, it will be very useful.

**Comment by alexng-canuck** [comment]
Hi @sanketdjain , support for importing path route sets (among other load balancer-related resources) is now available in the latest v3.2.0 release.

Can you see if that addresses your request?

For details on upgrading to latest provider from pre-v3.0.0 providers; please refer to this guide:
https://www.terraform.io/docs/providers/oci/guides/version-3-upgrade.html
