### ISSUE TITLE
OCI object storage as remote backend

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#540]
### Terraform Version

v0.11.7

### OCI Provider Version
v2.1.10

### Description:
Terraform supports multiple remote backends e.g. S3, Consul etc. This is a feature request to add oci object storage as an additional remote state backend, including multiple Terraform workspaces support.

### Terraform Plan

This is an feature request

**Comment by jbolla** [comment]
This solution doesn't do exactly what you are suggesting, but does it meet your needs? https://github.com/oracle/terraform-provider-oci/wiki/Using-Oracle-Object-Storage-to-store-Terraform-state-files

**Comment by hyder** [comment]
Thanks, that helped in storing the state remotely. My backend config was incorrect. However, what I was really after was multiple workspace support. See: https://www.terraform.io/docs/state/workspaces.html. The terraform http backend does not support named state and throws the following when attempting to create a new workspace:

"Failed to get configured named states: named states not supported"

I think it would be good to have oci storage as an additional backend. That way we can have support for named workspaces.

Note that I'm currently able to work around it by simply changing the backend address and run init again.

**Comment by briangustafson** [comment]
The S3 backend can be used with OCI Object Storage, and that does support workspaces. See https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/terraformUsingObjectStore.htm#s3

**Comment by andrewjwarren** [comment]
Following up on this it seem while we can store the state file on Object Storage we can't read from it. I have created PAR's for the read access and it works but would much rather have either something more native to OCI or be able to use s3 for both.
`
reading state file:
data "terraform_remote_state" "blah" {
  backend = "s3"
  config {
    bucket = "terraform-state"
    key    = "some/path/terraform.tfstate"
    region = "us-ashburn-1"
    endpoint = "https://mytenancy.compat.objectstorage.region.oraclecloud.com"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
  }
}`
This gives me a certificate error as OCI does not have a SAN for *.*.compat.objectstorage.us-ashburn-1.oraclecloud.com

`x509: certificate is valid for *.compat.objectstorage.us-ashburn-1.oraclecloud.com, not terraform-state.mytenancy.compat.objectstorage.us-ashburn-1.oraclecloud.com`

**Comment by tsammut** [comment]
This probably isn't the place to troubleshoot S3 access...

> This gives me a certificate error as OCI does not have a SAN for _._.compat.objectstorage.us-ashburn-1.oraclecloud.com
> 
> `x509: certificate is valid for *.compat.objectstorage.us-ashburn-1.oraclecloud.com, not terraform-state.mytenancy.compat.objectstorage.us-ashburn-1.oraclecloud.com`

Checkout the page shared by @briangustafson . 

https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm

You'll receive that error unless you specific "force_path_style = true".

**Comment by andrewjwarren** [comment]
@tsammut  That is for using the object store in
```
terraform {
  backend "s3" {
```

I am specifically talking about `data "terraform_remote_state" ` which allows you to read from that data store but not write so I can grab things like vcn id. ie 
```
data "terraform_remote_state" "vcn" {
 info here
}
resource "oci_core_security_list" "blah" {
vcn_id         = "${data.terraform_remote_state.vcn.vid}"
}
```

There is no force_path_style in `terraform_remote_state`

**Comment by kral2** [comment]
S3-compat mode means a single/fixed compartment, no integration with iam etc ...

Same view here: having OCI Object Storage natively supported, without relying on S3-Compat mode would be great.
Bonus for locking support, like every other major provider is doing.

Issue #1074 expose the shortcomings of the current S3-Compat mode in more details.

**Comment by zexinwanoci** [comment]
closing issue as it is dup as 1074
