### ISSUE TITLE
Issue when re-running TF scripts with oci_core_route_table 

### ISSUE THREAD

**Issue by vsampath79** [terraform-providers/terraform-provider-oci#570]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.7
+ provider.null v1.0.0
+ provider.oci v2.1.17
</details>

### OCI Provider Version 

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

v2.1.17
</details>

### Description:
Include a description with repro steps, expected result and actual result
We are creating a routing table with NAT gateway targets. We retrieve the PRIVATE_IP ID for the NAT gateway using oci_core_private_ips in a datasource. If there is failure the nat gateway creation and route table creation, On re-running apply detects that there is change in route table and try to perform change that fails the script. 
### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

* oci_core_route_table.natgw[0]: oci_core_route_table.natgw.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.7
    Resource ID: oci_core_route_table.natgw.0
    Mismatch reason: attribute mismatch: route_rules.1807523824.destination
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"route_rules.1807523824.network_entity_id":*terraform.ResourceAttrDiff{Old:"ocid1.servicegateway.oc1.phx.aaaaaaaa5fxhpbwstt35llfp4zlpypspu3hzxnt5qvnuebqam4mk6hgz2iqa", New:"ocid1.servicegateway.oc1.phx.aaaaaaaa5fxhpbwstt35llfp4zlpypspu3hzxnt5qvnuebqam4mk6hgz2iqa", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.1807523824.destination":*terraform.ResourceAttrDiff{Old:"oci-phx-objectstorage", New:"oci-phx-objectstorage", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.1807523824.destination_type":*terraform.ResourceAttrDiff{Old:"SERVICE_CIDR_BLOCK", New:"SERVICE_CIDR_BLOCK", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.~1306718462.destination_type":*terraform.ResourceAttrDiff{Old:"", New:"CIDR_BLOCK", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.~1306718462.network_entity_id":*terraform.ResourceAttrDiff{Old:"", New:"${lookup(module.natgw_lon.natgwip[count.index],\"id\")}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.~1306718462.cidr_block":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.~1306718462.destination":*terraform.ResourceAttrDiff{Old:"", New:"0.0.0.0/0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "route_rules.1106141296.network_entity_id":*terraform.ResourceAttrDiff{Old:"ocid1.privateip.oc1.phx.abyhqljtohh2pkcohjn3747ynedr7cestyekn2z7q23vtshezltkhx6tvgxq", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

</details>

**Comment by rcohenma** [comment]
Can you share what you have in your config for the route_table?

**Comment by vsampath79** [comment]
resource "oci_core_route_table" "natgw_rt" {
  depends_on = [
    "module.natgw",
    "module.svcgw",
  ]

  count          = 3
  compartment_id = "${local.compartment_id}"
  vcn_id         = "${module.aoac_vcn.vcn_id}"
  display_name   = "${format("${local.vcn_name}-natgw-%d-rt", count.index + 1)}"
  provider = "oci"

  route_rules {
    destination       = "${local.anywhere}"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${lookup(module.natgw.natgwip[count.index],"id")}"
  }

  # Add Service gateway routing rule for Object Storage
  route_rules {
    destination       = "${local.objectstorage_svc_cidr}"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = "${module.svcgw.svcgw_id}"
  }
}

**Comment by kilokahn** [comment]
@vsampath79 I am closing this, but feel free to get back to us if there is anything else that we can help with.
