### ISSUE TITLE
How to assign a backup policy to a boot volume?

### ISSUE THREAD

**Issue by vinidba** [terraform-providers/terraform-provider-oci#573]
Hello,

I need to assign a backup policy to a volume.

Ex: backup policy Gold (part of default backup policies).

But, I can't find any policy_id for Gold backup policy.

Thanks!

**Comment by jbolla** [comment]
We don't currently support this, but it is already in development and should be released soon.

**Comment by kilokahn** [comment]
Ability to specify the backup policy for boot volumes is going to be released soon. 

To find the policy_id for gold backup policy, you can use the datasource `oci_core_volume_backup_policies` as documented at https://github.com/oracle/terraform-provider-oci/blob/master/docs/core/volume_backup_policies.md

```
data "oci_core_volume_backup_policies" "test_boot_volume_backup_policies" {
    filter {
        name = "display_name"
        values = [ "gold" ]
    }
}
```

**Comment by imrizvi** [comment]
Hi, tried the link but it is not working (tf plugin version 2.2), can you please show us the output example?

**Comment by vinidba** [comment]
Yes, it worked for me.

Thanks.

bkp2.tf:

data "oci_core_volume_backup_policies" "test_boot_volume_backup_policies" {
    filter {
        name = "display_name"
        values = [ "gold" ]
    }
}


terraform plan
terraform state show oci_core_volume_backup_policies.test_boot_volume_backup_policies

id                                                     = 2018-08-16 19:02:06.116083 +0000 UTC
filter.#                                               = 1
filter.1355985234.name                                 = display_name
filter.1355985234.regex                                = false
filter.1355985234.values.#                             = 1
filter.1355985234.values.0                             = gold
volume_backup_policies.#                               = 1
volume_backup_policies.0.display_name                  = gold
volume_backup_policies.0.id                            = ocid1.volumebackuppolicy.oc1..aaaaaaaagcremuefit7dpcnjpdrtphjk4bwm3emm55t6cghctt2m6iyyjdva
volume_backup_policies.0.schedules.#                   = 4
volume_backup_policies.0.schedules.0.backup_type       = INCREMENTAL
volume_backup_policies.0.schedules.0.offset_seconds    = 0
volume_backup_policies.0.schedules.0.period            = ONE_DAY
volume_backup_policies.0.schedules.0.retention_seconds = 604800
volume_backup_policies.0.schedules.1.backup_type       = INCREMENTAL
volume_backup_policies.0.schedules.1.offset_seconds    = 0
volume_backup_policies.0.schedules.1.period            = ONE_WEEK
volume_backup_policies.0.schedules.1.retention_seconds = 2419200
volume_backup_policies.0.schedules.2.backup_type       = FULL
volume_backup_policies.0.schedules.2.offset_seconds    = 0
volume_backup_policies.0.schedules.2.period            = ONE_MONTH
volume_backup_policies.0.schedules.2.retention_seconds = 31560000
volume_backup_policies.0.schedules.3.backup_type       = FULL
volume_backup_policies.0.schedules.3.offset_seconds    = 0
volume_backup_policies.0.schedules.3.period            = ONE_YEAR
volume_backup_policies.0.schedules.3.retention_seconds = 157680000
volume_backup_policies.0.time_created                  = 2017-10-01 00:00:00 +0000 UTC

**Comment by imrizvi** [comment]
Hi, did you try terraform apply? Plan works for me as well but fails on apply:
terraform apply
data.oci_core_volume_backup_policies.test_boot_volume_backup_policies: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:

 <= data.oci_core_volume_backup_policies.test_boot_volume_backup_policies
      id:                         <computed>
      filter.#:                   "1"
      filter.1355985234.name:     "display_name"
      filter.1355985234.regex:    "false"
      filter.1355985234.values.#: "1"
      filter.1355985234.values.0: "gold"
      volume_backup_policies.#:   <computed>


Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

data.oci_core_volume_backup_policies.test_boot_volume_backup_policies: Refreshing state...

Error: Error applying plan:

1 error(s) occurred:

* output.mroutput: Resource 'data.oci_core_volume_backup_policies.test_boot_volume_backup_policies' not found for variable 'data.oci_core_volume_backup_policies.test_boot_volume_backup_policies.volume_backup_policies.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by imrizvi** [comment]
I meant the "output" section of .tf file.

**Comment by kilokahn** [comment]
@imrizvi I don't see the output configuration, but I am guessing that it is `data.oci_core_volume_backup_policies.test_boot_volume_backup_policies.volume_backup_policies.id` whereas it should be `data.oci_core_volume_backup_policies.test_boot_volume_backup_policies.volume_backup_policies.0.id`, right?

**Comment by kilokahn** [comment]
Can you please share the config file that you are using?

Also, can you run this command to apply the config with all debug logs enabled?
`DEBUG=true TF_LOG=DEBUG OCI_GO_SDK_DEBUG=1 terraform apply`

**Comment by kral2** [comment]
Hi,

You can assign a backup policy to a boot volume using instance's properties.
Below my working config :
```
# Retrieve backup policies into a data object
# 0 = silver, 1 = bronze, 2 = gold

data "oci_core_volume_backup_policies" "oci_volume_backup_policies" {}

# Assign a backup policy to instance's boot volume
resource "oci_core_volume_backup_policy_assignment" "inst_bcm_boot_backup_policy" {
  asset_id = "${oci_core_instance.inst_bcm.boot_volume_id}"
  policy_id = "${lookup(data.oci_core_volume_backup_policies.oci_volume_backup_policies.volume_backup_policies[2],"id")}"
}
```

**Comment by alexng-canuck** [comment]
@imrizvi Closing this since we have not heard a response. 
Please reopen this if you are still hitting this issue.
