### ISSUE TITLE
How to assign an *existing* reserved public IP to an instance's primary private ip

### ISSUE THREAD

**Issue by kral2** [terraform-providers/terraform-provider-oci#577]
Hi,

I am trying to associate an **existing** reserved IP with an instance's first vnic primary private ip.

The goal is to use a reserved IP *provisionned outside of the current terraform configuration*, so the reserved public IP can  be preserved accross ``terraform destroy`` commands.
``lifecycle {prevent_destroy}`` don't help here because it block the whole destroy operation, and we need to unassign prior destroy.

Ideally, we should be able to set the instance's ``public_ip`` property with a value collected via ``data.oci_core_public_ip.xxx.ip_address`` or indicate the OCID to match with on the resource ``oci_core_public_ip`` creation, so a new reserved IP is not created when declaring the terraform resource.

It seems like this operation is currently not possible (or I did not find the way :-))

**Comment by rcohenma** [comment]
Looking at the documentation of public IPs I don't think it is currently possible to do this.

assigning a public_ip to a private_ip_id is only done through a CreatePublicIp or UpdatePublicIp operation. These are operations that are only done in terraform through the public_ip resource.

You can manage the Public IP outside of the terraform config but you will also have to handle assigning that Public IP outside of terraform anytime you destroy and apply your config.

**Comment by alexng-canuck** [comment]
@kral2 we're closing this issue since there have been no updates.

If you have any additional questions, can you reopen this issue and let us know?
