### ISSUE TITLE
Unable to get private_ip from running instance

### ISSUE THREAD

**Issue by joshmullis** [terraform-providers/terraform-provider-oci#579]
### Terraform Version

<details>
Terraform v0.11.8

</details>

### OCI Provider Version

<details>
+ provider.oci v2.2.1
</details>

### Description:
private_ip field is blank when listing instance details

### Terraform Plan

<details>
provider "oci" {
   auth        = "InstancePrincipal"
   region    = "us-ashburn-1"
}

data "oci_core_instances" "datasource" {
  compartment_id = "<instance_compartment_ocid>"
  filter {
    name = "display_name"
    values = [ "<instance_display_name>" ]
  }
}

output "output" {
  value = "${data.oci_core_instances.datasource.instances}"
}
</details>

### Terraform Ouput

<details>
terraform apply
data.oci_core_instances.datasource: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

output = [
    {
        availability_domain = NZTX:US-ASHBURN-AD-1,
        boot_volume_id = ,
        compartment_id = <REDACTED>,
        create_vnic_details = [],
        defined_tags = map[],
        display_name = <REDACTED>,
        extended_metadata = map[],
        freeform_tags = map[],
        hostname_label = ,
        id = <REDACTED>,
        image = ocid1.image.oc1.iad.aaaaaaaa2tq67tvbeavcmioghquci6p3pvqwbneq3vfy7fe7m7geiga4cnxa,
        ipxe_script = ,
        launch_mode = NATIVE,
        launch_options = [map[remote_data_volume_type:ISCSI boot_volume_type:ISCSI network_type:VFIO firmware:UEFI_64]],
        metadata = map[<REDACTED>],
        preserve_boot_volume = 0,
        private_ip = ,
        public_ip = ,
        region = iad,
        shape = VM.Standard2.2,
        source_details = [map[source_type:image source_id:ocid1.image.oc1.iad.aaaaaaaa2tq67tvbeavcmioghquci6p3pvqwbneq3vfy7fe7m7geiga4cnxa boot_volume_size_in_gbs:]],
        state = RUNNING,
        subnet_id = ,
        time_created = 2018-08-23 18:57:12.466 +0000 UTC
    }
]
</details>

**Comment by rcohenma** [comment]
Public_ip and private_ip fields are not currently available for the oci_core_instances datasource. 
They are only available for the oci_core_instance resource.

We will make sure to update the documentation to reflect this.

The way you would get a private_ip from an instance id is through listing the vnic attachments to get the vnic_id and then using the oci_core_vnic datasource to get the vnic object from which you can get the IPs.

You can see an example of this in the private_ips example
https://github.com/oracle/terraform-provider-oci/blob/master/docs/examples/compute/private_ip/private_ip.tf#L78

We will investigate if we can make it easier.

**Comment by alexng-canuck** [comment]
Hello @joshmullis , 

The latest version of Terraform v3.4.0 now has support for singular data sources that can get additional instance information such as private_ip.

To use it, you could specify something like this:

```
provider "oci" { auth = "InstancePrincipal" region = "us-ashburn-1" }
data "oci_core_instances" "datasource" {
  compartment_id = "<instance_compartment_ocid>"
  filter {
    name = "display_name"
    values = [ "<instance_display_name>" ]
  }
}

data "oci_core_instance" "singledatasource" {
  instance_id = "${data.oci_core_instances.datasource.instances.0.id}"
}

output "output" {
  value = "${data.oci_core_instance.singledatasource.private_ip}"
}
```

If you're using a pre-v3.0.0 provider, see this guide on how to upgrade to the latest:
https://www.terraform.io/docs/providers/oci/guides/version-3-upgrade.html

**Comment by alexng-canuck** [comment]
@joshmullis I'm closing this issue since there's now a way to retrieve the private ip from a data source.
Let us know if you have any additional questions.
