### ISSUE TITLE
Cannot destroy after creating > 50 host DNS entries

### ISSUE THREAD

**Issue by tsella** [terraform-providers/terraform-provider-oci#581]
### Terraform Version

Terraform v0.11.7

### OCI Provider Version

v2.2.0

### Description:

My setup creates multiple oci_core_instances and oci_dns_record host records to point to them. Recently I've created >50 instances, and when trying to destroy them, terraform croaked while refreshing:

> Error: Error refreshing state: 2 error(s) occurred:
> 
> * module.dns_suborigin.oci_dns_record.host: 1 error(s) occurred:
> 
> * module.dns_suborigin.oci_dns_record.host: oci_dns_record.host: target A record could not be matched against data XXX.XXX.XXX.XXX
>  from set [{ ....

The returned set is capped at 50 records, and so, while the XXX.XXX.XXX.XXX address has a corresponding DNS entry, terraform is unable to find it.

**Comment by tsella** [comment]
### Terraform Plan

```
provider "oci" {
  version              = "~> 2.2"
  tenancy_ocid         = ""
  user_ocid            = ""
  fingerprint          = ""
  private_key_path     = ""
  region               = "us-ashburn-1"
  disable_auto_retries = "true"
}

variable number_of_entries {
  type = "string"
}

variable zone_name {
  type = "string"
  default = ""
}

variable compartment_ocid {
  type = "string"
  default = ""
}

resource "oci_dns_zone" "vcn-zone" {
  compartment_id = "${var.compartment_ocid}"
  name = "${var.zone_name}"
  zone_type = "PRIMARY"
}

resource "oci_dns_record" "host" {
  count = "${var.number_of_entries}"
  zone_name_or_id = "${oci_dns_zone.vcn-zone.name}"
  domain = "192-168-168-${count.index}.${oci_dns_zone.vcn-zone.name}"
  rtype = "A"
  rdata = "192.168.168.${count.index}"
  ttl = "600"
}
```

Fill in your provider configuration, compartment_ocid and zone_name.

Apply for **number_of_entries** of 20, then destroy: works
Apply for **number_of_entries** of 51, then destroy: fails.

**Comment by rcohenma** [comment]
We have a fix for this. We plan to release it next week.

**Comment by tsella** [comment]
Thanks for the update

**Comment by rcohenma** [comment]
v3.0.0 should have the fix for this issue.

in v3.0.0 we changed the way to get the latest version of our provider in order to be more in line with other terraform providers. See the following doc for instructions on how to upgrade
https://www.terraform.io/docs/providers/oci/guides/version-3-upgrade.html
