### ISSUE TITLE
 provider.oci: can not create client, bad configuration: did not find a proper configuration for private key

### ISSUE THREAD

**Issue by nmshaik** [terraform-providers/terraform-provider-oci#588]
### Terraform Version
v0.11.8
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.8
+ provider.oci v2.2.2

### OCI Provider Version

2.2.2
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

/home/tfa/.terraform.d/plugins/linux_amd64

### Description:
Include a description with repro steps, expected result and actual result

terraform init  - works fine 
like terrraform plan is givning errors

### Terraform Plan

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key

**Comment by ravitandonrt** [comment]
@nmshaik We need more information to better investigate what is happening here. It looks like a configuration issue where authentication may not have been setup for the OCI tools.

Please refer to these steps to create a PEM format based key that is used by the provider to make the API calls: **https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm**

Once you have created and uploaded your keys, you can either provide the key value or path of those files for authentication for provider operations.

```
export TF_VAR_public_key_path=/Users/user/.oci/oci_api_key_public.pem
export TF_VAR_private_key_path=/Users/user/.oci/oci_api_key.pem
```

Let us know if you still face issues after following these steps.

**Comment by ravitandonrt** [comment]
Good points @dmikenz. The terraform provider uses the oci-go-sdk underneath whereas CLI uses the PythonSDK, so all their configuration should be similar in terms of setup and that's what the link above covers.

It's format of the key (PEM) that is important and might have been the culprit. I am on Mac OSX as well.

@nmshaik - Let us know if you issue is resolved so we can close this or if you still need assistance.

**Comment by hosecode** [comment]
I was getting the same error. Switching from: 
~/.oci/oci_api_key.pem 
to 
/Users/USERNAME/.oci/oci_api_key.pem 
resolved it.

**Comment by alexng-canuck** [comment]
Hi @nmshaik 
We are going to close this issue, since we haven't heard any updates on this issue.

Can you reopen this, if you still need assistance?

**Comment by pramod4555** [comment]
Hi I am configuring OCI terraform in windows environment. 
getting error when triggered Terraform plan 
"Error: can not create client, bad configuration: did not find a proper configura
tion for private key

  on oci.tf line 1, in provider "oci":
   1: provider "oci" {"

have configured my private key path in this way
private_key_path = "D:\oci\oci_api_key"

**Comment by romanmacchia** [comment]
atlantis plan
