### ISSUE TITLE
Changing Volume backup policy should not destroy Volume resource

### ISSUE THREAD

**Issue by scotmoor** [terraform-providers/terraform-provider-oci#589]
### Terraform Version
Terraform v0.11.7

### OCI Provider Version
v2.2.3

### Description:
If you change the backup policy of an existing volume in terraform, it will destroy and recreate the volume as well as any volume attachment. If you use the console, you can simple remove the current policy and then re-assign a new policy without having to destroy your resource. 

The attached plan is for after changing the backup policy for existing block volume

### Terraform Plan
[customer_overlay.plan.zip](https://github.com/oracle/terraform-provider-oci/files/2368295/customer_overlay.plan.zip)

**Comment by ravitandonrt** [comment]
@scotmoor We are aware of this issue and the fix for it has been delayed due to some changes in service behavior. We are working with them to provide a fix that will allow you to change the backup policy.

FYI @kilokahn - can you please update this issue when we have more data.

**Comment by kilokahn** [comment]
As @ravitandonrt mentioned, the backup policy has been marked as forceNew and hence not really updatable. However, we could make it updatable - though we'd need to use a different set of APIs to make it updatable. The underlying solution is quite similar to #590 and we are working on fixing it.

**Comment by kilokahn** [comment]
@scotmoor With the introduction of the backup policy being specified at the volume resource, there is now more than one way of volume assignment (the other being via the volume backup assignment resource). This opens up the possibility of a user attempting to specify different backup policies via the two ways and the policy that takes precedence depends on the last resource that was executed and gets flipped in the subsequent invocation. We discussed this internally, and we wish to mark the backup policy attribute on the volume resource as deprecated, and retain the volume backup assignment as the only recommended way to assign backup policy to a volume.

**Comment by kilokahn** [comment]
I am closing the issue, but please let us know if you have any difficulties in using the existing volume backup assignment resource for this use case. Thanks!
