### ISSUE TITLE
Importing resource to refresh state file does not work.

### ISSUE THREAD

**Issue by scotmoor** [terraform-providers/terraform-provider-oci#590]
### Terraform Version
v0.11.7

### OCI Provider Version
v2.2.3

### Description:
While attempting to use Terraform to update the backup policy for my block volume without having to destroy the volume [see Issue #589](https://github.com/oracle/terraform-provider-oci/issues/589), I update the resource via the OCI console. This of course left my state file out of sync with what was in the cloud so I did the following to update the state file:

NOTE: Terraform code updated to reference the correct backup policy ID chosen in the console
1. ran `terraform plan` which showed that the resource in question would be updated (destroyed/recreated really) since the state file did not match the code
2. ran `terraform state rm <resource_name_in_terraform>` to remove the resource in question from the state file
3. ran `terraform state list` to confirm the resource was removed
4. ran `terraform import <resource_name_in_terrafrom> <ocid_of_resource_in>`
5. Re-ran `terraform plan` which still indicated that the resource in the state file referenced the previous backup policy and thus would need to be updated (destroyed/recreated)

**Expected Result**
Since the resource had been removed from the state file, `terraform import` should update the state file with the current values from the cloud. Even if it used the existing value for the backup policy ID in the source code, a reference requiring interpolation, it would still need to obtain that  value from the cloud and update it in the state file.

**Actual Result**
The `terraform plan` command still showed that backup policy ID was being changed from it's previous value to the new value that had been changed both in the resource in the cloud as well as in the terraform code.

**Comment by kilokahn** [comment]
@scotmoor this looks like a genuine problem with the import functionality for block volumes that define backup policy in creation and we are working on a fix for it.

**Comment by kilokahn** [comment]
@scotmoor a fix for this was released in v3.4.0 - can you please try it out and let us know?

**Comment by kilokahn** [comment]
Please let us know if this doesn't work. Thanks!
