### ISSUE TITLE
error when cloning a volume of a larger size than the source volume

### ISSUE THREAD

**Issue by kilokahn** [terraform-providers/terraform-provider-oci#591]
### Terraform Version

Terraform v0.11.7

### OCI Provider Version

2.2.3

### Description:
When a volume of size larger than the source volume is specified, we get an error like:
```
* oci_core_volume.t: Service error:InvalidParameter. Requested new volume size created from this source volume must be equal to 51200.. http status code: 400. Opc request id: 3a1855482bfad7fc4e4aee06f9806c1b/B96BC7C94B78983E265509260D8DC86C/FC7A2803D1A23F31E5932B960EBA4931
```

### Terraform Plan

[clone_larger_vol_error.zip](https://github.com/oracle/terraform-provider-oci/files/2368991/clone_larger_vol_error.zip)

**Comment by ravitandonrt** [comment]
The block storage team has been notified about this failure, and are working on its fix. There is no known ETA at this moment, but we will update this issue as soon as we know more.

**Comment by kilokahn** [comment]
The block storage team has fixed the underlying issue and limited resizing to sizes defined in https://docs.cloud.oracle.com/iaas/Content/knownissues.htm#volResize
