### ISSUE TITLE
 Service error:InvalidParameter. Invalid format for ssh public key. http status code: 400. 

### ISSUE THREAD

**Issue by kemila-codegen** [terraform-providers/terraform-provider-oci#604]
Can someone help on below error I am getting?

When we give plain text value of ssh key, its working fine.  
But it is not working when give the path of the key where exist. Please check commented lines those are the ways that I tried. 

variable "ssh_public_key" {
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4Og9GpSYbH6Pn5GdbObcprAwvFLJRHEt8uy6rtQjQH/apWggCjRHr3L0dN3VVeCmZhJMP3Io2/BOpg0cHgZtWyLPlCeQTP4x5yOa3PAS0FLw9ck3SKM/t1OXEn/LzXBQDRD2dh9j2w10aBBs9/ngb1V62lDz9+LNYn3bcoH4V9DZbk9kRnfMzxTW5nqGZMwy/CVgpeFGZbZ7obXBqhHMTPpzFYv503KYPmbKDdWlisncaGrG1limNyrZxE71C9Qa4c22wZMZTMiS2JshbDprTXRP1Ha+5PENGOdo/Pd8TWhqqUm6+EGCKZUOFbY4eBtg+eEKrIOIM7saQ+Nw2wDrtw== oracle"
  #default = "./userdata/public.pem"
  #default = "./userdata/web-instance-public.ppk"
  #default = "./userdata/ssh-key.pub"
  #default = "cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub"
  #default = "$(cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub)"

}

export TF_VAR_ssh_public_key= $(cat /f/~DEMO-Migration~/terraform/TEST/userdata/ssh-key.pub)

**Comment by stephenpearson** [comment]
Try `"${file("${var.ssh_key_path}")}"` instead?
