### ISSUE TITLE
v3.1.0 load balancer issue illegal compositeId

### ISSUE THREAD

**Issue by RiaanRossouw** [terraform-providers/terraform-provider-oci#612]
### Terraform Version

<details>
$ terraform -v
Terraform v0.11.8
+ provider.oci v3.1.0
</details>

### Description:
After upgrade from v2.2.0 to v3.1.0 see this issue "illegal compositeId" with private load balancers.

### Terraform Plan
$ tf plan
{...}
Error: Error refreshing state: 1 error(s) occurred:
* oci_load_balancer_backend_set.lb-dr01-bes-ebs_8000: 1 error(s) occurred:
* oci_load_balancer_backend_set.lb-dr01-bes-ebs_8000: oci_load_balancer_backend_set.lb-dr01-bes-ebs_8000: illegal compositeId lb-dr01-bes-ebs_8000 encountered

**Comment by RiaanRossouw** [comment]
[lb.tf.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2406225/lb.tf.txt)

**Comment by alexng-canuck** [comment]
@RiaanRossouw we understand the issue and are working on a fix for this.

**Comment by alexng-canuck** [comment]
@RiaanRossouw in the meantime, you can avoid this issue by specifying a previous version in your provider config like this:

```
provider oci {
  ...
   version = "3.0.0"
}
```

**Comment by RiaanRossouw** [comment]
Thx Alex strapping to 3.0.0 works.

**Comment by alexng-canuck** [comment]
@RiaanRossouw , we just released v3.1.1 which fixes this issue. Can you give it a try and let us know?

Just make sure to set your `version` to pick up this release and run `terraform init --upgrade`.

**Comment by RiaanRossouw** [comment]
Looks good thanks.
$ tf -version
Terraform v0.11.8
+ provider.oci v3.1.1

$ tf plan
{...}
------------------------------------------------------------------------
No changes. Infrastructure is up-to-date.
