### ISSUE TITLE
Invalid code example in documentation

### ISSUE THREAD

**Issue by nitishch** [terraform-providers/terraform-provider-oci#615]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
Terraform v0.11.8
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
 provider.oci v3.1.1
</details>

### Description:
The second code sample in https://www.terraform.io/docs/providers/oci/guides/filters.html is the following:

```
data "oci_core_instances" "r1" {
  ...
  filter {
    name = "source_details.source_type"
    value = ["image"]
  }
}

data "oci_core_instances" "r2" {
  ...
  filter {
    name = "defined_tags.Operations.CostCenter"
    value = ["42"]
  }
}
```

In this, the arguments to filter blocks must be `values` - not `value`.

**Comment by alexng-canuck** [comment]
Thanks @nitishch for reporting this. We will fix this.

**Comment by alexng-canuck** [comment]
@nitishch This has now been fixed.
