### ISSUE TITLE
Problem on OCI with Terraform Creating Db System

### ISSUE THREAD

**Issue by cpruvost** [terraform-providers/terraform-provider-oci#617]
### Terraform Version
Terraform v0.11.7
+ provider.oci v2.2.3

### OCI Provider Version
PS C:\Users\chris\AppData\Roaming\terraform.d\plugins> .\terraform-provider-oci_v2.2.3.exe
2018/09/27 16:58:19 [INFO] terraform-provider-oci 2.2.3

### Description:
I built the network parts (VCN and Co) and the Db --> OK

But when running terraform plan again it wants to update the SSH key 
again....if terraform apply then it updates the key and after a new 
plan it wants to update the key again...???

Terraform will perform the following actions:

   ~ oci_database_db_system.TFDBNode
       ssh_public_keys.0: "ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAAAgQCZ3cFQHNWxqyYOXs1E/vwL30B17EIMy72/2IAfts
sMsCx6olRS2sZIlKwKDCAfAo/gokH2ruvlXTu2UDpabGV1CQgu9ehRnV/seFPLhs/rvSn5
r/NMqGtIjO7yY8/jEhG0n+I/4PiU5otU1YIU41f/vOAH7cwaT/y95LmOCvlZRQ==

RSA-1024" => "ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAAAgQCZ3cFQHNWxqyYOXs1E/vwL30B17EIMy72/2IAfts
sMsCx6olRS2sZIlKwKDCAfAo/gokH2ruvlXTu2UDpabGV1CQgu9ehRnV/seFPLhs/rvSn5
r/NMqGtIjO7yY8/jEhG0n+I/4PiU5otU1YIU41f/vOAH7cwaT/y95LmOCvlZRQ==

RSA-1024\n"

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by codycushing** [comment]
Hi, remove the newline from the end of your key and this should stop occurring--the service strips this character causing an apparent diff if it exists in your plan files.

**Comment by cpruvost** [comment]
I did it but the same result

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ oci_database_db_system.TFDBNode
      ssh_public_keys.0: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCZ3cFQHNWxqyYOXs1E/vwL30B17EIMy72/2IAftssMsCx6olRS2sZIlKwKDCAfAo/gokH2ruvlXTu2UDpabGV1CQgu9ehRnV/seFPLhs/rvSn5r/NMqGtIjO7yY8/jEhG0n+I/4PiU5otU1YIU41f/vOAH7cwaT/y95LmOCvlZRQ== RSA-1024" => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCZ3cFQHNWxqyYOXs1E/vwL30B17EIMy72/2IAftssMsCx6olRS2sZIlKwKDCAfAo/gokH2ruvlXTu2UDpabGV1CQgu9ehRnV/seFPLhs/rvSn5r/NMqGtIjO7yY8/jEhG0n+I/4PiU5otU1YIU41f/vOAH7cwaT/y95LmOCvlZRQ== RSA-1024\n"


Plan: 0 to add, 1 to change, 0 to destroy.


My key is only on one line like that : 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCZ3cFQHNWxqyYOXs1E/vwL30B17EIMy72/2IAftssMsCx6olRS2sZIlKwKDCAfAo/gokH2ruvlXTu2UDpabGV1CQgu9ehRnV/seFPLhs/rvSn5r/NMqGtIjO7yY8/jEhG0n+I/4PiU5otU1YIU41f/vOAH7cwaT/y95LmOCvlZRQ== RSA-1024

**Comment by codycushing** [comment]
Can you remove the `\n` at the end of `== RSA-1024\n`

**Comment by cpruvost** [comment]
it seems to be ok this morning...the \n was printed only by terraform plan and I have no \n in the key file ...strange..ty for all
