### ISSUE TITLE
multiple PDBs in a CDB

### ISSUE THREAD

**Issue by sudhakarjrk** [terraform-providers/terraform-provider-oci#621]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

Terraform v0.11.8
+ provider.oci v2.2.4

### Description:
How can we create multiple PDBs 

### Terraform Plan

<details>
Is there a way to increase  db_home.#  and  db_home.0.database.# values to more than 1.
when I am trying to give more than one db_home value I am getting below issue

db_home.0.database: attribute supports 1 item maximum, config has 2 declared

      db_home.#:                                "1"
      db_home.0.database.#:                     "1"

</details>

**Comment by kilokahn** [comment]
@sudhakarjrk thanks for reporting this. Currently, the `db_home` is a subresource of the `db_system` and the attribute only supports one item. There is no resource to separately represent the `db_home` to associate to the `db_system`. I will check with the team if there is any workaround.

**Comment by sudhakarjrk** [comment]
Thanks for the update  @kilokahn
Appreciate if you can share some workaround for creating multiple PDBs in a CDB.

**Comment by kilokahn** [comment]
As mentioned in https://www.terraform.io/docs/providers/oci/r/database_db_system.html you can use the [dbacli](https://docs.cloud.oracle.com/iaas/Content/Database/References/dbacli.htm) to create additional databases.

Relevant snip:
>The DB System will include a command line interface (CLI) that you can use to create additional databases and manage existing databases. For more information, see the Oracle Database CLI Reference

**Comment by sudhakarjrk** [comment]
Ok, I will try to work on this alternative and see if it works.
thank you.

**Comment by kilokahn** [comment]
@sudhakarjrk - does this work for you?

**Comment by kilokahn** [comment]
Let us know if you need any other information here. Thank you!

**Comment by mukkadinesh64** [comment]
any update on creating multiple PDB's and multiple databases?
