### ISSUE TITLE
net/http: TLS handshake timeout 

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-oci#626]
### Terraform Version

<details>
$ terraform -v
Terraform v0.11.8
+ provider.oci v3.3.0
</details>

### OCI Provider Version

<details>
.terraform/plugins/darwin_amd64/terraform-provider-oci_v3.3.0_x4
2018/10/11 10:46:22 [INFO] terraform-provider-oci 3.3.0
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
</details>

### Description:
Download the OCI Terraform examples
Source the TF vars
Add v3 in examples\compute\instance\providers.tf like this:
provider "oci" {
  version              = ">= 3.0.0"
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  region               = "${var.region}"
  disable_auto_retries = "true"
}
Run terraform init
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domains.ADs: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.oci_identity_availability_domains.ADs: 1 error(s) occurred:

* data.oci_identity_availability_domains.ADs: data.oci_identity_availability_domains.ADs: Get https://identity.eu-frankfurt-1.oraclecloud.com/20160918/availabilityDomains?compartmentId=ocid1.tenancy.oc1..aaaaaaaaqzjxp7mwrv7zu3krwuwy2zahxe3l2i4hqouopiq7rzqljpj3voua: net/http: TLS handshake timeout

<details>
also in an attached plan an output of TF_LOG=DEBUG OCI_GO_SDK_DEBUG=1 terraform plan
[output.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2467873/output.txt
</details>

**Comment by ravitandonrt** [comment]
@Forgotbkru Are you still facing this issue? The TLS handshake timeout usually occurs due to proxy issues or a proxy configuration issue in your environment. You may also want to check if your are running behind a VPN.

```
export http_proxy=http://www.your-proxy.com:80/
export https_proxy=http://www.your-proxy.com:80/
export no_proxy='*.oraclecloud.com,containerengine.eu-frankfurt-1.oraclecloud.com'
```

The OCI terraform provider does support http_proxy, https_proxy and no_proxy variables where you can define your inclusion or exclusion lists assuming it is a local machine problem.

Upon going through your [output.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2467873/output.txt) file, I see that before this call even the call to Hashicorp website failed with Client timeout errors:
```
2018/10/11 10:56:34 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=ba227796-3a11-cd21-03cf-87aebe52fd3d&version=0.11.8: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

From the same terminal does curl to other https endpoints resolve properly?

**Comment by Forgotbkru** [comment]
Unfortunatly setting proxy environment variebles didn't help. 
Still got "net/http: TLS handshake timeout" 

Also the curl request to checkpoint-api.hashicorp.com works well.

```
$ curl https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=ba227796-3a11-cd21-03cf-87aebe52fd3d&version=0.11.8

{"product":"terraform","current_version":"0.11.8","current_release":1534374840,"current_download_url":"https://releases.hashicorp.com/terraform/0.11.8/","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v0.11.8/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}

```
And to eu-frankfurt-1.oraclecloud.com also. 
I use bash script from https://docs.cloud.oracle.com/iaas/Content/API/Concepts/signingrequests.htm#Bash

See it [oci-curl.sh.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2478210/oci-curl.sh.txt)

```
./oci-curl.sh

[ {
  "id" : "ocid1.availabilitydomain.oc1..aaaaaaaaa2artt5wizbqvwl3rgptylx2l7jqbnyv4dygcfvlrd3dphvi3mdq",
  "compartmentId" : "ocid1.tenancy.oc1..aaaaaaaaqzjxp7mwrv7zu3krwuwy2zahxe3l2i4hqouopiq7rzqljpj3voua",
  "name" : "MIZF:EU-FRANKFURT-1-AD-1"
}, {
  "id" : "ocid1.availabilitydomain.oc1..aaaaaaaalcdcbl7u6akbmkojxhrozpj2v7yavqqydkj3ytyjbt47lnoqnm2q",
  "compartmentId" : "ocid1.tenancy.oc1..aaaaaaaaqzjxp7mwrv7zu3krwuwy2zahxe3l2i4hqouopiq7rzqljpj3voua",
  "name" : "MIZF:EU-FRANKFURT-1-AD-2"
}, {
  "id" : "ocid1.availabilitydomain.oc1..aaaaaaaaiifj24st3w4j7cowuo3pmqcuqwjapjv435vtjmgh5j7q3flguwna",
  "compartmentId" : "ocid1.tenancy.oc1..aaaaaaaaqzjxp7mwrv7zu3krwuwy2zahxe3l2i4hqouopiq7rzqljpj3voua",
  "name" : "MIZF:EU-FRANKFURT-1-AD-3"
} ]
```

**Comment by afedorch** [comment]
@Forgotbkru are you using a passphrase for your private key? could you, please, try without it?

**Comment by Forgotbkru** [comment]
@afedorch 
Definitely not.  I don't use a passphrase. 
Simple configuration using only default values.

**Comment by Forgotbkru** [comment]
Any update? 
Still facing this issue.

**Comment by bowfeng** [comment]
@Forgotbkru can you remove disable_auto_retries = "true" in oci provider and try it again?

**Comment by Forgotbkru** [comment]
No.
Unfortunately it wasn't helped. 
Both values ( disable_auto_retries = "true" |  disable_auto_retries = "false") end up with same result:
"net/http: TLS handshake timeout".

**Comment by atzimler** [comment]
Hi,

Today, I've run into the same issue. Terraform was working previously on my Mac and now it is not. The command `terraform init` fails with `net/http: TLS handshake timeout`. Interestingly, the from a Ubuntu running in a Parallels VM on my Mac, the command completes correctly.

**Comment by alexng-canuck** [comment]
@atzimler The `terraform init` command belongs to the core Terraform github repository and is not part of the OCI provider. 

Have you tried seeking help from core Terraform team at https://github.com/hashicorp/terraform/issues?

**Comment by alfemy** [comment]
I found the strange solution. I checked that another one user at my Mac is able do terraform init. It means that problem is located in my profile.  Finally I've found solution. It is really strange but I deleted all certificates in my login keychain. And now I'm able to use terraform init

**Comment by zehicle** [comment]
> I deleted all certificates in my login keychain

Confirmed this solution works for Mac users, but without deleting ALL certificates.  Remove expired / self-generated certificatates.  More details: https://support.apple.com/guide/keychain-access/delete-a-keychain-kyca2423/mac

**Comment by c240amg** [comment]
Confirmed that worked for me also.
