### ISSUE TITLE
resource oci_identity_tag doesn't support import

### ISSUE THREAD

**Issue by sbussetti** [terraform-providers/terraform-provider-oci#628]
### Terraform Version

<details>
Terraform v0.11.8
</details>

### OCI Provider Version

<details>
2018/10/16 11:49:33 [INFO] terraform-provider-oci 3.4.0
</details>

### Description:
imports appear to not have been implemented for all resources. For instance, using the 3.4.0 provider plugin trying to import an oci_identity_tag, I get:

```
Error: module.all_tags.module.compute_tags.oci_identity_tag.tag[2] (import id: ocid1.tagdefinition.oc1..<redacted>): import module.all_tags.compute_tags.oci_identity_tag.tag (id: ocid1.tagdefinition.oc1..<redacted>): resource oci_identity_tag doesn't support import
```

### Terraform Plan

<details>
No plan as this is an issue with import command.  i.e.

```
$ terraform import module.all_tags.module.compute_tags.oci_identity_tag.tag[13] ocid1.tagdefinition.oc1..aaaaaaaan7wnbhgrzydliy5socuhnxgpx2sqt524slgnuvzblk7vwfnha4ia
```

```
module.all_tags.module.compute_tags.oci_identity_tag.tag: Importing from ID "ocid1.tagdefinition.oc1..aaaaaaaan7wnbhgrzydliy5socuhnxgpx2sqt524slgnuvzblk7vwfnha4ia"...

Error: module.all_tags.module.compute_tags.oci_identity_tag.tag[13] (import id: ocid1.tagdefinition.oc1..aaaaaaaan7wnbhgrzydliy5socuhnxgpx2sqt524slgnuvzblk7vwfnha4ia): import module.all_tags.compute_tags.oci_identity_tag.tag (id: ocid1.tagdefinition.oc1..aaaaaaaan7wnbhgrzydliy5socuhnxgpx2sqt524slgnuvzblk7vwfnha4ia): resource oci_identity_tag doesn't support import
```
</details>

**Comment by hatvik** [comment]
Hi! @abhilash-av  Any ETA on this?

**Comment by abhilash-av** [comment]
Hello apologies we forgot to update the issue and close. The fix has been made and released. It is available since Terraform Provider V3.11.0(https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.11.0) but the latest release version is v3.13.0 which should also have the fix.

**Comment by hatvik** [comment]
Thanks @abhilash-av 

But I get error:
`terraform import oci_identity_tag.owner ocid1.tagdefinition.oc1..cut`

> oci_identity_tag.owner: Importing from ID "ocid1.tagdefinition.oc1..cut"...
> oci_identity_tag.owner: Import complete!
>   Imported oci_identity_tag (ID: ocid1.tagdefinition.oc1..cut)
> oci_identity_tag.owner: Refreshing state... (ID: ocid1.tagdefinition.oc1..cut)
> 
> Error: oci_identity_tag.owner (import id: ocid1.tagdefinition.oc1..cut): 1 error(s) occurred:
> 
> * import oci_identity_tag.owner result: ocid1.tagdefinition.oc1..cut: oci_identity_tag.owner: can not marshal to path in request for field TagNamespaceId. Due to can not marshal a nil pointer
>

**Comment by abhilash-av** [comment]
Hello could you please try importing using the following import format **tagNamespaces/{tagNamespaceId}/tags/{tagName}** (also mentioned in the release notes https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.11.0 for importing tag). Tags are imported differently than other resources because tags don’t have support for retrieval via ID.

**Comment by hatvik** [comment]
Ah, sorry for not seeing that. It works! Thank you

`terraform import oci_identity_tag.owner tagNamespaces/ocid1.tagnamespace.oc1..cut/tags/Owner`

**Comment by sbussetti** [comment]
just confirming this also works for me using 0.3.11.  thanks all
