### ISSUE TITLE
oci_database_db_system restore from existing backup restores CDB, not PDB

### ISSUE THREAD

**Issue by robert-schweighardt** [terraform-providers/terraform-provider-oci#631]
### Terraform Version

Terraform v0.11.7

### OCI Provider Version

provider.oci v2.1.15

### Description:
I created a backup via GUI for a DB System and then tried to restore it into a new DB SYstem 
All went through without error, the CDB was restored ok, 
but the PDB was not restored, but created fresh
For verification I restored the DB via GUI, that worked ok including PDB content
More details can be found in Oracle Support Service Request SR 3-18544289931

### Terraform Plan

variable "CPUCoreCount" { default = "1" }
variable "DBEdition" { default = "STANDARD_EDITION" }
variable "DBAdminPassword" { default = "mypassword" }
variable "DBName1" { default = "TESTCDB" }
variable "CharacterSet" { default = "AL32UTF8" }
##variable "CharacterSet" { default = "WE8MSWIN1252" }
##variable "NCharacterSet" { default = "AL16UTIA16" }
variable "NCharacterSet" { default = "UTF8" }
variable "DBWorkload" { default = "OLTP" }
variable "PDBName1" { default = "TESTPDB" }
variable "DBVersion" { default = "12.2.0.1" }
variable "DBDisplayName1" { default = "TESTPDB" }
variable "DBDiskRedundancy" { default = "HIGH" }
variable "DBNodeShape1" { default = "VM.Standard2.4" }
####old: variable "DBNodeShape1" { default = "VM.Standard2.1" }
variable "DBNodeDisplayName1" { default = "TEST_DB_SRV_1" }
variable "DBNodeDomainName" { default = "" }
variable "DBNodeHostName1" { default = "testdbsrv1" }
variable "DataStorageSizeInGB1" { default = "256" }
variable "DataStorageSizeInGB2" { default = "256" }
variable "DataStorageSizeInGB3" { default = "256" }
variable "LicenseModel" { default = "LICENSE_INCLUDED" }
variable "NodeCount" { default = "1" }

resource "oci_database_db_system" "TEST_DB_SRV_1" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.test_db_ad.availability_domains[0],"name")}"
  compartment_id = "${var.compartment_ocid_test_db}"
##  cpu_core_count = "${var.CPUCoreCount}"
  database_edition = "${var.DBEdition}"
  db_home {
    database {
      "admin_password" = "${var.DBAdminPassword}"
## restore from old 2.1er shape
      "backup_id" = "ocid1.dbbackup.oc1.eu-frankfurt-1.OCIDfromBACKUP"
      "backup_tde_password" = "${var.DBAdminPassword}"
##
      "db_name" = "${var.DBName1}"
      "character_set" = "${var.CharacterSet}"
      "ncharacter_set" = "${var.NCharacterSet}"
      "db_workload" = "${var.DBWorkload}"
      "pdb_name" = "${var.PDBName1}"
    }
    db_version = "${var.DBVersion}"
    display_name = "${var.DBDisplayName1}"
  }
  disk_redundancy = "${var.DBDiskRedundancy}"
  shape = "${var.DBNodeShape1}"
  subnet_id = "${oci_core_subnet.test_db_net_1_a.id}"
  ssh_public_keys = ["${var.mytest_ssh_public_key}"]
  display_name = "${var.DBNodeDisplayName1}"
##  domain = "${var.DBNodeDomainName}"
  domain = "net1a.testdb.oraclevcn.com"
  hostname = "${var.DBNodeHostName1}"
  data_storage_percentage = "40"
  data_storage_size_in_gb = "${var.DataStorageSizeInGB1}"
  license_model = "${var.LicenseModel}"
  node_count = "${var.NodeCount}"
}

**Comment by robert-schweighardt** [comment]
I got info from a colleague, that it had worked ok with same parameter set in version 
Terraform v0.11.1
+ provider.oci v2.1.13

**Comment by afedorch** [comment]
could you try to reproduce it with the latest provider (it is v3.5.0 now)?

please enable logs: https://github.com/terraform-providers/terraform-provider-oci#troubleshooting-the-provider

**Comment by ravitandonrt** [comment]
@robert-schweighardt This issue is more than 3 months old now, are you still facing this problem? Can you try with a newer provider version (v3.14) and let us know.

Please re-open with details and enabling logs as suggested in https://github.com/terraform-providers/terraform-provider-oci#troubleshooting-the-provider

```
export TF_LOG=DEBUG
export OCI_GO_SDK_DEBUG=v
```
