### ISSUE TITLE
Default to Root Compartment

### ISSUE THREAD

**Issue by benofben** [terraform-providers/terraform-provider-oci#632]
It would be really nice if TF_VAR_compartment_ocid defaulted to the root compartment if not specified.

**Comment by afedorch** [comment]
Thank you for sharing this idea. The requested behavior will be inconsistent with other OCI tools (for an example CLI). It can be convenient for the users who want to use tenancy as a compartment not to specify the ocid again, but this change in behavior can create unexpected results to the existing users who just forgot to specify the compartment.
