### ISSUE TITLE
oci_core_nat_gateway does not update when removing block_traffic attribute

### ISSUE THREAD

**Issue by sanketdjain** [terraform-providers/terraform-provider-oci#633]
### Terraform Version

$ terraform -v

Terraform v0.11.8
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.oci v3.5.0
+ provider.template v1.0.0

### OCI Provider Version

    v3.4

### Description:
As per [documentation for NAT gateway](https://www.terraform.io/docs/providers/oci/d/core_nat_gateway.html), block_traffic is optional attribute with default of **false**.

```
block_traffic - Whether the NAT gateway blocks traffic through it.
The default is false. Example: true 
```

I created a NAT gateway resource as follows:
```
# NAT Gateway
resource "oci_core_nat_gateway" "ng_service" {
  compartment_id = "${oci_core_virtual_network.vcn1.compartment_id}"
  vcn_id = "${oci_core_virtual_network.vcn1.id}"
  display_name = "ng_service"
  block_traffic = "true"
}
```

The above NAT gateway resource is created to block traffic by default. 
Later, I wanted to enable the traffic through the NAT gateway, and I removed the **block_traffic** attribute. So I simply removed the **block_traffic** attribute, as follows:
```
# NAT Gateway
resource "oci_core_nat_gateway" "ng_service" {
  compartment_id = "${oci_core_virtual_network.vcn1.compartment_id}"
  vcn_id = "${oci_core_virtual_network.vcn1.id}"
  display_name = "ng_service"
}
```

However, the terraform plan does not show any update of NAT gateway resource to change the attribute **block_traffic** to "false".

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

oci_identity_compartment.comp_network: Refreshing state... (ID: ocid1.compartment.oc1..aaaaaaaa5gjl6vxj...nfpmvq7ypeu3bcqfrgvrizy55nbbedclkptc3q)
oci_core_virtual_network.vcn1: Refreshing state... (ID: ocid1.vcn.oc1.phx.aaaaaaaarxqoemtu6plp65yc72dbwi7uvpjvj3xgwjrihlrn675guehrb2jq)
oci_core_nat_gateway.ng_service: Refreshing state... (ID: ocid1.natgateway.oc1.phx.aaaaaaaaly7zmg...2z2kem46uug3dlzdztyeyvsnhkhv2zzdsyiuoq)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Terraform Plan

Terraform code and plan details above in description. The **Issue** is about the plan not showing any changes.

**Comment by alexng-canuck** [comment]
Separately had a chat with @sanketdjain about this, and we can close this.

**Comment by alexng-canuck** [comment]
@bowfeng FYI.

**Comment by alexng-canuck** [comment]
For more details of this behavior in Terraform, refer to https://github.com/hashicorp/terraform/issues/4501
