### ISSUE TITLE
Evaluate Count, etc in Plan

### ISSUE THREAD

**Issue by benofben** [terraform-providers/terraform-provider-oci#636]
It would be awesome if our provider evaluated things like counts and arithmetic in plan so you could see what it was going to do.  Ditto for checking if there are going to be AD issues (ie volume not in same AD as compute).

![image](https://user-images.githubusercontent.com/8282917/47760267-a8214280-dc70-11e8-9442-ccee6aaacff9.png)

**Comment by rcohenma** [comment]
Thanks for your request Ben,
Evaluating counts and arithmetic in plan is not something we can do in the provider. This is controlled by the terraform code. You could make a feature request in their project:
https://github.com/hashicorp/terraform/issues

AD checks are server side validations that are done by our services. We do not plan to mimic server side validations in our provider, given the challenges of keeping them in sync.
