### ISSUE TITLE
Subnet Forces Rebuild when DHCP Options are Changed

### ISSUE THREAD

**Issue by tjkervin** [terraform-providers/terraform-provider-oci#642]
### Terraform Version

<details>
Terraform v0.11.7

</details>

### OCI Provider Version

<details>
3.6
</details>

### Description:
Attempting to change the DHCP options on a Subnet forces a rebuild of the entire subnet through Terraform. In the console, I can go in and change the DHCP options associated with the subnet directly. 

### Terraform Plan
Omitted much of the plan as well as specific OCIDs. 

<details>
-/+ oci_core_subnet.MY_SUBNET (new resource required)
      id:                         "ocid1.subnet.oc1.iad.SUBNET_OCID" => <computed> (forces new resource)
....
 "ocid1.dhcpoptions.oc1.iad.OCID1" => "ocid1.dhcpoptions.oc1.iad.NEW_OCID" (forces new resource)

</details>

**Comment by abhilash-av** [comment]
Thank you for your request. We are working on it and it will be released soon.

**Comment by ravitandonrt** [comment]
The issue was addressed as part of v3.7.0 release and should be updatable.

https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.7.0
* Make route_table_id, dhcp_options_id in oci_core_subnet updatable
