### ISSUE TITLE
Support OCI Instance Pools

### ISSUE THREAD

**Issue by mayanklahiri** [terraform-providers/terraform-provider-oci#643]
### Terraform Version

<details>
Terraform v0.11.10
</details>

### OCI Provider Version

<details>
2018/11/08 00:29:25 [INFO] terraform-provider-oci 3.6.0
</details>

### Description:

(enhancement request)
There are no resource types for creating Instance Pools, even though the OCI API exists: [Creating an Instance Pool](https://docs.cloud.oracle.com/iaas/Content/Compute/Tasks/creatinginstancepool.htm)

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by abhilash-av** [comment]
Thank you for your request. We are working on it.

**Comment by dmitrypol** [comment]
+1

**Comment by codycushing** [comment]
Support for instance pools was added in the [v3.9.0 release](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.9.0).
