### ISSUE TITLE
Doc on installing the provider

### ISSUE THREAD

**Issue by mobjerkn** [terraform-providers/terraform-provider-oci#644]
### Terraform Version
Terraform v0.11.10
### OCI Provider Version

Trying to use the latest version from GitHub
https://github.com/terraform-providers/terraform-provider-oci/blob/master/README.md

### Description:
Verified that GO is working, then done:
 ###################################################
https://github.com/terraform-providers/terraform-provider-oci/blob/master/README.md
Clone repository to: $GOPATH/src/github.com/terraform-providers/terraform-provider-oci

$ mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
$ git clone git@github.com:terraform-providers/terraform-provider-oci
Enter the provider directory and build the provider

$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-oci
$ make build
######################################################

~/go/src/github.com/terraform-providers/terraform-provider-oci

terraform-provider-oci $make build
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./oci/core_virtual_circuit_test.go
./oci/helpers_objectstorage.go
./oci/load_balancer_backend_set_test.go
./oci/object_storage_object_lifecycle_policy_test.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1

Hope you can help me. Just to be clear I'm not trying to change anything on the provider I would just like to use it together with Terraform to access and manage OCI.
Cheers

**Comment by abhilash-av** [comment]
@mobjerkn 
Could you please try to build using go version 1.9.6

**Comment by mivankov** [comment]
I have the same problem as mobjerkn.  I'm using go version go1.11.2 linux/amd64

**Comment by codycushing** [comment]
> I'm not trying to change anything on the provider I would just like to use it together with Terraform to access and manage OCI.

Hello, you don't need to clone and compile at all, with an up to date version of the Terraform binary installed, from the directory containing your .tf configuration files, run `terraform init`. This will download the OCI Provider from the official registry.

To actually compile the binary, you can run `go install` and find the binary in your `$GOPATH/bin` location. Currently the `make build` command runs `go fmt` and `goimports` and fails if there are files that require formatting. Depending on your version of go or goimports, this might result in file formatting differences fail arbitrarily.
