### ISSUE TITLE
Support for emulated attachment in oci_core_volume_attachment

### ISSUE THREAD

**Issue by mosinuga** [terraform-providers/terraform-provider-oci#654]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.10

</details>

### OCI Provider Version
+ provider.oci v3.7.0
<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
To be able to add option "emulated" in the list of attachment_type
### Terraform Plan
resource "oci_core_volume_attachment" "volume-attach" {
    count = "${var.isvolumerequired == "true" ? 1 : 0}"
    attachment_type = "emulated"
    compartment_id = "${var.compartment_ocid}"
    instance_id = "${oci_core_instance.instance.id}"
    volume_id = "${oci_core_volume.volume.id}"
}
<details>
Error: module.ecml-as.oci_core_volume_attachment.volume-attach: expected attachment_type to be one of [iscsi paravirtualized], got emulated

Documentation states the following: attachment_type - (Required) The type of volume. The only supported value are "iscsi" and "paravirtualized".

When will emulated be added to the list as OCI now supports emulated.

</details>

**Comment by alexng-canuck** [comment]
Hi @mosinuga , thanks for the request.

At the moment, it appears AttachVolume API documentation does not yet support "emulated" type. https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/AttachVolumeDetails

We will relay this request and will keep you updated.

**Comment by mosinuga** [comment]
You’re right that only paravirtualised and iscsi are supported at the moment but OCI has introduced emulated in the last month.

Thanks a lot and best wishes,

Mobolaji

Sent from my handheld PC

On 27 Nov 2018, at 21:41, Alex Ng <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @mosinuga<https://github.com/mosinuga> , thanks for the request.

At the moment, it appears AttachVolume API documentation does not yet support "emulated" type. https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/AttachVolumeDetails

We will relay this request and will keep you updated.

**Comment by mosinuga** [comment]
So, hopefully the APIs will be updated  soon since it’s only been a recent addition.


On 27 Nov 2018, at 21:41, Alex Ng <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @mosinuga<https://github.com/mosinuga> , thanks for the request.

At the moment, it appears AttachVolume API documentation does not yet support "emulated" type. https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/AttachVolumeDetails

We will relay this request and will keep you updated.

**Comment by srishtipmishra** [comment]
This is supported in release 3.69.0 of Terraform Provider.

**Comment by srishtipmishra** [comment]
Marking this upstream as service team is working on it.

**Comment by mulpk** [comment]
fixed in release v3.70.0
