### ISSUE TITLE
instance shape VM.Standard1.1 is no longer available

### ISSUE THREAD

**Issue by pvaldria** [terraform-providers/terraform-provider-oci#659]
Seems like the below shape is no longer available.  We should update all examples to use the shape which are available.  

variable "instance_shape" {
  default = "VM.Standard1.1"
}

**Comment by alexng-canuck** [comment]
@pvaldria Thanks for the request. We are working on this.

**Comment by ravitandonrt** [comment]
@pvaldria This has been now addressed with v3.9.0 release. The examples now use `VM.Standard2.1` instead. Reference: https://github.com/terraform-providers/terraform-provider-oci/blob/master/docs/examples/compute/instance/variables.tf#L33
