### ISSUE TITLE
User-rate limit exceeded on while refreshing states

### ISSUE THREAD

**Issue by tjkervin** [terraform-providers/terraform-provider-oci#678]
### Terraform Version
Terraform v0.11.7

### OCI Provider Version
3.7.0

### Description:
When attempting to perform a terraform plan on an admittedly large number of resources, I hit the API rate limit while the plan refreshes the state, and my terraform plan fails. If I am lucky, it will work on the next run. My concern is if I keep building infrastructure out, I will run into a point where I won't be able to re-run by builds, as my code base has become too large. 

I could split up my states, so that each state tracks a smaller group of inventory, but other providers have solved this exact problem [by adding a configurable API retry](https://github.com/hashicorp/terraform/pull/1787) to their provider configuration.

I am wondering if we can do something similar here. 

### Terraform Plan

<details>

Error: Error refreshing state: 1 error(s) occurred:

* module.instance_name_1.data.oci_core_vnic.resource_Vnic_n2: 1 error(s) occurred::

* module.instance_name_1.data.oci_core_vnic.resource_Vnic_n2: data.oci_core_vnic.resource_Vnic_n2: Service error:TooManyRequests. User-rate limit exceeded.. http status code: 429. Opc request id: f1f727525fda6940c8c105ce7058e8c4/CAB13F834C66C4763C955BFA05E664F5/23D5EE262DE0B8B3A68144D777606E99

</details>

**Comment by kilokahn** [comment]
Thanks for reporting this @tjkervin. We are working on this, and we will share the details with you.

**Comment by alexng-canuck** [comment]
@tjkervin We plan to release an enhancement to allow configurable retry timeouts. The way you would set this is through a new field in the `provider oci` block like this:

```
provider oci {
    retry_timeout_seconds = "3600"
}
```

This would affect how long retries will continue in the face of 429 and 500 errors.

Would this address your concern?

**Comment by tjkervin** [comment]
This would indeed address the concern. Thank you.

**Comment by alexng-canuck** [comment]
@tjkervin With the latest release of Terraform OCI provider (v3.12.0); this should now be addressed.

If you want to read more about how to configure the retry time, you can refer to this guide:
https://www.terraform.io/docs/providers/oci/#configuring-automatic-retries

Let us know if you have any feedback on this.
