### ISSUE TITLE
VNIC OCID is an invalid entity type for route rule

### ISSUE THREAD

**Issue by matmacfarlane** [terraform-providers/terraform-provider-oci#681]
### Terraform Version

Terraform v0.11.8

### OCI Provider Version

+ provider.oci v3.9.0

### Description:
When attempting to create a route table with networkEntityId set to the OCID of a vnic, the Apply fails with the following error: 

"* oci_core_route_table.public_route_table: Service error:InvalidParameter. The requested networkEntityId ocid1.vnic.oc1.uk-london-1.abw...... is invalid: Invalid entity type in Id ocid1.vnic.oc1.uk-london-1.abw..."

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

resource "oci_core_route_table" "private_route_table" {
  compartment_id = "${oci_identity_compartment.common_services.id}"
  vcn_id         = "${oci_core_virtual_network.UKDOCRT1.id}"

route_rules = [{
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_nat_gateway.nat_gateway.id}"
  },
  {
    destination       = "172.192.0.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "ocid1.vnic.oc1.uk-london-1.abw......"
  },
]
}

**Comment by matmacfarlane** [comment]
Figured it out - the private IP specifically has a separate OCID to the VNIC itself and this must be used.

This could be clarified in the docs if possible.

**Comment by yojimbo1984** [comment]
@matmacfarlane Did you ever figure out this part;
"Is there any data resource which can export this private IP OCID as an attribute?"

I need to do exactly this.

**Comment by matmacfarlane** [comment]
Hey yojimbo, checking my commit history it seems we made the decision to use the IPSec connection service rather than VPN appliances on VMs on the 10th January 2019, so moved to DRG entries in the route tables instead. I had the ocids hardcoded before that so found nothing more elegant I'm afraid...

 {
    destination       = "172.19.150.0/24"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "ocid1.privateip.oc1.uk-london-1.abwgiljrocqfl5...."
  },

**Comment by yojimbo1984** [comment]
Thanks for the replyd.  I actually ran across something a few hours ago that seems to do the trick.  You can use the data source 'oci_core_private_ips', matching IP / subnet OCID / VNIC OCID and generate a list of private_ips, then "lookup" on the PrivateIp object to get the OCID.  Example;

data "oci_core_private_ips" "fw_lan_gw" {
  ip_address                     = "192.168.1.10"
  subnet_id                      = oci_core_subnet.fw_lan_subnet.id
}

Then under your route_table resource;

  route_rules {
    destination                  = "0.0.0.0/0"
    destination_type             = "CIDR_BLOCK"
    network_entity_id            = lookup(data.oci_core_private_ips.fw_lan_gw.private_ips[0],"id")

Just needs to be ordered accordingly so the data arguments are defined first.
