### ISSUE TITLE
Computed values in oci_core_instance metadata cause TF crash

### ISSUE THREAD

**Issue by wmcdermid** [terraform-providers/terraform-provider-oci#685]
### Terraform Version
Terraform v0.11.11

### OCI Provider Version
terraform-provider-oci 3.11.1

### Description:
After upgrading from 3.11.0 -> 3.11.1, terraform plan/apply causes Terraform to crash with the following error:

> Error: Error running plan: 1 error(s) occurred:
> * oci_core_instance.nat: 1 error(s) occurred:
> * oci_core_instance.nat: unexpected EOF

I have attached the crash.log as well:
[crash.log](https://github.com/terraform-providers/terraform-provider-oci/files/2742057/crash.log)

The sample code below is a bit contrived, greatly simplified from the original source, but serves to reproduce the issue. 

Seems as though the `metadata` attribute of `oci_compute_instance` no longer handles computed values if computing those values requires output attributes from another resource (not yet created). The level of indirection due to the use of `data` resources doesn't seem to matter; I was also able to reproduce the same crash when attempting to set a metadata value that depends on the `oci_core_subnet` resource directly (e.g. `oci_core_subnet.seed.time_created`). Ideally, either pattern would result in a "computed" value during plan.

FWIW, this does not seem to affect `extended_metadata`, so putting computed values there could be a viable workaround for now. The documentation recommends against this; if there is no need for nested metadata, then we're ["strongly advised to avoid"](https://www.terraform.io/docs/providers/oci/d/core_instance.html#extended_metadata) using this attribute.

### Terraform Plan

```
provider "oci" {
  version          = "3.11.1"
  tenancy_ocid     = "<redacted>"
  user_ocid        = "<redacted>"
  fingerprint      = "<redacted>"
  private_key_path = "<redacted>"
  region           = "us-ashburn-1"
}

locals {
  availability_domain = "HUYg:US-ASHBURN-AD-3"
  compartment_ocid    = "<redacted>"
  nat_offset          = "4"
}

# Network
resource "oci_core_vcn" "test_vcn" {
  compartment_id = "${local.compartment_ocid}"

  display_name = "test vcn"
  cidr_block   = "10.63.255.0/25"
}

resource "oci_core_internet_gateway" "ig" {
  compartment_id = "${local.compartment_ocid}"
  vcn_id         = "${oci_core_vcn.test_vcn.id}"
  display_name   = "Internet gateway"
}

resource "oci_core_subnet" "seed" {
  vcn_id              = "${oci_core_vcn.test_vcn.id}"
  compartment_id      = "${local.compartment_ocid}"
  availability_domain = "${local.availability_domain}"
  display_name        = "Seed"

  cidr_block = "${cidrsubnet(oci_core_vcn.test_vcn.cidr_block, 1, 0)}"

  prohibit_public_ip_on_vnic = "true"
}

# Compute
variable "services" {
  type = "list"
  default = [
    {
      name = "test1"
      outside_ip = "10.60.24.24"
    },
    {
      name = "test2"
      outside_ip = "10.60.24.48"
    }
  ]
}

data "null_data_source" "nat_entries" {
  count = "${length(var.services)}"

  inputs {
    name       = "${lookup(var.services[count.index], "name")}"
    inside_ip  = "${cidrhost(oci_core_subnet.seed.cidr_block, local.nat_offset + 1 + count.index)}"
    outside_ip = "${lookup(var.services[count.index], "outside_ip")}"
  }
}

resource "oci_core_instance" "nat" {
  compartment_id      = "${local.compartment_ocid}"
  availability_domain = "${local.availability_domain}"
  display_name        = "nat001"

  shape = "VM.Standard2.2"

  create_vnic_details {
    subnet_id              = "${oci_core_subnet.seed.id}"
    private_ip             = "${cidrhost(oci_core_subnet.seed.cidr_block, local.nat_offset)}"
    assign_public_ip       = "false"
    skip_source_dest_check = "true"
  }

  metadata {
    should_observe_dependency = "${jsonencode(data.null_data_source.nat_entries.*.outputs)}"
    this_should_also = "${oci_core_subnet.seed.time_created}"
  }
}
```

**Comment by codycushing** [comment]
Thank you for the report and logs, we will investigate and get a fix out as soon as possible.

**Comment by wmcdermid** [comment]
No longer seems to be issue under version 3.11.2 of the provider.

Thanks so much for the quick fix!

**Comment by ravitandonrt** [comment]
@wmcdermid We have put the original instance metadata customdiff back into the provider again but to address the TF crash have also made a minor fix in vendored Terraform SDK as well (as Hashicorp is going to address it after v12 release), please let us know your feedback: https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.13.0
