### ISSUE TITLE
Importing resources from OCI

### ISSUE THREAD

**Issue by PeterJamesHarrison** [terraform-providers/terraform-provider-oci#70]
Is importing all resources supported? 
e.g. https://www.terraform.io/docs/import/usage.html

Has the importer function been implemented?  If so, for what resources?
https://www.terraform.io/docs/plugins/provider.html#resources
https://www.terraform.io/docs/import/importability.html

**Comment by mikejihbe** [comment]
Not yet, but it'll be in our next batch of changes (after this upcoming release)

**Comment by mrhearn** [comment]
v1.0.16
Importing a compute instance (with an assigned subnet) succeeds.  However, checking the contents of the statefile I see the supporting entries do not include the subnet_id.   Is this a bug or expected behavior?

**Comment by kilokahn** [comment]
@mrhearn We have recently overhauled the importability of resources and imports of instance should work. When inspecting the state file, did you notice the absence of the subnet_id in the instance state? It would be helpful if you can share the logs and the corresponding state file to take this forward.

**Comment by kilokahn** [comment]
@sbussetti - can you please file a separate ticket to track and fix the importability of tags? As of now, it had been explicitly excluded because at that time, the service had a bug that affected this functionality.

**Comment by sbussetti** [comment]
@kilokahn https://github.com/terraform-providers/terraform-provider-oci/issues/628

**Comment by ravitandonrt** [comment]
I am closing this old issue. Most if not all, resources are supported for import in OCI Terraform Provider now and each doc has a section at bottom that provides the help text on how to use it.

Simple ID cases:
https://www.terraform.io/docs/providers/oci/r/core_instance.html

Complex ID cases:
https://www.terraform.io/docs/providers/oci/r/kms_key.html

The previously reported #628 issues was also resolved and closed.
