### ISSUE TITLE
Docs for oci_identity_tag_namespace has a 404 link

### ISSUE THREAD

**Issue by cpoczatek** [terraform-providers/terraform-provider-oci#705]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

NA
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

NA
</details>

### Description:
Broken link in this sentence:  
```
It does not have to be unique, and you can change it with
[UpdateTagNamespace](https://docs.cloud.oracle.com/iaas/api/#/en/tagging/20170101/TagNamespace/UpdateTagNamespace).
```

In this [doc file](terraform-provider-oci/website/docs/r/identity_tag_namespace.html.markdown).

### Terraform Plan

<details>
NA
</details>

**Comment by ravitandonrt** [comment]
Thanks for reporting @cpoczatek 

The link seems to point to a newer API Version - will investigate.

The current working link is: https://docs.cloud.oracle.com/iaas/api/#/en/identity/20160918/TagNamespace/UpdateTagNamespace

**Comment by bowfeng** [comment]
close it since it has been fixed.
