### ISSUE TITLE
getting this error while running terraform apply :* oci_core_virtual_network.simple-vcn: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401.

### ISSUE THREAD

**Issue by kishlay5373** [terraform-providers/terraform-provider-oci#706]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by ravitandonrt** [comment]
@kishlay5373 The issue you have filed has inadequate information and does not conform to the bug template, please add more details.

Looking at the error, it looks like a configuration issue on your end. The NotAuthenticated error would occur if you have not setup your API Key correctly.

Please follow this documentation to setup your configuration and additionally for Terraform specify the provider block with all the values

https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm

As a side note, try to use a private key without password.

**Comment by rcohenma** [comment]
closing as there has not been a response from the reporter for some time.
