### ISSUE TITLE
while creating security list getting this error.

### ISSUE THREAD

**Issue by kishlay5373** [terraform-providers/terraform-provider-oci#714]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
I am trying to create a security list and below is the code i am using in the .tf file.

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}

resource "oci_core_security_list" "ExampleSecurityList" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "ocid1.vcn.oc1.eu-frankfurt-1.aaaaaaaawvhvvi5qwolqvfh7a77j2vvstlgtmwcsbrstqzdhjfzv5jh3erjq" 
  display_name   = "TFExampleSecurityList"

  // allow outbound tcp traffic on all ports
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "6"
  }

  // allow outbound udp traffic on a port range
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "17"        // udp
    stateless   = true

    udp_options {
      // These values correspond to the destination port range.
      "min" = 319
      "max" = 320
    }
  }

  // allow inbound ssh traffic from a specific port
  ingress_security_rules {
    protocol  = "6"         // tcp
    source    = "0.0.0.0/0"
    stateless = false
	
    tcp_options {
      source_port_range {
        "min" = 100
        "max" = 100
      }

      // These values correspond to the destination port range.
      "min" = 22
      "max" = 22
    }
  }

  // allow inbound icmp traffic of a specific type
  ingress_security_rules {
    protocol  = 1
    source    = "0.0.0.0/0"
    stateless = true

    icmp_options {
      "type" = 3
      "code" = 4
    }
  }
}

protocol  = "6"         // tcp
    source    = "0.0.0.0/0"
    stateless = false

    tcp_options {
      

      // These values correspond to the destination port range.
      "min" = 3389
      "max" = 3389
	  }

**Comment by kishlay5373** [comment]
[opc@tf-instance lab2]$ terraform init

Error: Unknown root level key: protocol



Error: Unknown root level key: source



Error: Unknown root level key: stateless



Error: Unknown root level key: tcp_options


[opc@tf-instance lab2]$

**Comment by kishlay5373** [comment]
![1](https://user-images.githubusercontent.com/47242864/53096637-9e845900-3545-11e9-8735-b7296f17eb0f.PNG)

**Comment by rcohenma** [comment]
The last section of your tf config is not valid

The following needs to be within a `ingress_security_rules` or a `egress_security_rules` block

```
protocol = "6" // tcp
source = "0.0.0.0/0"
stateless = false

tcp_options {
  

  // These values correspond to the destination port range.
  "min" = 3389
  "max" = 3389
  }
```

**Comment by rcohenma** [comment]
That part is also outside of the `resource "oci_core_security_list" "ExampleSecurityList" {` block
