### ISSUE TITLE
Add support for WAF

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#717]
### Terraform Version

<details>
0.11.10
</details>

### OCI Provider Version

<details>
N/A
</details>

### Description:
OCI just released the Web Application Firewall as a service. It would be great if WAF policies, rules and other features can be managed from the Terraform OCI provider

**Comment by alexng-canuck** [comment]
Hi @hyder ,

Thanks for the request. WAF is on our support roadmap and will be coming out in a future release. We will let you know here when it is released.

Thanks,
Alex

**Comment by kilokahn** [comment]
@hyder - this is was released in v3.20.0 of the provider https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md#3200-march-27-2019
