### ISSUE TITLE
Plugin code structure does not follow common conventions

### ISSUE THREAD

**Issue by geoffmorrison** [terraform-providers/terraform-provider-oci#723]
### Terraform Version

<details>
Terraform v0.11.11
</details>

### OCI Provider Version

<details>
3.17.0
</details>

### Description:
The code in the OCI provider does not follow conventions that are common to nearly every other TF provider. In particular:
- The OCI provider uses `package provider` instead of `package oci`
- The OCI provider does not provide a no-args `Provider` function (`Provider` takes a `ConfigureFunc` to facilitate mocking)

Neither of these has any functional impact, but they do break assumptions from other tools. For example, https://github.com/VladRassokhin/intellij-hcl assumes this package and constructor structure to generate code completion information.

Please consider adjusting the plugin code to conform to these conventions.

I am happy to contribute patches if there is consensus that this is a worthwhile change. In particular, I don't know if changing the package name will have any complications.

**Comment by codycushing** [comment]
Hello, `oci` was the recommended package name for us to use by HashiCorp. Accepting a `ConfigureFunc` is a fully sanctioned concept and central to the provider architecture. Possibly the `intellij-hcl` component could take a pull request to accommodate these patterns with more flexibility.

**Comment by geoffmorrison** [comment]
Are you planning to change the package name to `oci`? The directory (and so import path) is `oci`, but the package directive still says `package provider`.

I'm not sure about being sanctioned, but of the 100 providers under github.com/terraform-providers, only `terraform-provider-oci` does not provide a `func Provider() terraform.ResourceProvider`. As far as I can tell, `Provider` only accepts a `ConfigureFunc` in the OCI provider so tests can supply an alternate implementation -- the `ConfigureFunc` is always `ProviderConfig` outside of tests.

It might be possible to update `intellij-hcl` to the OCI-specific `Provider` signature. This is probably not the only tool that attempts to dynamically inspect providers, though, so there may be value in following the convention set by the other providers.

**Comment by codycushing** [comment]
Hello, we do have a ticket for aligning the package name with the folder structure. We'll evaluate if the provider instantiation code path is needlessly parameterized.

**Comment by e1nh4nd3r** [comment]
👍 Voting for this enhancement.  Several internal stakeholders at Oracle are interested in seeing this enhancement so that plugins that do code completion start working as intended.

**Comment by sajeevnambidi** [comment]
This enhancement required. +1 vote

**Comment by afedorch** [comment]
the package and Provider function were updated as part of the changes for the v3.51.0 release.  thanks!
