### ISSUE TITLE
Add a data source to retrieve available K8s versions for container engine

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#726]
### Terraform Version

<details>

$ terraform -v
0.11.13
</details>

### OCI Provider Version
<details>
3.16
</details>

### Description:
Currently, we need to manually specify the Kubernetes version we want to deploy for Container Engine. The only way to find available versions is to look into the OCI Console, start the creation of a cluster and see which versions are available. 

It would be nice if there is a data source that can provide this information, or at least provide the latest version.

### Terraform Plan

<details>
N/A
</details>

**Comment by brandonbell** [comment]
Does oci_containerengine_cluster_option not provide you with what you need?

https://www.terraform.io/docs/providers/oci/d/containerengine_cluster_option.html#kubernetes_versions

**Comment by hyder** [comment]
Ah sorry. I didn't notice this. My apologies. I'll close the issue
