### ISSUE TITLE
Enhancement Request: add an attribute "ids" to all non-singular data sources to return flat list of objects' OCIDs

### ISSUE THREAD

**Issue by olkoko** [terraform-providers/terraform-provider-oci#732]
Would it be possible to add an attribute "ids" to ALL normal (non-singular) data sources which will return flat list of just OCIDs of objects' returned by this data source?

In example below we are trying to get a flat list (not a list of maps) of compartments' IDs:

```
data oci_identity_compartments this  {
  compartment_id = "${var.tenancy_ocid}"
}

output "compartment_ocids" {
  value = "${data.oci_identity_compartments.this.compartments.*.id}",
}

```

This code does not work in Terraform 0.11.x (which does not allow to splat operations over data source with nested attributes) producing the error:

```
...
Error: Error applying plan:
1 error(s) occurred:
* output.compartments_ocids: Resource 'data.oci_identity_compartments.this' does not have attribute 'compartments.*.id' for variable ' data.oci_identity_compartments.this.compartments.*.id'
...
```

The proposed functionality would allow to generate a list of OCIDs by using simple interpolation like "${data.oci_identity_compartments.this.ids}".

**Comment by kilokahn** [comment]
@olkoko thanks for reporting this! So this will be purely to workaround the 0.11.x behavior, right? Since 0.12 is around the corner (don't know the exact date), maybe we may just want to wait for it? I will leave this ticket open and see if other customers who can't move to 0.12 may also need it and then pick it up as an enhancement.

**Comment by codycushing** [comment]
Hello, you can employ this approach to get a flat list of ids out of plural data sources:
```
data "oci_identity_compartments" "compartments1" {
  compartment_id = "${var.tenancy_ocid}"
}

data "template_file" "compartment_ids" {
  count = "${length(data.oci_identity_compartments.compartments1.compartments)}"
  template = "${lookup(data.oci_identity_compartments.compartments1.compartments[count.index], "id")}"
}

output "compartments" {
  value = "${data.template_file.compartment_ids.*.rendered}"
}
```

**Comment by olkoko** [comment]
@codycushing thank you for your suggestion. 

I'm aware of this workaround. It does work but makes the code more difficult to read and troubleshoot. I was looking for something more simpler and elegant.

Most of the Terraform providers out there get around of this "pre-0.12" problem by using "plural" data sources to generate the flat lists of ids/keys that uniquely identify resources, and "singular" data sources to get the rest of attributes of given resource by resource id/key.

Obviously with Terraform 0.12 this will not be an issue, but until then I guess would need to fall back to the workaround you described.

Thanks again.

**Comment by codycushing** [comment]
Since v12 is right around the corner and there is an acceptable workaround, it's safe to conclude we wont add this functionality.
