### ISSUE TITLE
looking for multiple ad data sources example

### ISSUE THREAD

**Issue by beide** [terraform-providers/terraform-provider-oci#733]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by beide** [comment]
I am trying to use regional subnet and multiple ad data sources on top of the example of autoscaling. do you have an example of multiple ads for the placement? Thanks a lot!

**Comment by kilokahn** [comment]
hey @beide - let me check with the autoscaling folks for this one.

**Comment by beide** [comment]
Here is what I did to support multiple AD for a quick test under "TFInstancePool"

placement_configurations {
    availability_domain = "AHKQ:US-ASHBURN-AD-3"
    #availability_domain="${data.oci_identity_availability_domain.AD.name}"
    primary_subnet_id   = "${oci_core_subnet.ExampleSubnet.id}"
  }

   placement_configurations {
    availability_domain = "AHKQ:US-ASHBURN-AD-1"
    #availability_domain="${data.oci_identity_availability_domain.AD.name}"
    primary_subnet_id   = "${oci_core_subnet.ExampleSubnet.id}"
  }

   placement_configurations {
    availability_domain = "AHKQ:US-ASHBURN-AD-2"
    #availability_domain="${data.oci_identity_availability_domain.AD.name}"
    primary_subnet_id   = "${oci_core_subnet.ExampleSubnet.id}"
  }

**Comment by kilokahn** [comment]
For regional subnets, you'd still need to provide each AD in the `placement_configurations`. As an example:

```
data "oci_identity_availability_domain" "ad1" {
  compartment_id = "${var.tenancy_ocid}"
  ad_number      = 1
}

data "oci_identity_availability_domain" "ad2" {
  compartment_id = "${var.tenancy_ocid}"
  ad_number      = 2
}


resource "oci_core_instance_pool" "TFInstancePool" {
  compartment_id            = "${var.compartment_ocid}"
  instance_configuration_id = "${oci_core_instance_configuration.TFInstanceConfiguration.id}"
  size                      = 2
  state                     = "RUNNING"
  display_name              = "TFInstancePool"

  placement_configurations {
    availability_domain = "${data.oci_identity_availability_domain.ad1.name}"
    primary_subnet_id   = "${oci_core_subnet.ExampleRegionalSubnet.id}"
  }
  placement_configurations {
    availability_domain = "${data.oci_identity_availability_domain.ad2.name}"
    primary_subnet_id   = "${oci_core_subnet.ExampleRegionalSubnet.id}"
  }
}
```

An explicit note about this should appear on http://docs.cloud.oracle.com in the future

**Comment by kilokahn** [comment]
@beide  didn't see your update before I made mine. Did you have any other questions?

**Comment by beide** [comment]
Thanks a lot. We are good for now.
