### ISSUE TITLE
Question: Support for Terraform 0.12-beta1

### ISSUE THREAD

**Issue by olkoko** [terraform-providers/terraform-provider-oci#734]
Are you planning to release version of OCI Terraform provider with support of Terraform 0.12-beta1, or you are going to wait until the official release?

**Comment by alexng-canuck** [comment]
Hi @olkoko ,

As you may have noticed, HashiCorp has not officially released 0.12 compatible providers at this time yet and is relying on beta testers to pickup preview builds.

We do plan to release a 0.12 compatible Terraform OCI provider but are waiting on a stable release version of the v0.12 plugin SDKs from HashiCorp. This should be happening before the official v0.12 release.

**Comment by alexng-canuck** [comment]
@olkoko in the meantime, an early development version of the v0.12-compatible OCI provider is here:
http://terraform-0.12.0-dev-snapshots.s3-website-us-west-2.amazonaws.com/terraform-provider-oci/3.15.1-dev20190216H00-dev/

This should be usable with 0.12 beta.

**Comment by alexng-canuck** [comment]
I'm closing this issue. Let me know if you have further questions.
