### ISSUE TITLE
oci_database_backup - error out "timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 15m0s)"

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#737]
### Terraform Version

<details>
./terraform -version
Terraform v0.11.13
+ provider.external v1.0.0
+ provider.oci v3.17.0
# Run this command to get the terraform version:

$ terraform -v

</details>
./terraform -version
Terraform v0.11.13
+ provider.external v1.0.0
+ provider.oci v3.17.0
### OCI Provider Version

<details>
./terraform -version
Terraform v0.11.13
+ provider.external v1.0.0
+ provider.oci v3.17.0
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

</details>

### Description:
Include a description with repro steps, expected result and actual result

oci_database_backup resource creation is errored out but OCI GUI shows that backup is in progress. 
* module.database-instance.oci_database_backup.tf_database_iad-EXTERNALNONPROD-20190325182430-28283: 1 error(s) occurred:

* oci_database_backup.tf_database_iad-EXTERNALNONPROD-20190325182430-28283: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 15m0s)

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

The point is that we need to increase timeout for oci_database_backup because the db size is 256 smallest and it is the 1st full backup.

Jerry

**Comment by kshinkr** [comment]
I should be flexible ad DBaaS took 1 hour 42 mins without timeout, so may be same amount of timeout needed. Some time later OCI GUI shows that backup has been completed and status is 'ACTIVE'.

We need to avoid this timeout for oci_database_backup creation otherwise big DB will fail every time.

Jerry

**Comment by kilokahn** [comment]
hey @kshinkr - have you tried setting the `timeout` for the `oci_database_backup` resource to a higher value? 

```hcl
resource "oci_database_backup" "test_backup" {
    #Required
    database_id = "${oci_database_database.test_database.id}"
    display_name = "${var.backup_display_name}"

    timeouts {
      create = "120m"
    }
}
```

See https://www.terraform.io/docs/configuration/resources.html#operation-timeouts for more information on timeouts.

**Comment by kshinkr** [comment]
Great!!, Let me give it a try.
Jerry

**Comment by kilokahn** [comment]
Feel free to re-open if you have any other problems.

**Comment by ravvitta** [comment]
@kilokahn 
resource "oci_database_backup" "test_backup" {
   #Required
   database_id = "${oci_database_database.test_database.id}"
   display_name = "${var.backup_display_name}"

   timeouts {
     create = "120m"
   }
}
I see that we can find the OCID using this :- database_id = "${oci_database_database.test_database.id}"
But does that mean test_backup database has to be created for resource "oci_database_backup" to find the OCID?

**Comment by kilokahn** [comment]
@ravvitta confirmed that his question was answered. In general, please open up a new issue rather than tagging on an existing unrelated closed one so that we are able to answer your questions in a timely manner. Thanks.
