### ISSUE TITLE
Out-of-date Provider Config Documentation

### ISSUE THREAD

**Issue by StuporHero** [terraform-providers/terraform-provider-oci#738]
### Description:
The documentation for the provider config does not reflect the full extent and behavior of the options that are valid in the provider config. I discovered this while setting Terraform Enterprise up because I thought I was out of luck because I was unable to get a `private_key_file` into a run until I found an issue in this repository that made reference to a `private_key` option which worked for me.

**Comment by codycushing** [comment]
Hello StuporHero, is there a reason you can't use the recommended `private_key_path` field mentioned in the official docs here: https://www.terraform.io/docs/providers/oci/ The `private_key` field is mostly used for testing. We are aware of two other doc deficiencies: the previous link does not mention the `private_key_password` field, when you key was forged with a password. Nor do they mention some compatibility with the CLI/SDK's means of supplying configuration data: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliconfigure.htm

Are there any other setup details you found lacking in either the terraform.io docs or the project's readme?

**Comment by StuporHero** [comment]
@codycushing As I mentioned, I'm using Terraform Enterprise, and I cannot see a secure way to place a file in the environment that doesn't involve me putting it in the git repository. Even if it is password protected, I consider that to be less secure than using a secure variable to pass the value in.

**Comment by kilokahn** [comment]
@StuporHero we will look to update our documentation for it.

**Comment by StuporHero** [comment]
@kilokahn Thanks! When I create tickets like this, my goal is simply to make the team aware of a deficiency so it gets on their radar. Schedule it as you please. I already got past my problem.

**Comment by alexng-canuck** [comment]
@mbfrahry , FYI.

**Comment by parrneet** [comment]
Documentation has been updated.
