### ISSUE TITLE
Unable to upgrade the OKE Cluster to supported version without change in name

### ISSUE THREAD

**Issue by kilokahn** [terraform-providers/terraform-provider-oci#740]
### Terraform Version

Terraform v0.11.7

### OCI Provider Version

2019/03/27 11:10:29 [INFO] terraform-provider-oci 3.19.0

### Description:

Create an `oci_containerengine_cluster`. Attempt to update the kubernetes version alone in the tf config. We will get an error like:
```
oci_containerengine_cluster.test_cluster: Service error:InvalidParameter. The name must be different than the existing name.. http status code: 400. Opc request id: fdc37b5c66b018f8bc9601e51f7a2d97/EB0B3937EAA04E56A4F51DB073ECA8F8/6C18FEED79A74BF5952D6CB1764E56A0
```

Now attempt to change the name of the cluster as well (say add a prefix). The update will go through fine.

**Comment by kilokahn** [comment]
We are following up with the service team on fixing the behavior. For now, and ugly workaround is to also temporarily change the name along with the version, and then change it back again.

**Comment by abhilash-av** [comment]
Service has fixed the behavior. Please verify. Closing the ticket for now.
