### ISSUE TITLE
Support to create additional databases with Exadata

### ISSUE THREAD

**Issue by svilmune** [terraform-providers/terraform-provider-oci#741]
### Terraform Version

All

### OCI Provider Version

All
### Description:

Currently you can create Exadata resource using oci_database_db_system but after creation you can't create additional databases in Exadata using OCI provider but have to revert to console or to Exadata dbaasapi. This is not convenient in the long run to break deployment into different tools.

Only creation of the initial database is possible at this point in time.

**Comment by kilokahn** [comment]
hey @svilmune - can you pleas confirm if this is similar to #621 ? If yes, we have a solution that we are going to roll out soon to support it.

**Comment by svilmune** [comment]
> hey @svilmune - can you pleas confirm if this is similar to #621 ? If yes, we have a solution that we are going to roll out soon to support it.

It's similar if I understood it correctly. With Exadata you have multiple db_homes under db_system. So when creating a new database from console or using dbaasapi it will always create new home which is not shared.

**Comment by kilokahn** [comment]
Thanks for confirming. We are likely to roll this out for the release on
04/03. We will update this ticket when we have done that.

**Comment by mukkadinesh64** [comment]
is there any update on creating multiple databases and PDB's using terraform?

**Comment by svilmune** [comment]
I see 3.21.0 is out now with additional support for multiple db_homes/databases in BM systems. @kilokahn is there any example how this is used and do we expect that it works also on Exadata?

**Comment by afedorch** [comment]
The issue was added as part of the v3.21.0 release. Please, give it a try. Thank you.
All current db_system examples are available at: https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/database/db_systems
