### ISSUE TITLE
terraform import fails with nil pointer on bucket import

### ISSUE THREAD

**Issue by mayanklahiri** [terraform-providers/terraform-provider-oci#743]
### Terraform Version

<details>
v0.11.13
</details>

### OCI Provider Version

<details>
3.20.0
</details>

### Description:

Attempting to import an existing bucket with a remote http backend. Expected import to work. Instead, getting a nil pointer exception.

This is the output:

```
module.ssm_terraform_buckets.oci_objectstorage_bucket.ssm_data_enc_secret: Importing from ID "ocid1.bucket.oc1.phx.xxxxxx"...
module.ssm_terraform_buckets.oci_objectstorage_bucket.ssm_data_enc_secret: Import complete!
  Imported oci_objectstorage_bucket (ID: ocid1.bucket.oc1.phx.xxxxx)
module.ssm_terraform_buckets.oci_objectstorage_bucket.ssm_data_enc_secret: Refreshing state... (ID: ocid1.bucket.oc1.phx.xxxxxxxx)

Error: module.ssm_terraform_buckets.oci_objectstorage_bucket.ssm_data_enc_secret (import id: ocid1.bucket.oc1.phx.xxxxx): 1 error(s) occurred:

* import module.ssm_terraform_buckets.oci_objectstorage_bucket.ssm_data_enc_secret result: ocid1.bucket.oc1.phx.xxxxxxxxxa: oci_objectstorage_bucket.ssm_data_enc_secret: can not marshal to path in request for field NamespaceName. Due to can not marshal a nil pointer
```

### Terraform Plan

<details>
n/a 
</details>

**Comment by parrneet** [comment]
Hey @mayanklahiri - Looks like you are using the bucket ocid for `id` in the import command. Please refer to the import section of the docs- https://www.terraform.io/docs/providers/oci/r/object_storage_bucket.html for the correct id format.

**Comment by kilokahn** [comment]
@mayanklahiri - i am curious on how you got the `ocid1.bucket.oc1.phx.xxxxx` ocid. Can you please share your terraform command invocation and the config associated with it. Bucket resource was not importable before this release and it doesn't have an ocid associated with it as such.

**Comment by mayanklahiri** [comment]
@parrneet Thanks, you're right. Changing to the namespace/bucket identifier fixed it. 
@kilokahn The bucket was created manually I believe, or its state file was lost somehow. All buckets have OCIDs, so importability doesn't affect that.
