### ISSUE TITLE
Instance Pooling creation hung up on creation with defined tags being used 

### ISSUE THREAD

**Issue by jauyzed** [terraform-providers/terraform-provider-oci#746]
### Terraform Version

$ terraform -v

   Terraform v0.11.13
    provider.oci v3.21.0

</details>

### Description:
Instance Pooling creation hung up on creation. Instance configuration is created from a image. We have defined tags for all resources and emphasize on using defined tags. 
I tried creating a pool from the same instance config in the web console, but the process is stuck on scaling. We are well within tenancy service limits also.  Is there a way to see the output and errors of a resource creation in OCI? 

### Terraform Code
main.tf renamed [main.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3045490/main.txt)

### Terraform Plan
[terraform_plan.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3045513/terraform_plan.txt)

### Terraform Apply
[terraform_apply_output.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3045525/terraform_apply_output.txt)

#### Other thoughts: 
Looking through governance I notice the username is computemanagement. 

![Screen Shot 2019-04-04 at 3 20 49 PM](https://user-images.githubusercontent.com/18094384/55589372-4cf6ee80-56ed-11e9-98b6-fe102738e031.png)

**Comment by afedorch** [comment]
Thanks for reporting the problem!

To get the most verbose information from TF provider side you need to turn on debug logs.
```
To get verbose console output when the provider is running, precede your Terraform command with the `TF_LOG` and `OCI_GO_SDK_DEBUG` flags:
TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan
```
However, I am not sure that it could help for this case. You can consider the Instance configuration resource as a template for the instances in the Instance Pool resource. If creating an Instance pool stucks on scaling for both console and TF the problem could be in the Instance configuration resource. I was able to reproduce this for the simplified configuration, could you try to remove `metadata` attribute for the `launch_details` in the Instance configuration?

**Comment by jauyzed** [comment]
@afedorch The instance configuration gets created successfully. 

As suggested I removed the metadata attribute completely in the TF. But still no improvements so far. 

Ran `TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform apply` 

I have attached the output from terraform apply with debug on as above

[terraform apply_out.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3048948/terraform.apply_out.txt)

In the output file at line 49, 
` DEBUG 2019/04/05 10:54:40.357193 http.go:903: RawResponse does not contain presentIn tag. Skipping
2019-04-05T10:54:40.358-0600 [DEBUG] plugin.terraform-provider-oci_v3.21.0_x4: DEBUG 2019/04/05 10:54:40.357207 http.go:800: Unmarshaling from body to field: InstancePool`

It is hung up at this process and repeats over and over. I am thinking it might not be related to metadata tag in TF.  

Let me know if you need anything more or suggest something else to proceed

**Comment by afedorch** [comment]
@jauyzed thanks for trying it!

The scenario you have reported hits a few problems on the service side:
- instance pool defined tags checks failure
- instance configuration metadata validation 

There is nothing that we can change on TF provider side for this request, but we will keep the issue open until corresponding problems will be resolved. Thank you!

**Comment by afedorch** [comment]
@jauyzed 
You can try to workaround the problem for now:

```
Log into the console for the target tenancy
From the left hand pane go to Identity → Policies 
Click on create Policy button
Add the policy statements below for the correct environment in the root compartment:


DEFINE tenancy compute_management AS ocid1.tenancy.oc1..xxxxx
ADMIT any-user OF tenancy compute_management to use tag-namespace in tenancy
ADMIT any-user OF tenancy compute_management to use tagdefinitions in tenancy

you need to specify target tenancy where the pools will be launching instances
```

**Comment by jauyzed** [comment]
@afedorch Thanks for the suggestion! 

We have defined policies and groups in the tenancy in a standardized manner esp in prd tenancy. Since, we are testing this in dev tenancy to get this working, I will test out your suggestion.

**Comment by alexng-canuck** [comment]
Hi @jauyzed ,

Just following up to see if the workaround provided by @afedorch unblocks your use case.

Thanks,
Alex

**Comment by jauyzed** [comment]
@alexng-canuck The workaround didn't help much. It is the same error status as described above "Scaling"

**Comment by alexng-canuck** [comment]
@jauyzed Can you also try adding some extra policies and see if this works?

```
ALLOW any-user to manage tag-namespace in tenancy
ALLOW any-user to manage tagdefinitions in tenancy
```

**Comment by ravitandonrt** [comment]
@jauyzed - I will be closing this issue today. The service teams have acknowledged both the problems and will be fixing it in future:
1. InstanceConfigs not validating ssh_authorized_keys
2. Instance Pool defined tags check

The compute service team has suggested the following work-around similar to what @alexng-canuck mentioned above.

```
DEFINE tenancy compute_management AS <your-tenancy-id>
ADMIT any-user OF tenancy compute_management to use tag-namespace in tenancy
ADMIT any-user OF tenancy compute_management to use tagdefinitions in tenancy
```

You may reopen the issue if the problem persists despite these policies.
