### ISSUE TITLE
Question: How to get Kubernetes configuration to configure helm provider without kubeconfig ?

### ISSUE THREAD

**Issue by pchalamet** [terraform-providers/terraform-provider-oci#749]
### Terraform Version
Terraform v0.11.13
+ provider.helm v0.9.0
+ provider.kubernetes v1.5.2

### OCI Provider Version

2019/04/08 09:49:34 [INFO] terraform-provider-oci 3.21.0
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
</details>

### Description:
Using `oci_containerengine_cluster` it's easy to create a cluster. Also using `oci_containerengine_cluster_kube_config`, kubeconfig can be fetchedstored to a file using `local_file`. Unfortunately this breaks graph dependencies when injecting configuration into `helm` provider.

A correct way to do this would be to get hands on required data to initialize correctly the `helm` provider from kubernetes resource:
* host
* client_certificate
* cluster_ca_certificate
* client_key

Unfortunately, `oci_containerengine_cluster_kube_config` does not expose much but kubeconfig content.

Is there a way to get all those data without persisting a kubeconfig on disk ?
Thanks.

**Comment by afedorch** [comment]
@pchalamet 
It could be great if you can add more details to the request for us to understand the problem: the example of the current configuration could help. From the description, it looks like you should be able to force any "helm" resources to depend on any kube_config resources. Have you tried to use depends_on for this?
https://learn.hashicorp.com/terraform/getting-started/dependencies.html#implicit-and-explicit-dependencies

**Comment by pchalamet** [comment]
Yes sure.

Module to deal with Kubernetes cluster creation (details omitted for brevity):
````
resource "oci_containerengine_cluster" "kube" {
  compartment_id     = "${var.compartment_ocid}"
  ....
}

data "oci_containerengine_cluster_kube_config" "kube_config" {
	cluster_id = "${oci_containerengine_cluster.kube.id}"
}

resource "local_file" "kubeconfig" {
	content = "${data.oci_containerengine_cluster_kube_config.kube_config.content}"
	filename = ".kube/config"
}
````

And in another module to create apps:
````
provider "helm" {
    kubernetes {
        config_path = "./kube/config"
    }
}

resource "helm_release" "mariadb" {
   ....
}
````

This does work if we break the deployment in 2 workflows (and copying kubeconfig to 2nd) - but it's not great in term of dependencies. Instead of relying on kubeconfig (which could generate noise on CI), we'd like to statically initialize Helm provider using following parameters (and not relying on explicit dependencies):
`````
provider "helm" {
    kubernetes {
        load_config_file = false
        host = "${oci_containerengine_cluster.kube.endpoints.0.kubernetes}"
        client_certificate = "????"
        cluster_ca_certificate = "????"
        client_key = "????"
    }
}
````
But in order to do this, we have to get some information from the freshly created Kubernetes cluster. I'm asking this because Digital Ocean are exposing the information:
````
client_certificate     = "${base64decode(digitalocean_kubernetes_cluster.foo.kube_config.0.client_certificate)}"
client_key             = "${base64decode(digitalocean_kubernetes_cluster.foo.kube_config.0.client_key)}"
cluster_ca_certificate = "${base64decode(digitalocean_kubernetes_cluster.foo.kube_config.0.cluster_ca_certificate)}"
````

So maybe the oci provider does expose information - but I fail to find it. 
Is there any way to get aforementioned information using oci provider ?

**Comment by jhorwit2** [comment]
@pchalamet OKE doesn't rely on client tls to communicate with the clusters for end users. The kubeconfig that is returned contains the CA, cluster url and token. You'd need to extract the token out of the kubeconfig file and set it explicitly when instantiating the helm/kubernetes providers. 

For right now your best option is to load the kubeconfig file from disk to the providers via the local_file. Additionally, you can request as many kubeconfigs as you want for your user/cluster, so you could have 

```
data "oci_containerengine_cluster_kube_config" "kube_config" {
	cluster_id = "${oci_containerengine_cluster.kube.id}"
}

resource "local_file" "kubeconfig" {
	content = "${data.oci_containerengine_cluster_kube_config.kube_config.content}"
	filename = ".kube/config"
}
```

In each terraform module to avoid copy/paste/coupling.

**Comment by abhilash-av** [comment]
Thank you for your response. I have conveyed the same to our service team and will update you once service team provides an update.

**Comment by pchalamet** [comment]
OK - we will use explicit dependencies (using depends_on) on `local_file` - it's a bit ugly but will do the trick. Thanks all for your help.

**Comment by abdel1979** [comment]
just change : 

provider "helm" {
    kubernetes {
        config_path = "./kube/config"
    }
}

by 

provider "helm" {
  kubernetes {
 config_path  = "${local_file.kubeconfig.filename}"
}
  }

**Comment by piotr-zasuwa-sollers-eu** [comment]
> OK - we will use explicit dependencies (using depends_on) on `local_file` - it's a bit ugly but will do the trick. Thanks all for your help.

Could you elaborate with details? I'm looking for workaround but nothing works
