### ISSUE TITLE
oci_containerengine_cluster.TestOKECluster: Service error:InvalidParameter. Invalid kubernetes version

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#755]
### Terraform Version

Terraform v0.11.13
+ provider.external v1.1.0
+ provider.oci v3.19.0

### OCI Provider Version

+ provider.oci v3.19.0

### Description:

Terraform OCI oke cluster creation fails with following error. Where can I find OKE version and worker image compatibility matrix?

Getting following error suspect oke version and worker image not compatible.

* oci_containerengine_node_pool.TestOKECluster: Service error:InvalidParameter. Invalid kubernetes version.. http status code: 400. Opc request id: 
* module.oke-cluster.oci_containerengine_cluster.TestOKECluster: 1 error(s) occurred:

 * oci_containerengine_cluster.TestOKECluster: Service error:InvalidParameter. Invalid kubernetes version.. http status code: 400. Opc request id: 
### Terraform Plan

* oci_containerengine_node_pool.TestOKECluster: Service error:InvalidParameter. Invalid kubernetes version.. http status code: 400. Opc request id: 
* module.oke-cluster.oci_containerengine_cluster.TestOKECluster: 1 error(s) occurred:

 * oci_containerengine_cluster.TestOKECluster: Service error:InvalidParameter. Invalid kubernetes version.. http status code: 400. Opc request id: 

Thank you.

**Comment by alexng-canuck** [comment]
Hi @wggit 

This document might be helpful. Have you checked whether the Kubernetes versions that you're using are following these constraints?

https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengupgradeoverview.htm

**Comment by wggit** [comment]
Thank you alexng-canuck.  Yes followed that document.
I tried v1.12.6 for both Kubernetes cluster and worker node but that failed.

I suspect issue is with Kubernetes and image you select for worker node. 
Tried some combinations and some how it worked for "v1.10.11" and Oracle-Linux-7.6-2018.12.19-0.

**Comment by parrneet** [comment]
Hi @wggit 

Please refer to https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengaboutupgradingclusters.htm for the supported versions.
According to this doc, if you are using v1.10.11, an upgrade is needed. Please check with the valid version and let us know if the issue still persists.

**Comment by alapidas** [comment]
@wggit 

As you have discovered, v1.10.11 is available as an option in the API, but it will be removed soon.  As @parrneet pointed out, only 1.11 and 1.12 are currently supported today.  Remember that you can always use the node pool option data source to discover the currently supported versions (they updated periodically - https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/containerengine_node_pool_option_data_source.go)

**Comment by wggit** [comment]
Thank you.
