### ISSUE TITLE
"unexpected EOF" when running Terraform plan

### ISSUE THREAD

**Issue by AONunan** [terraform-providers/terraform-provider-oci#759]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

```
Terraform v0.11.13
+ provider.oci v3.24.0
```

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

```
2019/04/30 15:51:54 [INFO] terraform-provider-oci 3.24.0
```
</details>

### Description:
Include a description with repro steps, expected result and actual result

First noticed this issue on 26/04/2019 when trying to run `terraform plan`

I have tried changing the OCI provider version to an older version, e.g. `version = "3.20.0"` but this did not fix the issue.

The issue also persists when I checkout an older version of my Terraform code, that passed the `terraform plan` a few days ago.

I think it might be an issue with the .tfstate file as the crash log continues to reference resources that I have removed from the .tf files (but they still exist in the .tfstate file).

[command line output.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3131922/command.line.output.txt)

[crash.log](https://github.com/terraform-providers/terraform-provider-oci/files/3131921/crash.log)

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.

</details>

**Comment by codycushing** [comment]
Hello, based on the error message and exact line number match, this appears to be a different symptom of an issue discovered yesterday #758. Can you please add your .tf files (sanitized of any sensitive info) so we can investigate further?

**Comment by AONunan** [comment]
Hi Cody. I have discovered the reason why Terraform was crashing.

A security list rule was manually added in the OCI web console (not created through Terraform). The rule was an ingress TCP rule but there was no TCP ports specified (i.e. TCP port range = ALL). While this rule existed, the `terraform plan` would crash. After I removed this rule in the OCI web console, the `terraform plan` succeeds.

Unfortunately by this point I had already lost a working version of my .tfstate file so had to `terraform import` all the live resources into a new .tfstate, but everything is working for me now again.

Thanks

**Comment by codycushing** [comment]
Thanks for following up, I have repro's this as well. We'll add error handling for this so it at least does not crash and ideally gives a good error message indicating the potential cause.

**Comment by codycushing** [comment]
This behavior will no longer result in a crash. However, you may or may not be able to resolve the inconsistencies between .tf file and statefile simply by putting the same values from the console into your .tf files. I have seen it succeed in some cases or result in a service error depending on the order in which you refresh and modify the values. Best option is to remove the offending entries from the Console and add them to your .tf
