### ISSUE TITLE
assign_public_ip not working as documented

### ISSUE THREAD

**Issue by StuporHero** [terraform-providers/terraform-provider-oci#760]
### Terraform Version

0.11.3

### OCI Provider Version

3.24

### Description:

Leaving out the `assign_public_ip` from the `create_vnic_details` block of an `oci_core_instance` resource appears to be defaulting to `true` instead of behaving in accordance with the rules of the assigned subnet as [documented](https://www.terraform.io/docs/providers/oci/r/core_instance.html#assign_public_ip) resulting in the following error when an instance so configured is assigned to a subnet with `prohibit_public_ip_on_vnic` set to `true`.

```
* oci_core_instance.middleware: Service error:InvalidParameter. Public IP addresses are prohibited in this subnet {ocid1.subnet.oc1.iad.aaa...}. http status code: 400. Opc request id: ...
```

Either the documentation needs to be modified to reflect the way the provider behaves, or the behavior of the provider needs to be modified to reflect the documentation.

### Terraform

It's actually impossible to provide a truly self-contained terraform file since you need to specify the details of your own OCI account, so I spent far more time than I should have prepping this one with variables for everything complete with sensible defaults. I even tested it to make sure it produces the error I described.

```hcl
variable "tenancy_ocid" { }
variable "user_ocid" { }
variable "fingerprint" { }
variable "private_key_path" { default = "~/.oci/oci_api_key.pem" }
variable "region" { default = "us-ashburn-1" }
variable "compartment_id" { }
variable "vcn_cidr_block" { default = "10.0.0.0/16" }
variable "subnet_cidr_block" { default = "10.0.1.0/24" }
variable "ad_list" { type = "list" }
variable "shape" { default = "VM.Standard2.1" }
variable "image" { default = "ocid1.image.oc1.iad.aaaaaaaao6dbj3hdyd6dcbgfl3crm6ksvd4xlp2gk547q5kgcarqnhpydhfa" }

provider "oci" {
  tenancy_ocid      = "${var.tenancy_ocid}"
  user_ocid         = "${var.user_ocid}"
  fingerprint       = "${var.fingerprint}"
  private_key_path  = "${var.private_key_path}"
  region            = "${var.region}"
}

resource "oci_core_vcn" "vcn" {
  compartment_id = "${var.compartment_id}"
  cidr_block     = "${var.vcn_cidr_block}"
}

resource "oci_core_subnet" "subnet" {
  compartment_id             = "${var.compartment_id}"
  vcn_id                     = "${oci_core_vcn.vcn.id}"
  cidr_block                 = "${var.subnet_cidr_block}"
  security_list_ids          = ["${oci_core_vcn.vcn.default_security_list_id}"]
  prohibit_public_ip_on_vnic = true
}

resource "oci_core_instance" "test" {
  availability_domain = "${var.ad_list[0]}"
  compartment_id      = "${var.compartment_id}"
  shape               = "${var.shape}"
  
  create_vnic_details {
    subnet_id = "${oci_core_subnet.subnet.id}"
  }
  
  source_details {
    source_id   = "${var.image}"
    source_type = "image"
  }  
}
```

**Comment by codycushing** [comment]
Thanks for the meticulous write-up. This does [appear to be intentional](https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_instance_resource.go#L99). I'll see if this can function as described without the default, then test how it functions for users who have already set up configs without specifying a value here. Ideally we can make it function as described, otherwise we'll have to update the documentation.

**Comment by codycushing** [comment]
I have tested all the behaviors and the current (default to true) is best, I have updated the documentation to reflect this:
https://github.com/terraform-providers/terraform-provider-oci/commit/cef5183175b274e0a3b4ed2a32f68a9b48b3e9ae
