### ISSUE TITLE
Support for consistent device paths in oci_core_instance_configuration

### ISSUE THREAD

**Issue by bnestelroad** [terraform-providers/terraform-provider-oci#764]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v
0.11.13

</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
* provider.oci: version = "~> 3.22"

</details>

### Description:
According to the documentation for [oci_core_instance_configuration->instance_details->block_volumes->attach_details](https://www.terraform.io/docs/providers/oci/r/core_instance_configuration.html#attach_details) there is currently no support for [consistent device paths](https://docs.cloud.oracle.com/iaas/Content/Block/References/consistentdevicepaths.htm).  That functionality was added for oci_core_instance in #689.  Is there a plan to add this functionality for oci_core_instance_configuration?  Or is this already available and the documentation is not updated?

**Comment by ravitandonrt** [comment]
Thank you for reporting this issue @bnestelroad 

Upon doing the API review, it looks like the property is only available in instance but is rather achieved through the block volume attachment resource.

The instance configurations API (https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/InstanceConfiguration/) does not return this property and even in the case of instances this is just a `computed` (generated) field based on how the block volume was attached: using `device_name` attribute of `oci_core_volume_attachment` as indicated in #689 

We will pass this feedback to the compute service team, but as the APIs currently stand neither Instance or Instance Configurations have this attribute in their CREATE or UPDATE operations, only instance supports this property in the GET operation based on how the volume was attached. 

You will likely need to list all the instances launched with said configuration to get this data.
