### ISSUE TITLE
invalid or unknown key: recovery_window_in_days for oci_database_db_home and oci_database_db_system

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#771]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

dhcp-10-187-25-214:db_system_stg1 jerryshin$ terraform version
Terraform v0.11.13
+ provider.oci v3.24.1

I am using example template for db_system creation and "terraform plan" is giving me an error like that.

Error: oci_database_db_home.hrit_stgdb2_home: database.0.db_backup_config.0: invalid or unknown key: recovery_window_in_days
====================================================================
Error: oci_database_db_system.hrit_stgdb2_system: db_home.0.database.0.db_backup_config.0: invalid or unknown key: recovery_window_in_days
====================================================================

resource "oci_database_db_home" "hrit_stgdb2_home" {
  db_system_id = "${oci_database_db_system.hrit_stgdb2_system.id}"

  database {
    admin_password = "${var.db_admin_password}"
    db_name        = "${var.db_home_db_name}"
    character_set  = "${var.character_set}"
    ncharacter_set = "${var.n_character_set}"
    db_workload    = "${var.db_workload}"
    pdb_name       = "${var.pdb_name}"

    freeform_tags = {
      "Department" = "hritpaas"
    }

    db_backup_config {
      auto_backup_enabled     = true
      recovery_window_in_days = 10
    }
  }

  db_version   = "${var.db_version}"
  display_name = "${var.db_home_display_name}"
}

**Comment by rcohenma** [comment]
Hello,
Thanks for reporting this.
It seems the example was updated before the release was complete.

Today's release introduced support for the recovery_window_in_days.

Please try with the latest version of the terraform provider:
https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.25.0
