### ISSUE TITLE
create multiple dataguard resources

### ISSUE THREAD

**Issue by damtst** [terraform-providers/terraform-provider-oci#774]
**Description:**

We are trying to create a set of primary and standby databases. the example attached is based on the dataguard dbsystem example.

can you please let me know how to loop and get all the dbsystem when they are still not being created?

** Versions **
Terraform v0.11.13
+ provider.oci v3.25.0

**Example 1**

`
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

variable "ssh_public_key" {}

provider "oci" {
  version           = ">=3.24"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "eu-frankfurt-1"
  alias = "eu-fra"
  disable_auto_retries = "true"

}  

data "oci_identity_availability_domain" "ad" {
  compartment_id = "${var.tenancy_ocid}"
  ad_number      = 1
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block     = "10.0.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "TFExampleVCN"
  dns_label      = "tfexamplevcn"
}

resource "oci_core_security_list" "test_security_list" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_virtual_network.vcn1.id}"
  display_name   = "TFExampleSecurityList"

  // allow outbound tcp traffic on all ports
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "6"
  }

  ingress_security_rules {
    protocol = "6"
    source   = "0.0.0.0/0"
  }
}

// An AD based subnet will supply an Availability Domain
resource "oci_core_subnet" "test_subnet" {
  availability_domain = "${data.oci_identity_availability_domain.ad.name}"
  cidr_block          = "10.0.2.0/24"
  display_name        = "TFADSubnet"
  dns_label           = "adsubnet"
  compartment_id      = "${var.compartment_ocid}"
  vcn_id              = "${oci_core_virtual_network.vcn1.id}"
  security_list_ids   = ["${oci_core_security_list.test_security_list.id}"]
  route_table_id      = "${oci_core_virtual_network.vcn1.default_route_table_id}"
  dhcp_options_id     = "${oci_core_virtual_network.vcn1.default_dhcp_options_id}"
}

resource "oci_database_db_system" "test_db_system" {
  count = "2"
  availability_domain     = "${oci_core_subnet.test_subnet.availability_domain}"
  compartment_id          = "${var.compartment_ocid}"
  subnet_id               = "${oci_core_subnet.test_subnet.id}"
  database_edition        = "ENTERPRISE_EDITION"
  disk_redundancy         = "NORMAL"
  shape                   = "VM.Standard2.1"
  ssh_public_keys         = ["${trimspace(file("${var.ssh_public_key}"))}"]
  domain                  = "${oci_core_subnet.test_subnet.subnet_domain_name}"
  hostname                = "${format("%s%02d","myOracleDB",count.index + 1)}"
  data_storage_size_in_gb = "256"
  license_model           = "LICENSE_INCLUDED"
  node_count              = "1"
  display_name            = "${format("%s%02d","TFExampleDbSystem",count.index + 1)}"

  db_home {
    db_version   = "12.1.0.2"
    display_name = "${format("%s%02d","TFExampleDbHome",count.index + 1)}"
    database {
      "admin_password" = "BEstrO0ng_#11"
      "db_name"        = "${format("db%02d","TFExampleDbHome",count.index + 1)}"
    }
  }
}

data "oci_database_db_systems" "test_db_systems" {
  compartment_id = "${var.compartment_ocid}"
}
data "oci_database_db_homes" "t" {
  count = "${length(data.oci_database_db_systems.test_db_systems.db_systems.*.id)}"
  compartment_id = "${var.compartment_ocid}"
  db_system_id   = "${oci_database_db_system.test_db_system.*.id}"
}

data "oci_database_databases" "db" {
  compartment_id = "${var.compartment_ocid}"
  db_home_id     = "${data.oci_database_db_homes.t.db_homes.*.db_home_id}"
}

resource "oci_database_data_guard_association" "test_data_guard_association" {
  count = "${length(flatten(data.oci_database_databases.db.databases.id))}"
  creation_type                    = "NewDbSystem"
  database_admin_password          = "BEstrO0ng_#11"
  database_id                      = "${data.oci_database_databases.db.databases.*.id}"
  protection_mode                  = "MAXIMUM_PERFORMANCE"
  transport_type                   = "ASYNC"
  delete_standby_db_home_on_delete = "true"

  display_name        = "TFExampleDataGuardAssociationVM"
  subnet_id           = "${oci_core_subnet.test_subnet.id}"
  availability_domain = "${oci_core_subnet.test_subnet.availability_domain}"
  hostname = "${format("%s-%s","ocidb",(data.oci_database_databases.db.databases.*.db_name))}"
}
`

**Comment by bowfeng** [comment]
Hi @damtst based on your script, I tried to make it run locally, and modified it a bit.
Here is my version of it, hope it helps u.
`
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

variable "ssh_public_key" {}

provider "oci" {
  version = ">=3.24"
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "eu-frankfurt-1"
  alias = "eu-fra"
  disable_auto_retries = "true"
}

data "oci_identity_availability_domain" "ad" {
  compartment_id = "${var.tenancy_ocid}"
  ad_number      = 1
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block     = "10.0.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "TFExampleVCN"
  dns_label      = "tfexamplevcn"
}

resource "oci_core_security_list" "test_security_list" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_virtual_network.vcn1.id}"
  display_name   = "TFExampleSecurityList"

  // allow outbound tcp traffic on all ports
  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "6"
  }

  ingress_security_rules {
    protocol = "6"
    source   = "0.0.0.0/0"
  }
}

// An AD based subnet will supply an Availability Domain
resource "oci_core_subnet" "test_subnet" {
  availability_domain = "${data.oci_identity_availability_domain.ad.name}"
  cidr_block          = "10.0.2.0/24"
  display_name        = "TFADSubnet"
  dns_label           = "adsubnet"
  compartment_id      = "${var.compartment_ocid}"
  vcn_id              = "${oci_core_virtual_network.vcn1.id}"
  security_list_ids   = ["${oci_core_security_list.test_security_list.id}"]
  route_table_id      = "${oci_core_virtual_network.vcn1.default_route_table_id}"
  dhcp_options_id     = "${oci_core_virtual_network.vcn1.default_dhcp_options_id}"
}

resource "oci_database_db_system" "test_db_system" {
  count                   = "2"
  availability_domain     = "${oci_core_subnet.test_subnet.availability_domain}"
  compartment_id          = "${var.compartment_ocid}"
  subnet_id               = "${oci_core_subnet.test_subnet.id}"
  database_edition        = "ENTERPRISE_EDITION"
  disk_redundancy         = "NORMAL"
  shape                   = "VM.Standard2.1"
  ssh_public_keys         = ["${trimspace(file("${var.ssh_public_key}"))}"]
  domain                  = "${oci_core_subnet.test_subnet.subnet_domain_name}"
  hostname                = "${format("%s%02d","myOracleDB",count.index + 1)}"
  data_storage_size_in_gb = "256"
  license_model           = "LICENSE_INCLUDED"
  node_count              = "1"
  display_name            = "${format("%s%d","DbSys",count.index + 1)}"

  db_home {
    db_version   = "12.1.0.2"
    display_name = "${format("%s%d","DbHm",count.index + 1)}"

    database {
      "admin_password" = "BEstrO0ng_#11"
      "db_name"        = "${format("%s%d","HmDb",count.index + 1)}"
    }
  }
}

data "oci_database_db_homes" "t" {
  count = "${length(oci_database_db_system.test_db_system.*.id)}"
  compartment_id = "${var.compartment_ocid}"
  db_system_id   = "${element(oci_database_db_system.test_db_system.*.id, count.index)}"

  filter {
    name   = "display_name"
    values = ["TFExampleDbHome1"]
  }
}

data "oci_database_databases" "db" {
  count          = "${length(oci_database_db_system.test_db_system.*.id)}"
  compartment_id = "${var.compartment_ocid}"
  db_home_id     = "${element(oci_database_db_system.test_db_system.*.db_home.0.id,count.index)}"
}

resource "oci_database_data_guard_association" "test_data_guard_association" {
  count = "${length(oci_database_db_system.test_db_system.*.id)}"
  #Required
  creation_type                    = "NewDbSystem"
  database_admin_password          = "BEstrO0ng_#11"
  database_id                      = "${element(data.oci_database_databases.db.*.databases.0.id, count.index)}"
  protection_mode                  = "MAXIMUM_PERFORMANCE"
  transport_type                   = "ASYNC"
  delete_standby_db_home_on_delete = "true"

  display_name        = "${format("DataGuardAssociationVM-%d", count.index+1)}"
  subnet_id           = "${oci_core_subnet.test_subnet.id}"
  availability_domain = "${oci_core_subnet.test_subnet.availability_domain}"
  hostname            = "${format("%s-%d","ocidb", count.index+1)}"
}


`

**Comment by damtst** [comment]
Hello, 

thank you @bowfeng for your time and help, much appreciated.

Please, be aware I am learning terraform as we speak and apologies if my questions might be obvious.

when executing the script I face this error:
`
 terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.oci_identity_availability_domain.ad: Refreshing state...

Error: Error refreshing state: 2 errors occurred:
        * data.oci_database_db_homes.t: data.oci_database_db_homes.t: value of 'count' cannot be computed
        * data.oci_database_databases.db: data.oci_database_databases.db: value of 'count' cannot be computed
`

and I am wondering if there is a problem with copy&paste, as I think the error is caused by ..

`
count = "${length(oci_database_db_system.test_db_system**..**id)}"
`
(it might be a syntax I am not familiar with).

I am modifying the script (once it works) to have something like the following:
1. one list of maps to describe the configuration of the dbsystems to be creates, like 

`
db_config = [
  {
    db_name       = "DBSYS1"
    db_node_count = "2"
    db_version    = "12.1.0.2"
    db_dataguard  = "YES"
  },
  {
    db_name       = "DBSYS2"
    db_node_count = "1"
    db_version    = "12.2.0.1"
    db_dataguard  = "NO"
  },
  {
    db_name       = "DBSYS3"
    db_node_count = "1"
    db_version    = "18.5.0.0"
    db_dataguard  = "YES"
  },
]
`

and should the db_dataguard = "YES", then create the dataguard.

so far creating the dbsystems is fine ("${length(var.db_name)}" )

but I have not found a way to pass the id's of the dbsystems created to the resource in charge of create the dataguard if the count > 1.

cheers.

**Comment by damtst** [comment]
hello, 

not sure it will help but I can see the output of oci_database_db_homes to be

`
-> oci_database_db_homes.t = [
    [
        map[compartment_id:ocid1.compartment.oc1.....vtjsv2uzu746ya database:[] db_home_id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljtu...26v3byzkcz4csi3pnvsqwzxwn5kxnyxjq db_system_id:ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljtnz3zx...wquaox7fjjaheuv5tcqt3hhxyhww43jna db_version:12.1.0.2.190416 display_name:TFExampleDbHome011 id:ocid1.dbhome.oc1.eu-frankfurt-1.abthelj...ky26v3byzkcz4csi3pnvsqwzxwn5kxnyxjq last_patch_history_entry_id: source: state:AVAILABLE time_created:2019-05-24 09:03:55.249 +0000 UTC]
    ],
    [
        map[compartment_id:ocid1.compartment.oc1.....vtjsv2uzu746ya database:[] db_home_id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljt...b7a3fmbhhnigortvrprqoaky4d4o5ru2ehya db_system_id:ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljt2xbvl...jev346u2kyi4yvuxviha4dh4cvnhfq db_version:12.1.0.2.190416 display_name:TFExampleDbHome012 id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljtylx7gs5...bhhnigortvrprqoaky4d4o5ru2ehya last_patch_history_entry_id: source: state:AVAILABLE time_created:2019-05-24 09:02:42.619 +0000 UTC]
    ]
]        
`
and I have the following error on oci_database_databases

`
        * data.oci_database_databases.db[1]: Resource 'data.oci_database_db_homes.t' not found for variable 'data.oci_database_db_homes.t.db_homes.db_home_id'
        * data.oci_database_databases.db[0]: Resource 'data.oci_database_db_homes.t' not found for variable 'data.oci_database_db_homes.t.db_homes.db_home_id'
`

could it be that oci_database_db_homes is not returning a full map? like database:[1]

`
-> oci_database_db_homes.t = [
    [
        map[compartment_id:ocid1.compartment.oc1.....vtjsv2uzu746ya database:[0] db_home_id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljtu...nvsqwzxwn5kxnyxjq db_system_id:ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljtnz3zx...heuv5tcqt3hhxyhww43jna db_version:12.1.0.2.190416 display_name:TFExampleDbHome011 id:ocid1.dbhome.oc1.eu-frankfurt-1.abthelj...pnvsqwzxwn5kxnyxjq last_patch_history_entry_id: source: state:AVAILABLE time_created:2019-05-24 09:03:55.249 +0000 UTC]
    ],
    [
        map[compartment_id:ocid1.compartment.oc1.....vtjsv2uzu746ya database:[1] db_home_id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljt...rqoaky4d4o5ru2ehya db_system_id:ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljt2xbvl...uxviha4dh4cvnhfq db_version:12.1.0.2.190416 display_name:TFExampleDbHome012 id:ocid1.dbhome.oc1.eu-frankfurt-1.abtheljtylx7gs5...y4d4o5ru2ehya last_patch_history_entry_id: source: state:AVAILABLE time_created:2019-05-24 09:02:42.619 +0000 UTC]
    ]
]  
`

cheers

**Comment by bowfeng** [comment]
@damtst 
somehow GitHub editor magically filtered out  asterisk sign 
for instance "${element(oci_database_db_system.test_db_system.*.id, count.index)}"
in the previous example, whenever you see two dot, add asterisk sign in-between.

**Comment by damtst** [comment]
Hello @bowfeng 
thank you for the heads up, I will test it and see what happens.
cheers.

**Comment by damtst** [comment]
Hello, 

just a quick heads up, I managed to solve this "issue" by upgrading to terraform 0.12 and modifying the logic of the resources and type of variable (using objects).

cheers.
