### ISSUE TITLE
Provider v3.26 wants to destroy/recreate ipsec resource with no modifications to that resource declaration

### ISSUE THREAD

**Issue by ravitandonrt** [terraform-providers/terraform-provider-oci#779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**NOTES:**
* This issue only impacts existing configurations that have `core_ipsec_connection` in their state files
* There is a work-around to ignore the lifecycle changes on `tunnel_configuration` until an update to the resource is released in the provider.

### Terraform Version and Provider Version
Terraform version: 0.11.7 
terraform-provider-oci: v.26.0

### Affected Resource(s)
resource `oci_core_ipsec`

### Terraform Configuration Files

```hcl
resource "oci_core_ipsec" "test_ip_sec_connection" {
  #Required
  compartment_id = "${var.compartment_ocid}"
  cpe_id         = "${oci_core_cpe.test_cpe.id}"
  drg_id         = "${oci_core_drg.test_drg.id}"
  static_routes  = "${var.ip_sec_connection_static_routes}"

  #Optional
  cpe_local_identifier      = "${var.ip_sec_connection_cpe_local_identifier}"
  cpe_local_identifier_type = "${var.ip_sec_connection_cpe_local_identifier_type}"
  defined_tags              = "${map("${oci_identity_tag_namespace.tag-namespace1.name}.${oci_identity_tag.tag1.name}", "${var.ip_sec_connection_defined_tags_value}")}"
  display_name              = "${var.ip_sec_connection_display_name}"
  freeform_tags             = "${var.ip_sec_connection_freeform_tags}"

  /*
  tunnel_configuration {
    #Optional
    bgp_session_config {
      #Optional
      customer_bgp_asn      = "${var.ip_sec_connection_tunnel_configuration_bgp_session_config_customer_bgp_asn}"
      customer_interface_ip = "${var.ip_sec_connection_tunnel_configuration_bgp_session_config_customer_interface_ip}"
      oracle_interface_ip   = "${var.ip_sec_connection_tunnel_configuration_bgp_session_config_oracle_interface_ip}"
    }

    display_name  = "${var.ip_sec_connection_tunnel_configuration_display_name}"
    routing       = "${var.ip_sec_connection_tunnel_configuration_routing}"
    shared_secret = "${var.ip_sec_connection_tunnel_configuration_shared_secret}"
  }
  */
  lifecycle {
    //ignore_changes = [ "tunnel_configuration" ]
  }
}
```

From example: https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/networking/ipsec_connections

### Debug Output

```
-/+ oci_core_ipsec.test_ip_sec_connection (new resource required)
      id:                                                     "ocid1.ipsecconnection.oc1.phx.a" => <computed> (forces new resource)
2019/05/28 15:26:41 [DEBUG] plugin: waiting for all plugin processes to complete...
      compartment_id:                                         "ocid1.compartment.oc1..a" => "ocid1.compartment.oc1..a"
      cpe_id:                                                 "ocid1.cpe.oc1.phx.a" => "ocid1.cpe.oc1.phx.a"
      cpe_local_identifier:                                   "189.xx.2.zz" => "189.xx.2.zz"
      cpe_local_identifier_type:                              "IP_ADDRESS" => "IP_ADDRESS"
      defined_tags.%:                                         "1" => "1"
      defined_tags.testexamples-tag-namespace.tf-example-tag: "value" => "value"
      display_name:                                           "MyIPSecConnection" => "MyIPSecConnection"
      drg_id:                                                 "ocid1.drg.oc1.phx.a" => "ocid1.drg.oc1.phx.a"
      freeform_tags.%:                                        "1" => "1"
      freeform_tags.Department:                               "Finance" => "Finance"
      state:                                                  "AVAILABLE" => <computed>
      static_routes.#:                                        "1" => "1"
      static_routes.0:                                        "10.0.0.0/16" => "10.0.0.0/16"
      time_created:                                           "2019-05-28 21:30:34.977 +0000 UTC" => <computed>
      tunnel_configuration.#:                                 "" => <computed> (forces new resource)


Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior

Terraform plan should not have resulted in a diff for a resource which did not have any tunnel configuration before v3.26.0 or now after upgrading.

Additionally, it should support update of the tunnel configuration as indicated in this API: https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/IPSecConnectionTunnel/UpdateIPSecConnectionTunnel

### Actual Behavior

Terraform plan showed oci_core_ipsec.test_ip_sec_connection (new resource required) due to tunnel_configuration.#:                                 "" => <computed> (forces new resource)

### Steps to Reproduce

1. Run the `terraform apply` with an older provider version for the above example without any `tunnel_configuration` such that the Terraform state has no entry for `tunnel_configuration`. Alternatively, you can modify to remove the entry for `tunnel_configuration` from the state file.
2. Update to newer v.3.26.0 provider version that introduces `tunnel_configuration` in `core_ipsec_connection` and run `terraform plan`. It will show that it has to destroy the resource.

      tunnel_configuration.#:                                 "" => <computed> (forces new resource)

**Comment by StuporHero** [comment]
I can confirm that this affects Terraform `0.12.0` and this provider version `3.27.0`.

**Comment by rhuesken** [comment]
Last week I have modified my terraform code to be compliant with 0.12. There are many improvements, so in general I'm quite happy. 

However, I noticed a more general pattern with inline blocks. Using dynamic blocks it is not possible (or at least: not straightforward for me, with only 6 months of terraform experience) to prevent the generation of an inline block completely.

I guess that being able to do so, would prevent this issue (and also allow more flexible use of the source_details with block volumes, see: https://github.com/terraform-providers/terraform-provider-oci/issues/776).

The code snippet below shows that is is possible to prevent the creation of nested dynamic blocks (tcp_options and udp_options) with the oci_core_security_list resource. I'm not familiar with Golang, so I do not see why this is possible for e.g. the tcp_options inline block, and cannot be achieved for e.g. the ingress_rules (oci_core_security_list), source_details (oci_core_volume) or the tunnel_configuration inline block.

    DMZ_PROD_PUBLIC_I  = [ # Public Internet    
                           { protocol = "6", cidr_block = "0.0.0.0/0", min_port =  80, max_port =  80, stateless = false } # http 
                         , { protocol = "6", cidr_block = "0.0.0.0/0", min_port = 443, max_port = 443, stateless = false } # https 
                         ] 

  dynamic "ingress_security_rules" {
    # Publish the attributes from the configuration for use within this dynamic block
    for_each = [for conf in var.VCN-SECLISTS.DMZ_PROD_PUBLIC_I : {
        protocol   = conf.protocol
        cidr_block = conf.cidr_block
        min_port   = conf.min_port
        max_port   = conf.max_port
        stateless  = conf.stateless
      }]

      content {
        protocol    = ingress_security_rules.value.protocol
        source      = ingress_security_rules.value.cidr_block

        dynamic "tcp_options" { 
          # Only create an tcp_options block in case of an TCP rule
          for_each = ingress_security_rules.value.protocol == "6" ? [1] : []
          content {
            min = ingress_security_rules.value.min_port
            max = ingress_security_rules.value.max_port
          }
        } 
        
        dynamic "udp_options" { 
          # Only create an udp_options block in case of an UDP rule
          for_each = ingress_security_rules.value.protocol == "17" ? [1] : []
          content {
            min = ingress_security_rules.value.min_port
            max = ingress_security_rules.value.max_port
          }
        } 
      }
  }

**Comment by bowfeng** [comment]
Followed up with this bug, and made a new release.

**Terraform Provider Version**
terraform-provider-oci: v.3.28.2

**Affected Resource(s)**
resource oci_core_ipsec

**Changes**
It fixed the ipsec issue by removing `tunnel_configuration` from `oci_core_ipsec`, meanwhile it adds a new resource `oci_core_ipsec_connection_tunnel_management` to manage IPSec tunnel configuration.

For example: https://github.com/terraform-providers/terraform-provider-oci/tree/master/examples/networking/ipsec_connections
