### ISSUE TITLE
Unsupported block type: "metadata" in oci_core_instance resource in terraform 0.12 and provider 3.27.0

### ISSUE THREAD

**Issue by SoftwareMaven** [terraform-providers/terraform-provider-oci#781]
I'm experimenting with upgrading to 0.12 and provider 3.27.0. I'm seeing the following error:

> Error: Unsupported block type
> 
>   on oci-patterns/tfmodules/terraform-oci-compute-instance/main.tf line 57, in resource "oci_core_instance" "this":
>   57:   metadata {
> 
> Blocks of type "metadata" are not expected here. Did you mean to define
> argument "metadata"? If so, use the equals sign to assign it a value.
> 

Here is the `oci_core_instance` resource definition:

```
resource "oci_core_instance" "this" {
  count                = "${var.instance_count}"
  availability_domain  = "${local.availability_domain}"
  compartment_id       = "${var.compartment_ocid}"
  display_name         = "${var.instance_count != "1" ? "${var.instance_display_name}_${count.index + 1}" : "${var.instance_display_name}"}"
  extended_metadata    = "${var.extended_metadata}"
  ipxe_script          = "${var.ipxe_script}"
  preserve_boot_volume = "${var.preserve_boot_volume}"
  shape                = "${var.shape}"
  freeform_tags        = "${var.freeform_tags}"

  create_vnic_details {
    assign_public_ip       = "${var.assign_public_ip}"
    display_name           = "${var.vnic_name}"
    hostname_label         = "${var.hostname_label}"
    private_ip             = "${var.private_ip}"
    skip_source_dest_check = "${var.skip_source_dest_check}"
    subnet_id              = "${var.subnet_ocid}"
  }

  metadata {
    ssh_authorized_keys = "${file("${var.ssh_authorized_keys}")}"
    user_data           = "${var.user_data}"
  }

  source_details {
    boot_volume_size_in_gbs = "${var.boot_volume_size_in_gbs}"
    source_id               = "${var.source_ocid}"
    source_type             = "${var.source_type}"
  }

  timeouts {
    create = "${var.timeout}"
  }
}
```
```

**Comment by alexng-canuck** [comment]
Hi @SoftwareMaven ,

With Terraform v0.12, HashiCorp has introduced changes to the syntax to more clearly differentiate between attributes (like `metadata`) and nested resource blocks (such as `source_details`).

In the case of attributes, you now need to specify an `=` sign in front of the block like this:
```
metadata = {
...
}
```

I highly recommend that you review the v0.12 upgrade guidance to understand other ways that v0.12 might impact your configurations.

https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks
