### ISSUE TITLE
Virtual Circuit Creation fails with VLAN ID null is invalid

### ISSUE THREAD

**Issue by saravanakumarmohan** [terraform-providers/terraform-provider-oci#782]
### Terraform Version and Provider Version

Terraform Version: 0.11.13
OCI Provider Plugin: 3.25.0_x4

### Affected Resource(s)

oci_core_virtual_circuit

### Terraform Configuration Files

```hcl
resource "oci_core_virtual_circuit" "bss-fastconnect-private-interxion-vc-01" {
    #Required
    compartment_id = "${var.compartment_ocid}"
    type = "${var.virtual_circuit_type_vc_01}"

    bandwidth_shape_name = "${var.virtual_circuit_bandwidth_vc_01}"
    cross_connect_mappings {
        #bgp_md5auth_key = -1
        #cross_connect_or_cross_connect_group_id = -1
        customer_bgp_peering_ip = "${var.customer_bgp_peering_ip_vc_01}"
        oracle_bgp_peering_ip = "${var.oracle_bgp_peering_ip_vc_01}"
        #vlan = -1
    }
    customer_bgp_asn = "${var.customer_bgp_asn_vc_01}"
    display_name = "bss-fastconnect-private-interxion-vc-01"
    gateway_id = "${data.terraform_remote_state.bss-transit-vcn.bss-transit-drg-ocid}"
    provider_service_key_name = "${var.provider_service_key_name_vc_01}"
}```

### Expected Behavior

The scenario is to create a virtual circuit with an Oracle Provider. When creating a Virtual Circuit using the OCI console, we do not provide a VLAN ID. Why is this mandatory when using terraform?

### Actual Behavior

Apply errors out with 
* oci_core_virtual_circuit.bss-fastconnect-private-interxion-vc-02: Service error:InvalidParameter. VLAN ID null is invalid. Must be between 100 and 4094.. http status code: 400

**Comment by varmax2511** [comment]
Hi @saravanakumarmohan, I am unable to reproduce the issue using the above terraform configuration, I get successful creation of `virtual_circuit`. Can you share the full debug logs for further investigation? 
Please remove any sensitive data from the logs.

**Comment by saravanakumarmohan** [comment]
The full logs are available here: https://gist.github.com/saravanakumarmohan/0d44d5a50e65ae20dd3061dbf4ae5272

**Comment by varmax2511** [comment]
Thanks @saravanakumarmohan for sharing the logs. We are still not able to reproduce this issue at our end and are working with the back-end service team to identity the cause. This will require us to look into the service calls made. 
You can enable logging of these calls by setting an environment variable `export OCI_GO_SDK_DEBUG=1`. Can you please share the full debug logs generated after enabling this env variable?

**Comment by saravanakumarmohan** [comment]
Thank you @varmax2511; here are the logs with OCI_GO_SDK_DEBUG set to 1.
https://gist.github.com/saravanakumarmohan/ecbf5d58d366d4ea2e8e8208fe96da66

**Comment by varmax2511** [comment]
I am able to reproduce your issue. Below is my finding:
In OCI console, setting up a `fastconnect` is a two step process. In the first dialog step you pass the provider details, the console at this point makes a call to fetch
`provider_service_id`. In the second dialog you pass the connection details and click `create`, the console supplies the `provider_service_id` in the `Create` request. 

In terraform you can fetch the provider service ids for your desired provider by using the data source below and filtering the result

```hcl
# data source to fetch the provider services available in your compartment
# we are filtering the output by the desired provider name and provider service name
data "oci_core_fast_connect_provider_services"  "test_fast_connect_provider_services" {
  compartment_id = "${var.compartment_ocid}"

   filter{
     name = "provider_service_name"
     values = ["Cloud Connect"]
   }

  filter {
    name = "provider_name"
    values = ["Interxion"]
  }
}

# output values to visually confirm that you are getting the desired provider details
output "provider_names"{
  value = ["${data.oci_core_fast_connect_provider_services.test_fast_connect_provider_services.fast_connect_provider_services}"]
}

Then you can use this data source to supply the service id in your `oci_core_virtual_circuit` resource
`provider_service_id = "${data.oci_core_fast_connect_provider_services.test_fast_connect_provider_services.fast_connect_provider_services.0.id}"`
```

Please let us know if the issue still persists.

**Comment by mauryarr** [comment]
I have seen the above configuration and tried executing as @varmax2511  suggested. 
However I am getting this error: 
* oci_core_virtual_circuit.esv1_nrt7_833: Resource 'data.oci_core_fast_connect_provider_services.test_fast_connect_provider_services' does not have attribute 'fast_connect_provider_services.1.id' for variable 'data.oci_core_fast_connect_provider_services.test_fast_connect_provider_services.fast_connect_provider_services.1.id'
