### ISSUE TITLE
"invalid new value for .content:"

### ISSUE THREAD

**Issue by rramge** [terraform-providers/terraform-provider-oci#786]
### Terraform Version and Provider Version

Terraform v0.12.1
+ provider.oci v3.28.0

### Affected Resource(s)

oci_objectstorage_object

### Terraform Configuration Files

resource "oci_objectstorage_bucket" "tfstate" {
  lifecycle { prevent_destroy = true }

  compartment_id = data.oci_objectstorage_namespace_metadata.global.default_s3compartment_id
  namespace      = data.oci_objectstorage_namespace.ns.namespace
  name           = "terraform-tfstate-DO_NOT_DELETE"
  access_type    = "NoPublicAccess"
}

resource "oci_objectstorage_object" "tfstate" {
  //lifecycle { prevent_destroy = true }

  namespace        = data.oci_objectstorage_namespace.ns.namespace
  bucket           = oci_objectstorage_bucket.tfstate.name
  object           = "terraform.tfstate"
  content_language = "en-US"
  content_type     = "application/json"
  content          = "${file("terraform.tfstate")}" // if you uncomment this line, the remote tfstate file will
  // get overwritten with your local copy, HANDLE WITH CARE!
}

resource "oci_objectstorage_preauthrequest" "tfstate-par" {
  lifecycle { prevent_destroy = true }

  namespace    = data.oci_objectstorage_namespace.ns.namespace
  bucket       = oci_objectstorage_bucket.tfstate.name
  object       = oci_objectstorage_object.tfstate.object
  name         = "terraform.tfstate"
  access_type  = "ObjectReadWrite" // ObjectRead, ObjectWrite, ObjectReadWrite, AnyObjectWrite
  time_expires = "2019-12-31T23:59:59Z"
}

[ralf@olinux7 terraform]$ ls -al terraform.tfstate
-rw-r--r--. 1 ralf ralf 18361 Jun  6 14:54 terraform.tfstate
[ralf@olinux7 terraform]$ 

### Expected Behavior

After commenting out the "content = ..." line in the oci_objectstorage_object.tfstate resource, the following should happen:

1) The existing resource should be destroyed
2) A new resource with the contents of the file specified should be created in the bucket.

### Actual Behavior

Step 1 is performed, the object is deleted.
Step 2 throws the following error now:

ralf@olinux7 terraform]$ tapply out/20190606145357.plan
oci_objectstorage_object.tfstate: Destroying... [id=n/sco01/b/terraform-tfstate-DO_NOT_DELETE/o/terraform.tfstate]
oci_objectstorage_object.tfstate: Destruction complete after 0s

Error: Provider produced inconsistent final plan

When expanding the plan for oci_objectstorage_object.tfstate to include new
values learned so far during apply, provider "oci" produced an invalid new
value for .content: was cty.StringVal("e6d5a23abf5ce0116e9a16da8bd8d85c"), but
now cty.StringVal("df187d8c655270ba08e5cafbc4f167a0").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

Running 'terraform apply' a second time without changing anything actually worked.

**Comment by varmax2511** [comment]
Hi @rramge. I notice that you are trying to upload the terraform state file for the terraform config you are executing. The `content` field in `oci_objectstorage_object` generates a hash of the input file. 

Since the terraform state file changes between `plan` and `apply` you are getting a Diff in `content` post apply resulting in error. The subsequent `apply` succeeds because now there is no update in your terraform config and hence no update in state file, which generates the same hash value. 

Please try uploading a file which will not change between `terraform plan` and `terraform apply`.

**Comment by rramge** [comment]
Wow, this is really a great explanation and very good to know. Thanks a lot, highly appreciated!
