### ISSUE TITLE
Changing time_Zone

### ISSUE THREAD

**Issue by damtst** [terraform-providers/terraform-provider-oci#794]
Hello, 

I am currently facing this error while trying to create a dbsystem with a time_zone = "Europe/Zurich". do we have a timeline to support this feature?

`
Error: Service error:IncorrectState. Setting a non UTC time zone feature is not currently supported for VM.Standard2.4 shape..
`
seems that only UTC is supported.

Thank you.

**Comment by afedorch** [comment]
@damtst The Time Zone field in the Console and in the API allows you to launch an Exadata DB system with a time zone other than UTC (the default): https://docs.cloud.oracle.com/iaas/Content/Database/References/timezones.htm 
Are you asking about a timeline for bare metal and/or virtual machine? thanks!

**Comment by damtst** [comment]
@afedorch, I am currently testing on dbsystems, exadata is planned for later on. as far as I see on the docs (https://www.terraform.io/docs/providers/oci/r/database_db_system.html), there are not restrictions on configuration time_zone on bare metal or VMs... can you please confirm this is the case or the docs are a bit misleading?

thank you.

**Comment by afedorch** [comment]
@damtst we have passed the request to the service team.

As you mentioned terraform provider docs has a link to the service documentation with all the relevant information:
* `time_zone` - (Optional) The time zone to use for the DB system. For details, see [DB System Time Zones](https://docs.cloud.oracle.com/iaas/Content/Database/References/timezones.htm).

You can track the updates for the `DB System Time Zone` there - no changes will be required on provider side to support it (should be an update for the `The Time Zone field in the Console and in the API allows you to launch an Exadata DB system with a time zone other than UTC (the default).`)

Please feel free to create a new request if you have any other questions. thanks!
