### ISSUE TITLE
Unable to delete tags assigned to compartments using defined_tags

### ISSUE THREAD

**Issue by meanjollies** [terraform-providers/terraform-provider-oci#795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.2
+ provider.oci v3.29.0
### Affected Resource(s)

oci_identity_compartment

### Terraform Configuration Files

```hcl
resource "oci_identity_compartment" "this" {
  count          = "${var.compartment_create ? 1 : 0}"
  compartment_id = "${var.compartment_id == "" ? var.tenancy_ocid : lookup(data.oci_identity_compartments.get_id.compartments[0],"id")}"
  name           = "${var.compartment_name}"
  description    = "${var.compartment_description}"
  enable_delete  = "${var.compartment_enable_delete}"
  defined_tags   = "${var.compartment_defined_tags}"
}

locals {
  compartment_ids = "${concat(flatten(data.oci_identity_compartments.this.*.compartments), list(map("id", "")))}"
}

data "oci_identity_compartments" "this" {
  count          = "${var.compartment_create ? 0 : 1}"
  compartment_id = "${var.tenancy_ocid}"

  filter {
    name   = "name"
    values = ["${var.compartment_name}"]
  }
}

data "oci_identity_compartments" "get_id" {
  compartment_id = "${var.tenancy_ocid}"
  filter {
    name   = "name"
    values = ["${var.compartment_id}"]
  }
}
```

### Debug Output
There's quite a bit of output that contains a great deal of sensitive information about my environment. I'd prefer to not include this. If absolutely required, please let me know, but I will need to redact a bunch of information.

### Expected Behavior
I would like to be able to clear all defined tags from the compartment. I can do this using the CLI by passing `{}` to the `--defined-tags` argument, which results in all defined tags being cleared. If I pass the same `{}` as a map type to the `defined_tags` argument in the oci_identity_compartment resource, I expect identical behavior.

### Actual Behavior

When passing `{}` of a map type to `defined_tags`, a plan shows what I would expect:
```
# module.compartment-Development.oci_identity_compartment.this[0] will be updated in-place
  ~ resource "oci_identity_compartment" "this" {
        compartment_id = "ocid1.compartment.oc1..aaaa<redacted>"
      ~ defined_tags   = {
          - "eng.Lifecycle" = "development" -> null
        }
        description    = "A sample compartment"
        enable_delete  = false
        freeform_tags  = {}
        id             = "ocid1.compartment.oc1..aaaa<redacted>"
        name           = "Development"
        state          = "ACTIVE"
        time_created   = "2019-06-14 19:52:38.144 +0000 UTC"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.compartment-Development.oci_identity_compartment.this[0]: Modifying... [id=ocid1.compartment.oc1..aaaa<redacted>]
module.compartment-Development.oci_identity_compartment.this[0]: Modifications complete after 3s [id=ocid1.compartment.oc1..aaaa<redacted>]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
However, despite this showing a success, the `defined_tags` attribute still shows the old tag, as evident in cli output and the web console. If I re-run plan/apply, it continues to show that the change did not take effect.

### Important Factoids

1. This occurs with compartments that have both been imported or originally created using Terraform.
2. In addition to top-level compartments, it occurs with subcompartments as well.
3. I have `{}` set as the default value for `defined_tags`. If I create a new compartment, it assigns this without any problems.
4. I can successfully change defined tag values in place. The problem is only deleting the tags themselves.
5. I can reproduce this using Terraform 0.11.x.
6. I cannot reproduce this with freeform_tags. That behaves as expected.

**Comment by rcohenma** [comment]
This was fixed in the latest release. Please give it a try

https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.31.0

**Comment by meanjollies** [comment]
😀 Can confirm it works! Thanks for fixing this.
