### ISSUE TITLE
Freeform tags support on oci_core_virtual_circuit

### ISSUE THREAD

**Issue by kral2** [terraform-providers/terraform-provider-oci#799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, resource oci_core_virtual_circuit do not allow freeform tag. Terraform return this error when a Freeform tag block is added to the resource. " invalid or unknown key: freeform_tags"

Console UI allows the user to add freeform tags on virtual circuit. This is a request to have feature parity between OCI Console & the terraform oci provider.

### Potential Terraform Configuration

Being able to add a freeform_tags block .

```hcl
resource "oci_core_virtual_circuit" "this" {
  # regular virtual circuit required and optional attributes
  freeform_tags = {
    "Terraformed" = "yes"
  }
```

### References

Documentation do not list freeform_tags as a supported attribute on resource oci_core_virtual_circuit.

**Comment by kilokahn** [comment]
hey @kral2 - this is scheduled for release in v3.36.0 on 7/31.

**Comment by abhilash-av** [comment]
@kral2 this is release now. Closing this issue.
