### ISSUE TITLE
data_storage_percentage is not working as expected.

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#810]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by kshinkr** [comment]
We have created the DBCS with this values but data_storage_percentage is not working as expected.

Here is the description for data_storage_percentage.
"data_storage_percentage - (Optional) The percentage assigned to DATA storage (user data and database files). The remaining percentage is assigned to RECO storage (database redo logs, archive logs, and recovery manager backups). Specify 80 or 40. The default is 80 percent assigned to DATA storage. Not applicable for virtual machine DB systems."

[DBCS input]
    "db_version": "18.0.0.0",
    "db_system_shape": "VM.Standard2.4",
    "data_storage_percentage": "40",
    "data_storage_size_in_gb": "1024",

So we try to create DATA for 400GB and 600GB for RECO, total 1024GB but ...

				                             Total Raw     Free Raw   
 NO NAME	    STATE      TYPE        Size (GB)     Size(GB)   	 
  1 DATA	    CONNECTED  EXTERN	   1,048         1,035		
  2 RECO	    CONNECTED  EXTERN	      262	         237		

Totally different layout for ASM diskgroup. DATA has 1048GB and FRA 262GB and We put HIGH redundancy but it shows external.

This is not what we planned to create.

Is it a bug?

**Comment by kshinkr** [comment]
It seems like that this parameter is not working in VM, then what is the default layout?
For our case, 1024GB for DATA and 1/4 of size of total size will be RECO?

**Comment by rcohenma** [comment]
The service does seem to ignore that parameter for VM and it has its own default.
Here is the documentation for the differences between BM and VM: https://docs.cloud.oracle.com/iaas/Content/Database/Concepts/overview.htm

**Comment by kshinkr** [comment]
Yes correct. There is no way to change the default option for data/reco allocation for VM DBCS and redundancy is external only. But can't see the exact description about that on the document. This kind of storage allocation is supposed to be able to changed on customer plan.
Anyway that is current status.

**Comment by alexng-canuck** [comment]
Hi @kshinkr 

As you've pointed out, the `data_storage_percentage` does not apply to VM shapes and this limitation is documented in both the provider and the service API documentation: 
- https://www.terraform.io/docs/providers/oci/r/database_db_system.html#data_storage_percentage
- https://docs.cloud.oracle.com/iaas/Content/Database/Tasks/creatingDBsystem.htm#create

That being said, the service documentation doesn't appear to state what the defaults are for the VM case. We can file a request to service team to have the documentation updated.

Is there any other information that you are seeking?

**Comment by parrneet** [comment]
Closing the issue. Feel free to reopen if any other information is needed.
