### ISSUE TITLE
Network Security Groups finally released

### ISSUE THREAD

**Issue by matmacfarlane** [terraform-providers/terraform-provider-oci#820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Network Security Groups have finally been released on OCI.

### New or Affected Resource(s)

Compute instances: primary VNIC
Compute instances: secondary VNICs
DB systems
Load balancers

### Potential Terraform Configuration

resource "oci_core_security_group" {
}

resource "oci_core_security_group_rule" {
}

Ideally the security group rule would be a separate resource as in AWS.

### References

Please see release notes:
https://docs.cloud.oracle.com/iaas/releasenotes/changes/3445abe7-41b7-4669-b03d-d6e43b70279f/

**Comment by parrneet** [comment]
Hi @matmacfarlane,

Network Security Group and Security rule are indeed implemented as separate resources in provider. Please refer to these docs:
https://www.terraform.io/docs/providers/oci/r/core_network_security_group.html
https://www.terraform.io/docs/providers/oci/r/core_network_security_group_security_rule.html
