### ISSUE TITLE
Instance pool creation failes if a network security group is specified in the instance_configuration

### ISSUE THREAD

**Issue by ionel-cerghit** [terraform-providers/terraform-provider-oci#827]
### Terraform Version and Provider Version

Terraform v0.11.14
(the same happens with v0.12.5)
Oci provider v3.34.0

### Description

When I specify a value for the field `nsg_ids` inside a `oci_core_instance_configuration` resource it will cause an error while trying to create a `oci_core_instance_pool` from it. Without that field everything applies successfully. 

The nsg is in the same vcn as the pool that will be created.

### Terraform Configuration Files

```hcl
resource "oci_core_instance_configuration" "test_instance_configuration" {
  compartment_id = "${var.compartment_ocid}"

  instance_details {
    instance_type = "compute"

    launch_details {
      compartment_id = "${var.compartment_ocid}"

      create_vnic_details {
        assign_public_ip = "true"
        subnet_id        = "${var.instance_subnet_id}"
        hostname_label   = "${var.instance_hostname}"
        nsg_ids          = ["${var.nsg_id}"]
      }

      display_name = "Test config terraform"

      metadata = {
        ssh_authorized_keys = "${file(var.ssh_public_key)}"
      }

      shape = "${var.instance_shape}"

      source_details {
        source_type = "image"
        image_id    = "${var.instance_image}"
      }
    }
  }

  display_name = "Test instance configuration"
}

resource "oci_core_instance_pool" "test_instance_pool" {
  compartment_id            = "${var.compartment_ocid}"
  instance_configuration_id = "${oci_core_instance_configuration.test_instance_configuration.id}"

  placement_configurations {
    availability_domain = "${var.ad}"
    primary_subnet_id   = "${var.instance_subnet_id}"
  }

  size         = "1"
  display_name = "${var.pool_name}"
}
```

### Terraform apply
Error: Error applying plan:

1 error occurred:
        * oci_core_instance_pool.test_instance_pool: 1 error occurred:
        * oci_core_instance_pool.test_instance_pool: timeout while waiting for state to become 'STOPPED, RUNNING' (last state: 'SCALING', timeout: 15m0s)

### Instance Pool work request error message

`Instance launch failed. network security group ocid1.networksecuritygroup.oc1.... not found`

In the cloud interface the pool remains in the `Scaling` state.

**Comment by kilokahn** [comment]
hey @ionel-cerghit - thanks for reporting this! From the error message, it looks like the network security group was not found. Can you please elaborate on how `${var.nsg_id}` is being populated? Venturing a guess: it might be the case that the network security id that you are referring to here may belong to a different region. 

To objectively troubleshoot this, can you please provide the verbose logging using the instructions at https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider ? Thanks!

**Comment by ionel-cerghit** [comment]
Hi @kilokahn ,
I looked into the issue and the problem was that I was missing a iam policy. We can close the issue.

Thank you
Ionel

**Comment by kilokahn** [comment]
Thanks for confirming @ionel-cerghit ! I am closing this one out.
