### ISSUE TITLE
Not able to create a new server via oci provider

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#833]
Hi Team,

We are getting the following error while we tryto provision a new server in OCIC via Terraform. Kindly help us resolve this issue.

Error: Provider produced inconsistent result after apply

When applying changes to opc_compute_instance.srv1 provider "opc"
produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Thanks in Advance. Please help us at the earliest.

**Comment by kilokahn** [comment]
Hey @shruthi2703 - i think the issue which you are facing is related to `terraform-provider-opc`, and should be reported at https://github.com/terraform-providers/terraform-provider-opc/issues
Thank you.
