### ISSUE TITLE
good-bot and some other entries are missing from the waas provider

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please review the waas provider as there are missing entries for the oci_waas_waas_policy protection rules recommendations the good-bot management
we can update the missing section with oci cli .. but if we start to this path then its better not to use the terraform provider 

### New or Affected Resource(s)

oci_waas_waas_policy 

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References
https://www.terraform.io/docs/providers/oci/r/waas_waas_policy.html

**Comment by kilokahn** [comment]
hey @eugsim1 - thanks for reporting this! There was an inconsistency in the service team's implementation of the creation of the WAAS Policy for these fields, and hence it was omitted in the initial version. Based on this feedback, we are going to reach out to the WAF team to have this inconsistency fixed so that it can be supported in the Terraform provider.

**Comment by kilokahn** [comment]
The fields that are missing support in Terraform are:

- ThreatFeeds
- GoodBots
- ProtectionRules

All others are being supported.

**Comment by jotruon** [comment]
Hi,
Terraform v3.88.0 add support `ProtectionRules`: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/waas_protection_rule
