### ISSUE TITLE
Documentation bug: wrong block name in oci_core_ipsec_connection_tunnel_management

### ISSUE THREAD

**Issue by dhoogfr** [terraform-providers/terraform-provider-oci#838]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I noticed that the documentation page for the oci_core_ipsec_connection_tunnel_management lists the bgp_session_config block. but using this causes an "invalid or unknown key: bgp_session_config" error.
I found an [example code](https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/ipsec_connections/ipsec_connection.tf) which uses bgp_session_info instead and that works.

It is unclear in which versions this block had which name, but with versions 3.35 and 3.36 it fails and bgp_session_info has to be used instead.

The oci_core_ipsec_connection_tunnel_management resource seems to be added by [pull request #787](https://github.com/terraform-providers/terraform-provider-oci/pull/787)

### Terraform Version and Provider Version

Terraform v0.12.6
+ provider.oci v3.36.0

### Affected Resource(s)

oci_core_ipsec_connection_tunnel_management

### References
https://github.com/terraform-providers/terraform-provider-oci/pull/787

**Comment by varmax2511** [comment]
Hi @dhoogfr, thanks for identifying and raising this issue. We have fixed the documentation:
https://www.terraform.io/docs/providers/oci/r/core_ipsec_connection_tunnel_management.html#argument-reference
