### ISSUE TITLE
Verbose logging for OCI Terraform Provider doesnt work

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#839]
I m trying to get verbose info from terraform as described here:
To get verbose console output when the provider is running, precede your Terraform command with the TF_LOG and OCI_GO_SDK_DEBUG flags: sh TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan

The tf_log level and OCI_GO_SDK_DEBUG flags can also be set as environment variables.

 sh TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan doesnt work for as such !

sh TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan
sh: TF_LOG=DEBUG: No such file or directory

 env | grep TF
TF_VAR_LOG_PATH=./terraform.log
TF_VAR_LOG=DEBUG

env | grep OCI

env | grep OCI
OCI_GO_SDK_DEBUG=v

 terraform -v
Terraform v0.12.6
+ provider.oci v3.36.0

**Comment by varmax2511** [comment]
Hi @eugsim1 , can you please try the below command
```
TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan
```

**Comment by eugsim1** [comment]
hi it works can you please update the doc 
Verbose logging for OCI Terraform Provider

To get verbose console output when the provider is running, precede your Terraform command with the TF_LOG and OCI_GO_SDK_DEBUG flags: sh TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan 

please remove the sh from this phrase 👍 Verbose logging for OCI Terraform Provider

To get verbose console output when the provider is running, precede your Terraform command with the TF_LOG and OCI_GO_SDK_DEBUG flags: sh TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan

**Comment by varmax2511** [comment]
Hi @eugsim1, we have updated the OCI Terraform provider doc. Thanks for identifying and raising this issue
https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html
