### ISSUE TITLE
How to assigne a Public IP to an instance ?

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#840]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by eugsim1** [comment]
Hello
I m trying to figure out a way to assign a Public IP to an instance that i m creating / recreating.
the reason is that these Ip are alredy published to a DNs service, and from a range of reserved IP i should allocate them to my vm.
I can do this for private IP, but why this is not possible for fixed public IPs ?
What would be the workaround i dont want to pollute a DNS service with additional update etc etc

**Comment by varmax2511** [comment]
Hi @eugsim1 -- to assign public IP to an instance, you can refer the below example, where we set the flag `assign_public_ip` in `create_vnic_details` for the instance.
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/instance/compute.tf

Doc link: https://www.terraform.io/docs/providers/oci/r/core_instance.html#argument-reference

Please let us know if this helps?

**Comment by eugsim1** [comment]
i have asked the wrong question .. so here is the real question..
I have created a fixed public IP, and i want to assign this fixed ip to my instance, or every time that i create an instance i want to allocate not a random public IP but the public ip with lets say the ocid  ocid1.publicip.oc1.eu-frankfurt-1.aaaaaaaalxfzsdla3ic74xsgobt64slfngzqrlhe5khjcvpnk5tryzw7636a

I dont see how i can do it ?

**Comment by rramge** [comment]
There'S an example for working with public IPs, including assigning previously unassigned IP Addresses to a VNIC. It may look a bit overwhelming at first sight, but it helped me a lot when I asked myself the same question.
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/public_ip/public_ip.tf

**Comment by eugsim1** [comment]
Hi again
I saw the example, it creates 3 public Ip i think and then it assigns them to private . My problem is the other way around i have created a public IP, and i want to assign it to a private IP .
for an older version of the oracle cloud this scenario was working  :
[](https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stopc/assigning-public-ip-address-instance.html)
To give your Compute Classic a fixed public IP address, you must reserve an address and then attach that address to the instance. 

how can we do the same with terraform ?

**Comment by dhoogfr** [comment]
Yes, 

First you must get the id for the private IP address for that guest
This can be done by filtering the IP resources using the IP address and the subnet id for the guest on which you want to assign the public IP address

```
data "oci_core_private_ips" "apachedev1Ips" {
  ip_address = oci_core_instance.apachedev1.private_ip
  subnet_id  = oci_core_subnet.bagsup_pubdev1.id
}
```
And then you assign the reserved public ip to that private IP id

```
resource "oci_core_public_ip" "apachedevpubip" {
  compartment_id = <compartment_id>
  display_name   = "reserved public ip for the apache dev host"
  lifetime       = "RESERVED"
  private_ip_id  = data.oci_core_private_ips.apachedev1Ips.private_ips[0]["id"]
  defined_tags   = var.common_tags
}
```

When you leave the private_ip_id attribute empty, it will either just reserve a public ip address or when already reserved and attached, unattach it from that guest (but still keep it reserved).
When you want to attach the reserved public ip to a guest, you update that attribute again.

These code examples work with terraform 0.12, if you are using 0.11 the format is somewhat different, using lookup and stuff.
I can get you an example if required

**Comment by dhoogfr** [comment]
To make my answer perhaps a bit more clear.
The oci_core_public_ip resource is both used for reserving and attaching the public IP, but these two things don't necessary need to happen at the same time.
You could first reserve the public IPs and then later on assign them by updating the private_ip_id attribute.
Also when you use this at the same time as you create the compute instance, Terraform will work out the correct order.
So it will first create the guest and then reserve the public IP (if not already reserved) and assign it to the newly created guest

**Comment by eugsim1** [comment]
thanks for the reply but in this case the call  resource "oci_core_public_ip"  creates an Public IP.
I have created allready one , that i want to bind every time that i create the same instance ..

this is from terraform show
```
# data.oci_core_public_ip.test_oci_core_public_ip_by_ip:
data "oci_core_public_ip" "test_oci_core_public_ip_by_ip" {
    compartment_id = "ocid1.compartment.oc1..XXXXXXXXXXXXXXXXXXXXXXXX"
    defined_tags   = {}
    display_name   = "ebs1"
    freeform_tags  = {}
    id             = "ocid1.publicip.oc1.eu-frankfurt-1.aaXXXXXXXXXXXXXXXXXXX"
    ip_address     = "130.61.199.XXXX"
    lifetime       = "RESERVED"
    scope          = "REGION"
    state          = "AVAILABLE"
    time_created   = "2019-08-06 16:47:43.135 +0000 UTC"
}
```
and this is from

```
# oci_core_public_ip.ReservedPublicIPAssigned:
resource "oci_core_public_ip" "ReservedPublicIPAssigned" {
    assigned_entity_id   = "ocid1.privateip.oc1.eu-frankfurt-1.aXXXXX"
    assigned_entity_type = "PRIVATE_IP"
    compartment_id       = "ocid1.compartment.oc1..aaXXXXXXX"
    defined_tags         = {}
    display_name         = "TFReservedPublicIPAssigned"
    freeform_tags        = {}
    id                   = "ocid1.publicip.oc1.eu-frankfurt-1.aXXXXXXXX"
    ip_address           = "132.145.243.237"
    lifetime             = "RESERVED"
    private_ip_id        = "ocid1.privateip.oc1.eu-frankfurt-1.XXXXXX"
    scope                = "REGION"
    state                = "ASSIGNED"
    time_created         = "2019-08-07 15:47:42.74 +0000 UTC"


the private is assigned to a new public IP "132.145.243.237" i want to bind the private to the existing ip_address     = "130.61.199.XXXX" public, but i dont see any call to do this association even after the creation of the instance


```

**Comment by dhoogfr** [comment]
You need to set the private_ip_id attribute of the oci_core_public_ip resource for the public IP you want to assign to the id of the private IP of the guest to which the public IP needs to be attached.

If the public IP reource has already been created it will not reserve a new IP. It will just attach it.
If you reserved this public IP reource outside Terraform, you need first to import it.

**Comment by varmax2511** [comment]
Hi @eugsim1 --  The solution mentioned by @dhoogfr with one change should solve the problem. Since the public IP is already created, it will be present in your Terraform config (else you can import it). Now when launching an instance we want to map the private IP of the new instance with the Public IP that already exists. This requires:
- In`create_vnic_details` set `assign_public_ip = false`. This will prevent generation of a new public IP for your instance.
- Pass the private_ip_id of the vnic of the newly created instance as `private_ip_id` in already created public IP `oci_core_public_ip`



```

# Already existing Public IP 
resource "oci_core_public_ip" "ReservedPublicIPAssigned" {
  compartment_id = "${var.compartment_ocid}"
  lifetime = "RESERVED"

  # map private IP of the instance here
  private_ip_id  = "${lookup(data.oci_core_private_ips.TFPrivateIps1.private_ips[0],"id")}"
}


resource "oci_core_instance" "TFInstance" {
  availability_domain = "${data.oci_identity_availability_domain.ad.name}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "TFInstance"
  shape               = "${var.instance_shape}"

  create_vnic_details {
    subnet_id        = "${oci_core_subnet.ExampleSubnet.id}"
    display_name     = "primaryvnic"
    hostname_label   = "tfexampleinstance"

    # disable auto-assignment of public IP for instance
    assign_public_ip = false
  }

  metadata = {
    ssh_authorized_keys = "${var.ssh_public_key}"
    user_data           = "${base64encode(file(var.BootStrapFile))}"
  }

  source_details {
    ......
  }
}
######
# data sources to find the private IP id of the new instance
######

# Gets a list of VNIC attachments on the instance
data "oci_core_vnic_attachments" "TFInstanceVnics" {
  compartment_id      = "${var.compartment_ocid}"
  availability_domain = "${data.oci_identity_availability_domain.ad.name}"
  instance_id         = "${oci_core_instance.TFInstance.id}"
}

data "oci_core_vnic" "TFInstanceVnic1" {
  vnic_id = "${lookup(data.oci_core_vnic_attachments.TFInstanceVnics.vnic_attachments[0],"vnic_id")}"
}

data "oci_core_private_ips" "TFPrivateIps1" {
  vnic_id = "${data.oci_core_vnic.TFInstanceVnic1.id}"
}

```



I ran the above use case and am able to ssh to the instance using the public IP. Please let us know if this helps.

**Comment by dhoogfr** [comment]
I indeed forgot to mention that you need to set the assign_public_ip attribute of the oci_core_instance resource to false.

Not sure if it is ok to mention here, but I have now written a blog post about this: https://www.exitas.be/blog/assigning-reserved-public-ips-to-guests-with-oracle-cloud-and-terraform/

**Comment by eugsim1** [comment]
thanks a lot

**Comment by RahulMetangale** [comment]
Hi @eugsim1 

If IP's are reserved from the OCI portal or lets say that during disaster recovery i want to assign the public ip of instance that went down to a new instance. In scenarios like this i am not clear how above approach would work. Is there any way using which i can query specific public ip using ocid and then attach it instance created using terraform? 

Thanks,
Rahul

**Comment by eugsim1** [comment]
Hi ,
for this cas its better to use oci cli, and for ha maybe and lb with several vm nodes

**Comment by hv24** [comment]
Hello @eugsim1, 
I stumbled into the same issue. Deployed all the solutions others mentioned here yet it kept creating new IP rather selecting the one I need. So I decided to go with deploying a script with oci-cli. 
I was hoping if you could help me with the cli commands.
