### ISSUE TITLE
oci_file_storage_mount_target should optionally support nsg_ids during creation, over security list requirements

### ISSUE THREAD

**Issue by lubo-p** [terraform-providers/terraform-provider-oci#841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since OCI provider already supports oci_core_network_security_group for some time. It would be nice if oci_file_storage_mount_target could be created optionally with specifying nsg_ids, just like it's possible with oci_core_instance.

Currently, following is documented with use of default security list:
https://docs.cloud.oracle.com/iaas/Content/File/Tasks/securitylistsfilestorage.htm

It would be nice if instead of security list we could specify network security group ID that contains the NFS rules and is referred just by the mount_target and core_instances that need to access this resource.

### New or Affected Resource(s)

oci_file_storage_mount_target

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by varmax2511** [comment]
Hi @lubo-p , we have passed your feedback to the service to provide File Storage support for Network security groups.

**Comment by alexng-canuck** [comment]
Hi @lubo-p , the latest version of terraform-provider-oci supports specifying NSGs for your mount targets.

See https://registry.terraform.io/providers/hashicorp/oci/3.55.0/docs/resources/file_storage_mount_target#nsg_ids

**Comment by alexng-canuck** [comment]
Closing this for now.
