### ISSUE TITLE
Network_Security_Group not recognized by provider

### ISSUE THREAD

**Issue by twmcelroy** [terraform-providers/terraform-provider-oci#844]
I am trying to create a Network Security Group and Network Security Group rule via terraform. I am using Terraform 0.12.1 and OCI provider 3.28.1. My restriction on the OCI provider is >=3.27.0
When running a plan I get 
Error; Invalid resource type for "oci_core_network_security_group" and "oci_core_network_security_group_security_rule" as shown in the provider documentation. I also noticed issue #820 that it was named "oci_core_security_group" and "oci_core_security_group_rule" but I received the same error that the provider.oci does not support these resource types. 
Do I not have the latest version?

**Comment by varmax2511** [comment]
Hi @twmcelroy, Support for Granular Security Lists using Network Security Group, `oci_core_network_security_group` `oci_core_network_security_group_security_rule` were added in OCI terraform provider version 3.33.0 and hence are not recognized in older versions.

I am using the provider restriction as below and it downloads the latest version for me
Please refer:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md

```
provider{
  ....
  version = ">=3.27.0"
}
```

**Comment by twmcelroy** [comment]
Ok I got it to upgrade by changing it to version = ">=3.33.0". Don't know why it wouldn't upgrade before but I am up to version 3.36.0. Thank you
