### ISSUE TITLE
private_key_path: YubiKey

### ISSUE THREAD

**Issue by chaim1221** [terraform-providers/terraform-provider-oci#845]
Hi there,

I am trying to plan against the OCI platform using this provider and I have run into a problem; I am trying to use my PIV key (Yubi) for authentication; I've uploaded the publickey in PEM format and put in the fingerprint like a normal SSH key, and then provided the path to my driver as I do for SSH:

```
terraform:$ ssh-add -l
2048 SHA256:f6FMo+vgL9xPzuT7fOJ06McRCZVZvspd9kMB99xUiyc /usr/local/lib/opensc-pkcs11.so (RSA)
```

...usually that path is what I use to identify my private key and it sort of "just works."

In any case, when running `terraform plan` I am met with:

```
Error: can not create client, bad configuration: did not find a proper configuration for private key

  on provider.tf line 2, in provider "oci":
   2: provider "oci" {
```

(validate works and the env var is set; same hello-world example as in the [docs](https://www.terraform.io/docs/providers/oci/index.html#environment-variables))

...given that I can't really export the private key (PIV), is there a supported way of doing this? Am I doing something obviously wrong?

Thanks!

**Comment by chaim1221** [comment]
This has nothing to do with the key and everything to do with syntax. It would be nice to see a better error message.

https://github.com/terraform-providers/terraform-provider-oci/issues/712#issuecomment-504254374

**Comment by chaim1221** [comment]
Well shoot... at first I thought it was just something in my syntax, and now I don't think it is. I made a `~/.oci` directory with an RSA key pair, which gets me a 401... not wanting to troubleshoot that because it isn't the auth method I'd prefer (too many keys, use my smart card!), lol. Anyways while the management console accepts the public key, the Terraform provider nevertheless gives this error with `/usr/local/lib/opensc-pkcs11.so`. I will try to work around it for now.

**Comment by matthbak** [comment]
Did you manage to get this working?

What's the official line? Is this supported?
