### ISSUE TITLE
Way to fetch SCAN Name for DB System using "scan_dns_record_id"

### ISSUE THREAD

**Issue by rishimahajan** [terraform-providers/terraform-provider-oci#846]
Terraform version - 0.11.11
OCI provider version - 3.28.2

I could not find a way to fetch SCAN Name using "db_systems.0.scan_dns_record_id"

Is there a way a get the SCAN name from VCN DNS using scan_dns_record_id?

                 "db_systems.0.data_storage_percentage": "80",
                            "db_systems.0.data_storage_size_in_gb": "1024",
                            "db_systems.0.database_edition": "ENTERPRISE_EDITION_EXTREME_PERFORMANCE",
                            "db_systems.0.db_home.#": "0",
                            "db_systems.0.defined_tags.%": "0",
                            "db_systems.0.disk_redundancy": "NORMAL",
                            "db_systems.0.display_name": "ebsazdbash11",
                            "db_systems.0.domain": "dbsubnet.ebsinttest.oraclevcn.com",
                            "db_systems.0.fault_domains.#": "2",
                            "db_systems.0.fault_domains.0": "FAULT-DOMAIN-1",
                            "db_systems.0.fault_domains.1": "FAULT-DOMAIN-2",
                            "db_systems.0.freeform_tags.%": "0",
                            "db_systems.0.hostname": "ebsazdbash11",
                            "db_systems.0.id": "ocid1.dbsystem.oc1.iad.abuwcljt7uoi7fzua6abgdd6y7wvx5kbirlfyoffwecoej4px6757nwalnya",
                            "db_systems.0.iorm_config_cache.#": "0",
                            "db_systems.0.last_patch_history_entry_id": "",
                            "db_systems.0.license_model": "LICENSE_INCLUDED",
                            "db_systems.0.lifecycle_details": "",
                            "db_systems.0.listener_port": "1521",
                            "db_systems.0.node_count": "2",
                            "db_systems.0.reco_storage_size_in_gb": "256",
                            "db_systems.0.scan_dns_record_id": "ocid1.vcndnsrecord.oc1.iad.abuwcljtup5zjgyrlwtl5o5sgernv4v6d43tkrttr3lrh4lpzaibyjowsdfa",
                            "db_systems.0.scan_ip_ids.#": "3",
                            "db_systems.0.scan_ip_ids.0": "ocid1.privateip.oc1.iad.aaaaaaaabosjfj5mnxln3wa6rghlud6zjadwcnm27flymvuerrakaffs27na",
                            "db_systems.0.scan_ip_ids.1": "ocid1.privateip.oc1.iad.aaaaaaaaa7vilohnazitwdaz5fhqdqpd66zkd4njcr36s7dw5jh2nsstdmea",
                            "db_systems.0.scan_ip_ids.2": "ocid1.privateip.oc1.iad.aaaaaaaal252xdtn43bgzkdmsj3yo5pgwsdmssux3coqk32igfdcsxeb6baa",
                            "db_systems.0.shape": "VM.Standard2.8",
                            "db_systems.0.source": "",
                            "db_systems.0.sparse_diskgroup": "false",
                            "db_systems.0.ssh_public_keys.#": "1",
                            "db_systems.0.ssh_public_keys.0": "xxxxxxx",
                            "db_systems.0.state": "AVAILABLE",
                            "db_systems.0.subnet_id": "ocid1.subnet.oc1.iad.aaaaaaaaspfzmx4zxrrc2oacaamzkf5j3oko37aslysi2wrkuwriiuf4t46a",
                            "db_systems.0.time_created": "2019-08-12 08:28:16.272 +0000 UTC",
                            "db_systems.0.time_zone": "UTC",
                            "db_systems.0.version": "18.6.0.0.190416",
                            "db_systems.0.vip_ids.#": "2",
                            "db_systems.0.vip_ids.0": "ocid1.privateip.oc1.iad.aaaaaaaaxl5rqt7puth5hkpseojzqiqps27b47maifnpobitzg3o4ot4fjeq",
                            "db_systems.0.vip_ids.1": "ocid1.privateip.oc1.iad.aaaaaaaagnau3vvvd274bu4p6xczarowjtqttgb5x7dvmdcvt46ec75gngha",
                            "filter.#": "1",
                            "filter.165605606.name": "display_name",
                            "filter.165605606.regex": "false",
                            "filter.165605606.values.#": "1",
                            "filter.165605606.values.0": "ebsazdbash11",
                            "id": "2019-08-13 08:12:17.663482033 +0000 UTC"
                        },

**Comment by afedorch** [comment]
@rishimahajan
Looks like a common request to the API, could you please add more details for the scenario you are trying to achieve with the config? 
Are you able to get SCAN name by console/CLI? Thanks!

**Comment by afedorch** [comment]
@rishimahajan
As per the service team's response, there is no public API for SCAN name now. We have shared the service request with you. thanks!

**Comment by rishimahajan** [comment]
This is for a multi cloud deployment scenario where terraform is creating database on OCI and has to pass SCAN name to another provider. As a workaround, i have generated the SCAN using <hostname>-scan.domain. But would prefer an API call to do that. I'll add more details in service request and follow with the team. Thanks for the update.
