### ISSUE TITLE
nsg_ids in oci_core_instance create_vnic_details does not take list values

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#849]
./terraform version
Terraform v0.11.13
+ provider.external v1.1.2
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.oci v3.26.0
+ provider.template v2.1.2
+ provider.tls v2.0.1

OCI resource "oci_core_instance"

Problem description:
Trying to incorporate nsg_ids  in our terraform code. However, it is not taking values defined in standard list formate. Tried following combinations:

1. in tf code
nsg_ids                 = ["ocid1.networksecuritygroup.ababa"]

error:  
Error: module.compute.oci_core_instance.compute_node_nsg: create_vnic_details.0: invalid or unknown key: nsg_ids

2.  in tf code
nsg_ids                 = '["ocid1.networksecuritygroup.ababa"]'

error:  
Error: module.compute.oci_core_instance.compute_node_nsg: create_vnic_details.0: invalid or unknown key: nsg_ids

3.  with TF_VAR

TF_VAR_nsg_ids= ["ocid1.networksecuritygroup.ababa"]

same error. Tried couple of things.

Can you help by providing working example if  possible?

Thank you.

**Comment by afedorch** [comment]
Support for Network Security Groups was added in v3.33.0:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md#3330-july-10-2019

you are using provider.oci v3.26.0, could you update the provider and give it a try? Thanks!

you can find an example here: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/networking/network_security_group/network_security_group.tf#L130

**Comment by wggit** [comment]
Thank you.  That worked.
