### ISSUE TITLE
kms decrypted value datasource schema field not marked as sensitive

### ISSUE THREAD

**Issue by anilarora** [terraform-providers/terraform-provider-oci#850]
### Terraform Version and Provider Version

terraform.oci 3.37.0

### Affected Resource(s)

datasource kms_decrypted_data 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/kms_decrypted_data_data_source.go

The schema field plaintext and plaintext_checksum should be marked as Sensitive: true

```hcl
			// Computed
			"plaintext": {
				Type:     schema.TypeString,
				Computed: true,
                                Sensitive: true,
			},
			"plaintext_checksum": {
				Type:     schema.TypeString,
				Computed: true,
                                Sensitive: true,
			},
```

The main issue is that currently, the plaintext value is being stored in the statefile.  This should be hidden the statefile.  This could be a case where the datasource should automatically reach out to the service every time.

**Comment by afedorch** [comment]
@anilarora thanks for reporting it! Could share the use case that you are trying to address with this request? 
my understanding is that the datasource exports only these two attributes and it the reason why it was added: `Decrypts data using the given DecryptDataDetails resource` https://www.terraform.io/docs/providers/oci/d/kms_decrypted_data.html

**Comment by anilarora** [comment]
The use case I'm looking at is in #847.  I have to decrypt the data before passing it into the database resource as plaintext.  What I see in the statefile is that the plaintext value is getting recorded as is when we want do hide it.

**Comment by afedorch** [comment]
@anilarora  you see the password value in the state file as part of the oci_database_autonomous_database resource, correct? 
The `admin_password` is marked as `Sensitive` but the value exists in the state file, please see hashicorp/terraform#516 for more details. We will check what is the best solution on the provider side for the reported problem.

do we need this issue open to modify kms_decrypted_data_data_source? thanks!

**Comment by anilarora** [comment]
Yes. I see the password in the state file even if the value is set to sensitive. I think the flag only affects logging right now. 

So I see this issue in multiple places.  My guess that this should be a comprehensive fix across various data sources and resources. 

Unfortunately the product level fix isn’t coming in any time soon so we are looking for fixes in the OCI provider since that’s we use.

**Comment by afedorch** [comment]
@anilarora  `kms_decrypted_data_data_source` is added to export `plaintext` and `plaintext_checksum` attributes values. You can find more details for the scenario you mentioned #847 in the https://github.com/hashicorp/terraform/issues/21758 It looks that for now there is no scenario when we need to mark these attributes as `sensitive`. thanks!
