### ISSUE TITLE
resource type: database tag and db system tag

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#862]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Hi 
I am working on TF automation for OCI db system.
What I am seeing is that we can set the tag for the db system. what about database resource?
Can I use same format of tag for database resource type ?

Jerry

**Comment by rcohenma** [comment]
You can specify tags for the database in the db_system in the same way:
https://www.terraform.io/docs/providers/oci/r/database_db_system.html#defined_tags

if it is an additional database then you can specify it as part of the db_home resource:
https://www.terraform.io/docs/providers/oci/r/database_db_home.html#defined_tags
