### ISSUE TITLE
Create tag_namespace and tag_names using list of objects

### ISSUE THREAD

**Issue by damtst** [terraform-providers/terraform-provider-oci#863]
Hello,

not sure if this has been answered before.

I have a requirement to create tag using OCI following this pattern:

namespace: Operations
tag: Environment
tag: CostCenter
namespace: departments
tag: HR
tag: IT
tag: Network

so far I have defined a variable as follows:

```
variable “tags” {
description = “test”
type = list(object({
tag_namespace = string
tag_namespace_description = string
tag_name = list(string)
}))
default = [
{
tag_namespace = “Operations”
tag_namespace_description = “tag to represent operations”
tag_name = [“Environment”, “CostCenter”]
},
{
tag_namespace = “departments”
tag_namespace_description = “tag to represent departments”
tag_name = [“HR”,“IT”,“Network”]
},
]
}

```
so far I can create the namespaces (resource “oci_identity_tag_namespace” “test_tag_namespace”).

The problem I am having is to create the tags (resource “oci_identity_tag” “test_tag”) for each namespace, basically, iterate the structure so I call resource “oci_identity_tag” “test_tag” for each tag of each namespace.

any help will be appreciated.

Versions:

```
Terraform v0.12.7
provider.oci v3.33.0
provider.template v2.1.0
```

**Comment by rcohenma** [comment]
Hello,
Have you seen this doc: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each
The last example on the "Dynamic Nested Blocks" section seems similar to what you need

**Comment by damtst** [comment]
Hello,

Yes and several times. Can you please tell me where exactly mention swere to call two different resources and scan a list (object(list of strings?

Thank you

**Comment by rcohenma** [comment]
I see, you are right that the example I mentioned doesn't cover your case.

It will take some time for us to investigate and help you find a solution.

This is a generic question on terraform 0.12 functionality so I think you will have better luck posting here: https://github.com/hashicorp/terraform

**Comment by damtst** [comment]
Hello, 

I already raised the question on Hashicorp/terraform forum but so far no luck.

it seems all examples are based on azure/aws.

Thank you

**Comment by rhuesken** [comment]
Hi,

We use the following structure for our variable:

```
variable "TAG_PARAMS" {
   type = object({
      NAMESPACE   = string
      DESCRIPTION = string
      NS_RETIRED  = bool
      TAGS_LIST   = list(tuple([string, string, bool, bool]))
    })
    default = {
      NAMESPACE   = "Template"
      DESCRIPTION = "Namespace Description"
      NS_RETIRED  = false 
      TAGS_LIST   = [ ["Tag1", "Tag 1 description", false, false]
                    , ["Tag2", "Tag 2 description", false, false]
                    ]
    }
}
```

We the create the tag namespace:
```
resource "oci_identity_tag_namespace" "MyTagNamespace" {
  #Required
  compartment_id = var.compartment_ocid
  description    = var.TAG_PARAMS.DESCRIPTION
  name           = var.TAG_PARAMS.NAMESPACE

  is_retired = var.TAG_PARAMS.NS_RETIRED
}
```


Finally, we use the following code to create the tags:
```
resource "oci_identity_tag" "MyTag" {
  #Required
  count            = length(var.TAG_PARAMS.TAGS_LIST)
  name             = element(flatten(var.TAG_PARAMS.TAGS_LIST),count.index*4)  
  description      = element(flatten(var.TAG_PARAMS.TAGS_LIST),count.index*4+1)

  tag_namespace_id = oci_identity_tag_namespace.MyTagNamespace.id

  #Optional
  is_cost_tracking = element(flatten(var.TAG_PARAMS.TAGS_LIST),count.index*4+2)
  is_retired       = element(flatten(var.TAG_PARAMS.TAGS_LIST),count.index*4+3)

}
```

Does that help ?

**Comment by rhuesken** [comment]
You might need to rewrite things a bit to support multiple tag namespaces in a single datastructure, or use a single file for each tag namespace (which is what we prefer).

**Comment by damtst** [comment]
Hello @rhuesken, 

thank you for the heads up and giving me another point of view. I will see if I can integrate it with our configuration.

I will keep you posted.

Cheers.

**Comment by abhilash-av** [comment]
Hello @damtst 

The below solution is one way to solve the issue you are facing.
This is as per hashicorp's recommendation in https://discuss.hashicorp.com/t/nested-loop-using-github-provider/2837


variable "tags" {
  description = "test"
  type = list(object({
    tag_namespace             = string
    tag_namespace_description = string
    tag_name                  = list(string)
  }))
  default = [
    {
      tag_namespace             = "Operations"
      tag_namespace_description = "tag to represent operations"
      tag_name                  = ["Environment", "CostCenter"]
    },
    {
      tag_namespace             = "departments"
      tag_namespace_description = "tag to represent departments"
      tag_name                  = ["HR", "IT", "Network"]
    },
  ]
}

locals {
  tags = flatten([
    for tag in var.tags : [
      for tag_name in tag.tag_name : {
        namespace   = tag.tag_namespace
        description = tag.tag_namespace_description
        tag         = tag_name
      }
    ]
  ])
}

resource "oci_identity_tag_namespace" "TagNamespace" {
  compartment_id = "${var.compartment_ocid}"
  for_each = {
    for rc in var.tags :
    "${rc.tag_namespace}" => rc
  }
  name        = each.value.tag_namespace
  description = each.value.tag_namespace_description
}

resource "oci_identity_tag" "MyTag" {
  for_each = {
    for t in local.tags :
    "${t.namespace}:${t.tag}" => t
  }

  name        = each.value.tag
  //As description is mandatory for tag using the same as tag_namespace_description
  description = each.value.description

  tag_namespace_id = oci_identity_tag_namespace.TagNamespace[each.value.namespace].id
}

I will close the ticket for now.
