### ISSUE TITLE
"access_uri": this field cannot be set

### ISSUE THREAD

**Issue by torstenstern** [terraform-providers/terraform-provider-oci#864]
Hello,

i am trying to set the following parameters in the "oci_objectstorage_preauthrequest"

#Create a pre-authenticated request
resource "oci_objectstorage_preauthrequest" "test_preauthenticated_request" {
    #Required
    access_type     = "${var.preauthenticated_request_access_type}" 
    bucket          = "${var.bucket_name}"
    name            = "${var.preauthenticated_request_name}"
    namespace       = "${var.bucket_namespace}"
    time_expires    = "${var.preauthenticated_request_time_expires}"
    object          = "${var.object_name}"
    access_uri      = "https://objectstorage.${var.region}.oraclecloud.com/${var.access_uri}"
}

But as soon then i apply the the code i get the following back.

> Error: "access_uri": this field cannot be set
> on main.tf line 19, in resource "oci_objectstorage_preauthrequest" "test_preauthenticated_request": 19: resource "oci_objectstorage_preauthrequest" "test_preauthenticated_request" {

I followed this example: https://www.terraform.io/docs/providers/oci/r/objectstorage_preauthrequest.html

I am using Terrafrom v0.12.6 and provider.oci v3.40.0

Thanks for your help

**Comment by rcohenma** [comment]
access_uri is not an argument of the resource so you cannot set it.
https://www.terraform.io/docs/providers/oci/r/objectstorage_preauthrequest.html

We use the word argument to refer to parameters you can set in the resource

We use the word attribute to refer to properties you can read from the resource if the service returns them

**Comment by torstenstern** [comment]
@rcohenma sorry but i dont get it, how can i set the then access_uri or can i get the output?
I tried several scenarios and nothing is working.
