### ISSUE TITLE
Importing OCI Pre-Authenticated Request (PAR) fails

### ISSUE THREAD

**Issue by acarvalhopt** [terraform-providers/terraform-provider-oci#867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.7
provider.oci: version = "~> 3.40"

### Affected Resource(s)

oci_objectstorage_preauthrequest

### Terraform Configuration Files

```
resource "oci_objectstorage_preauthrequest" "PRD_TERRAFORM_STATE_PAR" {
  namespace    = "namespace"
  bucket       = "${oci_objectstorage_bucket.PRD_TERRAFORM_TFSTATE.name}"
  object       = "${oci_objectstorage_object.terraform_tfstate.object}"
  name         = "PRD_TERRAFORM_STATE_PAR"
  access_type  = "ObjectReadWrite"                                       // ObjectRead, ObjectWrite, ObjectReadWrite, AnyObjectWrite
  time_expires = "2020-02-07T17:20:00Z"
}
```
### Expected Behavior

It was supposed to import a Pre-Authenticated Request (PAR) with success.

### Actual Behavior

When tried to import got a error:
`Error: can not marshal to path in request for field NamespaceName. Due to can not marshal a nil pointer
`

### Steps to Reproduce

What was found is that if the PAR ID generated by OCI has a "slash ( / )"  in the middle of the ID i can't import the resource, i tried to escape the character but without success.

Here is an example that NOT work:
1. `terraform import oci_objectstorage_preauthrequest.PRD_TERRAFORM_STATE_PAR "n/namespace/b/PRD_TERRAFORM_TFSTATE/p/1FuV7wYGgb1DKUDOl/4UPJlEvvs4BU6+QwqDK24macU=:terraform.tfstate"`

Here is an example that WORK:
1. `terraform import oci_objectstorage_preauthrequest.PRD_TERRAFORM_STATE_PAR "n/namespace/b/PRD_TERRAFORM_TFSTATE/p/irkEYKcgAstYckhxCHkrrnnkI+cC2k6KvlkMZPEt6TM=:terraform.tfstate"`

**Comment by parrneet** [comment]
Hi @zordlyon 

Thank you for reporting this. It looks like a bug in provider. We will plan a fix for this.

**Comment by alexng-canuck** [comment]
@zordlyon

As a possible workaround, can you try replacing "/" in the import command with a hex representation? So replace `/` with `%2F` in the preauth part of the ID.

`1FuV7wYGgb1DKUDOl/4UPJlEvvs4BU6+QwqDK24macU=:terraform.tfstate` becomes `1FuV7wYGgb1DKUDOl%2F4UPJlEvvs4BU6+QwqDK24macU=:terraform.tfstate`
