### ISSUE TITLE
Mapping tf resources to an inconsistent datamodel for the OCI File Storage Resources

### ISSUE THREAD

**Issue by cosmindev** [terraform-providers/terraform-provider-oci#870]
The OCI FSS containins the following resources:

- oci_file_storage_export
- oci_file_storage_export_set
- oci_file_storage_file_system
- oci_file_storage_mount_target
- oci_file_storage_snapshot

Those resources should map to the corresponding objects in the OCI FSS REST API and they do. 
The issue is created by an inconsistency in mapping the relationship between the oci_file_storage_mount_target and oci_file_storage_export_set. 

**OCI REST API Mapping the relation between mount_targets and export_sets**

- Many mount_targets(mount_target.export_set_id) to one export_set
- Many to one relation between mount_targets and export_sets

- mount_targets
https://docs.cloud.oracle.com/iaas/api/#/en/filestorage/20171215/MountTarget/

```
{
  "availabilityDomain": "pWEh:PHX-AD-2",
  "compartmentId": "ocid1.compartment.oc1..examplea4ssrz2joq66nyomcvb4ydlbfmn2qg7wow5neo2ytcdznohhsyca",
  "displayName": "mount-target-5",
  "exportSetId": "ocid1.exportset.oc1.phx.exampleaaaaacvbobuhqllhmfwwcotqnb4c2ylefuzaaaaa",
  "id": "ocid1.mounttarget.oc1.phx.exampleaaaaaafcvbobuhqllhmfwwcotqnb4c2ylefuzaaaaa",
  "lifecycleDetails": "",
  "lifecycleState": "ACTIVE",
  "privateIpIds": [
  "ocid1.privateip.oc1.phx.examplet6rxwzfauxvmlhuvh4z3rhmyyucik6u5pl4qai6dulsfeerr7nsma"
      ],
  "subnetId": "ocid1.subnet.oc1.phx.exampleale662rd2rcvbqi5dlerqvfcobnjs5h4h7ssosxwo4fu7mjvp2ia",
  "timeCreated": "2017-12-01T22:13:22.534Z"
 }
```

- export_sets
https://docs.cloud.oracle.com/iaas/api/#/en/filestorage/20171215/ExportSet/

```
{
 "availabilityDomain": "pWEh:PHX-AD-2",
 "compartmentId": "ocid1.compartment.oc1..examplea4ssrz2joq66nyomcvb4ydlbfmn2qg7wow5neo2ytcdznohhsyca",
 "displayName": "mount-target-5 - export set",
 "id": "ocid1.exportset.oc1.phx.exampleaaaaaafcvbobuhqllhmfwwcotqnb4c2ylefuzaaaaa",
 "lifecycleState": "ACTIVE",
 "maxFsStatBytes": 9223372036854775807,
 "maxFsStatFiles": 9223372036854775807,
 "timeCreated": "2017-12-01T22:35:59.954Z",
 "vcnId": "ocid1.vcn.oc1.phx.exampleafx7g55xhcvbquc2vv3c2adknvo3d6j2t6vfljy6gkxz6xutfwjxa"
}
```

**Terraform provider mapping the relation between mount_targets and export_sets**

- Many export_sets(export_set.mount_target_id) to one mount_target
- Many to one relation between export_sets and mount_targets

mount_targets:
https://www.terraform.io/docs/providers/oci/r/file_storage_mount_target.html
```
resource "oci_file_storage_mount_target" "test_mount_target" {
  #Required
  availability_domain = "${var.mount_target_availability_domain}"
  compartment_id      = "${var.compartment_id}"
  subnet_id           = "${oci_file_storage_subnet.test_subnet.id}"

  #Optional
  defined_tags   = { "Operations.CostCenter" = "42" }
  display_name   = "${var.mount_target_display_name}"
  freeform_tags  = { "Department" = "Finance" }
  hostname_label = "${var.mount_target_hostname_label}"
  ip_address     = "${var.mount_target_ip_address}"
}
```
export_sets:
https://www.terraform.io/docs/providers/oci/r/file_storage_export_set.html
```
resource "oci_file_storage_export_set" "test_export_set" {
    #Required
    mount_target_id = "${oci_file_storage_mount_target.test_mount_target.id}"

    #Optional
    display_name = "${var.export_set_name}"
    max_fs_stat_bytes = 23843202333
    max_fs_stat_files = 223442
}
```
![fss-data-model](https://user-images.githubusercontent.com/9591602/64411684-6d5d1780-d096-11e9-96a1-d5df8a26b6f8.jpg)

**Symptoms**
Input - mount_targets and export_sets.
As per tf resources definitions, I'm creating multiple export_sets that are referencing the same mount_target - it should be the other way around: an export_set used by multiple mount targets.
This use-case is crucial as sharing mount_targets across multiple fss is a common practice.
The mechanism it should be the one defined by the relations in the rest API. For example:

1. define 2 X FSS
2. define 1 x export_sets
3. define 1 x mount target
- mount_target_1 reference the export_set_1
5. define 2 exports:
- export_1: links fss_1 with mt_1 via fss_1_id <->(exports.fs_id)exports(exports.export_set_id) <-> export_set <-> (export_set_id)mount_target
- export_2: links fss_2 with mt_1 via fss_2_id <->(exports.fs_id)exports(exports.export_set_id) <-> export_set <-> (export_set_id)mount_target

Instead of the behavior above, terraform resources allows you to define multiple export_sets for a mount target.

```
mount_targets = {
  mt1 = {
    ad             = 1
    subnet_id      = "ocid1.subnet.ocxxxx"
    hostname_label = "mt1"
    ip_address     = null
    compartment_id = null
    defined_tags   = null
    freeform_tags  = null
  }
 
  mt2 = {
    ad             = 1
    subnet_id      = "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaxxxx"
    hostname_label = "mt2"
    ip_address     = null
    compartment_id = null
    defined_tags   = null
    freeform_tags  = null
  }
 
}
 
export_sets = {
  fs1_mt1_export_set1 = {
    max_fs_stat_bytes = 23843202333
    max_fs_stat_files = 223442
    mount_target      = "mt1"
  }
  fs1_mt2_export_set1 = {
    max_fs_stat_bytes = 23843202333
    max_fs_stat_files = 223442
    mount_target      = "mt2"
  }
  fs2_mt1_export_set1 = {
    max_fs_stat_bytes = 23843202333
    max_fs_stat_files = 223442
    mount_target      = "mt1"
  }
  fs2_mt2_export_set1 = {
    max_fs_stat_bytes = 23843202333
    max_fs_stat_files = 223442
    mount_target      = "mt2"
  }
}
```

- TF automation output - duplicating exports sets - please notice the duplicate id.

```
"export_sets" = [
    {
      "availability_domain" = "uFjs:EU-FRANKFURT-1-AD-1"
      "compartment_id" = "ocid1.compartment.oc1.xxxxxx"
      "display_name" = "fs1_mt1_export_set1"
      "id" = "ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2so6huemzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "max_fs_stat_bytes" = "23843202333"
      "max_fs_stat_files" = "223442"
      "mount_target_id" = "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaaa4np2so6hufmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "state" = "ACTIVE"
      "time_created" = "2019-09-05 18:12:49 +0000 UTC"
      "vcn_id" = "ocid1.vcn.oc1.eu-frankfurt-1.aaaaaaaapg6nhfxxxxxx"
    },
    {
      "availability_domain" = "uFjs:EU-FRANKFURT-1-AD-1"
      "compartment_id" = "ocid1.compartment.oc1..xxxx"
      "display_name" = "fs1_mt2_export_set1"
      "id" = "ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxhyib6mzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "max_fs_stat_bytes" = "23843202333"
      "max_fs_stat_files" = "223442"
      "mount_target_id" = "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaacvippxhyib7mzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "state" = "ACTIVE"
      "time_created" = "2019-09-05 18:12:49 +0000 UTC"
      "vcn_id" = "ocid1.vcn.oc1.eu-frankfurt-xxxxx"
    },
    {
      "availability_domain" = "uFjs:EU-FRANKFURT-1-AD-1"
      "compartment_id" = "ocid1.xxxxx"
      "display_name" = "fs2_mt1_export_set1"
      "id" = "ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2so6huemzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "max_fs_stat_bytes" = "23843202333"
      "max_fs_stat_files" = "223442"
      "mount_target_id" = "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaaa4np2so6hufmzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "state" = "ACTIVE"
      "time_created" = "2019-09-05 18:12:49 +0000 UTC"
      "vcn_id" = "ocid1.vcn.oc1.eu-frankfurt-xxxxx"
    },
    {
      "availability_domain" = "uFjs:EU-FRANKFURT-1-AD-1"
      "compartment_id" = "ocid1.compartment.xxx"
      "display_name" = "fs2_mt2_export_set1"
      "id" = "ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxhyib6mzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "max_fs_stat_bytes" = "23843202333"
      "max_fs_stat_files" = "223442"
      "mount_target_id" = "ocid1.mounttarget.oc1.eu_frankfurt_1.aaaaacvippxhyib7mzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa"
      "state" = "ACTIVE"
      "time_created" = "2019-09-05 18:12:49 +0000 UTC"
      "vcn_id" = "ocid1.vcn.ocxxxx"
    },
  ]
```
- Actually it just creates the right number of export_sets, aleatory picking from the list of 4 above:
```
XXXXX-mac:~ XXXXX-mac$ oci fs export-set list --compartment-id ocid1.compartment.oc1..aaaaaaaacnmuyhg2mpb3z6v6egermq47nai3jk5qaoieg3ztinqhamalealq  --availability-domain uFjs:EU-FRANKFURT-1-AD-1
 
{
 
  "data": [
 
    {
 
      "availability-domain": "uFjs:EU-FRANKFURT-1-AD-1",
 
      "compartment-id": "ocid1.compartment.oc1..xxxxx",
 
      "display-name": "fs1_mt1_export_set1",
 
      "id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaaa4np2so6huemzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
 
      "lifecycle-state": "ACTIVE",
 
      "time-created": "2019-09-05T18:12:49+00:00",
 
      "vcn-id": "ocid1.vcn.oc1.eu-frankfurt-1xxxxx"
 
    },
 
    {
 
      "availability-domain": "uFjs:EU-FRANKFURT-1-AD-1",
 
      "compartment-id": "ocid1.compartment.oc1..aaddddd",
 
      "display-name": "fs2_mt2_export_set1",
 
      "id": "ocid1.exportset.oc1.eu_frankfurt_1.aaaaacvippxhyib6mzzgcllqojxwiotfouwwm4tbnzvwm5lsoqwtcllbmqwtgaaa",
 
      "lifecycle-state": "ACTIVE",
 
      "time-created": "2019-09-05T18:12:49+00:00",
 
      "vcn-id": "ocid1.vcn.oc1.eu-frankfurt-1...."
 
    }
 
  ]
 
}
```

**Comment by abhilash-av** [comment]
Hello @cosmindev,

Thank you for bringing this up.

As per oracle docs, https://docs.cloud.oracle.com/iaas/Content/File/Concepts/filestorageoverview.htm export_sets and mount_targets and are 1:1 mapping. Multiple export_sets for the same mount_targets should not be configured in the terraform config. We will make note of this in the export_set document for OCI provider.

Alternatively,
If you are creating the export_set for purely export purposes and not for managing its properties, you could directly use the oci_file_storage_mount_target's export_set_id in the oci_file_storage_export resource.

I will close this ticket for now.

**Comment by cosmindev** [comment]
> Hello @cosmindev,
> 
> Thank you for bringing this up.
> 
> As per oracle docs, https://docs.cloud.oracle.com/iaas/Content/File/Concepts/filestorageoverview.htm export_sets and mount_targets and are 1:1 mapping. Multiple export_sets for the same mount_targets should not be configured in the terraform config. We will make note of this in the export_set document for OCI provider.
> 
> Alternatively,
> If you are creating the export_set for purely export purposes and not for managing its properties, you could directly use the oci_file_storage_mount_target's export_set_id in the oci_file_storage_export resource.
> 
> I will close this ticket for now.

Hi Abhilash,

I understand the documentation recommendation. But, to me this is still a bug, as the relation between the 2 objects is improperly defined, and this can generate issues as the one above.

I do not think this can be closed.

Thanks,
Cosmnin
