### ISSUE TITLE
Cluster Networking destroying error 

### ISSUE THREAD

**Issue by MarcinZablocki** [terraform-providers/terraform-provider-oci#871]
This happens every time on the first attempt running ```terraform destroy```. At this point terraform exits and running it again moves on to terminating other resources. 

```
Error: Error applying plan:

1 error occurred:
	* oci_core_cluster_network.cluster_network (destroy): 1 error occurred:
	* oci_core_cluster_network.cluster_network: unexpected state 'RUNNING', wanted target 'TERMINATED'. last error: %!s(<nil>)
```

**Comment by parrneet** [comment]
Hi @MarcinZablocki 

Please provide the complete TF configs so we can try to reproduce the issue.

**Comment by MarcinZablocki** [comment]
[cn_terraform_20190910.zip](https://github.com/terraform-providers/terraform-provider-oci/files/3592055/cn_terraform_20190910.zip) Attached.

**Comment by bowfeng** [comment]
Currently it is pending on deployment.

**Comment by varmax2511** [comment]
Hi @MarcinZablocki a fix has been deployed by the service for this issue. Can you please confirm if its fixed at your end?

**Comment by afedorch** [comment]
@MarcinZablocki we are closing the issue please feel free to reopen if you still see the problem. thanks!
