### ISSUE TITLE
oci_waas_certificate is it possible to use a file for the certificates ?

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#876]
Hi 
I m trying to create certificates for the waaf
im trying to upload them by reading the content of the file as below but i m getting an error

if i copy paste the content as 
  certificate_data = "-----BEGIN CERTIFICATE-----\nMIIGYzCCBUugAwIBAgISBO73/6rXXw3cGwK1jDiQ31n6MA0GCSqGSIb
 private_key_data ="---- ...

the call works fine, but not the code below where i m trying to do the same with the "file call"  is there any obvious error ?

resource "oci_waas_certificate" "waf_policy_certificate" {
  compartment_id   = "${var.compartment_ocid}"
  
  certificate_data = "${file("${var.ssh_certificate_data}"))}"
  private_key_data = ${file("${var.ssh_private_key_data}")}"

**Comment by kumar-dhanagopal** [comment]
With v12, the following should work:

`certificate_data = file(var.ssh_certificate_data)`
