### ISSUE TITLE
can you please provide full life cycle managment for the waas certificate

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#877]
The oci cli and the REST API are giving full managment capabilities for the Waas certificates which are missing from the provider and then we have to combine oci cli commands to delete them 
Can you pleas provide the same level of service like delete / update ?
Thanks
Eugene

**Comment by bowfeng** [comment]
We do support delete and update.
if you want to delete waas certificate. in your tf script, just remove resource "oci_waas_certificate" block. 

if you want to update wass certificate, change the properties in resource "oci_waas_certificate" block.

**Comment by eugsim1** [comment]
if there are any created cert how can i delete them if i havent create them with the api does the import  ressource works on this case ?

**Comment by bowfeng** [comment]
Yes. If the resource is not created by Terraform, you need to import it first, then remove it.
