### ISSUE TITLE
matching rules for oci_identity_dynamic_group should be a list

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When creating a dynamic group, it is possible to specify more than 1 rule in the console. However, the oci_identity_dynamic_group resource and the oci_identity_dynamic_groups data source allow adding or retrieving only 1 rule

### New or Affected Resource(s)

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```
resource "oci_identity_dynamic_group" "mydynamicgroup" {
  ....
  matching_rule  = "[local.rule_1, local.rule2]"  //similar to how subnet security list ids can be passed in an array
}

**Comment by kilokahn** [comment]
Hey @hyder - We can specify a rich set of rules via the grammar specified at https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingdynamicgroups.htm#writerules . Specifically, to associate multiple rules, can use the `any` keyword.

I looked through the console experience, and the `any` keyword is being explicitly appended to the matching rule when it is added for the individual rules, which is not necessary if the actual rule is used. So while the experience is different, it seems redundant to reimplement this in the Terraform experience, given that the array representation in TF corresponds to the `any` keyword and is not as expressive as the grammar supported at https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingdynamicgroups.htm#writerules
Thoughts?

**Comment by kilokahn** [comment]
@hyder if there are no objections to the suggestion, we can close this one out. Thanks.

**Comment by hyder** [comment]
Thanks for the suggestion. 

Can you please provide 1 example in the examples directory? I'll close the issue afterwards.
