### ISSUE TITLE
Error: can not create client, bad configuration: did not find a proper configura tion for private key

### ISSUE THREAD

**Issue by pramod4555** [terraform-providers/terraform-provider-oci#880]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Hi i have configured terrafrom oci in windows facing issues when i hit terraform plan 
error

Error: can not create client, bad configuration: did not find a proper configura
tion for private key

  on oci.tf line 1, in provider "oci":
   1: provider "oci" {

this is the  error
i have configured my private key path as
private_key_path = "D:\oci\oci_api_key"
please privde my the tfvars files for windows environment terraform oci variables

**Comment by bowfeng** [comment]
@pramod4555 
   Can you add file extension for your private key path and try it again?

**Comment by pramod4555** [comment]
Hi thanks 
but this the new error which i got

Error: Invalid escape sequence

  on det.tfvars line 4:
   4: private_key_path = "D:\oci\oci_api_key.pem"

The symbol "o" is not a valid escape sequence selector.

**Comment by kumar-dhanagopal** [comment]
Try "escaping" the "\" characters in the path:

`private_key_path = "D:\\oci\\oci_api_key.pem"`

**Comment by bowfeng** [comment]
close it for now. feel free to open it if you still have the problem

**Comment by pramod-art** [comment]
Thank you.. 

My script  got executed after trying escaping \ with Kumar dhanagopal suggestions..
