### ISSUE TITLE
Limit nonephemeral-regional-publicip-per-tenant of 2 has been already reached

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#883]
terraform version
Terraform v0.11.14
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.oci v3.43.0

Problem statement:

Creating private LBaaS using LBaaS subnet getting following error. This is Subnet Type: Regional

Error:

While creating a private LBaaS got this error - * oci_load_balancer_load_balancer.XYT_LBaaS_001: WorkRequest FAILED: [{ ErrorCode=BAD_INPUT Message=com.oracle.pic.commons.client.exceptions.RestClientException: Limit nonephemeral-regional-publicip-per-tenant of 2 has been already reached. }]

thank you.

**Comment by wggit** [comment]
this is Subnet Type: Regional

**Comment by kilokahn** [comment]
@wggit - thanks for reporting this. It looks like you have exhausted the limit defined for your tenancy. Have you already gone through the https://docs.cloud.oracle.com/iaas/Content/General/Concepts/servicelimits.htm doc for the background on service limits?  If yes, do you think this is a bug in the terraform provider?

**Comment by wggit** [comment]
Thank you @kilokahn that helped.
