### ISSUE TITLE
"unknown resource 'iam.principal' referenced in variable iam.principal.name"

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#884]
terraform version
Terraform v0.11.13
+ provider.external v1.2.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.oci v3.44.0
+ provider.random v2.2.0
+ provider.template v2.1.2
+ provider.tls v2.1.0

Trying to incorporate defined tags using 'variable tag' in compute creation using terraform
https://docs.cloud.oracle.com/iaas/Content/Identity/Concepts/taggingoverview.htm section 'Using Tag Variables' CreatedBy tag is a defined tag

"tagnamespace.username"= "${iam.principal.name}"

Error: 
"unknown resource 'iam.principal' referenced in variable iam.principal.name"

Please advise how to proceed.
Appreciate help.
Thank you.

**Comment by priteshkp** [comment]
Can you paste the full resource definition?  Most likely you have no escaped the string correctly, and terraform is interpolating it instead of sending the literal.

**Comment by wggit** [comment]
defined_tags = {
                  "tagnamespace.tag1"= "tag1_value"
                  "peo-applications.username"= "${iam.principal.name}"
                 }

**Comment by priteshkp** [comment]
See https://www.terraform.io/docs/configuration-0-11/interpolation.html

> You can escape interpolation with double dollar signs: $${foo} will be rendered as a literal ${foo}.

Add an extra '$' and try again.

**Comment by kilokahn** [comment]
Thanks @priteshkp for the suggestion - that is the right way. 

@wggit - can you paste the exact error you are seeing - I don't think you'd get the ""unknown resource 'iam.principal' referenced in variable iam.principal.name"" error - but something different

**Comment by wggit** [comment]
Thank you. 

 ./terraform plan -target=module.compute-instance..oci_core_instance.instance10

Error: resource 'oci_core_instance.instance10' config: unknown resource 'iam.principal' referenced in variable iam.principal.name

**Comment by wggit** [comment]
I see actually it worked with  

"tagnamespace.username"= "$${iam.principal.name}"

**Comment by wggit** [comment]
Thank you Pritesh and kilokahn appreciate your time and help.
