### ISSUE TITLE
would be possible to provide a better documentation to oci terraform provider

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#887]
Hello
Reading the provider as it is the calls and navigating between the data source or the core call its a hell of work. Several references are truncated i  m struggling to find out what are the correct calls to create an autonomous, before i was struggling with the compute, its not feasible the way that you present the references.
Would be possible to improve the presentation and even create a pdf file to download the implementation of the calls 
I m internal and i m spending a lot of time trying to copy paste, lookup for the references , the customers maybe are in the same position as me

for instance try to navigate to the autonomous part and you will see that most call are truncated 
even reducing the browser view down to 90% i m not seeing the full string and i have to click back and forth

Thanks

**Comment by alexng-canuck** [comment]
@eugsim1 can you give a link to the type of resource/datasource documentation that is causing issues for you?

Maybe a screenshot will also help us understand what you are seeing in your browser.

**Comment by twmcelroy** [comment]
Is this the best place to submit these requests? 
I love the new layout with data sources and resources collapsable and separate. It make searching the page much easier by collapsing data source or the other. 

I was just curious where the best place to submit request was. For example, I am working with the oci_core_volume_backup_policy and neither the terraform documentation or OCI CLI documentation lays out the variable options very well (I still haven't figured out the format of time zone). Where can i submit this? Btw here is the documentation i'm speaking of:
https://www.terraform.io/docs/providers/oci/r/core_volume_backup_policy.html
https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/VolumeBackupSchedule

**Comment by parrneet** [comment]
A feature to allow people to submit feedback is on the roadmap.
 
However, in the meantime if you have an Oracle contact please pass the feedback. Otherwise, please open a ticket here and we can open a ticket.
