### ISSUE TITLE
autonomous cloning is not supported ?

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#888]
Hello
Its possible to clone an autonomous database. the steps are referenced here https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/clone-autonomous-database.html#GUID-D771796F-5081-4CFB-A7FF-0F893EABD7BC

We have a scenario where one autonomous database has to be cloned several times but i dont see any terraform call to perform this operation.
would be possible to implement this missing feature ?

**Comment by varmax2511** [comment]
Hi @eugsim1 -- thanks for reaching out. Yes, cloning is supported for autonomous database. Please refer: https://www.terraform.io/docs/providers/oci/r/database_autonomous_database.html

Below is an example

```
resource "oci_database_autonomous_database" "test_autonomous_database_source" {
  ....
  ...
}

resource "oci_database_autonomous_database" "test_autonomous_database" {
  ....
  ..
  clone_type = "FULL"
  source = "DATABASE"
  source_id = "${oci_database_autonomous_database.test_autonomous_database_source.id}"
}
```

Please let me know if this answers your question.

**Comment by eugsim1** [comment]
great many thanks

**Comment by eugsim1** [comment]
excellent thaks for the promt reply
