### ISSUE TITLE
Support for Token Based authentication for Oracle Cloud Infra (OCI)

### ISSUE THREAD

**Issue by manjeet-github** [terraform-providers/terraform-provider-oci#892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Terraform OCI provider doesn't support token based authentication. OCi is configured to use federated identities (SSO) and integrated with Azure AD. Auth Federation can happen with any auth tools like Okta, AD-Onprem etc. In this particular case it is Azure AD.

As part of this federation, the user usually logs in with their enterprise id which generates a config file and a token. Once this profile with the config and token is created, the user can interact with OCI and create resources from command line. Note: This token is valid for a certain time and then need to be regenerated.

It looks like OCI TF provider doesn't support this authentication mechanism where in the same is supported in OCI APIs using "oci session authenticate". The "oci session authenticate" launches a browser for authentication where in the user pass the AD credentials and it authenticate and close the browser. After this, the user can interact with OCI. This authentication also generates the config files and one of the files stores the token for the session.

### Potential Terraform Configuration

# Configure the Oracle Cloud Infrastructure provider with an API Key
provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "${var.region}"
}

### References
The issue is that our OCI Provider DOES not appear to support Token Based Authentication (See https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/clitoken.htm?Highlight=security_token_file) 

It supports API and Instance Principal based auth. (See https://www.terraform.io/docs/providers/oci/index.html#authentication) 

The ~/.oci/config file as a result of token based auth does not include the user_oci field which our provider needs

**Comment by jotruon** [comment]
Terraform support Token Based Authentication from version 3.81.0.

**Comment by alexng-canuck** [comment]
More specifically, this is how to use it: https://www.terraform.io/docs/providers/oci/index.html#security-token-authentication
