### ISSUE TITLE
oci_identity_compartments."alias".id outputs creation_datetime

### ISSUE THREAD

**Issue by wjvanroosmalen** [terraform-providers/terraform-provider-oci#894]
when calling oci_identity_compartments data source:

```
data "oci_identity_compartments" "customer_compartment" {
  compartment_id = var.tenancy_ocid
  filter {
    name   = "name"
    values = ["base"]
  }
}
```

And outputting a variable like so:
```
output "output_locals" {
  value = data.oci_identity_compartments.customer_compartment.id
}
```

instead of returning the id like  expected it returns a datetime creation value.
I expected the ID of a compartment  named base..

this is the full object:
```
outputting_comp_list = [
  {
    "compartment_id" = "ocid1.tenancy.oc1..12345"
    "defined_tags" = {}
    "description" = "Base Compartment for Shared Resources"
    "enable_delete" = false
    "freeform_tags" = {}
    "id" = "ocid1.compartment.xxxx"
    "inactive_state" = ""
    "is_accessible" = false
    "name" = "base"
    "state" = "ACTIVE"
    "time_created" = "2019-09-25 08:37:38.259 +0000 UTC"
  },
]
```

outputting e.g. compartment_id results in:

```
output_locals = ocid1.tenancy.oc1..12345
```

outputting id results in:

```
output_locals = 2019-10-03 15:21:15.262367 +0000 UTC
```
What am i doing wrong? Or is it something with the oci_provider?

**Comment by varmax2511** [comment]
Hi @wjvanroosmalen -- thanks for reaching out to us. Every resource / data source in Terraform has an attribute `id` to uniquely identify it. When you are trying to output `id` attribute of the data source, it returns this unique identifier. Since you are interested in the attribute `compartment_id`, you need to modify the output to give value of `compartment_id`

```
output "output_locals" {
  value = data.oci_identity_compartments.customer_compartment.compartment_id
}
```
Please let me know if this helps!

**Comment by holeunlee** [comment]
Hi @wjvanroosmalen -- I have also encountered this problem before. Try using:

output "output_locals" {
  value = data.oci_identity_compartments.customer_compartment.compartments.*.id
}

**Comment by kumar-dhanagopal** [comment]
The issue appears to be that the data returned by `data.oci_identity_compartments.customer_compartment.compartments` contains a top-level compartments object and a nested level as well. Both levels have an "id" attribute.

```
compartments = {
  "compartment_id" = "ocid1.tenancy.oc1..."
  "compartments" = [
    {
      ...
      "id" = "ocid1.compartment.oc1.."
      ...
    },
    {
      ...
      "id" = "ocid1.compartment.oc1.."
      ...
    },
    ...
  ]
  "id" = "2019-10-04 16:12:26.8836528 +0000 UTC"
}
```
How do we get the "id" attribute from the nested level?

**Comment by varmax2511** [comment]
Hi @wjvanroosmalen @kumar-dhanagopal   -- To get the compartment id of the nested compartments use the below output

```
output "output_locals" {
  value = data.oci_identity_compartments.customer_compartment.compartments.*.id
}
```

However, I do notice the confusion here. In the nested compartments list, the attribute `compartment_id` refers to the parent compartment and the attribute `id` refers to the child compartment. In the top level `id` refers to the unique terraform identifier while compartment_id refers to compartment id passed

https://www.terraform.io/docs/providers/oci/d/identity_compartments.html

**Comment by kumar-dhanagopal** [comment]
Thank you, @varmax2511 !

**Comment by wjvanroosmalen** [comment]
great! thanks for all the tips @holeunlee @varmax2511. I got it now!
