### ISSUE TITLE
Free Tier Support

### ISSUE THREAD

**Issue by cruepprich** [terraform-providers/terraform-provider-oci#904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for OCI Free Tier resources.

### New or Affected Resource(s)

Always Free Autonomous Database
Always Free Compute Instance (VM.Standard.E2.1.Micro)

**Comment by bowfeng** [comment]
@cruepprich 
Currently Free Tier allows 2 compute instances with Micro shape and 1 ADW/ATP.
What resources are you looking for?

**Comment by parrneet** [comment]
Please refer to shape names for Compute and Load Balancer [here](https://docs.cloud.oracle.com/iaas/Content/FreeTier/resourceref.htm) 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/CHANGELOG.md#3440-september-18-2019

Closing the issue. Please reopen if you have any more questions.
