### ISSUE TITLE
Does FSS support NSG?

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#907]
Does FSS supports NSG in OCI?

Thank you.

**Comment by bowfeng** [comment]
@wggit 
Currently it doesn't support, however it is already on our radar and will be implemented in the near future.

**Comment by wggit** [comment]
Thank you. Do you know ETA or approximate date?

**Comment by bowfeng** [comment]
We don't have a date for it.

**Comment by parrneet** [comment]
Feedback has already been passed on to the service team. 
https://github.com/terraform-providers/terraform-provider-oci/issues/841
Closing the issue as there is already one logged for this enhancement.

**Comment by alexng-canuck** [comment]
FYI @wggit , this is now supported as of version 3.55.0 of the provider.

See https://registry.terraform.io/providers/hashicorp/oci/3.55.0/docs/resources/file_storage_mount_target#nsg_ids for more details
