### ISSUE TITLE
Add OCI provider version to terraform documentation

### ISSUE THREAD

**Issue by rhuesken** [terraform-providers/terraform-provider-oci#912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The terraform documentation for the OCI provider reflects the latest version of the provider.
It would be very helpful if the relevant oci provider version number 
was listed prominently in the documentation.

I spent a couple of hours trying to find out why I got the error "this field cannot be set" on the oci_core_instance resource when trying to set the launch options.
https://www.terraform.io/docs/providers/oci/r/core_instance.html#launch_options

Only after upgrading to the latest provider version, the "error" automagically disappeared...

I'd appreciate a hint to check my provider version sooner.

### New or Affected Resource(s)

All OCI resources

**Comment by alexng-canuck** [comment]
Hi @rhuesken , out of curiosity, what was the first document or page that you checked when you encountered this error?

We have a troubleshooting guide at: https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html

So I wonder if that would be the right place for adding hints on how to troubleshoot `this field cannot be set` errors.

Ideally, we should give the hint as part of the error message, but unfortunately "field cannot be set" errors are determined by Terraform command and not in the OCI provider.

**Comment by rhuesken** [comment]
Hi,
I started to check out the manuals for the OCI provider for the resource. Since those were related to the newest version of the provider, it did not seem I was doing anything wrong. 
My terraform configuration was not upgraded automatically however, and used an older version of the oci provider where this field was read-only.

I guess 'check your terraform versions with terraform --version' might be a good hint for the  "this field cannot be set" error on the troubleshooting page. Adding a line to the documentation which explicitly mentions the OCI provider version will also help people to check their versions.

**Comment by srishtipmishra** [comment]
Hi @rhuesken - We have updated the docs here - https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/troubleshooting#error-message-when-field-cannot-be-set

Hope this helps.
