### ISSUE TITLE
Add support for multiple remote .tfstate stored on OCI bucket

### ISSUE THREAD

**Issue by dralquinta** [terraform-providers/terraform-provider-oci#919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently under a scenario where I need to maintain several different .tfstates stored remotely on OCI buckets. Current feature uses a pre-created PAR to store it remotely as described in the following code snippet: 

```
terraform {
  backend "http" {
    update_method = "PUT"
    address       = "https://objectstorage.us-phoenix-1.oraclecloud.com/p/_WqQoGnjzyKmqoW0RysqViW-XCEMlOX_JmYM8-eBOh0/n/example/b/terraform-state/o/terraform.tfstate"
  }
}
```

Upon using wrapping tools (such as terragrunt) in order to support the separate 1 by 1 creation of artifacts, its required to use S3 storage to alter the name of .tfstate and store it remotely, similar to what's shown on below snippet - see foobar.tfstate declaration: 

```
terraform {
  backend "s3" {
    bucket   = "terraform-state"
    key      = "myfoobar.tfstate"
    region   = "us-phoenix-1"
    endpoint = "https://acme.compat.objectstorage.us-phoenix-1.oraclecloud.com"    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}
```

Today as a single .tfstate is supported for storage, plus requiring a PAR, it is difficult to handle this use case. Workarounds detected are either use terraform workspaces which in the end, will make it unmanageable to track or performing manual copies of .tfstate into a bucket or simply abandon the usage of remote .tfstates and leave them local with all problems that may bring. 

For understanding use case, consider the following scenario: 

Refering to usage of [Terragrunt wrapper](https://github.com/gruntwork-io/terragrunt) I'll create a separate project per each artifact I design. Say I pull [Registry Definition of Compute](https://registry.terraform.io/modules/oracle-terraform-modules/compute-instance/oci/2.0.1) and I want to programatically create multiple instances using the same tagged code using Terragrunt and following the DRY principle. I'll declare a single new resource on terragrunt using the same terraform backend code, similar to what's describe on below code snippet: 

```
terraform {
  # Deploy version v0.0.3 in stage
  source = "git::git@github.com:foo/foobar_modules.git//app?ref=v0.0.3"
}

inputs = {
  instance_count = 1
  instance_type  = "VM.Standard2.1"
}
```

I'll generate a single terraform.tfstate for this execution. 

Then if I want to create a second instance, I'll declare it again on separate directory on terragrunt wrapper, producing a second terraform.tfstate. 

As I'm unable to programatically change the name of the file and I'm unable to store it remotely under that paradigm, that pushes me to either use remote backend and merge all states in a single file (which is not desirable), or leave them local. It's desirable to have the same GCP/AWS bucket behavior supported for OCI remote state supported by buckets. 

That will potentially also need to support some sort of remote authentication mechanism apart from a PAR, most likely injected through a json credential file. 

### New or Affected Resource(s)

Current feature (with AS-IS behavior) is described in OCI Doc: [OCI Documentation for Object Storage](https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm ) 

### Potential Terraform Configuration

Support behavior declared in S3 bucket or something similar to what's described on GCP's beavior documented [here](https://www.terraform.io/docs/backends/types/gcs.html) 

GCP backend configuration adds prefix support to inject a custom name. 

### References

The following is a similar-not-the-same [problem reported](https://github.com/terraform-providers/terraform-provider-oci/issues/540)

**Comment by zexinwanoci** [comment]
We have published a new version of https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformUsingObjectStore.htm
Please try using one file per config as per the doc
