### ISSUE TITLE
public key issues provisioning dbaas system

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#921]
Hello 
I m trying to create a dbaas system with terraform but the apply fails with this message :
(base) [oracle@localhost terraform]$ ./4-terraform-apply.sh 
data.oci_core_vcns.test_vcns: Refreshing state...
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_core_subnets.test_subnets: Refreshing state...
data.oci_core_subnets.pub_subnets: Refreshing state...
data.oci_core_subnets.priv_subnets: Refreshing state...
data.oci_core_vcn.test_vcn: Refreshing state...
data.template_file.deployment_ad[1]: Refreshing state...
data.template_file.deployment_ad[0]: Refreshing state...
data.template_file.deployment_ad[2]: Refreshing state...
data.oci_database_db_system_shapes.test_db_system_shapes: Refreshing state...
data.template_file.core_subnets_name[1]: Refreshing state...
data.template_file.core_subnets_name[0]: Refreshing state...
data.template_file.core_subnets[1]: Refreshing state...
data.template_file.core_subnets[0]: Refreshing state...
oci_database_db_system.test_db_system: Creating...

Error: Service error:InvalidParameter. sshPublicKeys[0] should be in format "<type> <base64> [<entity name>]".. http status code: 400. Opc request id: 05854431cbfd4c7db2158b133282232e/6F711F08AFA248F4CFD983617E6B1C8D/404D8E1DEEE2CEC9939D28142F962B6B

  on main.tf line 164, in resource "oci_database_db_system" "test_db_system":
 164: resource "oci_database_db_system" "test_db_system" {

[public.pem.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3815858/public.pem.txt)
[public.pub.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3815859/public.pub.txt)

[main.tf.txt](https://github.com/terraform-providers/terraform-provider-oci/files/3815860/main.tf.txt)

I m using the publix.pub it fails then i m using the publi.pem it fails as well

Try the GUI and copying pasting the content of the public.pub to the public key text box works and the database is created.

I have been using the public.pub key to several oci vm  without issues whats the problem now ?
I dont see any specific confi for the keys in the api

**Comment by eugsim1** [comment]
for the main.tf the correct section which is not working is :
  ssh_public_keys         = [ "${var.ssh_public_key}"]
in the uploaded file i  was trying to put the key in full extend please ignore the ssh_public_keys in the main.tf.txx and check with the above ssh_public_keys         = [ "${var.ssh_public_key}"]

**Comment by parrneet** [comment]
Hi @eugsim1 - I'm able to create a db_system with the pem key you provided using 
`ssh_public_keys = [ "${var.ssh_public_key}"]`
and setting the key as environment variable
`export TF_VAR_ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAA.................jv4PEZ+nI5agGfIjwoAGPAfNj8gyOE/k/K7Ff2cMK+45P9lFgL/J oracle@localhost.localdomain"`

How are you setting the key in the variable? 
Also, please provide debug logs so I can see the key being set in the request object. 

 .pub keys- starting with `"-----BEGIN"` are not allowed and will give an error looking like `sshPublicKeys[0] has invalid type "-----BEGIN"`

**Comment by eugsim1** [comment]
Hello
thanks for your answer i have tried again with both compinations and i m getting the same error
Error: Service error:InvalidParameter. sshPublicKeys[0] should be in format "<type> <base64> [<entity name>]".. http status code: 400. Opc request id: d773d6a6217e0ebb2630aae7535b34b6/C43563DBD9E55E2F2A4423D61388DC5E/5251255AA65ACBF33C9CA92BDCCB30FD

  on main.tf line 109, in resource "oci_database_db_system" "test_db_system":
 109: resource "oci_database_db_system" "test_db_system" {



Error: Service error:InvalidParameter. sshPublicKeys[0] should be in format "<type> <base64> [<entity name>]".. http status code: 400. Opc request id: 9a170e7edda9c765311bbf88550d476d/07F89A24733560CE991CFBD8D0511A3A/68BACAC4472ED463A21DAF6541A41E3A

  on main.tf line 109, in resource "oci_database_db_system" "test_db_system":
 109: resource "oci_database_db_system" "test_db_system" {



Error: Service error:InvalidParameter. sshPublicKeys[0] should be in format "<type> <base64> [<entity name>]".. http status code: 400. Opc request id: 9e3384fb17d304af5addd49aeec6aa72/E4BD228D98A955012A96CE6AB21A076A/F00D1BF7D57CDE64B05006799FADB036

  on main.tf line 109, in resource "oci_database_db_system" "test_db_system":
 109: resource "oci_database_db_system" "test_db_system" {


(base) [oracle@localhost terraform-dbcs]$ terraform -v
Terraform v0.12.13
+ provider.local v1.4.0
+ provider.oci v3.50.0
+ provider.template v2.1.2
(base) [oracle@localhost terraform-dbcs]$

**Comment by parrneet** [comment]
Please provide below information in order for me to look into this:
1. How are you setting the key in the variable? Are you:
```
- setting the variable as content of the key?
- setting the key contents in environment variable?
- reading the key file to set the variable?
```

2. Also, please provide `complete` debug logs so I can see the key content being set in the request object.
```
To get verbose console output when the provider is running, precede your Terraform command with the TF_LOG and OCI_GO_SDK_DEBUG flags:

TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan

The tf_log level and OCI_GO_SDK_DEBUG flags can also be set as environment variables.
```

**Comment by eugsim1** [comment]
the key is setup in terraform.tfvars 

ssh_public_key= "public.pub"
##ssh_public_key= "public.pem"
ssh_private_key="priv.txt"


terraform apply -no-color -auto-approve    -var-file=instance_count.tfvars  -var-file="terraform.tfvars"
i will send you the debug logs with slack

**Comment by parrneet** [comment]
Confirmed that file() option works for the scenario, closing the issue.
