### ISSUE TITLE
oci_file_storage_export export_option source can only be subnet?

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#926]
./terraform version
Terraform v0.11.13
+ provider.external v1.2.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.oci v3.38.0
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.0

oci_file_storage_export:
export_options.0.source:  does this support only subnet or can we list IP addresses to? 

Thank you,

**Comment by parrneet** [comment]
Hi @wggit Please refer to documentation [here](https://www.terraform.io/docs/providers/oci/r/file_storage_export.html#source) `Must be a either single IPv4 address or single IPv4 CIDR block`

**Comment by wggit** [comment]
Thank you. I have a requirement where I have 10 IP address I have to assign so was thinking how can I do that.

**Comment by parrneet** [comment]
Please refer to documentation [here](https://docs.cloud.oracle.com/iaas/Content/File/Tasks/exportoptions.htm#options)
`Each separate client IP address or CIDR block you want to define access for needs a separate export options entry in the export. For example, if you want to set options for NFS client IP addresses 10.0.0.6, 10.0.08, and 10.0.0.10, you need to create three separate entries, one for each IP address.`

Feel free to reopen if you have more questions on this.
