### ISSUE TITLE
OCI LBaaS http to https redirection

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#928]
I have LBaaS created via terraform. I have listener created listening on 443. How do I incorporate http --> https? 
Do not find any oci documentation on it.

Thank you.

**Comment by parrneet** [comment]
Hi @wggit - This feature is not yet supported by provider. We are planning to release it soon, likely by next week.

**Comment by wggit** [comment]
Thank you for your update. This is really helpful and going to help our implementations.
Is this going to be part of LBaaS core functionality oci platform?

**Comment by afedorch** [comment]
@wggit A new version v3.53.0 of the OCI provider has been released in the Terraform provider registry. There is support for URL Redirect Feature in `oci_load_balancer_rule_set` resource.
I am closing this request please feel free to open a new one if you have other questions, thank you.
