### ISSUE TITLE
Discovery Export Output File error

### ISSUE THREAD

**Issue by bterry100** [terraform-providers/terraform-provider-oci#929]

**Comment by alexng-canuck** [comment]
Hi @bterry100 can you provide more details about this error? And share the output logs from the command?

Please include `OCI_GO_SDK_DEBUG=v` and `TF_LOG=DEBUG` environment variables before running the command so we can get the full verbose logs.

**Comment by alexng-canuck** [comment]
Followed up with @bterry100 offline. Will close this issue.
