### ISSUE TITLE
Compute Instance user_data script is not executed

### ISSUE THREAD

**Issue by mthmulders** [terraform-providers/terraform-provider-oci#933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```
Terraform v0.12.13
+ provider.oci v3.52.0
```

### Affected Resource(s)
`oci_core_instance`

### Terraform Configuration Files

```hcl
resource "oci_core_instance" "example" {
    availability_domain = "dYbl:EU-FRANKFURT-1-AD-2"
    compartment_id = "${var.compartment_ocid}"
    shape = "VM.Standard.E2.1.Micro"
    display_name = "Example"
    
    agent_config {
        is_monitoring_disabled = false
    }

    create_vnic_details {
        assign_public_ip = true
        display_name = "Primary VNIC"
        hostname_label = "example"
        subnet_id = "${oci_core_subnet.example.id}"
    }
    
    metadata = {
        user_data = "${base64encode(file("../oci-init.sh"))}"
        ssh_authorized_keys = "(redacted)"
    }

    source_details {
        source_id = "${var.image_ids[var.region]}"
        source_type = "image"
    }
}
```

### Debug Output
https://gist.github.com/mthmulders/695dc102bfabc8d0cd9b51d4382cbd74

### Panic Output
N/A

### Expected Behavior
The contents of `oci-init.sh` are executed during machine provisioing.

### Actual Behavior
The script has not ran. I know this because it installs a few packages and touches some files. The packages aren't installed and the files aren't present.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Not that I'm aware of.

**Comment by afedorch** [comment]
@mthmulders thanks for reporting the problem!
Could you please attach debug logs for us to verify that `user_data` is part of the request before we redirect the problem to the service team?

Verbose logging for OCI Terraform Provider:
https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider

**Comment by mthmulders** [comment]
Oops, must've missed that one. Sorry for that. I've updated with a piece from the debug logging. AFAICS, there's no `user_data` in it....

**Comment by afedorch** [comment]
@mthmulders looks like mismatch to me, for an example there is `hostname_label = "example"` in the configuration for `create_vnic_details` but we have `"hostnameLabel":"smart-meter"` for the createVnicDetails the logs, same for `display_name` value. Could you please check that the logs correspond to the configuration? thanks!

To confirm that we are on the same page - could you try the example from the repository (`bootstrap` is part of the example as well): 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/instance/instance.tf#L98
do you see `user_data` as part of the request? thanks!

**Comment by mthmulders** [comment]
You're right. I redacted some of values (OCID's, keys, and names) but forgot a few. I'm sorry for the confusion.

I'll try to see if the example does submit the `user_data`.

**Comment by mthmulders** [comment]
In the example repo, the log file contains:

```
2019-11-26T10:21:14.862+0100 [DEBUG] plugin.terraform-provider-oci_v3.53.0_x4:   "metadata" : {
2019-11-26T10:21:14.862+0100 [DEBUG] plugin.terraform-provider-oci_v3.53.0_x4:     "ssh_authorized_keys" : "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA8v9U/BIz65mXdxx9LUlkJlL6PScgArI5ClVEcCG70WH/bvnCLDg3cSdEwO4SoJwDZmZ7bROPUFeCLKbs0k0mzXKG7/SRTy4yqyd8X4LrnGy95barbfADVkx+pLo+hmKB5hCsf0yejJahmzg+routOsOE9stkwm10OWnBsXkJRzv8b1D5CdE8t+S+ciTtPQrn87zaQcLRLx191wSoT5SvLV0FUY2b0FHCQPY4QVbj1hnjQ/nII1FYftmyEW8NocUlvetfLHltNU455tkE/puWGeGVATxLC4iaJ+gc1aamqd3fGRfuvNJIiojjmbmhTtazLOKsVfpIXhFTlBK1FMBUuQ== m.th.mulders@xs4all.nl",
2019-11-26T10:21:14.862+0100 [DEBUG] plugin.terraform-provider-oci_v3.53.0_x4:     "user_data" : "IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSAteQo="
2019-11-26T10:21:14.862+0100 [DEBUG] plugin.terraform-provider-oci_v3.53.0_x4:   },
````

So it looks as if the `user_data` *is* included there!

**Comment by afedorch** [comment]
@mthmulders 
correct, `user_data` should be part of the request. If you see it as part of the example then we need to verify your configuration to understand the reason it is not part of the request for your case. I have tried the configuration from the ticket and I see `user_data` as part of the request. Could you please try a clean run with the logs? Thanks.

The other option to check the configuration and state could be `terraform plan` command after the modification of the `oci-init.sh` file content. You should see something similar to:
```
  ~ metadata  = { # forces replacement
            "ssh_authorized_keys" = ""
          ~ "user_data"           = "dGVzdA==" -> "dGVzdDE="
        }
```

Unfortunately, now we cannot reproduce the problem with the attached `Terraform Configuration Files` and `Steps to Reproduce`.

**Comment by afedorch** [comment]
@mthmulders will you be able to share the content of the `oci-init.sh` script for us to try? thanks

**Comment by mthmulders** [comment]
I tried updating the `user_data` in the examples/ folder, and indeed it forces Terraform to replace the instance. So that works as expected.

My `oci-init.sh` script looks like this:

```sh
#!/bin/bash -x
touch ~opc/userdata.`date +%s`.start
apt-get update
apt-get install -y aptitude apticron ssmtp nginx-full
apt-get install -y fail2ban logcheck

# Do some sed magic to configure email delivery
sed -i 's/mailhub=.*/mailhub=REDACTED/g' /etc/ssmtp/ssmtp.conf
sed -i -r 's/hostname=(.*)/hostname=REDACTED/g' /etc/ssmtp/ssmtp.conf
sed -i 's/EMAIL=.*/EMAIL="REDACTED"/g' /etc/apticron/apticron.conf
sed -i 's/SENDMAILTO=.*/SENDMAILTO="REDACTED"/g' /etc/logcheck/logcheck.conf

ufw enable
ufw allow "OpenSSH"
ufw allow "Nginx HTTP"
ufw allow "Nginx HTTPS"
ufw status verbose
touch ~opc/userdata.`date +%s`.finish
```

I'll re-try with my original repo later today.

**Comment by mthmulders** [comment]
Tried it again. When I change the oci-init.sh script the instance gets re-created (as you would expect from the documentation).

I can also see that the `user_data` parameter is filled in the HTTP request. The _first_ `touch` instruction has been executed, but the _last_ one has not. So it seems the problem is somewhere in the script itself, and not in Terraform itself.

This leaves me with a few follow-up questions:

1. Would `terraform apply` terminate _before_ the script has completed?
1. If the script exits with a non-zero exit code, would provisioning fail?
1. Is there a way to read the output of the `user_data` script?

**Comment by afedorch** [comment]
@mthmulders Looks like after the fix in the script you will be able to see the result for the last `touch` as well.

1. `terraform apply` does not know anything about the script however it tracks the resource state. As soon as the instance is in `RUNNING` state `apply` command will be finished.

For questions 2 and 3 I think you will need to check the instance documentation for the supported behavior:
https://docs.cloud.oracle.com/iaas/Content/Compute/Tasks/updatinginstancemetada.htm

From Terraform point of view to invoke a script on a remote resource after it is created, you can also look at `remote-exec` solution: https://www.terraform.io/docs/provisioners/remote-exec.html

There is an example for the instance in Terraform OCI provider repo as well:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/instance/instance.tf#L164

**Comment by mthmulders** [comment]
Thanks for the extensive support, @afedorch!

**Comment by cmagnoc5561** [comment]
> Thanks for the extensive support, @afedorch!

Hi there! You probably solved your case, but I would like to leave here what I did to make my bash script work during the instance creation. I added the command 'sudo setenforce 0' to disable the selinux temporarily and I would set again to 1 in the end of the script.

Thank you for your post!
