### ISSUE TITLE
vpus_per_gb is not a supported argument for oci_core_volume

### ISSUE THREAD

**Issue by wjvanroosmalen** [terraform-providers/terraform-provider-oci#936]
resource "oci_core_volume" "scr_u01" {
  count               = var.application_global.application_group_list.scriptura.create == true ? 1 : 0
  availability_domain = var.ad
  compartment_id      = var.compartment_id
  display_name        = var.display_name
  size_in_gbs         = var.size
  freeform_tags       = var.freeform_tags_application
  vpus_per_gb         = var.vpus_per_gb
}

Error: Unsupported argument

  on ../../modules/compute/application_group/block_volume.tf line 230, in resource "oci_core_volume" "core_volume":
 230:   vpus_per_gb         = var.vpus_per_gb

An argument named "vpus_per_gb" is not expected here.

It seems that oci_core_volume does not support vpus_per_gb, however it is mentioned in the documentation.

https://www.terraform.io/docs/providers/oci/r/core_volume.html#vpus_per_gb

**Comment by bowfeng** [comment]
@wjvanroosmalen 
we do support it, what provider version did you use?

**Comment by wjvanroosmalen** [comment]
It was indeed an issue with my provider version. Thanks :)
vpus_per_gb was defined correctly. 

however when i am updating more than 2 block store volumes simultaneous i now get:

> Error: Service error:LimitExceeded. Update VPU request count has been exceeded in tenant ocid1.tenancy.oc1..XXX: The following service limits were exceeded in AD eu-frankfurt-1-ad-1: concurrent-vpu-update-request-count. Request a service limit increase from the service limits page in the console. . http status code: 400. Opc request id: aa6d15f1ac26cad96e3419f7257483a7/B2CADE8ED5FD2AA6AC9178DBC574076B/DD896CAE58A2D52B40982A0F8F6FC1CC

Including a time-out does not help unfortunatly

**Comment by bowfeng** [comment]
@wjvanroosmalen 
based on the error, it is clear that service limit was hit. To avoid this error, either update it one by one or increase the related service limit.
