### ISSUE TITLE
OCI_CONTAINERENGINER_NODE_POOL worker nodes getting stuck at "Updating Installing Software" status when node_metadata arugment is used

### ISSUE THREAD

**Issue by PraveenViswanathan** [terraform-providers/terraform-provider-oci#937]
HI,

I am using node_metadata argument in oci_containerengine_node_pool to run a shell script in a worker node as soon as it is created. The script is getting executed as expected but whenever I pass a value to node_metadata the worker node in node pool is getting stuck at "Updating Installing Software" status along with the below message. If I comment out the node_metadata argument and retry it is getting to "Active" status. Looking for the possible reasons and fix.

"compute instance was created 1h7m45s ago and has not been seen in k8s nodes for 20m0s - verify network pre-requisites are correct, if so, try terminating the compute instance to trigger a replacement"

In both the cases my worker node is with private subnet. Below is my code. Appreciate if you can provide on the root cause and possible fixes.

 # cloud-init
    data "template_file" "cloud_init_yaml" {
      template = "${file("./cloud-init.yaml")}"
    }

    data "template_cloudinit_config" "cloudconfig" {
      gzip          = true
      base64_encode = truE

      part {
        content_type = "text/cloud-config"
        content      = "${data.template_file.cloud_init_yaml.rendered}"
      }
    }

    #ADs
    data "oci_identity_availability_domains" "ad_list" {
      compartment_id = "${var.compartment_id}"
    }

    data "template_file" "ad_names" {
      count    = "${length(data.oci_identity_availability_domains.ad_list.availability_domains)}"
      template = "${lookup(data.oci_identity_availability_domains.ad_list.availability_domains[count.index], "name")}"
    }

    #user_data to pass on to node_metadata
    locals {
      ad_names = "${data.template_file.ad_names.*.rendered}"
      node_md = {
        ssh_authorized_keys = "${file("./id_rsa.pub")}"
        user_data = "${data.template_cloudinit_config.cloudconfig.rendered}"
      }
    }

    resource "oci_containerengine_node_pool" "spectra-cpe-np" {
      cluster_id         = "${var.cluster_id}"
      compartment_id     = "${var.compartment_id}"
      kubernetes_version = "v1.13.5"
      name               = "sample_node_pool"
      node_image_name    = "Oracle-Linux-7.6"
      node_shape         = "VM.Standard2.16"
      initial_node_labels {
        #Optional
        key   = "node_for"
        value = "sample_run"
      }

      node_config_details {
      placement_configs   {
        availability_domain = "${element(local.ad_names, 0)}"
        subnet_id = "{pv_subnet_ad1_id}"
      }
      size = "1"
    }     

      node_metadata = "${local.node_md}"
      
      ssh_public_key      = "${file("./id_rsa.pub")}"
      count = "1"
    }

**Comment by varmax2511** [comment]
Hi @PraveenViswanathan -- Thanks for reaching out to us. I notice that Terraform provider succeeds in executing above config. The issue is seen when launched node pool instance is executing the supplied metadata. 
This appears to be a service side issue or an issue in the input template. From a client perspective, I notice that Terraform is able to send the request with the desired payload at time of creation of `oci_containerengine_node_pool` and get the desired response from the service. 
Since per our discussion, you have raised this issue with the associated service team, please let us know if the Github issue can be closed?

**Comment by PraveenViswanathan** [comment]
Hi Varun - Thanks for the update. I am parallely working with OKE team as well on this. Will come back if they want any further analysis from terraform side.
