### ISSUE TITLE
Changes for OKE node pool custom image support broke idempotency

### ISSUE THREAD

**Issue by jwitko** [terraform-providers/terraform-provider-oci#948]
### Terraform Version and Provider Version
Terraform v0.11.14
+ provider.external v1.2.0
+ provider.oci v3.56.0

### Affected Resource(s)
OCI OKE node pool resource

### Expected Behavior
If I create an OKE node pool in terraform and do not modify anything a subsequent run should tell me there are no changes to make.

### Actual Behavior
The `node_source_details` field is newly added and set to ForceNew as well as computed ( https://github.com/terraform-providers/terraform-provider-oci/commit/2235ed73ce979b171ef037f45a301d9dc47daff9 ).  

Because of this leaving the field empty or setting it to null will *ALWAYS* make terraform believe there is a change which requires the node pool to be deleted and recreated.  

### Steps to Reproduce
1. Create an OKE node pool using terraform that does not specify a `node_source_details` parameter and instead uses `node_image_name`.
2. Run terraform apply twice

**Comment by jotruon** [comment]
Hi @jwitko, Thanks for reporting this bug.
Please note that the **node_image_name** is _deprecated_ from v3.56.0: https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/d/containerengine_node_pool.html.markdown 

So if you still want to use node_image_name, please change provider to v3.55.0

Please let me know if this can answer your request.

Thanks

**Comment by afedorch** [comment]
@jwitko new (v3.57.0) provider version was released with the support of the deprecated node_image_id, node_image_name attributes in oci_containerengine_node_pool resource for terraform v0.11. Please, let us know if it works for you, thanks!

**Comment by jwitko** [comment]
@afedorch Thanks for the update.  It appears to still be broken:
*Code*:
```
Gmodule "oke_cluster_node_pool_2" {
  source                    = "../../../../modules/oke/nodepool"
  cluster_id                = "${module.oke_cluster.id}"
  compartment_ocid          = "${data.oci_identity_compartments.target_compartment.compartments.0.id}"
  oke_version               = "${var.oke_version}"                                                     //updatable without destroy
  label_prefix              = "${var.label_prefix}"
  display_name              = "oke_cluster_node_pool_2"                                                //updatable without destroy
  node_image_name           = "${data.oci_core_images.OKECustomImage.images.0.id}"
  node_shape                = "${var.shapes["okeNode1"]}"
  initial_node_labels_key   = "${module.oke_cluster.name}"
  initial_node_labels_value = "${var.label_prefix}oke_cluster_node_pool_2"

  subnet_list = [
    "${module.oke_subnet.ids[format("%soke-ad1",var.label_prefix)]}",
    "${module.oke_subnet.ids[format("%soke-ad2",var.label_prefix)]}",
    "${module.oke_subnet.ids[format("%soke-ad3",var.label_prefix)]}",
  ]

  quantity_per_subnet = "${var.oke_quantity_per_subnet}" //updatable without destroy
  ssh_public_key      = "${module.ssh_public_keys.keys}"
}
```

*versions*:
```
$ terraform -version
Terraform v0.11.14
+ provider.external v1.2.0
+ provider.oci v3.57.0
```

*error*:
```
 $ terraform validate

Error: module "oke_cluster_node_pool_2": missing required argument "node_source_details"
```

**Comment by jwitko** [comment]
@afedorch Sorry I made a mistake and still had module code causing that error.  Everything works great now!  Closing this issue.
