### ISSUE TITLE
Assertion resource for validating values

### ISSUE THREAD

**Issue by anilarora** [terraform-providers/terraform-provider-oci#949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

One missing feature is the ability to short circuit the terraform apply function in the case of bad input or unexpected results from a data source.  Current solutions compatible with terraform 0.12 involve using local-exec to echo a message and return a non zero exit code.

This enhancement creates a simple resource that will fail if the incoming test value is false or 0, displaying a provided message and error code.  If possible, the message and error code are added to the state file to be processed by any caller for automation. 

### New or Affected Resource(s)

oci_assert

### Potential Terraform Configuration

```hcl

variable “mystring” {
   type = string
}

resource “oci_assert” “invalid_input” {
  that = var.mystring == “goodvalue”
  message = “bad input”
  error_code = “error-001”
}
```

**Comment by anilarora** [comment]
Found this provider, but this is not available anywhere AFAIK, https://github.com/bwoznicki/terraform-provider-assert

**Comment by alexng-canuck** [comment]
Hi @anilarora 

This kind of assertion functionality seems like it should be part of core Terraform; as other cloud and Terraform providers would find this useful as well.

Have you tried suggesting this to: https://github.com/hashicorp/terraform/issues?

Also, are you using Oracle Resource Manager? If so, we could give the feedback to include https://github.com/bwoznicki/terraform-provider-assert integration there.

**Comment by anilarora** [comment]
Yes, we are using ORM, which is why we were trying to find an avenue that will benefit Oracle Cloud Infrastructure here in lieu of any global solution.  

Looks like an upcoming version of terraform will support validation rules, although currently experimental and not available in ORM anyways.
https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

Will close...
