### ISSUE TITLE
Support for non-default profiles for credentials

### ISSUE THREAD

**Issue by priteshkp** [terraform-providers/terraform-provider-oci#952]
https://www.terraform.io/docs/providers/oci/index.html

Currently you can use the oci standard config file for credentials, but only for the default profile.  Can you please add support for specifying non-default profiles?

ex:
```
 provider "oci" {
   configFileProfile = "Profile1"
   region = "${var.region}"
 }
```

**Comment by mulpk** [comment]
fixed in release v3.70.0
