### ISSUE TITLE
Adding multiple rules to a load balancer ruleset does not match the documentation

### ISSUE THREAD

**Issue by gcordalis** [terraform-providers/terraform-provider-oci#955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v0.12.19
+ provider.oci v3.58.0
```
### Affected Resource(s)

`oci_load_balancer_rule_set`

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_rule_set" "test_rule_set" {
  items {
    action = "REDIRECT"
    conditions {
      attribute_name = "PATH"
      attribute_value = "/path2"
      operator = "EXACT_MATCH"
    }
    description = "rule 1"
    redirect_uri {
      protocol = "HTTPS"
      host = "host1"
    }
  }

  items {
    action = "REDIRECT"
    conditions {
      attribute_name = "PATH"
      attribute_value = "/path2"
      operator = "EXACT_MATCH"
    }
    description = "rule 2"
    redirect_uri {
      protocol = "HTTPS"
      host = "host2"
    }
  }
  load_balancer_id = "xxxx"
  name = "xxxx"
}
```

### Expected Behavior

An array of items should be defined to add multiple rules to a ruleset as per the [documentation](https://www.terraform.io/docs/providers/oci/r/load_balancer_rule_set.html#items):
>items - (Required) (Updatable) An array of rules that compose the rule set. For more information, see Managing Rule Sets

Here is the expected configuration as per the documentation. This matches the output of `data.oci_load_balancer_rule_set` when retrieving a ruleset with multiple rules.

```hcl
resource "oci_load_balancer_rule_set" "test_rule_set" {
  items = [
    {
      action = "REDIRECT"
      conditions {
        attribute_name = "PATH"
        attribute_value = "/path2"
        operator = "EXACT_MATCH"
      }
      description = "rule 1"
      redirect_uri {
        protocol = "HTTPS"
        host = "host1"
      }
    },
    {
      action = "REDIRECT"
      conditions {
        attribute_name = "PATH"
        attribute_value = "/path2"
        operator = "EXACT_MATCH"
      }
      description = "rule 2"
      redirect_uri {
        protocol = "HTTPS"
        host = "host2"
      }
    }
  ]
  load_balancer_id = "xxxx"
  name = "xxxx"
}
```

### Actual Behavior

The required configuration is to add multiple `items` blocks, with each block a separate rule in the ruleset.

### Steps to Reproduce

This occurs on `terraform plan|apply`.

### Important Factoids

N/A

### References

[oci_load_balancer_rule_set documentation](https://www.terraform.io/docs/providers/oci/r/load_balancer_rule_set.html#items)

**Comment by varmax2511** [comment]
Hi @gcordalis -- thanks for reaching out to us. `oci_load_balancer_rule_set` supports adding multiple rules as listed in your terraform configuration file and the  [documentation](https://www.terraform.io/docs/providers/oci/r/load_balancer_rule_set.html#items). 

Since each rule is expected to be unique, the collection is expressed via multiple individual `items` block within the `oci_load_balancer_rule_set`. This is in accordance with Terraform TypeSet schemas : https://www.terraform.io/docs/extend/schemas/schema-types.html. 
To learn more on using `oci_load_balancer_rule_set` , please refer: https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/load_balancer/lb_full/lb_full.tf#L339 
Please let us know if this helps.

**Comment by gcordalis** [comment]
@varmax2511 thanks for clearing this up!
