### ISSUE TITLE
Allow oci_core_network_security_group_security_rule to support dynamic blocks

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

Security rules allow the use of dynamic blocks e.g. 

```
resource "oci_core_security_list" "public_workers_seclist" {
  ...
  ingress_security_rules {
    # rule 4
    protocol  = local.icmp_protocol
    source    = local.anywhere
    stateless = false
  }

  dynamic "ingress_security_rules" {
    iterator = cidr_iterator
    for_each = local.pub_cidr_blocks

    content {
      protocol  = local.tcp_protocol
      source    = cidr_iterator.value
      stateless = false

      tcp_options {
        max = local.ssh_port
        min = local.ssh_port
      }
    }
  }
....
}
```
However, oci_core_network_security_group_security_rule does not allow more than 1. If we need to configure multiple tcp ports, then multiple rules have to be declared. This is repetive and cumbersome.

Is it possible to have oci_core_network_security_group_security_rule support more than 1 config item?

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

**Comment by parrneet** [comment]
Due to some API limitations, the security rule resource is modeled like this. Security rules are not part of the NSG Create and are added using a separate API call. We will update this when there is an update to the API from service team.

**Comment by hyder** [comment]
Ok thanks
