### ISSUE TITLE
How to pass-on the value for vcn_id from a vcn module to a compute module

### ISSUE THREAD

**Issue by Frank2nd** [terraform-providers/terraform-provider-oci#958]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

Before using this template, check whether your question is already answered in one of the following guides:
* [Frequently Asked Questions](https://www.terraform.io/docs/providers/oci/guides/faq.html)
* [Troubleshooting](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html)

If you have a support request related to Oracle Cloud Infrastructure services, please [contact Oracle support](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm)

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by Frank2nd** [comment]
I am working on two tf modules: vcn and compute
Within the vcn module the vcn and all its childs are created like subnets and network groups
Subsequently within the compute module I would like to leverage these childs
but then for each data block I need to provide the vcn_id
Is there a way to retrieve or pass-on this (freshly) created vcn_id to the compute module 
Within the aws TF provider I can define a data block and then query based on tags. Does OCI provides simular functionality?

**Comment by anilarora** [comment]
Use the instance metadata to pass in the value...

resource "oci_core_instance" "test_instance" {
 
  ...

  metadata = {
    ssh_authorized_keys = "${var.ssh_public_key}"
    vcn_id = "${var.vcn_id}"
  }

  ...
}

Then you should be able to use the oci-metadata util to get that value from within your compute.

**Comment by parrneet** [comment]
Hi @Frank2nd - Let us know if the above suggestion works for you. Else, Please share your TF config files so we can take a look.

**Comment by Frank2nd** [comment]
My vcn module code snippit 
..\terraform\oci\modules\services\vcn\main.tf

# Create a new VCN
# https://www.terraform.io/docs/providers/oci/r/core_vcn.html
resource "oci_core_vcn" "rlb_vcn" {
    #Required
    compartment_id  = var.compartment_ocid
    cidr_block      = var.vcn_cidr_block
    #Optional
    display_name    = "${var.pre_fix}vcn"
    dns_label       = var.vcn_dns_label
    freeform_tags   = {"IacProvider"="TF"}
}
...
And this goes on very well for all the vcn childs within that same vcn module e.g. internet gateway
# Create a new igw
# https://www.terraform.io/docs/providers/oci/r/core_internet_gateway.html
resource "oci_core_internet_gateway" "rlb_internet_gateway" {
    #Required
    compartment_id  = var.compartment_ocid
    vcn_id          = oci_core_vcn.rlb_vcn.id
    #Optional
    display_name    = "${var.pre_fix}igw"
    enabled         = var.internet_gateway_enabled
    freeform_tags   = {"IacProvider"="TF"}
}
...
Within that same vcn module I can reference the required vcn_id for igw with oci_core_vcn.rlb_vcn.id and all the other childs - no sweat

Now I would like to isolate my tf compute code in a separate module
..\terraform\oci\modules\services\compute\main.tf

resource "oci_core_instance" "rlb_instance" {
    #Required
    availability_domain = local.ad1
    compartment_id      = var.compartment_ocid
    shape               = local.instance_shape

    create_vnic_details {
        #Required
        subnet_id = <- how to get this value from the vcn module

        #Optional
        assign_public_ip = true
        #defined_tags = {"Operations.CostCenter"= "42"}
        #display_name    = "${var.pre_fix}bastionhostwindowsvnic"
        #freeform_tags   = {"IacProvider"="TF"}
        #hostname_label = "${var.vcn_dns_label}${var.pre_fix_sec}windowsvnc"
        nsg_ids = [<-how to get this value from the vcn module]
...
If I start - within compute module - with a data block to get all the subnet details 
it requires the vcn_id which is determined within the vcn module 

data "oci_core_subnet" "rlb_public_subnet" {
    compartment_id  = var.compartment_ocid
    vcn_id          = <-- how to pass on this value from the vcn to the compute module
    display_name    = "${var.pre_fix}pubsubnet"
}
Within the tf aws provider I can use other properties than the keys (vcn_id) like tags to get the resource details through a data block - see below
# retrieve aws_subnet details for public subnet
data "aws_subnet" "rlb_publicsubnet" {
  filter {
    name   = "tag:Name"
    values = ["${var.pre_fix}publicsubnet"]
  }
} 

Any ideas how to solve this within the oci provider:
data "oci_core_subnets" "test_subnets" {
    #Required
    compartment_id = "${var.compartment_id}"
    vcn_id = "${oci_core_vcn.test_vcn.id}" <-- required!
    #Optional
    display_name = "${var.subnet_display_name}"
    state = "${var.subnet_state}"
}

**Comment by parrneet** [comment]
[This ](https://www.terraform.io/docs/providers/oci/d/core_vcns.html) data source might help here. You can filter the vcns based on some parameters within this data source.

**Comment by Frank2nd** [comment]
Thanks for this suggestion indeed the plural data blocks accept other parameters than the keys
Unfortunately the TF apply fails with
...
Error: Service error:InvalidParameter. Invalid subnet: 2020-01-23 16:07:45.081429 +0000 UTC. http status code: 400. ... 
....
It seems that it uses a timestamp for the subnet id rather than the ocid:
...
 subnet_id              = "2020-01-23 16:07:45.081429 +0000 UTC"
...
Same applies for the nsg_ids:
    + nsg_ids                = [
              + "2020-01-23 16:07:45.0434068 +0000 UTC",
            ]
Have you seen this behavor before?

**Comment by parrneet** [comment]
Please share the data source config that gives error.

**Comment by alexng-canuck** [comment]
@Frank2nd Which datasource are you using to get the ID and how are you referencing it?

The reason you're seeing the timestamp for the subnet ID is likely because you're referencing the ID of the datasource itself. Since the datasource returns multiple items, you'll likely need to reference the ID of one of the resulting items from the datasource (e.g. use `datasource.items[0].id` instead of `datasource.id`)

**Comment by alexng-canuck** [comment]
Closing since there hasn't been a response in 2 weeks. Please feel free to reopen if the issue still persists.
