### ISSUE TITLE
Error:Post https://iaas.ashburn.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.ashburn.oraclecloud.com on 169.254.169.254:53: no such host

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#960]
Hi Team,

I am getting the below error when i try to create an instance using the terraform modules, i am passing the variables via terraform.tfvars file. Not sure why this is happening, could you please help us as early as possible?

OCI Porvider version - 3.58
Terraform version -  v0.12.1
Thanks in advance

**_Output on terraform apply gives the below:

module.servers.oci_core_instance.demo_instance[1]: Creating...
module.servers.oci_core_instance.demo_instance[0]: Creating...

Error: Post https://iaas.ashburn.oraclecloud.com/20160918/instances: dial tcp: lookup iaas.ashburn.oraclecloud.com on 169.254.169.254:53: no such host

  on compute/instance.tf line 15, in resource "oci_core_instance" "demo_instance":
  15: resource "oci_core_instance" "demo_instance" {_**

**Comment by parrneet** [comment]
Hi @shruthi2703 
Please share the debug logs from terraform plan and apply and minimal TF config file to reproduce the problem.

To get verbose console output when the provider is running, precede your Terraform command with the TF_LOG and
OCI_GO_SDK_DEBUG flags:

`TF_LOG=DEBUG OCI_GO_SDK_DEBUG=v terraform plan`
The tf_log level and OCI_GO_SDK_DEBUG flags can also be set as environment variables.

**Comment by shruthi2703** [comment]
Hi @parrneet 

Thanks for the response :) 

I am able to ping 169.254.169.254 but traceroute  says operation not permitted. I guess some issue with routing? IP tables? can that cause this error? Actually i tried it from couple of systems and it did not work, that's why raised the query. 


traceroute 169.254.169.254
traceroute to 169.254.169.254 (169.254.169.254), 30 hops max, 60 byte packets
send: Operation not permitted

**Comment by parrneet** [comment]
Looks like a network issue not related to provider but you can try if [these](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#dial-tcp-i-o-timeout-when-connecting-via-proxy) settings help

**Comment by alexng-canuck** [comment]
@shruthi2703 are you still having this issue?

**Comment by shruthi2703** [comment]
Hey ,

Yeah i still have this issue, i tried again on a different server and the issue persists.
I am not sure why this is happening, if i do not use Modules i do not face this problem.

**Comment by alexng-canuck** [comment]
Hi @shruthi2703 

I suspect the reason you're seeing this issue with modules is because the `region` isn't being set correctly. Note that your URL is `https://iaas.ashburn.oraclecloud.com/20160918/instances` when the valid URL should actually be `https://iaas.us-ashburn-1.oraclecloud.com/20160918/instances`

Can you make sure that you're using `us-ashburn-1` instead of `ashburn` in your region settings for the module?

**Comment by shruthi2703** [comment]
Hi Alex,

Thank you so much. That was the issue. This really helps.
