### ISSUE TITLE
Usage of oke resources oci_containerengine_cluster and oci_containerengine_node_pool does not result in healthy OKE cluster

### ISSUE THREAD

**Issue by Frank2nd** [terraform-providers/terraform-provider-oci#963]
All my compute instances within the node pool remain in the following update status:

"compute instance was created 48m21s ago and has not been seen in k8s nodes for 20m0s - verify network pre-requisites are correct, if so, try terminating the compute instance to trigger a replacement"

A visual control with a healthy OKE cluster does not reveal any network differences
Other than the fact that I cannot spread the instances across multiple AD's - see my question posted earlier today.
Prior to creating the OKE cluster - see below - I have created a VCN and LB - to be leveraged by the OKE cluster - simular to a quick created OKE cluster in the GUI console 
I have used the following TF resource scripting to create the oke cluster and node pool
```
# Creation of an OCI k8s cluster
# https://www.terraform.io/docs/providers/oci/r/containerengine_cluster.html
# MedRecOKE_Cluster
resource "oci_containerengine_cluster" "rlb_cluster" {
    #Required
    compartment_id       = var.compartment_ocid
    vcn_id               = oci_core_vcn.rlb_vcn.id
    kubernetes_version   = local.k8s_version
    name                 = "${var.pre_fix}cluster"
    #Optional
    #kms_key_id = "${oci_kms_key.test_key.id}"
    options {
        #Optional
        add_ons {

            #Optional
            is_kubernetes_dashboard_enabled = true
            is_tiller_enabled = true
        }
        kubernetes_network_config {
            #Optional
            pods_cidr     = var.pods_cidr_block
            services_cidr = var.services_cidr_block
        }
        service_lb_subnet_ids = [oci_core_subnet.rlb_public_subnet.id]
    }
}
# create oke node pool and instances
# https://www.terraform.io/docs/providers/oci/r/containerengine_node_pool.html
resource "oci_containerengine_node_pool" "rlb_node_pool" {
    #Required
    cluster_id         = oci_containerengine_cluster.rlb_cluster.id
    compartment_id     = var.compartment_ocid
    kubernetes_version = local.k8s_version
    name = "${var.pre_fix}pool"
    node_shape = local.instance_shape
    #subnet_ids = [oci_core_subnet.rlb_private_subnet_wkr.id]
    node_config_details {
         placement_configs {
           availability_domain = local.ad1
           subnet_id = oci_core_subnet.rlb_private_subnet_wkr.id
         }
         size = 3
    }
    #Optional
    initial_node_labels {
        #Optional
        key = "name"
        value = "${var.pre_fix}_pool"
    }
    #node_image_name = "${var.pre_fix}_pool_node"
    #node_metadata = "${var.node_pool_node_metadata}"
    node_source_details {
        #Required
        image_id = local.image_id_ole77
        source_type = local.image_source_type
    }
    #quantity_per_subnet = 3
    ssh_public_key = local.ssh_public_key
}
```

**Comment by Frank2nd** [comment]
And following the suggestion: "try terminating the compute instance to trigger a replacement" does not help: indeed a new compute instance is created, but also the newly created instance remain in the same status
Any suggestions?

**Comment by hyder** [comment]
I would start with verifying your security lists. Alternatively, you can also try this: https://github.com/oracle-terraform-modules/terraform-oci-oke

**Comment by alexng-canuck** [comment]
Hi @Frank2nd ,

I agree with @hyder and would also suggest you take a look at the following topology documentation when setting up OKE in Terraform. 
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/master/docs/topology.adoc
