### ISSUE TITLE
datasource oci_budget_budgets expected type 'string', got unconvertible type 'common.SDKTime'

### ISSUE THREAD

**Issue by rramge** [terraform-providers/terraform-provider-oci#966]
Hello,

Terraform v0.12.20
+ provider.oci v3.59.0

when following terraform-provider-oci/examples/budget/main.tf starting at line 64

--- 8< ---
data "oci_budget_budgets" "sco01" {
  #Required
  compartment_id = "${var.tenancy_ocid}"

  #Optional
  //  display_name = "${oci_budget_budget.sco01.display_name}"
  //  state        = "ACTIVE"
}
--- 8< ---

terraform plan results in the following error message:

--- 8< ---
Error: budgets.1.time_spend_computed: '' expected type 'string', got unconvertible type 'common.SDKTime'

  on 02-budget.tf line 42, in data "oci_budget_budgets" "sco01":
  42: data "oci_budget_budgets" "sco01" {
--- 8< ---

KR,

Ralf

**Comment by alexng-canuck** [comment]
Hi @rramge ,

Can you share the logs from running `terraform plan` with verbose logging enabled?

See https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider for how to enable verbose logging.

Thanks,
Alex

**Comment by alexng-canuck** [comment]
But I suspect this is a bug in the provider's setting logic. It is not converting a date time to the string type that Terraform expects.

**Comment by alexng-canuck** [comment]
Hi @rramge 
Thanks for reporting this issue. We are working on a fix for it and it should be out with our next Terraform provider release (ETA: Wednesday Feb. 5).

Thanks,
Alex

**Comment by abhilash-av** [comment]
Hello, @rramge new (v3.61.0) provider version was released with this fix. Please, let us know if it works for you, 
Thanks
