### ISSUE TITLE
There is a conflict between example usage and argument referance regarding oci_core_remote_peering_connection

### ISSUE THREAD

**Issue by esalimy** [terraform-providers/terraform-provider-oci#970]
While in the Example Usage section of [oci_core_remote_peering_connection](https://www.terraform.io/docs/providers/oci/r/core_remote_peering_connection.html) is mentioned that "peer_region_name" is optional to use, The Argument Reference section emphasizes on the fact that "Both peer_id and peer_region_name are required for the connection to succeed."

I tested it without using "peer_region_name" and received an error `Service error:InvalidParameter. peerRegionName may not be null.` showing that "peer_region_name" is necessary.

**Comment by abhilash-av** [comment]
@esalimy You could either only create the resource by not providing both peer_id and peer_region_name or provide both peer_id and peer_region_name which will result is resource creation and connect peering connection with peering connection from a remote region. Providing only peer_id is not a valid use case. We will also look further to see if the document can be improved to state the above explicitly.

**Comment by afedorch** [comment]
@esalimy the documentation for the resource was updated:
https://www.terraform.io/docs/providers/oci/r/core_remote_peering_connection.html#argument-reference
thanks!
