### ISSUE TITLE
unable to create 2nd listener on same port through terraform.. (oci_load_balancer_listener)

### ISSUE THREAD

**Issue by holeunlee** [terraform-providers/terraform-provider-oci#976]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.18

### Affected Resource(s)
oci_load_balancer_listener

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_listener" "app01" {
    #Required
    default_backend_set_name = "app01-backendset"
    load_balancer_id = data.oci_load_balancer_load_balancers.loadbalancer01.load_balancers[0].id #refers to created loadbalancer
    name = "app01_https_listener"
    port = 443
    protocol = "HTTP"
    depends_on = [ oci_load_balancer_backend_set.app01 ]
}

resource "oci_load_balancer_backend_set" "app01" {
    #Required
    health_checker {
        #Required
        protocol = "TCP"
    }
    load_balancer_id = data.oci_load_balancer_load_balancers.loadbalancer01.load_balancers[0].id
    name = "app01-backendset"
    policy = "ROUND_ROBIN"
}
```
### Panic Output
Error: Service error:InvalidParameter. Default Listener on port '443' refer to VIP 'private-vip' twice. http status code: 400. Opc request id:

### Expected Behavior
Resource is expected to be created, as it is possible to create a second listener on the same port through the OCI console without errors or warnings.

### References
https://www.terraform.io/docs/providers/oci/r/load_balancer_listener.html

**Comment by parrneet** [comment]
Hi @holeunlee 
I tried to create 2 listeners on same port from console and the 2nd work request failed with the same error. The creation request does get submitted on console.
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/17176271/74709692-a6b4ba00-51d4-11ea-938f-cdbc071cdacf.png">
Please confirm if the work request succeeded for both.

**Comment by holeunlee** [comment]
Hi @parrneet 
I have created a 3rd listener within the console which creates succesfully.

<img width="742" alt="Screenshot 2020-02-18 at 15 06 16" src="https://user-images.githubusercontent.com/11501022/74743169-3f444c00-5260-11ea-9208-78ba49cc7725.png">

<img width="1625" alt="Screenshot 2020-02-18 at 15 06 48" src="https://user-images.githubusercontent.com/11501022/74743218-4e2afe80-5260-11ea-916a-77ab4c28ef05.png">

**Comment by jotruon** [comment]
Hi @holeunlee, I confirmed that I also can't create second listener through console and get same error "Default Listener on port '443' refer to VIP 'public-vip' twice":
![Screen Shot 2020-02-19 at 3 20 48 PM](https://user-images.githubusercontent.com/49288829/74885924-a24ee500-532b-11ea-9226-b2b7597f523e.png)

**Comment by jotruon** [comment]
Hi @holeunlee, I check with service team and they confirm you can't have multiple listeners on the same port unless they have different hostnames.

**Comment by jotruon** [comment]
closing the ticket now
