### ISSUE TITLE
resource oci_database_autonomous_database result in Service error:InvalidParameter. Unable to process JSON input.

### ISSUE THREAD

**Issue by Frank2nd** [terraform-providers/terraform-provider-oci#977]
When calling the resource oci_database_autonomous_database in a module with the following tf code:
resource "oci_database_autonomous_database" "rlb_autonomous_database" {
    admin_password           = local.adminpw 
    compartment_id           = var.compartment_ocid     
    cpu_core_count           = 1   
    data_storage_size_in_tbs = 1
   db_name                  = "${var.pre_fix}atpf" 
    #Optional
    db_version       = local.db_version 
    db_workload      = "OLTP"
    display_name     = "${var.pre_fix}_atpf"
    freeform_tags    = {"IacProvider"="TF"}
    is_free_tier     = true
    license_model    = local.licse_mdl_payg 
     whitelisted_ips  = [var.private_subnet_as1_cidr_block,var.my_ip] 
}
locals {            
  licse_mdl_payg      = "PAY_AS_YOU_GO"
  db_version          = "18c"
  adminpw             = (sensative value)
}
and the following generated ouput:
  # module.atp.oci_database_autonomous_database.rlb_autonomous_database will be created
  + resource "oci_database_autonomous_database" "rlb_autonomous_database" {
      + admin_password                                 = (sensitive value)
      + autonomous_container_database_id               = (known after apply)
      + autonomous_database_backup_id                  = (known after apply)
      + autonomous_database_id                         = (known after apply)
      + clone_type                                     = (known after apply)
      + compartment_id                                 = "ocid1.compartment.oc1..aaaaaaaaxm74ajmbzbgjuooricuplbqebh7maiqzft3s2rkpkdablq5lq2ga"
      + connection_strings                             = (known after apply)
      + connection_urls                                = (known after apply)
      + cpu_core_count                                 = 1
      + data_safe_status                               = (known after apply)
      + data_storage_size_in_tbs                       = 1
      + db_name                                        = "platoatpf"
      + db_version                                     = "18c"
      + db_workload                                    = "OLTP"
      + defined_tags                                   = (known after apply)
      + display_name                                   = "plato_atpf"
      + freeform_tags                                  = {
          + "IacProvider" = "TF"
        }
      + id                                             = (known after apply)
      + is_auto_scaling_enabled                        = (known after apply)
      + is_dedicated                                   = (known after apply)
      + is_free_tier                                   = true
      + is_preview                                     = (known after apply)
      + is_preview_version_with_service_terms_accepted = (known after apply)
      + license_model                                  = "PAY_AS_YOU_GO"
      + lifecycle_details                              = (known after apply)
      + service_console_url                            = (known after apply)
      + source                                         = (known after apply)
      + source_id                                      = (known after apply)
      + state                                          = (known after apply)
      + system_tags                                    = (known after apply)
      + time_created                                   = (known after apply)
      + time_deletion_of_free_autonomous_database      = (known after apply)
      + time_maintenance_begin                         = (known after apply)
      + time_maintenance_end                           = (known after apply)
      + time_reclamation_of_free_autonomous_database   = (known after apply)
      + timestamp                                      = (known after apply)
      + used_data_storage_size_in_tbs                  = (known after apply)
      + whitelisted_ips                                = [
          + "10.120.1.0/24",(sensative value)
          ,
        ]
    }
I receive the error message:
Error: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. Opc request id: cbe9d5b7fe521c6d8361d7b29f19de15/00FC3B9B62A8C7FB94F585EB97523415/52DBFEC961AB50230003F6D5AA159E5C
  on ..\modules\atp\atp.tf line 3, in resource "oci_database_autonomous_database" "rlb_autonomous_database":
   3: resource "oci_database_autonomous_database" "rlb_autonomous_database" {

Note that the terraform show does not provide ouput since the creation is failed??

 I am calling this TF module as follows:
module "atp" {
  source = "../modules/atp"
  compartment_ocid                = "ocid1.compartment.oc1..aaaaaaaaxm74ajmbzbgjuooricuplbqebh7maiqzft3s2rkpkdablq5lq2ga" # plato
  pre_fix                         = "plato"
  private_subnet_as1_cidr_block   = "10.120.1.0/24"
  my_ip                           =  "(sensative value)"
}
Any ideas why this resource is failing?
Is there a way to lookup the generated json file?

**Comment by parrneet** [comment]
Hi @Frank2nd 

Please provide the debug logs and simplified terraform config to reproduce the issue.

To get debug logs follow [this](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider)

**Comment by Frank2nd** [comment]
I add to my env settings:
set F_LOG=DEBUG
set OCI_GO_SDK_DEBUG=v
reran terraform apply
But no additional console output other than (same as before)
module.atp.oci_database_autonomous_database.rlb_autonomous_database: Creating...
Error: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. 
.....
  on ..\modules\atp\atp.tf line 3, in resource "oci_database_autonomous_database" "rlb_autonomous_database":
   3: resource "oci_database_autonomous_database" "rlb_autonomous_database" {
..,
Or is there a log file I missed somewhere?
I have attached a zip file containing the simplified tf code creating an autonomous database
[oictf977.zip](https://github.com/terraform-providers/terraform-provider-oci/files/4218154/oictf977.zip)

**Comment by jotruon** [comment]
Hi @Frank2nd,
it should be:
`set TF_LOG=DEBUG`
instead of 

> set F_LOG=DEBUG

Can you try the apply with the debug log again.
Thanks

**Comment by jotruon** [comment]
Hi @Frank2nd,
In your config, 

> license_model="PAY_AS_YOU_GO"
There are only 2 valid value for license_model: "BRING_YOUR_OWN_LICENSE" or "LICENSE_INCLUDED". The error message return is a little confusing. 

Please check these references: https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/database_autonomous_database.html.markdown 
and https://docs.cloud.oracle.com/en-us/iaas/Content/Database/Tasks/adbcreating.htm

**Comment by jotruon** [comment]
closing this ticket
