### ISSUE TITLE
oci_identity_compartment doesn't really remove the compartment when running "destroy"

### ISSUE THREAD

**Issue by ruzickap** [terraform-providers/terraform-provider-oci#980]
### Community Note

* Please vote on this issue by adding a  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
$ terraform -v
Terraform v0.12.18
```

### Affected Resource(s)

* oci_identity_compartment

### Terraform Configuration Files

```hcl
resource "oci_identity_compartment" "infra" {
  description   = "pruzicka-infra infra compartment"
  name          = "pruzicka-infra-oic"
  freeform_tags = var.tags
}
```

### Actual Behavior

The output from `terraform destroy` looks like the compartment is successfully deleted, but I can still see it in the web interface.

### Steps to Reproduce

1. Create and delete the "compartment" using the code above.
2. `terraform apply && terraform destroy`

Logs for `terraform apply`

```
        "oci_identity_compartment.infra: Creating...",
        "oci_identity_compartment.infra: Creation complete after 9s [id=ocid1.compartment.oc1..aaaaaaaagsspezavqy2obm7p5xzqfebiufl256u6fu2tt3x2yt7fi2vfdu4q]",
```

Logs for `terraform destroy`

```
        "oci_identity_compartment.infra: Destroying... [id=ocid1.compartment.oc1..aaaaaaaagsspezavqy2obm7p5xzqfebiufl256u6fu2tt3x2yt7fi2vfdu4q]",
        "oci_identity_compartment.infra: Destruction complete after 0s",
```

Screenshot after destroy:

![image](https://user-images.githubusercontent.com/1434387/74875915-5881f100-5363-11ea-91f5-d4b767509ed4.png)

Thanks for looking at it...

**Comment by jotruon** [comment]
Hi @ruzickap ,

In order to destroy the compartment, please add the argument  `enable_delete` to the resource schema as in document: https://github.com/terraform-providers/terraform-provider-oci/blob/master/website/docs/r/identity_compartment.html.markdown#argument-reference 

Thanks

**Comment by ruzickap** [comment]
Thanks a lot. The `enable_delete` parameter did it :-)

Anyway I got impression, that when Terraform creates some "resource" which doesn't exit before, then it should also delete it when running destroy.

It makes me more sense to have `enable_delete = true` by default.

On the other hand - as you mentioned above - this is documented properly...

Thank you, closing...
