### ISSUE TITLE
Imported oci_core_instance that was launched from custom image shows source=bootVolume (not image)

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#981]
---
name: Imported oci_core_instance that was launched from custom image shows source=bootVolume (not image)
about: Import oci_core_instance and the source_details shows bootVolume (with bv ID) not image with image ID
labels: bug
---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.9
+ provider.null v2.1.2
+ provider.oci v3.62.0
+ provider.template v2.1.2
terraform-provider-oci 3.63.0

### Affected Resource(s)
oci_core_instance

### Debug Output
Below relevant output from import process. Note source imageId is detected
`2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "id" : "ocid1.bootvolume.oc1.phx.abyhqljtsyccraqvebws2rxqjmy4iqac5lhwb4lvgepow2asd6eosy2scnwa",
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "imageId" : "ocid1.image.oc1.phx.aaaaaaaablsuhpx3m6tai3ks3lghusj7v45cb723zmkkevawombytsxuzzzq",
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "isHydrated" : true,
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "vpusPerGB" : 10,
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "lifecycleState" : "AVAILABLE",
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "sizeInGBs" : 60,
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "sizeInMBs" : 61440,
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4:   "sourceDetails" : null`

However, resulting `terraform.tfstate` shows source as boot volume

```hcl
"source_details": [
  {
	"boot_volume_size_in_gbs": "",
	"kms_key_id": "",
	"source_id": "ocid1.bootvolume.oc1.phx. phx.abyhqljtsyccraqvebws2rxqjmy4iqac5lhwb4lvgepow2asd6eosy2scnwa",
	"source_type": "bootVolume"
  }
]
```

For comparison, consider this identical instance I launched via terraform. Note resulting terraform.tfstate source_details:
```hcl
"source_details": [
  {
	"boot_volume_size_in_gbs": "60",
	"kms_key_id": "",
	"source_id": "ocid1.image.oc1.phx. phx.aaaaaaaablsuhpx3m6tai3ks3lghusj7v45cb723zmkkevawombytsxuzzzq",
	"source_type": "image"
  }
]
```

### Expected Behavior
Imported oci_core_instance based on custom image should indicate source_details {source_type: image, source_id: custom_image_ocid}

### Actual Behavior
Import oci_core_instance based on custom image is indicating source_details {source_type: bootVolume, source_id: boot_volume_ociid_of_imported_instance}

### Steps to Reproduce

1. Launch new Compute Instance via OCI Console using custom image (does not matter what custom image)
2. Create compute.tf to match created image using source_details = "image"
3. Import new image `terraform import oci_core_instance.new_instance ocid……`
4. Test import by running `terraform plan -target=oci_core_instance.new_instance`
5. Note "1 to destroy" in part because source_details changing from "bootVolume" to "image" (as imported instance will have source_details = bootVolume not image as it should)

**Comment by jotruon** [comment]
Hi @jeliker ,
Can you share the config file?

**Comment by jeliker** [comment]
Forgive my ignorance but I don’t know what config file you mean. Are you referring to the file containing tenancy OCID, user OCID, region, key path?

_____
Jon-Eric Eliker (mobile)
Twitter: @jeliker
Jabber: jon@eliker.net

**Comment by jotruon** [comment]
Hi @jeliker , I mean Terraform Configuration Files, for example this boot_volume.tf file:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/boot_volume/boot_volume.tf 
I need the Terraform config file to reproduce the issue.
Thanks

**Comment by jeliker** [comment]
I understand. I have not used the term “config file” for that before. I’ll attach an example of my tf file used to represent the imported instance.

-----
Jon-Eric Eliker
Brunswick, Ohio, US
Twitter: @jeliker  LinkedIn: jeliker

People who are really serious about software should make their own hardware – Alan Kay, 1982

**Comment by jeliker** [comment]
Reminder: here are the steps I followed:

1. Launched instance from custom image via OCI Console
2. Used OCI CLI to get details of launched instanced and composed TF file. Noticed that `source_details` indicated `bootVolume` in the OCI CLI result but attempted to use `image` instead as that was the true source of this instance.
3. Imported using newly-created TF file and OCID of instance
4. Ran `plan` and found it wants to destroy/create saying the `source_details` must be `bootVolume` not instance (even though, as I say, source was actually `image`).

Here is representative version of TF I created then imported.

```hcl
resource "oci_core_instance" "instance_from_image" {
  availability_domain = "${data.template_file.ad_list.*.rendered[0]}"
  compartment_id = "${var.compartment_id}"
  shape = "VM.Standard2.4"

  agent_config {
    is_management_disabled = false
    is_monitoring_disabled = false
  }
  create_vnic_details {
    subnet_id = "${var.subnet_id}"
    assign_public_ip = false
    defined_tags = null
    display_name = null
    freeform_tags = null
    hostname_label = "pa"
    nsg_ids = "${var.nsg_ids}"
    private_ip = "10.0.0.10"
    skip_source_dest_check = false
  }
  dedicated_vm_host_id = null
  display_name = "pa"
  extended_metadata = {}
  fault_domain = "FAULT-DOMAIN-1"
  freeform_tags = null
  ipxe_script = null
  launch_options {
    boot_volume_type = "PARAVIRTUALIZED"
    firmware = "BIOS"
    is_consistent_volume_naming_enabled = false
    is_pv_encryption_in_transit_enabled = null
    network_type = "PARAVIRTUALIZED"
    remote_data_volume_type = "PARAVIRTUALIZED"
  }
  metadata = {
    ssh_authorized_keys = "${var.ssh_authorized_keys}"
    user_data = null
  }
  source_details {
    source_id = "ocid1.image.oc1.phx.aaaaaaaabl45cai3ks3lgb723zmkkevawsuhpx3usj7vombytsxm6thuzzzq"
    source_type = "image"

    boot_volume_size_in_gbs = null
    kms_key_id = null
  }
  preserve_boot_volume = true
}
```

**Comment by afedorch** [comment]
@jeliker Thanks for reporting it.

As I can see from the `Debug Output` you shared the log for the bootvolume import step:
```
2020-02-19T17:18:12.470-0500 [DEBUG] plugin.terraform-provider-oci_v3.63.0_x4: "id" : "ocid1.bootvolume.oc1.phx.abyhqljtsyccraqvebws2rxqjmy4iqac5lhwb4lvgepow2asd6eosy2scnwa",
```
But what we need to verify is the `sourceDetails` attribute value in the service response for the instance resource, something similar to:
```
"id" : "ocid1.instance.oc1.phx....",
"imageId" : "ocid1.image.oc1.phx...",
...
"sourceDetails" : {
"sourceType" : "image",
"bootVolumeSizeInGBs" : null,
"imageId" : "ocid1.image.oc1.phx...",
"kmsKeyId" : null
},
...
```
You can share the full log and/or verify what is the value for the `sourceDetails` in your case.


```
Used OCI CLI to get details of launched instanced and composed TF file. Noticed that source_details indicated bootVolume in the OCI CLI result but attempted to use image instead as that was the true source of this instance.
```
If you get `bootVolume` as `source_details` with CLI - Terraform provider will get the same result trying to verify the resource after the import. It means that if you set the image as `source_details` in the configuration the diff (attempt to recreate) will be expected behavior.

**Comment by jeliker** [comment]
OCI CLI is indeed reporting source as `bootVolume` though instance was launched from custom image.  Based on that do you believe this needs address via OCI CLI bug report not Terraform?

**Comment by afedorch** [comment]
@jeliker 
I see consistency between the CLI and Terraform - it means that `bootVolume` is a source as per service response.
To my mind, the problem could be in the launch instance process for this custom image (because as you mentioned you do not see the issue if the instance is launched with Terraform) and/or in the service response for the instance after this particular process.

If you can share the steps/image/instance you are using to reproduce the problem we will ask the service team to look at it. However, I am not sure that we can do anything for it on Terraform provider side. Thanks!

**Comment by jeliker** [comment]
I agree with you that Terraform matches the CLI. I must have made a mistake in my testing. I'll close this now to avoid causing unnecessary research until I can confirm the situation occurs as I originally _thought_ I was seeing.
