### ISSUE TITLE
When adding a dynamic group, the matching rule is not added correctly when there is more than 1 condition

### ISSUE THREAD

**Issue by hyder** [terraform-providers/terraform-provider-oci#984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

oci_identity_dynamic_group

### Terraform Configuration Files

```hcl
# Working dynamic group
resource "oci_identity_dynamic_group" "working_dynamic_group" {
  provider       = ....
  compartment_id = ....
  depends_on     = ....
  description    = ....
  matching_rule  = "ALL {instance.id = 'ocid1.instance.oc1.instance1'}"
  name           = "working dynamic group"
}

# Non-working dynamic group

resource "oci_identity_dynamic_group" "non_working_dynamic_group" {
  provider       = ....
  compartment_id = ....
  depends_on     = ....
  description    = ....
  matching_rule = "ANY { 
instance.id='ocid1.instance.oc1.instance1',instance.id='ocid1.instance.oc1.instance2',instance.id='ocid1.instance.oc1.instance3' }"
  name           = "non-working dynamic group"
}

```

### Expected Behavior

A dynamic group with the the matching rule created.

### Actual Behavior
The above code works fine when there's only 1 condition. However, when there are more than 1 condition, the leading string " ANY {" and the ending string "}" is stripped from the matching rule. As a result, instead of the matching rule looking like:

```
ANY { 
instance.id='ocid1.instance.oc1.instance1',instance.id='ocid1.instance.oc1.instance2',instance.id='ocid1.instance.oc1.instance3' }
```
the rule looks like: 
```
instance.id='ocid1.instance.oc1.instance1',instance.id='ocid1.instance.oc1.instance2',instance.id='ocid1.instance.oc1.instance3' 
```
in the OCI console.

### Steps to Reproduce

1. `terraform apply`

**Comment by hyder** [comment]
Update: It looks like the group membership worked after all. However, the ANY { } is not added/displayed in the OCI console. If I manually edit the rule in the OCI console, then it's displayed correctly. I'm wondering where the discrepancy is

**Comment by afedorch** [comment]
Hello  @hyder 

Thanks for reporting it!

I will need to revisit the docs for the rules syntax:
https://docs.cloud.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm

But as I can see from the state file you can try the following syntax to get `ANY` on console side:
```
resource "oci_identity_dynamic_group" "dynamic-group-1" {
  compartment_id = ...
  name           = ...
  description    = ...
  matching_rule  = "any {ANY {instance.id = 'ocid1.instance.oc1.instance1',instance.id = 'ocid1.instance.oc1.instance2',instance.compartment.id = 'ocid1.instance.oc1.instance3'}}"
}
```

**Comment by afedorch** [comment]
Hello @hyder 
It looks like console uses an additional `ANY` keyword to split the `Matching Rules` into different lines.
And as per API `matchingRule` is a string https://docs.cloud.oracle.com/en-us/iaas/api/#/en/identity/20160918/datatypes/CreateDynamicGroupDetails 

It means that if you want to use multi-line representation on console you need to add an additional `ANY` keyword and follow the rules' guidelines:
https://docs.cloud.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm

In terms of Terraform provider - full users' input for the `matchingRule` will be sent to the service.
I am closing this request let us know if you have any other questions. Thanks!

**Comment by hyder** [comment]
So that means the rule is still correct? It's just the OCI console needs an additional ANY to render it correctly?
