### ISSUE TITLE
Load balancer objects are referenced by name, not by OCID

### ISSUE THREAD

**Issue by tyskjohan** [terraform-providers/terraform-provider-oci#985]
I am creating my load balancer and certificates in one tf file, and the listener and backend in another file. This fails on first apply because the reference from the "listener/backend" file to the certificate in the "load balancer file" is by name and not by OCID (I don't think certificates even have OCIDs), because the certificate has not been created yet because Terraform cannot map the dependecy treed based on names.

This also happens if the two objects are in the same file, I have examples with e.g. rule sets and invalid references.

**Comment by afedorch** [comment]
@tyskjohan 
Could you please share the configuration to reproduce the problem?

Do you see any problems while executing the lb example from the repo?
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/load_balancer/lb_full/lb_full.tf

Are you using `depends_on` for the explicit resource dependencies? 
https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

Thanks!

**Comment by tyskjohan** [comment]
Hi - this is kinda helpful, you are referring to the certificate by  "${oci_load_balancer_certificate.lb-cert1.certificate_name}" which introduces a dependency to the string variable. I will try that before trying depends_on.

**Comment by afedorch** [comment]
@tyskjohan let us know if you need any other help with this request, thanks!
